### ISSUE TITLE
Having trouble installing in Apache

### ISSUE THREAD

**Issue by njolin** [voidlabs/mosaico#1]
Hello!  

Cloned from git, ran npm install, finished OK.
when running grunt, I get the following:
Running "combineKOTemplates:main" (combineKOTemplates) task

Running "browserify:debug" (browserify) task
>> Error: Cannot find module './checkModel.js' from '/home/devmaile/public_html/mosaico/mosaico/src/js/converter'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.

Any ideas?
Thanks!

**Comment by bago** [comment]
I think I just committed the fix: I included "checkModel.js" but the file is "checkmodel.js" (lowercase M): it worked anyway on my windows box!

Thank you for reporting! Please come back with feedback, suggestions, ideas!
