### ISSUE TITLE
Emails always going out with layout as that of Smartphone

### ISSUE THREAD

**Issue by deepak-srivastava** [voidlabs/mosaico#101]
Whether TEST or DOWNLOAD, always renders the template as we would see in live preview for "smartphone", and never see it as for "Largescreen".

Template we been using is: templates/versafix-1/template-versafix-1.html
And we using backend-php if that makes any difference.

Any ideas what we could be missing?

**Comment by bago** [comment]
Which email client are you using to see the email?
What do you see if you send the email using the same template to the same recipient from https://mosaico.io ? Same thing ? Correct result?

**Comment by deepak-srivastava** [comment]
We used gmail, mailtrap and also did a litmus test which showed pretty much same results (mobile layout) for all the clients.

Think we have figured it out its php-backend's premailer thats causing it. Specifically following line: 
`$premailer = Premailer::html( $_POST[ "html" ], true, "hpricot", $config['BASE_URL'] );`

Commenting it works and produces same results as you see with mosaico.io or grunt. 
Probably need to dig a bit deeper on what Premailer is doing and why we need it.

**Comment by bago** [comment]
Well, you provably should ask this in the mosaico-php-backend project issue tracking.

I hope to be able to implement #54 in the next months, so to avoid "fragmentation" on this kind of issues related to the css inliner that is *core* but is implemented differently by each backend (moving it to the client will make it more consistent and will require a more dumb backend).

**Comment by NJseo** [comment]
I got the same thing. I going to try your suggestions on removing premailer, but its there for a reason.

**Comment by NJseo** [comment]
I noticed when the emails where inlined with the premailer, the desktop previews of them were all of the mobile variety. When I used Litmus, I noticed that they were responsive, however, the 3 column layout portion were duplicating all three of the images per image cell on mobile. 

I am using the php-backend
