### ISSUE TITLE
idea: "Show/hide left panel" button

### ISSUE THREAD

**Issue by psyafter** [voidlabs/mosaico#104]
It possible to add "Hide left panel" button for viewing working template in max width?

**Comment by bago** [comment]
I thought at this various times but didn't find a good solution (for the User eXperience).
When you use mosaico you need to select things in the "body" and do stuff in the "left panel": if you make it collapsable you will always have to open it even for basic things (add a block, insert an URL for an image).

I saw that having a 1100px wide screen is enough to use mosaico and see both the left panel and the full size newsletter... do you have a larger template? Or are you trying to use mosaico with a narrower screen? How much narrower?

**Comment by psyafter** [comment]
I have wide responsive template (landing page).
I want to see it with max screen width before saving/publishing.

This icon-button can sit in top before "Blocks" button. Icon like standard menu  icon (3 horizontal lines) and it can hide/show left panel top buttons as well.

**Comment by bago** [comment]
Go to "mosaico.io" edit a template and start the javascript console.
Type ```viewModel.showToolbox(false);```
and then ```viewModel.showToolbox(true);```

So, is this the "behaviour" you want? If so you could easily implement it externally by adding your button in the html and then bind the call to your button
```javascript

var switchToolBox;
var myMosaicoPlugin = function (viewModel) {
  switchToolbox = function() {
    viewModel.showToolbox(!viewModel.showToolbox())
  };
}
// init Mosaico.init passing this plugin
```
add ```<a onclick="switchToolBox();return false;">menu</a>``` to your html.

Maybe this can be implemented in mosaico itself, but I think this could address your issue right now, without changes to mosaico sources.

Let me know!

**Comment by psyafter** [comment]
perfect, it what I need :)
thanks

**Comment by bago** [comment]
I'd like to see what you're working on with landing pages / forms... sounds interesing... can I see something? (if so, write me an email to info att mosaico.io)

**Comment by psyafter** [comment]
I just prepare myself to it now :)
I'll start with it next week, currently nothing to display.

The main idea is to adapt mosaico to be responsive landing pages editor.
I'll play with adding bootstrap to mosaico editor (as all pages will be bootstrap based) and other scripts.

May be you remember my idea about iframe (https://github.com/voidlabs/mosaico/issues/74). So at first I'll try to do it without iframe. Hoping I'll success in it :)
