### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by valterhenrique** [voidlabs/mosaico#106]
Hi guys, 
First of all, great project, love it!

Quick question: is possible to export the result as .pdf file ?
Thank you!

**Comment by bago** [comment]
Can I ask Why????

Download HTML, open it with Chrome, print as PDF.

**Comment by valterhenrique** [comment]
Hi @bago, sure you can :)
I  work with [factsheets](http://www.climate-policy-map.econsense.de/images/Kasten-Fact-Sheets-big.jpg), I do that using JasperSoft for example, however I would like use mosaico so the user can create its own factsheet on the web browser and them export it as PDF, because my customer needs to send this facthseet, the report, to their customers.

Using Chrome print as PDF feature seems doable but the problem is that the result is not so good, the content seems bigger, broken, and so on. So I'm just wondering if it's possible to have a link 'export to pdf', something like that and export the generated html page to pdf.

**Comment by bago** [comment]
Mosaico works with HTML templates. So exporting to PDF means converting HTML to PDF. If Chrome is not so good, I can't see how we could be better. I personally don't need export to PDF nor paying customers, so I keep this as invalid as I don't think exporting to PDF belongs to the mosaico architecture.

Mosaico as its core is an "html template based" email composer.

The way Chrome print it to PDF will mainly depend on the HTML you put in your template. You could convert the html 2 pdf using tools like [wkhtml2pdf](http://wkhtmltopdf.org/) on the server: results are pretty good (the most you can get from something automatic and not specific to build PDF reports).

**Comment by valterhenrique** [comment]
I see your point, it makes totally sense. Thank you for your answer @bago :)
