### ISSUE TITLE
iPhone email rendering issues when avast extension is installed in the browser using mosaico

### ISSUE THREAD

**Issue by bago** [voidlabs/mosaico#111]
We detected sometimes (very very rare) mosaico email (versafix-1) were blank when opened in iPhone. After some investigation we found the issue was an "Avast" extension inserting custom html in every frame of the browser, including the one we use in background to generate the output email html .

This html in found before the ```</head>``` tag
```html
<link id="avast_os_ext_custom_font" href="//fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet" type="text/css"><link href="//fonts.googleapis.com/css?family=Lato:400,900" rel="stylesheet" type="text/css"><link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,700&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css"><link href=3D"//fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet" type="text/css">
```

We could try to detect this kind of behaviour and alert the user the browser is not compatible.

**Comment by MirzaMateen** [comment]
email opens very slow  from one particular user using mac.....looked further found the same <link id="avast_os_ext_custom_font" ............. line...in the html... could this be the reason for slow loading ?

**Comment by bago** [comment]
I really don't know. Maybe you can try uninstalling avast from that mac or from the computer that sent the email and let us know.
