### ISSUE TITLE
Get html without downloading?

### ISSUE THREAD

**Issue by tmikaeld** [voidlabs/mosaico#115]
Is this possible, like showing it in a textarea?

**Comment by bago** [comment]
It is possible, but you won't get "inlined CSS" because the CSS inlining (needed for correct rendering) is currently a backend task.
https://github.com/voidlabs/mosaico/issues/54

```
viewModel.exportHTML() gives you the output html.
viewModel.exportHTMLtoTextarea('yourtextareaid') export it to a textarea
```

you can access "viewModel" via plugins.
https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins

**Comment by tmikaeld** [comment]
But you could save the rendered file locally, read it and send back the response?

**Comment by bago** [comment]
I don't understand what you mean.

- exportHTML is the HTML in the browser.
- the download button simply get that html in a textarea, submit the form, the backend inline the CSS and gives you back the response.

I don't really get what "save the rendered file locally" and "read it and send back the response" means.

**Comment by tmikaeld** [comment]
To be clear, be able to view the rendered css-inlined code so one can copy it without having to download and open a file.

**Comment by bago** [comment]
OK, I now understand this... 

Are you looking for a ready to use solution, or are you willing to develop one? (do you understand javascript? Do you understand https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins instructions?

(I want to understand if this is a feature suggestion, or a request for help/support developing that feature on your own)

**Comment by tmikaeld** [comment]
I'm probably able to create a plugin, but I'm 99% sure this is a feature that most people need/want - especially if they intend to embed this editor to their own newsletter system.

**Comment by bago** [comment]
I expect embeddor to do something automatically and not to ask their user to copy&paste things around...

**Comment by tmikaeld** [comment]
Not all systems are that open, but all other newsletter editors (wysiwyg) allow one to add HTML manually. This would enable that without much extra work. 

One could even add mosaico to the same server and run it on a different port, then just use cross-origin rules to allow pasting the code to the editor automatically.

But sure, i agree - done properly one would need to make an integration via plugin.

**Comment by bago** [comment]
What I mean is that if you start working with cross-origin rules and automatic paste things, then you are writing code and so I don't see it is too hard to invoke viewModel.exportHTML) from mosaico, make an ajax call to the backend that does the inlining for that code, take the result and paste it where you want... it should be few lines of javascript code.

I'm willing to do some improvements to mosaico to help integrators, and I already planned them... but before I add *UI* things to mosaico (e.g: for displaying the html output in a textare) I want to be sure it would be broadly used.

**Comment by mandadimuralidharreddy** [comment]
goto src/js/ext/localstorage.js
find
downloadCmd.execute = function() {
replace whole code in side this function 
like this 
```
 downloadCmd.execute = function() {
      viewModel.notifier.info(viewModel.t("Copied to clipboard"));
      viewModel.exportHTMLtoTextarea('#downloadHtmlTextarea');
      var htmlCode=$("#downloadHtmlTextarea").val();
      setClipboardText(htmlCode);
      function setClipboardText(text){
        var id = "mycustom-clipboard-textarea-hidden-id";
        var existsTextarea = global.document.getElementById(id);

        if(!existsTextarea){
          console.log("Creating textarea");
          var textarea = global.document.createElement("textarea");
          textarea.id = id;
          // Place in top-left corner of screen regardless of scroll position.
          textarea.style.position = 'fixed';
          textarea.style.top = 0;
          textarea.style.left = 0;

          // Ensure it has a small width and height. Setting to 1px / 1em
          // doesn't work as this gives a negative w/h on some browsers.
          textarea.style.width = '1px';
          textarea.style.height = '1px';

          // We don't need padding, reducing the size if it does flash render.
          textarea.style.padding = 0;

          // Clean up any borders.
          textarea.style.border = 'none';
          textarea.style.outline = 'none';
          textarea.style.boxShadow = 'none';

          // Avoid flash of white box if rendered for any reason.
          textarea.style.background = 'transparent';
          global.document.querySelector("body").appendChild(textarea);
          console.log("The textarea now exists :)");
          existsTextarea = global.document.getElementById(id);
        }else{
          console.log("The textarea already exists :3");
        }

        existsTextarea.value = text;
        existsTextarea.select();

        try {
          var status = global.document.execCommand('copy');
          if(!status){
            console.error("Cannot copy text");
          }else{
            viewModel.notifier.info(viewModel.t("The HTML is now on the clipboard"));
            console.log("The text is now on the clipboard");
          }
        } catch (err) {
          console.log('Unable to copy.');
        }
      }
    };
```

this will copy html to clipboard.

**Comment by tmikaeld** [comment]
@mandadimuralidharreddy Thanks for sharing! Will try it when i get a chance!

**Comment by mandadimuralidharreddy** [comment]
@tmikaeld Your welcome.I am using this in production.
