### ISSUE TITLE
Don't know if its a bad install or if its just different from the public version

### ISSUE THREAD

**Issue by NJseo** [voidlabs/mosaico#117]
When I load into the editor, I notice Mosaico's has directions and if I right click, a help menu that pops up. My version does not. Is this a bad install or just some I am expected to implement on my own?

**Comment by devpgtech** [comment]
Homepage says:
> On https://mosaico.io you can see a live demo of Mosaico: the live deploy has a custom backend (you don't see it) and some customization (custom Moxiemanager integration, customized onboarding slideshow, contextual menu, and some other small bits), but 95% of what you see is provided by this library. You will also see a second working template there: we are still working to open source it. Stay tuned!

So you need to implement by yourself.
