### ISSUE TITLE
Curios About HTML output for newsletter : &#13;

### ISSUE THREAD

**Issue by NJseo** [voidlabs/mosaico#119]
I see this &#13; all over the output and am wondering what its there for &#13

**Comment by bago** [comment]
I can't see that sequence in my templates output.

When you open an issue you should give detailed informations about the environment and the steps to reproduce it and more.

https://github.com/voidlabs/mosaico/blob/master/README.md

**Comment by NJseo** [comment]
Yeah, so whatever it is coming from, I guess, from your feedback, it's safe to say I can strip it from the HTML?

**Comment by bago** [comment]
I don't know. You didn't provide enough information for me to understand the issue, sorry.
