### ISSUE TITLE
Unable to delete Templates

### ISSUE THREAD

**Issue by notchris** [voidlabs/mosaico#121]
I'm sorry if this has been answered / documented somewhere, but I really have  searched for this a while now. I cannot seem to find where to remove a default template. I cannot see where templates are defined / called. After removing two of the default templates, they still appear on the template selection area.

**Comment by devpgtech** [comment]
List templates are define in editor.html and you can remove the template you don't want:
`var viewModel = {
        showSaved: ko.observable(false),
        edits: ko.observableArray(initialEdits),
        templates: [{
          name: 'versafix-1', desc: 'The versatile template'
        },{
          name: 'tedc15', desc: 'The TEDC15 template'
        },{
          name: 'tutorial', desc: 'The Tutorial'
        }]
      };`

**Comment by notchris** [comment]
Yeah this was my bad, I somehow totally missed the reference in index.html - thank you for the reply.
