### ISSUE TITLE
Built function to check for empty links in mosaico, but after making changes to the links, javascript doesnt recognize

### ISSUE THREAD

**Issue by NJseo** [voidlabs/mosaico#122]
Built function to check for empty links in mosaico, but after making changes to the links, javascript doesnt recognize. 

I'm running through the DOM, but its not seeing the changes made. Is there some type of binding I have to do with Knockout or something?

Any ideas?

**Comment by bago** [comment]
I'm sorry I don't understand you. If you wrote code, share it.
You should never deal direclty with the DOM in mosaico.

Please take your time when you open issues: be complete and clear, otherwise no one will be able to help you: https://github.com/voidlabs/mosaico/blob/master/README.md

**Comment by NJseo** [comment]
I interrupt the download process to first check to see if there are empty links. Although I havent figured out how to check to see if there is a value for the data-binded links, it would be nice if I could.

function checkContent(){
		passedTest = 0
		list = null;
		listItemAnchors = null;
		list = document.getElementById("main-wysiwyg-area");
		listItemAnchors = list.getElementsByTagName('a');
		
		if(tested == 1){
			
			for (i = 0, len = listItemAnchors.length; i < len; i++) {
				
				if(listItemAnchors[i].classList.contains("linkHighlight")){
					 listItemAnchors[i].classList.remove("linkHighlight");
				}
			}
			//replaceAll(list.innerHTML, "linkHighlight", "");
			return 0;
		}
		
		for (i = 0, len = listItemAnchors.length; i < len; i++) {
		   
		  	if(listItemAnchors[i].innerText != ''){
				if(listItemAnchors[i].innerText == "[mail]"){
					continue;
				}
				if(listItemAnchors[i].hasAttribute("data-bind")){ // getAttribute("bind").indexOf("unsubscribe") > -1){
					
					
				}else{
					//alert(listItemAnchors[i].href.length);
					
			  		if(listItemAnchors[i].innerText != ''){
						if(listItemAnchors[i].href.indexOf("mosaico/editor.html")){ //listItemAnchors[i].hasAttribute("href")
					  			
									listItemAnchors[i].classList.add("linkHighlight");
									listItemAnchors[i].setAttribute("href", "http://www.google.com");
									tested[i] = i;
								
					  		passedTest++;
							//return 0;
						}else{
							//alert("URL: " + listItemAnchors[i].href);
							if(listItemAnchors[i].classList.contains("linkHighlight")){
									listItemAnchors[i].classList.remove("linkHighlight");
								}
							
						}
					  
					}else{
						if(listItemAnchors[i].href.indexOf("mailto")){
									
						}else{
							if(listItemAnchors[i].classList.contains("linkHighlight")){
									listItemAnchors[i].classList.remove("linkHighlight");
							}
						}
					}
					if( listItemAnchors[i].getElementsByTagName('img').length > 0) {
							if( listItemAnchors[i].href.length > 1 && listItemAnchors[i].hasAttribute("href")){
								if(listItemAnchors[i].getElementsByTagName('img')[0].classList.contains("linkHighlight")){
									listItemAnchors[i].getElementsByTagName('img')[0].classList.remove("linkHighlight");
								}
							
							}else{
								
								listItemAnchors[i].getElementsByTagName('img')[0].classList.add("linkHighlight");
								//alert("You Have An Empty IMG Link In Your Template: " + listItemAnchors[i].getElementsByTagName('img')[0]);
								passedTest++;
								//return 0;
							}

					}
				}
				
			}
			
		}
		if(passedTest > 0){
			alert("There is " + passedTest + " Error(s) with The URLS in your document! \n\r They are highlighted in red \n\r The Editor Not Perform Another Check Until After The Page Is Saved!");
		}
		tested=1;
		return passedTest;
	}


If passedTest = 0, continue the process of downloading, else return quit function. Variable tested is set to one after it has had one go around to highlight unlinked anchors. After that, it removes the highlighted anchor class, and just saves.
