### ISSUE TITLE
Is there a way to limit the blocks used?

### ISSUE THREAD

**Issue by jrodri2001** [voidlabs/mosaico#125]
I wonder if there is a way to limit a particular block to be used only once. For example, I'd like to add a block of content containing a form. the block should be able to be moved around, but it should be able to be added only once into the template.

Thanks for any suggestions.

**Comment by psyafter** [comment]
I'm with you same here https://github.com/voidlabs/mosaico/issues/108

**Comment by bago** [comment]
At this time this is not something provided by Mosaico, nor it is easy to implement because this was not a requirement and still I don't see it as an useful feature for an email editor.

Are you trying to use Mosaico as a landing page editor, like @psyafter  ?
If not, why are you trying to put a form in an email?

I guess you will find much more in Mosaico that is not "well-fit" to landing pages (I don't know how it works with "web-oriented" styles, I don't know how it works with forms/form elements.
BTW, if you both are trying to adapt mosaico to make it work better for landing pages maybe the best option is to make a fork and start putting your hands in the code.

I'm not willing, TODAY, to start making mosaico more complex in order to support non-email editing scenarios, but this may change in future. Now I need to consolidate it for email and landing page is a distraction for my goal.
I'm happy if mosaico is adapted to other tasks, but I can help on this only if someone start digging in the code and undestanding the internals.

First of all let me know you real/final/pratical use-case.

**Comment by jrodri2001** [comment]
Yes, I am trying to use mosaico as a landing page generator. I understand this is not what it was build for, but seems possible though. 

I was able to override the addBlock function in a plugin, so that I can check what kind of block is being inserted, and add the logic there. 

In case anyone is interested, here is my plugin (it just prevents to add more than one block with word "form" in the name/type):

```javascript
plugins.push(function(viewModel) {
            viewModel.addBlock = function (obj, event) {
                // if there is a selected block we try to add the block just after the selected one.
                var selected = viewModel.selectedBlock();
                var foundform = false;
                var isform = obj.type.match(/form/gi);

                //If selected block is a form element, search current blocks for another block of type "Form"
                if (isform) {
                    for (var i = viewModel.content().mainBlocks().blocks().length - 1; i >= 0; i--) {
                        var block = viewModel.content().mainBlocks().blocks()[i]().id();
                        foundform = block.match(/Form/gi);
                        if (foundform) {
                            break;
                        }
                    }
                }

                //if found form is found, then just alert and don't add it
                if (foundform){
                    viewModel.notifier.error("You can't add another form to the Template");

                }else{
                    // search the selected block position.
                    var found;
                    if (selected !== null) {
                        // TODO "mainBlocks" is an hardcoded thing.
                        for (var i = viewModel.content().mainBlocks().blocks().length - 1; i >= 0; i--) {
                            if (viewModel.content().mainBlocks().blocks()[i]() == selected) {
                                found = i;
                                break;
                            }
                        }
                    }
                    var pos;
                    if (typeof found !== 'undefined') {
                        pos = found + 1;
                        viewModel.content().mainBlocks().blocks.splice(pos, 0, obj);
                        viewModel.notifier.info(viewModel.t('New block added after the selected one (__pos__)', {
                            pos: pos
                        }));
                    } else {
                        viewModel.content().mainBlocks().blocks.push(obj);
                        pos = viewModel.content().mainBlocks().blocks().length - 1;
                        viewModel.notifier.info(viewModel.t('New block added at the model bottom (__pos__)', {
                            pos: pos
                        }));
                    }
                    // find the newly added block and select it!
                    var added = viewModel.content().mainBlocks().blocks()[pos]();
                    viewModel.selectBlock(added, true);
                    // prevent click propagation (losing url hash - see #43)
                    return false;
                }

            }
        });
```

**Comment by bago** [comment]
More futureproof by calling the original function instead of copying the code):
```
plugins.push(function(viewModel) {
            var originalAddBlock = viewModel.addBlock;
            viewModel.addBlock = function (obj, event) {
               if (yourlogic) {
               } else originalAddBlock(obj, event);
            };
});
```

**Comment by jrodri2001** [comment]
Indeed. Thanks.

**Comment by NJseo** [comment]
jrodri2001, any luck with that? I wrote a simple SEO CMS that I could dig up if needed. Actually could combine it with Mosaico and AUTH0, and would make from an easy customizable system.
