### ISSUE TITLE
Need mosaico to run in local development without compile the codes

### ISSUE THREAD

**Issue by fatkhanfauzi** [voidlabs/mosaico#126]
Hi Bago,
Is there any ways to run the demo without compile the codes?
I don't have any ideas to debug this app, when i write console log, the sources are not changed.

![image](https://cloud.githubusercontent.com/assets/2447205/13875431/ca4e80c2-ed38-11e5-9063-6b973f9585df.png)

In addition, when i do breakpoint on one of the files in above path, the breakpoint couldn't catch the variable values.

Moreover, I need to know how it works since i'm going to install it in my app.
But i don't have any ideas how to do that.

Could you please let me know how to debug this demo and how to use it in another app ?
Which files that necessary to add on my app ?

Thanks.

**Comment by devpgtech** [comment]
Hi @fatkhanfauzi , 
You can put breakpoint on mosaico.js file (dist/mosaico.js), codes of all module (src/js) are compile here.

**Comment by devpgtech** [comment]
Hi @fatkhanfauzi ,
To debug you can put breakpoint on mosaico.js file (dist/mosaico.js), codes of all module (src/js) are compiled here.

**Comment by fatkhanfauzi** [comment]
Hi @devpgtech,
Alright, i'm wondering about which files that necessary to add in my own apps ?
So many files there, dunno the files that should use to make it work in my own apps.
Thanks in advance.

**Comment by devpgtech** [comment]
HI @fatkhanfauzi ,
Sorry if i misunderstand, I think add one minified file is better than add ton of files. To integrate the editor into your app you just care about some script reference in index.html and editor.html file.

**Comment by bago** [comment]
No way to run the code without the build
In the "build" folder you will find intermediate builds, like an unminified "debug" version of the build.
Just change your editor.html to include this file instead of the minified.

**Comment by JbalTero** [comment]
On the editor.html change this.


    <script src="build/mosaico.js?v=0.13"></script>

**Comment by bago** [comment]
I don't think you can "understand mosaico" by debugging if you don't understand grunt or similar "simple tools".

You will need a good understanding of the build tools, expecially "browserify" (they are easy to learn), and you will need to understand knockout.js (this is the main building block):
Also, read the wiki, starting from here: https://github.com/voidlabs/mosaico/wiki/Developers

**Comment by fatkhanfauzi** [comment]
Hi Bago, sorry for my late response.
Alright Bago, i'll take a look on browserify.
However, I'm wondering about there are so many files under /src/js/. 
Is it also necessary to include in my my apps ?
Or
After it's compiled then i can just include the 

`<script src="build/mosaico.js?v=0.13"></script>`

to my editor.html ?

Moreover, about the dependencies, will it be required to add all of them on my own apps ?

Thanks.

**Comment by bago** [comment]
In order to run mosaico you need the stuff you find in the dist folder after you build it.
In your page you will have to include the same thing you see included by editor.html file.

the "src" folder, like the name suggest, is the source of the library. There are many files because no sane person would work on a 500kb single file javascript code. Every non trivial application is composed by multiple source files.

**Comment by fatkhanfauzi** [comment]
Well explanation Bago. I got better understanding in how src files work.
Anyway, My goal is: i want to use Mosaico as a part of ui-kit component on existing app that's already used Angular as the dependency.
I think, i don't want to rewrite Mosaico, i was wondering about what's happened if i call Mosaico in the same file that using angular. Will it be conflict or not ?
However, i think i have to try to know how's the result will be.
Thanks Bago.

**Comment by fatkhanfauzi** [comment]
Hi Bago, i'm trying to use gulp.
is there any gulp version for the tasks (e.g CombineKOTemplates.js) ?

**Comment by bago** [comment]
From my previous message:

> You can even replace grunt with gulp and other similar changes... but why?? What's your goal?

If you want to use gulp you will have to rewrite the build to use it instead of grunt... if you enjoy altering the building blocks of a library then go ahead and do it, but don't ask me how to do that, the scope of this project is not to learn you build tools ;-)

**Comment by fatkhanfauzi** [comment]
Sorry, i'm just asking.
Alright Bago, i'll try to rewrite the grunt tasks to gulp.
Thanks anyhow. :)

**Comment by anujyadav1989** [comment]
hi Bago when i am trying to run down loded code dist folder is missing . how can i get that?

**Comment by bago** [comment]
Please, read the readme in the root folder!
