### ISSUE TITLE
Name property in Metadata

### ISSUE THREAD

**Issue by JbalTero** [voidlabs/mosaico#128]
There's a name property in Metadata, how do I add an input element as plugin/widget around the navbar beside save button? and bind it with the name property. Thanks.

**Comment by devpgtech** [comment]
Hi, do you mean:
Search **templateCompiler** function, you can add metadata property for content object:
`var content = performanceAwareCaller('generateModel', templateConverter.wrappedResultModel.bind(undefined, templateDef));
                        content().metadata = metadata;`
Then in main.tmpl template, add the binding you want:
`<input data-bind=\x22text: $root.content().metadata.name\x22 />`

**Comment by JbalTero** [comment]
Hmmm, is there a way to achieve it using plugin?

**Comment by devpgtech** [comment]
Sorry, my answer is not correct, I'm learning Mosaico ... and finding a way

**Comment by bago** [comment]
metadata.name us a property used only by the localstorage plugin.
At this time this is also used by the Mosaico.init() method, but you can use Mosaico.start() method and initialize mosaico without any support for the "name" property in metadata.

I know this is not the answer to your question, but this let me explain that name is already something deal in plugin and you can write your own plugin (similar to localstorage.js) that will put its own properties in the metadata object and deal with those properties as you like.

The needed html and bindings can be added by the plugin or you can simply write them in your html page: you need knockout.js knowledge to do this kind of plugins.

**Comment by bago** [comment]
At this time name is a simple property and not an "observable property", but maybe you can introduce a "myName" observable property (metadata.myName = ko.observable('default value');) and deal with it via data-bind property.

**Comment by JbalTero** [comment]
> metadata.name us a property used only by the localstorage plugin.
I want to use this also for the back-end.

> The needed html and bindings can be added by the plugin or you can simply write them in your html page: you need knockout.js knowledge to do this kind of plugins.
Thank you for the tips, I'll do what I can and post back here whenever I got the solution. Thanks.

**Comment by bago** [comment]
I'm closing this. But please give us feedback once you have a final solution.
