### ISSUE TITLE
Unable to run Mosaico

### ISSUE THREAD

**Issue by SamGoody** [voidlabs/mosaico#130]
Am unable to run Mosaico. Errors detailed below.

Specs: 
Ubuntu 15.10, Node v4.4.0, npm 3.8.3. 
$ npm list -g --depth=0
`bower@1.7.7, bower-npm-install@0.5.10, grunt@0.4.5, grunt-cli@1.0.0, npm@3.8.3`

$ npm install (same output as $ npm install --only=dev)
```
> mosaico@0.14.0 postinstall /home/sam/mosaico
> bower-npm-install --non-interactive

npm WARN optional Skipping failed optional dependency /watchify/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm WARN mosaico@0.14.0 No repository field.
npm WARN mosaico@0.14.0 license should be a valid SPDX license expression
```

$ grunt
 ```
Loading "bowercopy.js" tasks...ERROR
 >> Error: Cannot find module './array/append'  
Loading "phantom-thumbnailer-editor.js" tasks...ERROR
>> Error: Cannot find module 'webpage'
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'caniuse-db/features-json/transforms2d'
Warning: Task "default" not found. Use --force to continue.
```

Aborted due to warnings.

$ w3m http://localhost:9006
`w3m: Can't load http://localhost:9006.`

Other:

> you understand you have to build it and to run a backend server

Isn't Grunt supposed to start node as a server? If so, then I understand.

> you read this Readme three times and followed the instructions

Done. I have some experience with Node and Gulp (none with Grunt), but am no means a guru.

Please advise.

Thanks

**Comment by bago** [comment]
it seems npm is not working correctly in your environment (npm install output should be hundreds of lines). I know another user reported issues with default npm in the ubuntu distro:
https://github.com/voidlabs/mosaico/issues/82

**Comment by bago** [comment]
Well, I also forgot to congratulate with you because you are the first user that proved to read the readme ;-)

```
npm cache clean
npm install (multiple times if you get differnt errors, stop if same error)
npm update (multiple times if you get differnt errors, stop if same error)
```

remove the project.
download it again.
do "npm cache clean"
then "npm install" and "npm update" in a loop until both of them returns no error.
once all of this work, run "grunt".

If you still get stuck in the same place, please write here the full output of your npm install.

**Comment by bago** [comment]
Any feedback on this? Did you solve the issue? How?

**Comment by bago** [comment]
No feedback. Closing.
