### ISSUE TITLE
Template images are not loaded

### ISSUE THREAD

**Issue by learner0333** [voidlabs/mosaico#132]
I am able to configure the editor and its working. But when i click on any template part from left screen images are blank . Please review attached image. I have tried in firefox(45.0.2) and chrome(49.0.2623.112 m) as well
![editor](https://cloud.githubusercontent.com/assets/5172831/14488382/73cde604-0181-11e6-968f-df3dcf61d26e.png)

**Comment by bago** [comment]
Did you read the Readme? https://github.com/voidlabs/mosaico/blob/master/README.md

**Comment by learner0333** [comment]
Yes, I read it and follow all the steps

**Comment by learner0333** [comment]
It's working now

**Comment by bago** [comment]
What was the issue?

**Comment by nrileykc** [comment]
I'm having this same issue, how did you resolve?
