### ISSUE TITLE
Making Emails Responsive

### ISSUE THREAD

**Issue by DanSnelson** [voidlabs/mosaico#136]
It appears that when i create a customer template from scratch for Mosaico, I add my responsive CSS and it messes everything up? all the blocks seem to dissapear from the editor so is there a particular way that you suggest we code responsiveness? any help on making my template responsive in mosaico would be greatly appreicated!

**Comment by bago** [comment]
Please give me something I can see and debug. It should simply work, you can see versafix-1 have many styles and it works fine... but I would not be surprised if you found a bug or a special edge case.

If you don't want to share your template in public send a zip to info at mosaico dot io.

**Comment by DanSnelson** [comment]
The Responsive code i was using used conditional tags which i have realised is not supported by mosaico which makes me feel silly! i've always coded responsive code like this so am now a bit stuck on how im going to code the responsiveness in. Any method you could suggest that you use that would work best? I've been deciphering through the code of the Versafix-1 to see how the responsiveness is coded in there. Cheers.
