### ISSUE TITLE
Roles & Permissions

### ISSUE THREAD

**Issue by jrodri-ariad** [voidlabs/mosaico#138]
Hi, I'd like to explore the possibility to restrict what certain user can edit or see in the editor, based on roles and permissions. Is there a good practice where to start to integrate such functionality using a custom plugin?

**Comment by bago** [comment]
I think this will need core changes.

Can you detail a real example / use case?

**Comment by jrodri-ariad** [comment]
Sure,

I have roles in my app, let's say there is  an admin who can edit/change the email header, and then there is a marketing specialist that will only be able to edit certain contents inside that block, such a phone number or the address, but not being able to delete it or to move it... And then there might be another role, that can only see the block, but not being able to edit it.

Anyways, I think I can make this happen by making the default template(template-versafix-1.html) dynamic, I mean, making it a php file and parsing it before feeding it to mosaico... but I'd like to see if there are options that I can implement in the resulting html that I can then check from mosaico tool to restrict certain actions, such as the dragging or deletion of specific blocks.

Thanks for any help!

**Comment by bago** [comment]
We evaluated the idea and decided this is out of scope for mosaico library, sorry. Closing this.
Of course this could change if anyone will produce a PR or sponsor the development.
