### ISSUE TITLE
Disable drag and/or sort for certain elements

### ISSUE THREAD

**Issue by jrodri-ariad** [voidlabs/mosaico#139]
I know this is not a functionality that mosaico would like to add to its core, but I wonder if someone could help me with this. I am trying to restrict certain content blocks (based on roles and permissions of the currently logged user) from being dragged or sorted.

So far, I have been able to overwrite in a plugin common viewmodel methods to add my check like this:

``` javascript
viewModel.moveBlock = function (index, parent, up) {
                if (permissions.canMove) {
                    var idx = ko.utils.unwrapObservable(index);
                    var parentBlocks = ko.utils.unwrapObservable(parent.blocks);
                    if ((up && idx > 0) || (!up && idx < parentBlocks.length - 1)) {
                        var destIndex = idx + (up ? -1 : 1);
                        var destBlock = parentBlocks[destIndex];
                        viewModel.startMultiple();
                        parent.blocks.splice(destIndex, 1);
                        parent.blocks.splice(idx, 0, destBlock);
                        viewModel.stopMultiple();
                    }
                } else {
                    viewModel.notifier.error("You are not authorized to remove content blocks");
                    return false;
                }
            };
```

Although, I haven't found a way to restrict the dragging using the tool handler in the element's toolbox. Is there any property I could add to my template (versafix-1.html) that can make this happen?

Thanks.

**Comment by bago** [comment]
> dragging using the tool handler in the element's toolbox

Do you mean the draggable "blocks" in the left pane? Or what else?
In order to alter the content of the draggable "blocks" try altering the viewModel.blockDefs object.

**Comment by jrodri-ariad** [comment]
To give you an example, I have restricted moving blocks using the plugin above, but the user can still drag them to a new position, and for some reason, this function is not called then (viewModel.moveBlock). Therefore, I need to either unbind the event attached to the handler on the tooltip of each content block on the editor.

On a similar way, I have restricted the adding by overriding the addBlock function:
```viewModel.addBlock = function (obj, event) {
          if (permissions.canAddBlock) {
               ...
          }else{
               ...
          }
```

That code works on the Add button on the left panel, but doesn't prevent the user dragging the block to the main container in the right.

When you suggest to modify the ```viewModel.blockDefs``` object, where do you think I should hook this code up? in a plugin as well? could you give me a little snippet of code on how would you hook this logic in?
 
Thanks a lot Bago.

**Comment by bago** [comment]
Create a plugin. A plugin receives a "viewModel" as argument (vm, viewmodel, viewModel.. the name depends on how you name it in your plugin).
Put a console.log(vm.blockDefs) there and see how this array of object is populated by default and alter this array in your plugin...

Unfortunately this will only remove the blocks from the "draggable blocks" area: I have no ideas right now about how to restrict move by drag and drop: I don't think you can do this via plugin, and you will have instead to change the code.
