### ISSUE TITLE
Linking directly to template

### ISSUE THREAD

**Issue by emu42** [voidlabs/mosaico#140]
Hello all,

for demo purposes I am trying to link directly to one of the given Mosaico templates like this:
https://test.system.com/editor.html#templates/versafix-1/template-versafix-1.html
This almost works. Except images are broken and cannot be uploaded. Is there an easy way to fix this?

**Comment by bago** [comment]
I guess this is a bug introduced by #31 in editor.html

```javascript
  var basePath = window.location.href.substr(0, window.location.href.lastIndexOf('/'));
```
Change this line to something like:

```javascript
  var basePath = window.location.href;
  if (basePath.lastIndexOf('#') > 0) basePath = basePath.substr(0, basePath.lastIndexOf('#'));
  if (basePath.lastIndexOf('/') > 0) basePath = basePath.substr(0, basePath.lastIndexOf('/'));
```

Let me know.

**Comment by emu42** [comment]
Yep. That seems to work fine now. Thanks!
