### ISSUE TITLE
Background color tags

### ISSUE THREAD

**Issue by DanSnelson** [voidlabs/mosaico#142]
I am currently very close to completion of intergrating Mosaico to my platform and am currently creating a master template (similar to versafix) for customers to use when they load the editor. 

I am struggling intergrating the background colours. Some of my blocks use it fine and allow the backgroudn colors to be edited but a lot of my blocks crash mosaico and dont let the template load when background colours are added. 

All of the other editable tags are wokring but the background color is just not working no matter hwo many different ways i try to add the tag. 

I have attached a txt file. The title block works fine but the text block does not.
[code example.txt](https://github.com/voidlabs/mosaico/files/261604/code.example.txt)

**Comment by bago** [comment]
What do you mean with "crash mosaico"? Browser crash? What browser? Have you tried a different browser?

Or maybe it simply doesn't start correctly? Please, have a look at javascript console, because mosaico sends there a lot of output.

**Comment by DanSnelson** [comment]
I'll get the back end developer to have a look. I basically am doig the front end template design but we have someone else who does all the backend coding so i dont have access to the javascript console. But yeah the template doesn start correctly.

**Comment by bago** [comment]
Mosaico does some "check" while loading/parsing the template and sometimes gives useful logs. Some other times the errors are cryptic, but at this time if you want to deal with the templating language you will have better luck if you install node and start the mosaico backend so to test changes while you make them... otherwide debugging a full template written without "validation" may be really complex.

I'm sorry at this time the template language is not too "user friendly".
