### ISSUE TITLE
unable to start mosaico 

### ISSUE THREAD

**Issue by tybsjd** [voidlabs/mosaico#143]
I am using windows and wamp server.
i have downloaded the zip and after unzip place Mosaico PHP Backend files in it...but i am getting file missing error of 404.. 
127.0.0.1/:23 GET http://127.0.0.1:9006/mosaico-master/dist/mosaico-material.min.css 
127.0.0.1/:24 GET http://127.0.0.1:9006/mosaico-master/dist/vendor/notoregular/stylesheet.css 
(index):27 GET http://127.0.0.1:9006/mosaico-master/dist/vendor/jquery.min.js 
(index):26 GET http://127.0.0.1:9006/mosaico-master/dist/vendor/knockout.js 
(index):52 Uncaught ReferenceError: ko is not defined(anonymous function) @ (index):52
(index):292 Uncaught ReferenceError: $ is not defined(anonymous function) @ (index):292
(index):302 GET http://127.0.0.1:9006/mosaico-master/dist/img/mosaicologo.png 404 (Not Found)
(index):302 GET http://127.0.0.1:9006/mosaico-master/dist/img/byvoxmail.png 404 (Not Found)

npm and grunt is working on cmd.

Can you please help me ?

**Comment by bago** [comment]
Please read the Readme. If you have issues with the PHP backend, refer to their issue tracking (I can't help here with the php backend).

**Comment by tbaraiya** [comment]
I have this error to.. Please help @bago

**Comment by bago** [comment]
read the readme.
