### ISSUE TITLE
Cannot ulpoad image 404 code

### ISSUE THREAD

**Issue by yahyyya1234** [voidlabs/mosaico#145]
I have two problems, for imageTrick i install it correctly the commande convert shows the help in terminal.
my second problem is that I cannot upload image to `http://localhost/mosaico-master-7/backend-php/upload/` and the message error is : 

> localhost/:1 GET http://localhost:9006/backend-php/img/?method=placeholder&params=534%2C200 404 (Not Found)
> jquery.js:9664 POST http://localhost:9006/backend-php/upload/ 404 (Not Found)

how can i fix that please
For info my php version of mosaico is inside of the nodeJs version.
Thank you

**Comment by bago** [comment]
I can't answer questions about php backend here: I don't use it and I don't know it.
Please test mosaico with its own backend and its own instructions and if you still have the issue then open a new issue including all of the informatoins requested in the Readme of this project. If you don't have issues with the built-in backend then go to the mosaico-php project and open an issue there (after reading carefully their Readme).
