### ISSUE TITLE
how can I access to editor.html whithout  passing by index.html

### ISSUE THREAD

**Issue by yahyyya1234** [voidlabs/mosaico#146]
Hi, thank you guys for you app it's really great we are three society that use it here in France, and my question is how would I do to access directly to editor.html without seeing the index page, that would so kind to get an answer from you .
thank's

**Comment by bago** [comment]
There is no configuration for this.
Try to understand the role of the "localStorage" (looking at index.html code and src/js/ext/localstorage.js) and the initialization code in src/js/app.js.

Once you understand that code it will be clean how you can do what you want, depending on your requirements.

**Comment by yahyyya1234** [comment]
I foud a solution is with mentionning this: `http://localhost/wifiVIP/metronic/theme/admin_3/editor.html#templates/versafix-1/template-versafix-1.html`, now I can access directly. thank you
