### ISSUE TITLE
remoove Gallery from the template

### ISSUE THREAD

**Issue by yahyyya1234** [voidlabs/mosaico#147]
Hi sir, thank you for your efforts, I will integrate your template into my site web i and would like to remove the item "Gallery" from the Navbar and I didn't get it. can you help me-out. thanks

**Comment by bago** [comment]
Easier solution: Add your own CSS to the page and hide that element via CSS.

Alternative solution: alter the content of src\tmpl\main.tmpl.html (look for "gallery") and rebuild mosaico.

**Comment by yahyyya1234** [comment]
I didn't understand you first solution (CSS). when looking to the second one I did see all of the li object : REDO UNDO BLOCK DOWLOAD expect of GALLERY I didin't find it.

**Comment by bago** [comment]
Take your time and check the file again.. I'm sure you can find it.

**Comment by yahyyya1234** [comment]
Noresult found for 'Galory', I'm sure

**Comment by bago** [comment]
Check your spelling.

**Comment by yahyyya1234** [comment]
i'm sorry i checked it

**Comment by yahyyya1234** [comment]
well i did it, and i'm so glad , what I did actually is : 
`1- opening build/mosaico.js, in the ligne 4096 seleting all divs and  spans that contains Gallery.`
`2- include build/mosaico.js in my editor.html`.
It works :p
