### ISSUE TITLE
I can't change the background-color of the toolbar 

### ISSUE THREAD

**Issue by yahyyya1234** [voidlabs/mosaico#150]
the css that define the background-color of the toolbar is in the file src/css/style_mosaico.less, despite im modifying the color it didn't change that's pretty unbelieveble

**Comment by yahyyya1234** [comment]
Problem solved.
I was trying to modify the .less . The .less is a compiled file so I create a new file . css into dist I prepare my modification into it I and call it into editor.html.
It's works perfectly.

**Comment by bago** [comment]
I don't get why you keep manually changing compiled filed. Just change the source and run "grunt" so that the library is recompiled. If you keep grunt running, then compilation is automatically done in the background and the browser automatically reload once compilation have been completed.

**Comment by yahyyya1234** [comment]
waw ok! I didn't know that thank's a lot
