### ISSUE TITLE
This isn't an issue, but a question or suggestion

### ISSUE THREAD

**Issue by NJseo** [voidlabs/mosaico#154]
What do you think about using Mosaico as a web page builder? It scales well, its easy to edit and follows the clean styles of many websites today.

**Comment by bago** [comment]
I know other users are trying to use it as a landing-page editor.

Mosaico has been developed and architected thinking to email templates, so I don't really know how easy it can be to use it for web pages.

Mosaico architecture is very generic, so I think it can be probably be adapted to do that, but don't expect to do that without working a lot in the code: it will probably be faster than writing an editor from scratch, but not as easy as changing some configuration and some lines of code.
