### ISSUE TITLE
Creating a new style Tag

### ISSUE THREAD

**Issue by DanSnelson** [voidlabs/mosaico#155]
HI, 

I am trying to create a new variable for buttons that have a 1px border. 

I want to be able to change the color of the border so need to create a new tag but not sure how to do this.

I tried this " border-color {label: Border Color; widget: color } " But this did not work. 

Any help appreciated

Dan

**Comment by bago** [comment]
1st: declare the variable (don't use "-" and keep in mind there is an "autodeprefix" rule that will automatically inherit from "color" if you name it "somethingColor")
```
borderColor { label: Border Color }
```

2nd: you have to use this variable in your template. The editor only shows editing widgets for variables being really used in the current template.

**Comment by DanSnelson** [comment]
Tried that and it works brilliantly! 

Cheers for the help the template language is really clever. Very impressed

Again thanks for the help
