### ISSUE TITLE
Editor.html is just red

### ISSUE THREAD

**Issue by Daimeri** [voidlabs/mosaico#156]
Hi, I did build mosaico with grunt, I also installed npm and grunt-cli

And yes i also read readme.md at root folder.

When i build with grunt i just get 1 error ERROR
>> Error: Cannot find module 'webpage'

when i start server i get this 
> cmd.exe /c grunt -b "C:\mosaico-master" --gruntfile "C:\mosaico-master\Gruntfile.js" server
Loading "phantom-thumbnailer-editor.js" tasks...ERROR
>> Error: Cannot find module 'webpage'
Running "express:dev" (express) task
Running "express-server:dev" (express-server) task
Web server started on port:9006, hostname: 127.0.0.1 [pid: 10288]
Running "watch" task
Waiting...

But even that i can see index webpage on my browser. When i try to use editor i just see red screen.
I am not a professional website front end coder this all is new to me. I did have coded couple of years in vb.net but that's it.  So maybe i do  something wrong here.

![mosaicoeditor](https://cloud.githubusercontent.com/assets/19730468/15799810/f91f2822-2a71-11e6-9616-24d9932c1412.png)
![mosaicoindex](https://cloud.githubusercontent.com/assets/19730468/15799811/f9233e12-2a71-11e6-985b-3d0aa63c2193.png)

**Comment by bago** [comment]
The webpage error and the thumbnailer errors are expected to be there.

Open the browser javascript console and paste here the logs being written when you load the editor page.

**Comment by Daimeri** [comment]
knockout-jqueryui.js:12 Uncaught TypeError: Cannot read property 'ui' of undefined
jquery.iframe-transport.js:42 Uncaught TypeError: Cannot read property 'ajaxTransport' of undefined
jquery.fileupload.js:38 Uncaught TypeError: Cannot read property 'support' of undefined
jquery.fileupload-process.js:35 Uncaught TypeError: Cannot read property 'blueimp' of undefined
jquery.fileupload-image.js:45 Uncaught TypeError: Cannot read property 'blueimp' of undefined
jquery.fileupload-validate.js:35 Uncaught TypeError: Cannot read property 'blueimp' of undefined
evol.colorpicker.min.js:6 Uncaught TypeError: a.widget is not a function
mosaico.js:720 Uncaught TypeError: Cannot read property 'sortable' of undefined
C:\mosaico-master\bower_components\knockout-sortable\build\knockout-sortable.min.js:2Uncaught TypeError: Cannot read property 'sortable' of undefined
C:\mosaico-master\bower_components\knockout-sortable\build\knockout-sortable.min.js:2Uncaught TypeError: Cannot read property 'sortable' of undefined
C:\mosaico-master\bower_components\knockout-sortable\build\knockout-sortable.min.js:2 Uncaught TypeError: Cannot read property 'sortable' of undefined
editor.html:42 Uncaught ReferenceError: Mosaico is not defined

**Comment by Daimeri** [comment]
Yay!, Now i can see editor. Im using visual studio 2015. Solution was that¨

navigate to the [Tools] > [Options] > Text Editor > JavaScript > IntelliSense > References options
select Implicit (Web)

"~/Scripts/_references.js" (if you want to put it in different place, change it here)
go to ~/Scripts and add new item "_references.js"
add /// <reference path="path\jquery-1.7.1.js" /> in "_references.js"

![supercooleditor](https://cloud.githubusercontent.com/assets/19730468/15805524/f7e2358e-2b35-11e6-8357-09c67757cb12.png)

**Comment by Daimeri** [comment]
I have my vb.net coded email marketing software, but mosaico editor is way better than my own. My plan is to get this editor working and maybe smelt this editor to my own project somehow.
