### ISSUE TITLE
How i can change mosaico editor language

### ISSUE THREAD

**Issue by Daimeri** [voidlabs/mosaico#158]
Hello.

I did get my mosaico up and working  today. Next step is to me change mosaico editor language.
There is a lots of code and files inside mosaico. I dont know where i can edit that spesific code where i can changes exsample this text. 
![mosaicolanguage](https://cloud.githubusercontent.com/assets/19730468/15828724/178e0082-2c19-11e6-983c-e7e82cf66a21.png)

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/tree/master/res/lang
