### ISSUE TITLE
Template rendering in outlook with white space on the edges

### ISSUE THREAD

**Issue by DanSnelson** [voidlabs/mosaico#159]
Hi guys, 

I have been using the versafix-1 template in mosaico and got white space splling out on the edge of these full width blocks 
![screentshot outlook](https://cloud.githubusercontent.com/assets/18598022/15935216/75f17838-2e5e-11e6-921b-67ae836e0594.png)

Any idea what is causing this and how i can fix this?

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico#rendering-issues-with-templates-generated-by-mosaico
