### ISSUE TITLE
Mosaico.init fail on Apache

### ISSUE THREAD

**Issue by MatiasSW** [voidlabs/mosaico#16]
Hello guys, 
Firstly I'd like to give you guys a thumbs up for this project, there are so extremely few projects for email editors, and this one looks promising. So best of luck with this!

I am trying to test it on Apache and while on grunt version works just fine, I keep getting "Missing initialization hash" on apache. Not sure if I missed any special steps though (Moved dist/ and editor.html to my Apache serving directory)

Any directions would be appreciatted.

**Comment by bago** [comment]
You need index.html too. 
Using the "demo code" index.html will show you the available templates, when you click on a template it creates a new instance of your template in your "localStorage" and then redirect to the editor page passing the key of the template you want to edit (the key to the localstorage stored by the index). So if you call direclty the editor.html it won't find a this key and give you this error.

**Comment by MatiasSW** [comment]
Thanks a lot for your reply.
I completely ignored the index.html code and jumped straight with editor.
