### ISSUE TITLE
How to custom template that could add link to an img tag with src by default instead of uploading img?

### ISSUE THREAD

**Issue by xr** [voidlabs/mosaico#160]
Hi, thanks for creating such a nice tool, however, when i try to custom my own tpl, then have some problems. it looks like the default img src will only used for create thumbnails, but if i want to add link dynamically to a picture, how could i do that, i checked the existing tpls, it turns out that i have to upload images then create a link. but i do not want to upload images every time, i want to use that one just dynamically add links.

here is what i tried, but no events happen.
```
<a data-ko-link="someLogoLink.url" style="text-align:center;">
<img src="http://defaultImage.com/a.jpg" alt="" width="179" height="46">
</a>
```

thanks

**Comment by bago** [comment]
What's your issue with that code? Doens't it work as expected? Do you get an error?

Try to change "someLogoLink.url" to "someLogoUrl" (you don't need a "link" if you don't have a "text" content, too.

**Comment by xr** [comment]
OK, thanks, the previous problem was i can not add a "Link"  to the element, so now it looks fine now, thanks
