### ISSUE TITLE
Cannot apply default value to variable when using expressions

### ISSUE THREAD

**Issue by NJseo** [voidlabs/mosaico#161]
Getting issues.. Seemed be be working fine on previous server though. 

template-loader.js:212 ERROR: found unexpected -ko- attribute in compiled template footerBlock-show , you probably mispelled it: Array[3]0: "-ko-attr-href"1: "-ko-attr-src"2: "-ko-attr-alt"length: 3__proto__: Array[0]concat: concat()constructor: Array()copyWithin: copyWithin()entries: entries()every: every()fill: fill()filter: filter()find: find()findIndex: findIndex()forEach: forEach()includes: includes()indexOf: indexOf()join: join()keys: keys()lastIndexOf: lastIndexOf()length: 0map: map()pop: pop()push: push()reduce: reduce()reduceRight: reduceRight()reverse: reverse()shift: shift()slice: slice()some: some()sort: sort()splice: splice()toLocaleString: toLocaleString()toString: toString()unshift: unshift()values: values()Symbol(Symbol.iterator): values()Symbol(Symbol.unscopables): Object__proto__: Objectadder @ template-loader.js:212 11utils.js:61 

Before that set, I got this:

VM12005 extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'responseText' of undefined
    at chrome-extension://dloieblpdejbpjbpiaannihalhhjhebo/background.js:360:33handler @ VM12005 extensions::uncaught_exception_handler:8
template-loader.js:212 ERROR: found unexpected -ko- attribute in compiled template footerBlock-show , you probably mispelled it: Array[3]0: "-ko-attr-href"1: "-ko-attr-src"2: "-ko-attr-alt"length: 3__proto__: Array[0]concat: concat()constructor: Array()copyWithin: copyWithin()entries: entries()every: every()fill: fill()filter: filter()find: find()findIndex: findIndex()forEach: forEach()includes: includes()indexOf: indexOf()join: join()keys: keys()lastIndexOf: lastIndexOf()length: 0map: map()pop: pop()push: push()reduce: reduce()reduceRight: reduceRight()reverse: reverse()shift: shift()slice: slice()some: some()sort: sort()splice: splice()toLocaleString: toLocaleString()toString: toString()unshift: unshift()values: values()Symbol(Symbol.iterator): values()Symbol(Symbol.unscopables): Object__proto__: Objectadder @ template-loader.js:212

Any help would be appreciated.

**Comment by bago** [comment]
You probably altered the template in a wrong way so it is not "syntattically" valid for mosaico.
Check your template near the footerBlock or near the place you use "responseText".

**Comment by bago** [comment]
Also you titled this post in a way and then reported logs for a different issue... 
The title simply states a "fact": mosaico won't compute the default value for properties declared using expressions.. you wll have to put the default in the declaration, e.g:

Here is "imageWidth" declared with a default of 166 in the sideArticleBlock of versafix-1, because it is used in the template as "expressions", so the default cannot be read directly where the variable is used.
```
      sideArticleBlock { label: Image+Text Block; properties: backgroundColor titleVisible=true buttonVisible=true imageWidth=166 imagePos=left titleTextStyle longTextStyle buttonStyle  image  longText buttonLink; variant:imagePos; theme: contentTheme }
```

**Comment by NJseo** [comment]
Ok, so I bypassed my current implementation and drawn a template from your origninal mosaico/index page. And you are right, I will need to fix that. When I am getting now is a failure with the file upload which I am having problems addressing.

jquery.js:9664 XHR finished loading: POST "https://www.reviewlaunch.com/mosaico/php-backend/upload/".send @ jquery.js:9664ajax @ jquery.js:9215send @ jquery.fileupload.js:899_onSend @ jquery.fileupload.js:961(anonymous function) @ jquery-ui.min.js:6data.submit @ jquery.fileupload.js:667(anonymous function) @ jquery.fileupload.js:212j @ jquery.js:3148fireWith @ jquery.js:3260e.(anonymous function) @ jquery.js:3350j @ jquery.js:3148fireWith @ jquery.js:3260e.(anonymous function) @ jquery.js:3350j @ jquery.js:3148fireWith @ jquery.js:3260e.(anonymous function) @ jquery.js:3350j @ jquery.js:3148add @ jquery.js:3194(anonymous function) @ jquery.js:3308j @ jquery.js:3148fireWith @ jquery.js:3260(anonymous function) @ jquery.js:3312j @ jquery.js:3148fireWith @ jquery.js:3260(anonymous function) @ jquery.js:3312j @ jquery.js:3148fireWith @ jquery.js:3260e.(anonymous function) @ jquery.js:3350j @ jquery.js:3148add @ jquery.js:3194(anonymous function) @ jquery.js:3308j @ jquery.js:3148fireWith @ jquery.js:3260(anonymous function) @ jquery.js:3312j @ jquery.js:3148fireWith @ jquery.js:3260(anonymous function) @ jquery.js:3312j @ jquery.js:3148fireWith @ jquery.js:3260e.(anonymous function) @ jquery.js:3350j @ jquery.js:3148add @ jquery.js:3194(anonymous function) @ jquery.js:3308j @ jquery.js:3148fireWith @ jquery.js:3260e.(anonymous function) @ jquery.js:3350j @ jquery.js:3148fireWith @ jquery.js:3260(anonymous function) @ jquery.fileupload-image.js:165g.onload @ load-image.all.min.js:1
fileupload.js:304 fileuploadfail m.Event {type: "fileuploadfail", timeStamp: 1466344489076, jQuery1113003946079412540415: true, target: input.fileupload.nofile, isTrigger: 3…}currentTarget: input.fileupload.nofiledata: undefineddelegateTarget: input.fileupload.nofilehandleObj: ObjectisTrigger: 3jQuery1113003946079412540415: truenamespace: ""namespace_re: nullresult: undefinedtarget: input.fileupload.nofiletimeStamp: 1466344489076type: "fileuploadfail"__proto__: Object Object {disabled: false, create: null, dropZone: m.fn.init[1], replaceFileInput: false, singleFileUploads: true…}_bitrateTimer: Object_processQueue: Object_progress: Object_response: Object_time: 1466344488891abort: ()acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/iadd: (e, data)autoUpload: truebind: "fileupload: { data: _src, onerror: $root.notifier.error, onfile: $root.loadImage, canvasPreview: true }"bitrate: 41558857.14285714bitrateInterval: 500blob: nullcache: falsecanvasPreview: truecontentType: falsecreate: nulldata: FormDatadataType: "json"disableImageResize: falsedisabled: falsedropZone: m.fn.init[1]errorThrown: SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at m.parseJSON (https://www.reviewlaunch.com/mosaico/dist/vendor/jquery.min.js:5:15998)
    at Pb (https://www.reviewlaunch.com/mosaico/dist/vendor/jquery.min.js:5:18379)
    at x (https://www.reviewlaunch.com/mosaico/dist/vendor/jquery.min.js:5:21793)
    at XMLHttpRequest.b (https://www.reviewlaunch.com/mosaico/dist/vendor/jquery.min.js:5:26030)fileInput: m.fn.init[1]files: Array[1]forceIframeTransport: falseform: m.fn.initformAcceptCharset: undefinedformData: (form)getNumberOfFiles: ()headers: Objecti18n: (message, context)imageCrop: falseimageMaxHeight: 1080imageMaxWidth: 1920imageOrientation: falsejqXHR: ObjectlimitMultiFileUploadSizeOverhead: 512loadImageFileTypes: /^image\/(gif|jpeg|png|svg\+xml)$/loadImageMaxFileSize: 10000000loaded: 72728maxFileSize: 1048576messages: Objectmultipart: trueonerror: t(e,t,n)onfile: (e)originalFiles: Array[1]paramName: Array[1]pasteZone: m.fn.initpreviewCanvas: truepreviewCrop: falsepreviewMaxHeight: 200previewMaxWidth: 200previewOrientation: truepreviewThumbnail: trueprocess: (resolveFunc, rejectFunc)processData: falseprocessQueue: Array[9]processing: ()progress: ()progressInterval: 100recalculateProgress: truereplaceFileInput: falseresponse: ()sequentialUploads: falsesingleFileUploads: truestate: ()submit: ()textStatus: "parsererror"total: 72728type: "POST"uploadedBytes: 0url: "https://www.reviewlaunch.com/mosaico/php-backend/upload/"xhr: ()__proto__: Object

**Comment by bago** [comment]
Please don't reuse issues for different things than their subject.
You're using the PHP  backend so I cannot help: try asking in the mosaico php backend project.

If you have the same issue using the bundled node.js backend then open a new issue here.

Please make sure you fully read the Readme.md in the root of this project before you open more issues.
