### ISSUE TITLE
How to override applyBindingOptions method ?

### ISSUE THREAD

**Issue by lphm** [voidlabs/mosaico#162]
Hi,
I would like to develop a custom method to generate host based URLs for images **and** paths without host for images resizing.
For example :
- http://assets.domain.com/filename.jpg for real images path
- /images?src=filename.jpg&resize=300x300 for resizing

I saw the method "applyBindingOptions" that apparently contains the code to generate URLs.
How can I create custom method and tell Mosaico to use this custom applyBindingOptions method.

Maybe there's a simpler solution to meet this need?
Thanks for your help.

**Comment by bago** [comment]
I think you can provably override that method in a [mosaico plugin](https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins).

The "ko" is a global variable, so you can access it inside the plugin.
Just change the "ko.bindingHandlers.wysiwygSrc.convertedUrl" to use your own code in a "mosaico plugin" and pass this plugin to Mosaico.init/start.

Please keep me informed about your final solution, so I will take it into consideration when I make changes to Mosaico initialization/plugin.

**Comment by bago** [comment]
No feedback, closing issue.
