### ISSUE TITLE
dynamic table

### ISSUE THREAD

**Issue by michalfeher** [voidlabs/mosaico#163]
Is it possible to generate table rows and columns dynamically? or do I need one block for each table combination (rows x columns)? for example one block for 3x3 table, another one for 4x3 etc.
thank you.

**Comment by bago** [comment]
The mosaico template language does not implement loops.
Maybe you can implement something with the "-ko-display" and conditions agains a number (e.g: -ko-display="tableRowsSize > 3" ) but I'm not sure it will work fine.

**Comment by bago** [comment]
Please describe your use-case / share a sample of your layout-template

**Comment by bago** [comment]
15 days, no answers. Closing.
