### ISSUE TITLE
demo and code doesnt seem to be 1:1

### ISSUE THREAD

**Issue by michalfeher** [voidlabs/mosaico#164]
when I clone the repo and play around versafix template, this is the format options I have
![image](https://cloud.githubusercontent.com/assets/7691204/16311274/30b96e3e-3970-11e6-94c8-a114902955d8.png)

however, this is what is in demo on the web:
![image](https://cloud.githubusercontent.com/assets/7691204/16311298/4cdc414a-3970-11e6-8af0-d6da3c77b11a.png)

I am missing options like bulletlist, line height etc.

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico#live-demo
