### ISSUE TITLE
How can I change default background color

### ISSUE THREAD

**Issue by jordivaleri** [voidlabs/mosaico#165]
First, thank you for your good work! My question is how can I change background default color #bfbfbf for all blocks, actually I created my own template with my personal blocks but when Im trying to changing in embedded style or script style doesn't work, need help to find it, Thank you!

**Comment by bago** [comment]
I don't understand the question... are you asking how to change color via the interface as a final user?
Or are you asking how to alter the master template so to create a new template with different default behaviour?

In this last case then open templates/versafix-1/template-versafix-1.html and replace every #bfbfbf you find with your own new color, then create a new mosaico email on this template.

**Comment by jordivaleri** [comment]
Yea i had problems with styles, but changing in all blocks worked!, Thank you!
