### ISSUE TITLE
compilation of css from less failed.

### ISSUE THREAD

**Issue by aermicioi** [voidlabs/mosaico#169]
While running grunt after installation of mosaico I get following error, on less:css task:
```
Running "less:css" (less) task
>> FileError: '../../bower_components/toastr/toastr.css' wasn't found. Tried - bower_components/toastr/toastr.css,bower_components/toastr/toastr.css,../../bower_components/toastr/toastr.css in src/css/app_standalone.less on line 6, column 1:
>> 5 
>> 6 @import (less) "../../bower_components/toastr/toastr.css";
>> 7
Warning: Error compiling src/css/app_standalone.less Use --force to continue.

Aborted due to warnings.
```

On a machine with following characteristics:
Os: Debian sid.
nodejs v4.4.6, 
npm v1.4.21
Globally installed packages:
bower@1.7.9
bower-npm-install@0.5.11
cordova@6.2.0
grunt-cli@1.2.0
gulp@3.9.1
ionic@1.7.16
jspm@0.16.39
nodemon@1.9.2

Probably something fails, and bower_components folder which is in vendor folder is not linked, or copied, in root folder of mosaico and less preprocessor fails to find toastr.css file.
I think it is related to following bug: https://github.com/voidlabs/mosaico/issues/168

Thank you.

**Comment by bago** [comment]
If install fails then it is normal that other things don't work. So please don't open more issues for other tasks until you are able to install correctly.
