### ISSUE TITLE
Missing "dist" folder

### ISSUE THREAD

**Issue by brittk** [voidlabs/mosaico#17]
Hey guys,

I've just downloaded the zip of mosaico which seems awesome.
I uploaded it on my server but I've a lot of missing files (all from the 'dist' folder).
Am I missing something?

Thanks!

**Comment by bago** [comment]
On 8 October 2015 at 12:39, brittk <notifications@github.com> wrote:

> Hey guys,
>
> I've just downloaded the zip of mosaico which seems awesome.
> I uploaded it on my server but I've a lot of missing files (all from the
> 'dist' folder).
> Am I missing something?
>
The download is still a "source distribution", so you have to follow Readme
instructions to build it.

Stefano

**Comment by brittk** [comment]
Thanks Stefano, we'll give it a try!

**Comment by bago** [comment]
I close this. Please reople if compiling didn't create the dist folder.

**Comment by sean-thorburn** [comment]
I have built as per https://travis-ci.org/voidlabs/mosaico/jobs/95390454.

I have no dist directory.
only 'bower_components' and 'node_modules'
