### ISSUE TITLE
Conditionnal comment Outlook 120 dpi broken

### ISSUE THREAD

**Issue by Frolipon** [voidlabs/mosaico#170]
Hello,

It seems there is a problem on the conditionnal comment specific for the Outlook. For the 120 dpi Outlook, we use the following patch in the HTML (after the style, just before head)

```
<!--[if gte mso 9]><xml>
 <o:OfficeDocumentSettings>
  <o:AllowPNG/>
  <o:PixelsPerInch>96</o:PixelsPerInch>
 </o:OfficeDocumentSettings>
</xml><![endif]-->
```

And in the output code we have this: 

```
<!--[if gte mso 9]><xml>
 <o:officedocumentsettings>
  <o:allowpng></o:allowpng>
  <o:pixelsperinch>96<!-- cc:before:cco:PixelsPerInch --><!-- cc:after:cco:PixelsPerInch -->
 <!-- cc:before:cco:OfficeDocumentSettings --><!-- cc:after:cco:OfficeDocumentSettings -->
<![endif]-->
```

The result is that every Outlook except 2011 and on Mac will not render the email at all. Just a blank page. Is there a way to fix this?

Kind regards,

Grégory

**Comment by Hiswe** [comment]
Because it's a generic fix to this outlook problem, I think it should be better to inject this code directly from the `viewModel.exportHTML` function.

It avoids to duplicate this code in every template, keep the parser function untouched and fix this issue in all existing templates.

@bago Is that an acceptable solution?

**Comment by bago** [comment]
@Hiswe I'd like to keep mosaico NOT aware of template contents, hacks, details. So I think mosaico should be able to accept that kind of content in templates and keep it in the output.
Mosaico does something to "decomment" conditional comments so that variable interpolations can be made also on commented code... maybe this cannot be done for xml or other special code.. I have to investigate it.
The fact that you see "cc:before" comment means that html manipulation to decomment/recomment the code is not working

**Comment by bago** [comment]
Can you do a test for me?
Open this file:
https://github.com/voidlabs/mosaico/blob/master/src/js/converter/parser.js#L387
Change the [A-Za-z]* to [A-Za-z:]* (so that it accept ":" in the tag names) and rebuild mosaico, then reopen your template.

Let me know.

**Comment by Hiswe** [comment]
@bago Thanks for the answer. That make perfect sense.

I'll run the test tomorrow :)

**Comment by Hiswe** [comment]
@bago Nope

Still having:
```html
<!--[if gte mso 9]><xml>
 <o:officedocumentsettings>
  <o:allowpng></o:allowpng>
  <o:pixelsperinch>96<!-- cc:before:cco:PixelsPerInch --><!-- cc:after:cco:PixelsPerInch -->
 <!-- cc:before:cco:OfficeDocumentSettings --><!-- cc:after:cco:OfficeDocumentSettings -->
<![endif]-->
```

**Comment by bago** [comment]
Weird.. I tested the change and it worked fine here... are you sure you correclty rebuit mosaico after you did the change?

**Comment by Hiswe** [comment]
@bago thanks for the 2 commits.
Unfortunately this still doesn't work for me after rebuilding.
I have this now:

```html
<!--[if gte mso 9]>&gt;<![endif]-->
```

I'll make a test case and try to fix this issue by my own.

Thanks again.

**Comment by bago** [comment]
Sorry, try again now.. hope this is the last time.

**Comment by Hiswe** [comment]
@bago Thanks again.

Going better in a way:

This is preserved:

```html
<!--[if !mso]><!-->
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
<!--<![endif]-->

<!--[if (gte mso 9)|(IE)]>
  <style type="text/css">
    table {border-collapse: collapse;}
  </style>
<![endif]-->
```

But the initial issue:

```html
<!--[if gte mso 9]><xml>
 <o:OfficeDocumentSettings>
  <o:AllowPNG/>
  <o:PixelsPerInch>96</o:PixelsPerInch>
 </o:OfficeDocumentSettings>
</xml><![endif]-->
```

is still rendered as 

```html
<!--[if gte mso 9]><xml>
  <o:officedocumentsettings>
    <o:allowpng></o:allowpng>
    <o:pixelsperinch>96<!-- cc:before:cco:PixelsPerInch --></o:pixelsperinch><!-- cc:after:cco:PixelsPerInch -->
  <!-- cc:before:cco:OfficeDocumentSettings --></o:officedocumentsettings><!-- cc:after:cco:OfficeDocumentSettings -->
</xml><![endif]-->
```

Beside the `<!-- cc:before:cco:PixelsPerInch -->` there is 2 strange things going on:

- xml tags are expanded (`<o:AllowPNG/>` ➡️  `<o:allowpng></o:allowpng>`)
- xml tags are lowercased (`  <o:PixelsPerInch>`  ➡️   `<o:pixelsperinch>`)

**Comment by bago** [comment]
Argh... I should really take some time to look at this better and write some test case... :-(

BTW, I can probably fix the "cc:before" issues but the case and tag expansion is something done by the browser... I'm not sure I can prevent this while leaving those tag "parsed".. otherwise I should implement a way to tell mosaico that a given conditional comment doesn't need to be parsed, so it will leave the comment as a comment.

**Comment by bago** [comment]
Can you test if the directives works in Outlook when you change the case and you create the "expanded tag" (open+close instead of the self-closed)?

**Comment by bago** [comment]
I added some more logic so to wrap most tags in comments and rebuild them when generating output... I hope I will find some time to create tests for this.. in the mean time let me know if this works or not.

**Comment by Hiswe** [comment]
Ok I'll try to test it asap.

I think, I'll handle mso xml comment server-side on my custom back-office. 
It'll be more reliable for me to add this code as close as possible as MS provides it.
I know it breaks the main purpose of Mosaico front-app to be plugable with any BO :S

By the way, the `viewModel.exportHTML` function relying on `outerHTML` makes also some other issues for me, like converting text like `<% firstname %>` to `&lt;% firstname %&gt;`…

I should try to remove the use of the iframe for generating the HTML, but my knowledge in knockout is limited.
I've try to read the [documentation](http://knockoutjs.com/documentation/introduction.html) but I haven't seen any list of knockout methods.

As KO introduction says it is a `Pure JavaScript library - works with any server or client-side technology`. So if it can be rendered server-side, It should be able to be rendered without the Iframe. 
But I'm sure you've been using the iframe on purpose, even if as for now I can't see the benefits :(

Again, many thanks for the efforts you're putting in Mosaico!

n.b: Do you have any links that has a full description of knockout API?

**Comment by Hiswe** [comment]
@bago You're the best.
Works perfectly now. Just expand the `<o:AllowPNG></o:AllowPNG>` tag

**Comment by bago** [comment]
Can you tell me which browser/browser version did you test? In my Chrome the AllowPNG was correctly restored as "self-closing", but I know this may change from browser to browser and I didn't have the time to check the other browsers.

**Comment by Hiswe** [comment]
My bad. It was my test file that was bad.
Everything's preserved.

So perfect job :)
