### ISSUE TITLE
Save not showing image in Chrome and Opera

### ISSUE THREAD

**Issue by NkDimi** [voidlabs/mosaico#172]
Hello, 
When I click on Save button template is save but image disappeared and I need to reload page to see them. In Firefox and Safari everything working fine.
this is in Chrome
![screen shot 2016-07-06 at 10 20 13](https://cloud.githubusercontent.com/assets/11389050/16611727/6a71d79a-4363-11e6-9178-ec83b97b9dc8.png)
this is in Firefox
![screen shot 2016-07-06 at 10 21 00](https://cloud.githubusercontent.com/assets/11389050/16611739/7e198b44-4363-11e6-8cf6-945b856e1642.png)

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico#issues-runningediting

**Comment by NkDimi** [comment]
I am using `template-versafix-1`
Operation system: `Amazon Linux AMI 2016.03.3 (HVM), SSD Volume Type`
Version: `ImageMagick 6.7.8-9 2016-06-22 Q16 http://www.imagemagick.org`
`npm -v 3.9.6`
`node -v v5.9.1`
background grunt 
```
npm list --depth=0
mosaico@0.14.0
├── aliasify@1.9.0
├── async@0.9.0
├── autoprefixer-core@5.2.1
├── body-parser@1.13.3
├── bower@1.4.1
├── bower-npm-install@0.5.10
├── browserify@11.0.1
├── browserify-shim@3.8.10
├── cheerio@0.19.0
├── csswring@3.0.7
├── deamdify@0.1.1
├── debowerify@1.2.0
├── express@4.14.0
├── gm@1.18.1
├── grunt@0.4.5
├── grunt-bowercopy@1.2.0
├── grunt-browserify@4.0.0
├── grunt-contrib-connect@0.9.0
├── grunt-contrib-copy@0.8.2
├── grunt-contrib-jshint@0.11.2
├── grunt-contrib-less@1.0.1
├── grunt-contrib-watch@0.6.1
├── grunt-exorcise@2.0.0
├── grunt-express@1.4.0
├── grunt-jasmine-node-coverage@0.4.1
├── grunt-newer@1.1.1
├── grunt-postcss@0.6.0
├── jasmine-core@2.3.4
├── jasmine-node@1.14.5
├── jquery-file-upload-middleware@0.1.7
├── jshint-stylish@2.0.1
├── load-grunt-tasks@3.1.0
├── lodash@3.10.1
├── mockery@1.4.0
├── morgan@1.6.1
├── nodemailer@1.4.0
├── phantomjs@1.9.16
├── styliner@0.8.9
├── uglifyify@3.0.1
└── watchify@3.3.1

```

**Comment by bago** [comment]
PLEASE READ AGAIN THE README: did you test mosaico.io ? Do you see the same issue?
If you expect to receive help from me you have to take the time to read and understand the readme and provide full informations in the report.

**Comment by NkDimi** [comment]
Hallo bago, 
I test same scenario on https://mosaico.io and I do not have problem as I have on our server. We also using nginx on our server can that be problem? But in Firefox and Safari is working same as on mosaico.io. Also i notice when I sending test email same thing is happening when I click on TEST image disappeared and after reloading they are there. I am using your `server-config.js` only with AWS credential.

**Comment by bago** [comment]
I never heard your problem before, so I guess it is something in your chrome or in your specific setup (nginx). The error you describe is very weird and I exclude this may be something with mosaico itself.

**Comment by NkDimi** [comment]
hallo bago
just if you can tell me explanation about this error that i am getting now
![screen shot 2016-07-06 at 13 52 06](https://cloud.githubusercontent.com/assets/11389050/16616962/00ae4546-4381-11e6-9e3d-84749ec8bbe5.png)
thank you.

**Comment by bago** [comment]
Is this related to "Save not showing image in Chrome and Opera"?

**Comment by NkDimi** [comment]
yes this is related to same question "Save not showing image in Chrome and Opera" this is error when I want to save on Chrome, after saving before reloading page to show images.

**Comment by bago** [comment]
That error means the template syntax is wrong. If you didn't change the templates provided by mosaico then you have something in the middle breaking it.

**Comment by NkDimi** [comment]
hello bago, 

i found where is problem in src/js/app.js on line 28

```
var applyBindingOptions = function(options, ko) {
	  // push "convertedUrl" method to the wysiwygSrc binding
	  ko.bindingHandlers.wysiwygSrc.convertedUrl = function(src, method, width, height) {
	    var imgProcessorBackend = options.imgProcessorBackend ? options.imgProcessorBackend : './upload';
	    var backEndMatch = imgProcessorBackend.match(/^(https?:\/\/[^\/]*\/).*$/);
	    var srcMatch = src.match(/^(https?:\/\/[^\/]*\/).*$/);
	    if (backEndMatch === null || (srcMatch !== null && backEndMatch[1] == srcMatch[1])) {
	      return imgProcessorBackend + "?src=" + encodeURIComponent(src) + "&method=" + encodeURIComponent(method) + "&params=" + encodeURIComponent(width + "," + height);
	    } else {
	      console.log("Cannot apply backend image resizing to non-local resources ", src, method, width, height, backEndMatch, srcMatch);
	      return src + "?method=" + method + "&width=" + width + (height !== null ? "&height=" + height : '');
	    }
	  };

  ko.bindingHandlers.wysiwygSrc.placeholderUrl = function(width, height, text) {
    return options.imgProcessorBackend + "?method=" + 'placeholder' + "&params=" + width + encodeURIComponent(",") + height;
  };
```
there is not resizing so that is the reason why images not showing before reloding. Also he can not find `srcmatchhttp:`  do you have some advice about this? Can be this because of nginx?

**Comment by cameronhaddad** [comment]
I had a similar issue when i was saving.  I was using a plugin, and exporting the HTML out from the view model at the same time, and this was actually what caused the viewer to break.

I found a workaround to reimport the JSON to the viewer and this redrew the page and fixed the images.

```
var tm_meta = window.viewModel.exportMetadata();
var tm_json = window.viewModel.exportJSON();
var tm_cont = window.viewModel.exportHTML();

//Reset JSON to fix image (as exportHTML breaks viewer)
window.viewModel.importJSON(tm_json);

```

**Comment by bago** [comment]
@cameronhaddad this sounds weird and new to me.. if you have a way to reproduce the issue, please submit a new specific issue. I use the 3 export functions and the editor keep working fine.

**Comment by bago** [comment]
@NkDimi you say "there is not resizing so that is the reason why images not showing before reloding. Also he can not find srcmatchhttp: do you have some advice about this? Can be this because of nginx?" but you are trying to guess.. if images are not resized then they will show up unresized.. why do you think that "not resizing" would mean "not showing"? Why do you search for issue in mosaico code when the issue happens only in your deployment with your backend? Also, if you have a console error about ko issues then you are using a broken template: if you modified it then try with the default template, if you didn't change it then try to understand if your webserver does any alteration before serving html (the template is retrieved by the client using an HTTP request).

**Comment by NkDimi** [comment]
I resolve this issue switching on PHP Backend.
