### ISSUE TITLE
how do I uninstall?

### ISSUE THREAD

**Issue by robbrich** [voidlabs/mosaico#173]
how do I uninstall? I tried cd to directory, $ sudo npm uninstall but that doesn't work. just wondering in case it doesn't end up being something that I can use.

thanks

**Comment by bago** [comment]
mosaico doesn't install anything... you can simply remove the folder where you checked out or unzipped the source code.

The only things being installed outside from mosaico folder are things you installed manually (node, or grunt). Node should have its own unistaller. Grunt can probably be unistalled with  "npm uninstall -g grunt-cli"
