### ISSUE TITLE
Issue creating thumbnails.

### ISSUE THREAD

**Issue by zrb0529** [voidlabs/mosaico#174]
Mac OS Sierra 10.12
Node 6.2.1
Grunt CLA 1.2.0

Steps followed:

- download Mosaico from github, extract mosaico-master to /sites
- Create in /templates new directory 'myNewTemplate' duplicate tutorial template into myNewTemplate directory, rename to template-myNewTemplate.html
- CD to /sites/mosaico-master
- npm install

npm WARN mosaico@0.14.0 No repository field.
npm WARN mosaico@0.14.0 license should be a valid SPDX license expression

grunt makeThumbs:main:myNewTemplate

(node:7695) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
>> Local Npm module "grunt-parallel" not found. Is it installed?
Loading "phantom-thumbnailer-editor.js" tasks...ERROR
>> Error: Cannot find module 'webpage'

Running "makeThumbs:main:myNewTemplate" (makeThumbs) task
Creating thumbnails for templates [ './templates/myNewTemplate/template-myNewTemplate.html' ]
Creating thumbnail ./templates/myNewTemplate/template-myNewTemplate.html

PhantomJS threw an error:ERROR
>> 0 [ '' ]
Fatal error: failCode is not defined

**Comment by bago** [comment]
Well, the makeThumb referenced a missing variable in an "error printing code".
I just committed a fix so to not use failCode.

BTW if you got that error you have issues with executing "phantomjs" (an headless browser) we use to make thumbnailer .

You can ignore the other errors (webpage, grunt-parallel, SPDX): they are expected.

**Comment by emu42** [comment]
Apparently phantomjs does not work on my system either. I am getting the same error using the latest version from git.

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/commit/c6100b8191277f020cee1933d5871678a87139ec

"Same issue" means you still see "Fatal error: failCode is not defined" ?? I think I removed failCode references and you now should see a "more informative error". (so it won't work but it should say it is about something wrong with phantom, now)

**Comment by emu42** [comment]
No, I was merely referring to these two lines:

> Loading "phantom-thumbnailer-editor.js" tasks...ERROR
> Error: Cannot find module 'webpage'

No further error message. In fact "grunt build" completes with "Done, without errors." despite that.

I suspect this has something to do with my NodeJS environment being a bit dated. I'll try updating things and post here whether it solved the problem.

**Comment by bago** [comment]
"Node 6.2.1" is more updated than most environment where I built mosaico.
The errors loading tasks and cannot find "webpage" are not real errore: I see them all the time, but I can build mosaico and build thumbnails.

So, can you please paste the full output of your "makeThumbs:main:myNewTemplate" ? This is a standalone task that doesn't have anything related to the build of mosaico or the way mosaico works. It is just an utility to build thumbnails for templates.

**Comment by bago** [comment]
I did another change so to remove that misleading "Cannot find modue webpage" error.
