### ISSUE TITLE
About backend

### ISSUE THREAD

**Issue by rokatto** [voidlabs/mosaico#175]
Hi and thanks for this great job with Mosaico!

I have been testing Mosaico for a few weeks, modifying templates, etc, but i have not been able to make it work on Apache properly. I have read the documentation about serving Mosaico but i think my knowledge of the subject are insufficient to understand it.

What i have done is copying Mosaico folder on Apache and run Grunt.

I have tried on Ubuntu and Centos VMs with the same problems, issues uploading images and downloading the resulting HTML. I have installed ImageMagick and it's working without problems in a folder locally so i think the problem is just serving it with Apache.

I also read this -> https://github.com/ainterpreting/mosaico-php-backend but i don't understand where i have to copy the files or if i have to change something else.

Thanks in advance!
![error1](https://cloud.githubusercontent.com/assets/15254333/16796326/6a62bc68-48e2-11e6-82a7-2bbca335cdb0.jpg)
![error2](https://cloud.githubusercontent.com/assets/15254333/16796364/ad97d64e-48e2-11e6-915a-74a0b18bc669.jpg)

**Comment by nabenzine** [comment]
Just copy the php-backend directory in the root of your project where you have already template and dist directorys, then copy the editor.html of the mosaico-php-backend and not the original one, then in the mosaico.init configure your directory for example I have : 

var ok = Mosaico.init({
        imgProcessorBackend: '/backend-php/img',
        emailProcessorBackend: '/backend-php/dl',
        titleToken: "MOSAICO Responsive Email Designer",
        fileuploadConfig: {
          url: '/backend-php/upload',
          // messages??
        }
      });

**Comment by bago** [comment]
I can't accept issues regarding deployment with third party backends unless you provide informations about why you think the issue is with mosaico and not with the backend or the way you deployed the backend.

https://github.com/voidlabs/mosaico#are-you-having-issues-with-mosaico
