### ISSUE TITLE
versafluid template missing

### ISSUE THREAD

**Issue by nabenzine** [voidlabs/mosaico#176]
Hi and thanks for this amazing job with Mosaico!

I have noticed that the versafluid template is missing on github, could you please add it ?
 
![screenshot from 2016-07-13 12-52-50](https://cloud.githubusercontent.com/assets/7820285/16801044/c38f441c-48f8-11e6-9c20-107472af6855.png)

Thanks in advance!

**Comment by bago** [comment]
At this time we have no plan to opensource the versafluid template.

In the PR you say versaflui is "the most responsive", but I doubt that: what email client/device give you responsive result with versafluid and does not adapt with versafix? Versafix uses more modern (hybrid) solutions to get "adaptive results" also on Gmail App mobile, while versafluid can't do that.

**Comment by Rar9** [comment]
+1 please add
