### ISSUE TITLE
Achieve wysiwyg editor when toolbox is closed

### ISSUE THREAD

**Issue by jeeva0101** [voidlabs/mosaico#179]
Hi @bago

Fantastic work. Beautiful template builder.

I built Mosaico on my site and it's working fine. 

Also, I wanted to use Mosaico on iPad. For that I planned to toggle the left handside toolbox like image gallery and show only the edit area. i.e., on ipad the toolbox will be hidden by default and a button will be placed as a checkbox like image gallery on the top nav. so whenever I want to add new block I can click on the new button and add a new block in the edit area. I achieved this and able to toggle toolbox.

Now my problem is, If I click on the content in the edit area when tool box is closed, I am not able to edit the content i.e wysiwyg is not showing up. It's showing up only if toolbox is opened.

I want to edit content, and swap, copy or delete block(using orange color tools) even if toolbar is closed. Could you please give me some clue on this.

Thanks.

**Comment by bago** [comment]
It should simply work. Maybe you do something wrong hiding the toolbox...

on mosaico.io I open a javascript console and write:
```javascript
mosaicoViewModel.showToolbox(false);
```
wysiwyg editors keep working fine.

You won't have a global mosaicoViewModel variable, but you can expose it via plugin: https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins

**Comment by jeeva0101** [comment]
Thank you. It's working fine now.
