### ISSUE TITLE
Question: override _templateUrlConverter method

### ISSUE THREAD

**Issue by Hiswe** [voidlabs/mosaico#181]
Hi,

After checking this issue ( #162 ), I was wondering why `_templateUrlConverter` is not defined in KO, so we can easily override it.

I've done a workaround, but it should be cleaner if I only specify it in a `ko.bindingHandlers.wysiwygSrc.templateUrlConverter`

Same things goes also for the `templateLoader` function, which I had to tweek :)

If you have some thought about it, I'll be more than happy!

Thanks

**Comment by bago** [comment]
I'm not sure what's your problem.
Write a "plugin" (https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins)

```javascript
var plugin = function(vm) {
  ko.bindingHandlers.wysiwygSrc.templateUrlConverter = yourconverter;
}
```
pass this plugin to the Mosaico initialization.

**Comment by Hiswe** [comment]
As I understand your code:

1. in the [templateLoader function (line 140)](https://github.com/voidlabs/mosaico/blob/master/src/js/template-loader.js#L140) the `_templateUrlConverter` is affected to `templateUrlConverter`. 
2. Then `templateUrlConverter` is  [passed as an argument to templateCompiler](https://github.com/voidlabs/mosaico/blob/master/src/js/template-loader.js#L160)
3. Eventually this same `templateUrlConverter` function is passed again and again as an argument to any converter it needs.

I never see any call to any `ko.bindingHandlers.wysiwygSrc.templateUrlConverter` or an option to replace the `templateUrlConverter`

**Comment by bago** [comment]
Can you give me more details about what you are trying to do? It is probably harder to explain the whole code than understand what you're trying to achieve and give you "my solution".

**Comment by bago** [comment]
What I want to say is that "_templateUrlConverter" is a "path concatenation function": you are not supposed to change a "path concatenation function".. it is like you wanted to change "+" so to not make a sum... what is the goal?

**Comment by Hiswe** [comment]
All my templates are saved in DB and the related assets are uploaded on a CDN.
By doing so, all the image path of those assets are flattened.
In order to get the comited templates working without modifying them, I really need to alter path of their assets.

Also, I needed more control on the way certain path are ignored (see ESP below for an example)

```js
function templateUrlConverter(url) {
    if (!url) return null
    // handle: [unsubscribe_link] or mailto:[mail]
    if (/\]$/.test(url)) return null
    // handle absolute url: http
    if (/^http/.test(url)) return null
    // handle ESP tags: in URL <%
    if (/<%/.test(url)) return null
    // handle other urls: img/social_def/twitter_ok.png
    // as it is done, all files are flatten in asset folder (uploads or S3)
    url = /([^\/]*)$/.exec(url)[1]
    url = opts.imgProcessorBackend + opts.metadata._wireframe  + '-' + url
    return url
  }
```

**Comment by bago** [comment]
OK, now I understand it. I don't like the idea to put that method in "ko" (ko is a dependency and I don't want to pollute it with non-ko related stuff.

I'm not sure why you don't change the master template so to already have "flat urls" instead of flattening them in "runtime", considering that if you get them from a DB the paths don't make sense in any case.

We could "merge" the conditions to mosaico codebase so that <% is not "altered" and if your images urls are already flattened you would just need to change the template "basePath"... right?

(I like the idea that most users are able to use mosaico without patching it, but before I add new configurations I want to have a good understanding of the real need)

**Comment by Hiswe** [comment]
You're right that polluting ko is not a good idea.

It could be better to make it an option if you want to add the possibility for dev to alter this function. But the [templateLoader](https://github.com/voidlabs/mosaico/blob/master/src/js/template-loader.js#L132) doesn't have any access to those…

For the 2 problems:

#### Path

You're right I could have change the path in my templates.
But that alone won't suffice, as in `toolbox.tmpl.html` there is also [some path that are hardcoded](https://github.com/voidlabs/mosaico/blob/master/src/tmpl/toolbox.tmpl.html#L13):
```html
<img data-bind="attr: { alt: $root.t('Block __name__', { name: ko.utils.unwrapObservable(type) }), src: $root.templatePath('edres/'+ko.utils.unwrapObservable(type)+'.png') }" alt="Block __name__" />
```

It's a thing that I could fix with my backend by adding a route for `/edres/…`. I feel uncomfortable with this duplicated image route, but that could do the trick while letting the front mostly untouched,

#### ESP tags

It was mentioned also in this [issue](https://github.com/voidlabs/mosaico/issues/170#issuecomment-234459730)
I fixed this by altering the `_templateUrlConverter` and the `viewModel.exportHTML`. 
For the latter I added:
```js
content = content.replace(/&lt;%/g, '<%');
content = content.replace(/%&gt;/g, '%>');
```
I didn't made a pull request, as it seems for me really specific. And why fixing only `<% %>`  and not all `< >`.
