### ISSUE TITLE
2 blocks next to each other

### ISSUE THREAD

**Issue by michalfeher** [voidlabs/mosaico#182]
Hi. Is it possible to change width of some blocks and have, say, 2 blocks (50% width each) next to each other? 

Thanks.

**Comment by bago** [comment]
The current templates do not do this. They define blocks to be added one under the other in a container.
I never tried to create a template to put blocks one beside the other.

When you define a master template you simply tell Mosaico what html element is a "container" and which children and "blocks": they way they placed in your layout depends on your html+css.
