### ISSUE TITLE
Using main.js (backend)

### ISSUE THREAD

**Issue by jordivaleri** [voidlabs/mosaico#187]
Hi, I've looked at the documentation about using mosaic on a server, but does not work at all.

I have not any problem on local, it's just when i try to use it with Apache Server. For images and for downloading the HTML code. (i have imageMagick installed)

I would like to know how the main.js file works, because when I put mosaic on an Apache server, it would have to generate folders / dl / upload and / img, however it's not generated, and i get a URL error when I try to download the HTML (there is no folder). I would like to know how I have to set the main.js or Gruntfile.js to generate folders.

Thank you very much!

**Comment by bago** [comment]
The bundled backend/main.js is a NODE.JS application. You can't deploy it on an Apache Server (At least we never provided instructions to do so). You can deploy on any server where you use Node as webserver and not Apache HTTPD.

If you want to use Apache, probably you want a PHP backend (or something similar). You can find a php backend linked in the documentation. Go to their project and read their documentations. Open an issue against their project if you have issue with this.
