### ISSUE TITLE
Integrating mosaico email editor in my .net app

### ISSUE THREAD

**Issue by ShahVivek** [voidlabs/mosaico#190]
Hello,
I started to integrate mosaico email editor in my .net app (from scratch).
I am new to mosaico email editor , right now I didn't find "dist" folder in downloaded repository , where in "editor.html" and "index.html" some files are used from "dist" folder.
Can you help me with that ?
And if I can get any link or suggestion for "How to integrate mosaico email editor in your .net app." will be very helpful
Thanks.

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico#are-you-having-issues-with-mosaico

**Comment by nabenzine** [comment]
You need to run the grunt command to generate dist folder, follow the instruction bellow
https://github.com/voidlabs/mosaico#buildrun--
