### ISSUE TITLE
LESS problems with bower components

### ISSUE THREAD

**Issue by mattposch** [voidlabs/mosaico#191]
getting following errors when running less:css

```
Running "less:css" (less) task
>> FileError: '../../bower_components/evol-colorpicker/css/evol.colorpicker.css' wasn't found. Tried - bower_components/evol-colorpicker/css/evol.colorpicker.css,bower_components/evol-colorpicker/css/evol.colorpicker.css,../../bower_components/evol-colorpicker/css/evol.colorpicker.css in src/css/app_standalone.less on line 7, column 1:
>> 6 @import (less) "../../bower_components/toastr/toastr.css";
>> 7 @import (less) "../../bower_components/evol-colorpicker/css/evol.colorpicker.css";
Warning: Error compiling src/css/app_standalone.less Use --force to continue.
```

**Comment by bago** [comment]
did you follow the readme and installed the library?
Post-install will download the bower componets.. 
https://github.com/voidlabs/mosaico#buildrun--

**Comment by mattposch** [comment]
yes, followed the README instructions, apparently bower_components gets installed into the "app" folder, so the less imports fail...is this just me? o.O

**Comment by bago** [comment]
You probably did something wrong... The bower components are not installed inside app... start from scratch and run the install commands from the root folders.
