### ISSUE TITLE
ETIMEDOUT Error while configuring STMP

### ISSUE THREAD

**Issue by MaheshSundaramurthy** [voidlabs/mosaico#192]
Hi,
Have configured STMP Server for my email and specified the server name and credentials. Receiving ETIMEDOUT Error. Could you please help
![email1](https://cloud.githubusercontent.com/assets/20756874/17647307/08e78c12-61b9-11e6-8dae-d0af415acb18.png)
![email2](https://cloud.githubusercontent.com/assets/20756874/17647308/09e4b61c-61b9-11e6-9337-90492800b73d.png)

**Comment by MaheshSundaramurthy** [comment]
I actually got passed that error using another SMTP Provider. I think there is something different with Amazon SES. Now am receiving Emails. However, the images are not showing up. Could you please help

![email3](https://cloud.githubusercontent.com/assets/20756874/17647430/bb69f0ce-61bd-11e6-880b-ea62e5c65f1d.png)
![email4](https://cloud.githubusercontent.com/assets/20756874/17647431/c0b561c6-61bd-11e6-8cef-2d7c05915a9b.png)

**Comment by MaheshSundaramurthy** [comment]
The image rendering issue above seems to be happening in Gmail. Is there anything specific to be done for Gmail? It displays images in outlook? I also tried from mosaico.io site and same issue happened. Image below

![email6](https://cloud.githubusercontent.com/assets/20756874/17647517/8f68a11a-61c1-11e6-8b1f-43ea76f9c43f.png)

**Comment by bago** [comment]
Don't mix issues!

If images are not shown on Gmail it means you deployed Mosaico on a "non-public" url. Gmail try to access the images at your private url, and of course, it cannot access private urls.

Deploy mosaico on a public url.

**Comment by MaheshSundaramurthy** [comment]
Awesome. Let me give it a try. Thanks
