### ISSUE TITLE
Mosaico integration

### ISSUE THREAD

**Issue by andriyaucar** [voidlabs/mosaico#193]
Hi,
I develop an application and this application will allow users to create dynamic templates and send e-mail to customers. Does Mosaico provide it? 
I use Angularjs and Spring. How can I integrate Mosaico to my application? 
Can you help with this issue?

**Comment by bago** [comment]
1) "dynamic templates" doesn't mean anything to me.
2) Mosaico is not a tool to "send e-mail": it is a tool to compose html email.

Mosaico opensource is provided "as is". Just put your hands in the code and try to find your answers.

If you can succesfully use angularjs and spring I'm sure you can easily understand what mosaico does and how to integrate it.
