### ISSUE TITLE
Context menu (options missings)

### ISSUE THREAD

**Issue by nabenzine** [voidlabs/mosaico#194]
Hi,

I have noticed that, the context menu from the mosaico.io website is different from mine, it has more options, here is two screenshoot to explain better:

**Mosaico demo:**
![mosaico_menu](https://cloud.githubusercontent.com/assets/7820285/17702273/8f70ab5e-63cd-11e6-8499-f7585c047089.png)

**My version:**
![my_menu](https://cloud.githubusercontent.com/assets/7820285/17702284/99356724-63cd-11e6-8d8d-741bb5a9c54a.png)

I am wondering how to get the other options as well?

Thank you in advance.

**Comment by bago** [comment]
You can set tinymce toolbar configurations setting these 2 variables in a mosaico "plugin":

ko.bindingHandlers.wysiwyg.standardOptions
and
ko.bindingHandlers.wysiwyg.fullOptions

Have a look at src/js/bindings/wysiwyg.js file and to the Tinymce configuration for more details.

**Comment by nabenzine** [comment]
thank you very much for you answer @bago, you are doing a great job
