### ISSUE TITLE
Still unable to even generate thumbnails.

### ISSUE THREAD

**Issue by zrb0529** [voidlabs/mosaico#195]
Currently using:
node.js v 4.4.7
npm v 2.15.8
phantomJS v 2.1.1

Downloaded mosaico clean from website, extract to /sites directory

cd into mosaico-master directory, grunt and everything builds properly

Close browser and control+c to end grunt

copy tutorial directory, rename to myTemplate, rename html file to myTemplate.html

add myTemplate to the index.html file

execute grunt makeThumbs:main:myTemplate and get error:

```
Running "makeThumbs:main:myTemplate" (makeThumbs) task
Creating thumbnails for templates [ './templates/myTemplate/myTemplate.html' ]
Creating thumbnail ./templates/myTemplate/myTemplate.html

PhantomJS threw an error:ERROR
>> 0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code null. Use --force to continue.

Aborted due to warnings.
```

and finally, running grunt from main directory the template does show up in the list: http://screencast.com/t/ATR3UmrwPXe

But when I click it then all I see is a red BG: http://screencast.com/t/OdjBFyrV

So...where have I gone wrong? Do I need to use an older version of node.js?

**Comment by bago** [comment]
phantom is not needed at all to run mosaico, so the red page is not related to the phantom issue.
phantom is used to generate images for the template: if you don't run it then you won't get the image for the template and for the template blocks, buit everything else should simply work.

If you see a red page then you have a different issue and the browser javascript console will tell you something. (Your template is probably not a simple copy of a working template, but there is something broken)

**Comment by bago** [comment]
About pahntom not working, you probably have issues with ImageMagick: read the readme.
