### ISSUE TITLE
Mosaico style

### ISSUE THREAD

**Issue by pixelcriativo** [voidlabs/mosaico#196]
Hi.
I would like to know the best way to edit the CSS tool?

Is there a pattern?

**Comment by bago** [comment]
I'm sorry I don't understand the question. What is "the CSS tool"?
Take the time to explain your issue so that I don't have to guess ;-)

**Comment by pixelcriativo** [comment]
You will excuse me. I was not clear...
I would like to change the style of the mosaic, there is something related to this in the documentation?

Sorry for my english ;)

**Comment by bago** [comment]
Mosaico is styled through less. If you keep "grunt" running you will also see "live previews" of changes you do on the LESS files.
