### ISSUE TITLE
URL Parameter Substitution

### ISSUE THREAD

**Issue by MichaelJPDX** [voidlabs/mosaico#197]
I'm probably stretching the bounds of what Mosaico/KO can do, but I think it should be able to handle it. Just haven't figured out how yet. 

The challenge is this: I've got a block of four product images. The images are generated by an external service. All I have to do is pass a single parameter (category) as part of the image src as well as the link href. So, I've got a row in my layout at the top of the block with this:
`<span style="-ko-bind-text: @categoryMI;">MI Category (encoded)</span>`

There's a line in the blockdefs to define that:
`categoryMI {label: Category name for MI; extend:text; help: This is the category name passed.;}`

Lastly, after the span with the entry, I have the table for output. This is what I've got for the link and image so far:
`<a style="-ko-attr-href: http://www.imageservice.com/pc?mi_category_string=@[categoryMI]&mi_item_index=0" href="">
<img alt="" border="0" src="http://www.imageservice.com/p?&mi_category_string=@[categoryMI]&mi_item_index=0" style="border: 0; display: block;" width="130" /></a>

This isn't working. The substitutions don't get made at all, and even the fixed portion of URLs doesn't get inserted. Does this need to be defined elsewhere as a fixed variable? If so, how? I've seen reference to defining parameters in the blockdefs, but haven't seen an example of how to do it. Any ideas about how to make this work, or is it not possible?

**Comment by bago** [comment]
I'm sorry you lost something while writing... you talk about an image, but I only see code for a span.

**Comment by bago** [comment]
Btw, the problem with mosaico/ko is that it is too powerfull/flexible.. not viceversa.. so I guess this can be done...
maybe you need "expressions".:

```html
<img src="http://yoursite/img?q=param" style="-ko-attr-src: http://yoursite/img?q=@[categoryMI]">
or
<img src="http://yoursite/img?q=param" style="-ko-attr-src: @['http://yoursite/img?q='+categoryMI]">
```

If this doesn't wort please share the javascript console errors and/or the template workinprogress, otherwise I need too much guesswork.

**Comment by MichaelJPDX** [comment]
Thanks! The second variation (using @['string'+var] ) works for both anchors and images.
