### ISSUE TITLE
Help modal missing

### ISSUE THREAD

**Issue by nabenzine** [voidlabs/mosaico#198]
Hi,

I have noticed that, the right click from the mosaico.io website gives a help modal as shown in the image bellow 

![image](https://cloud.githubusercontent.com/assets/7820285/17929739/c5854aa2-6a02-11e6-9bf7-fb0d677eff38.png)

How can I get this in my app please ? the modal "How to use mosaico" in the beginning is also missing 

Thank you in advance.

**Comment by bago** [comment]
You have to create it on your own, it is not part of mosaico opensource:
https://github.com/voidlabs/mosaico#live-demo
