### ISSUE TITLE
Two question about styling Mosaico

### ISSUE THREAD

**Issue by NkDimi** [voidlabs/mosaico#200]
Halo, 
I have two question.

1) How I can remove Background Color and External Background to not allow users to change my settings?
![screen shot 2016-08-25 at 16 24 34](https://cloud.githubusercontent.com/assets/11389050/17972900/b2be0812-6ae0-11e6-8b9d-a0a732e0aef8.png)

2) How I can change color of button? I try few things but without successes.
![screen shot 2016-08-25 at 16 24 44](https://cloud.githubusercontent.com/assets/11389050/17972949/dbe2d72c-6ae0-11e6-86aa-1be8d915b0b7.png)

**Comment by bago** [comment]
First of all you have to know HTML/CSS.
What you can edit and the default color is all defined in the template you are using.
So, by default you probably want to look at templates/versafix-1/template-versafix-1.html

E.g: if you see a "background-color: red; -ko-background-color: @bgColor" then if you remove the "-ko-background-color: @bgColor" that property won't be editable anymore. If you change the "red" to something else you will change the default color.
