### ISSUE TITLE
JSON parse fail when importing data from localstorage

### ISSUE THREAD

**Issue by foyarash** [voidlabs/mosaico#202]
Hi,

I'm currently working on the import of saved templates from JSON datas i can found in my localstorage. So from what i've understand, i have to do something like this in my Mosaico.init:

`var ok = Mosaico.init({
    strings: strings,
    imgProcessorBackend: basePath+'/img/',
    emailProcessorBackend: basePath+'/dl/',
    titleToken: "MOSAICO Responsive Email Designer",
    data: {
      metadata: window.localStorage['metadata-8hv5vtl'],
      content: window.localStorage['template-8hv5vtl']
    },
    fileuploadConfig: {
      url: basePath+'/upload/',
      // messages??
    }
  }, plugins);
`

But that does not work, i have a JSON error which seems to occur at line 145 in src/js/app.js:

`Uncaught SyntaxError: Unexpected token o in JSON at position 1`

Am I doing something wrong? Or is that a bug that has not been fixed yet?

**Comment by bago** [comment]
jSON parsing is done by the browser.. so I guess you are not passing JSON where mosaico expect a JSON.
So "data" should be a JSON string not a JS object.

**Comment by foyarash** [comment]
Didn't think about that argh..Thanks man! 👍

**Comment by foyarash** [comment]
Ok now i am confused somehow. So i've sent the data as a json string with JSON.stringify function. So now i have something like this: 

```
var ok = Mosaico.init({
    strings: strings,
    imgProcessorBackend: basePath+'/img/',
    emailProcessorBackend: basePath+'/dl/',
    titleToken: "MOSAICO Responsive Email Designer",
    data: JSON.stringify({
      metadata: window.localStorage['metadata-8hv5vtl'],
      content: window.localStorage['template-8hv5vtl']
    }),
    fileuploadConfig: {
      url: basePath+'/upload/',
      // messages??
    }
  }, plugins);
```

No more JSON parse error now, BUT:

`Uncaught TypeError: Cannot read property 'lastIndexOf' of undefined` occurs on template-loader.js, in function templateLoader. Actually the templateMetadata.template returns undefined. The solution to avoid this is to use JSON.parse. Again, am I doing something wrong?

**Comment by foyarash** [comment]
Ok i've found the solution, maybe it was a bug or just me doing bad things.

I had to add call the function start like that:

`start(options, undefined, JSON.parse(data.metadata), JSON.parse(data.content), customExtensions);`

**Comment by bago** [comment]
> "Actually the templateMetadata.template returns undefined"

So, make sure your template metadata includes the template property: how did you manage to have a metadata from mosaico with no "template" property?

**Comment by foyarash** [comment]
The template property was here, i checked.

The problem was that the data.metadata and data.content were strings, not objects. So when you try to access templateMetadata.template for example well it does not work. But with the fix i proposed above, the import now works perfectly (there is just an absence of 'save', 'test' and 'download' buttons but i don't really care about that).
