### ISSUE TITLE
HTML URL encoding

### ISSUE THREAD

**Issue by MichaelJPDX** [voidlabs/mosaico#203]
I'm finding that URLs for links and images are being HTML encoded, specifically '&' is being converted to `&amp;`. I know this considered proper HTML but it's causing issues with a very fussy third-party product we're integrating into messages, so I need to see if I can stop it from happening. Most manipulation of the code when downloaded is done in viewmodel.js but it doesn't appear to be doing this. Can anyone point me to where this encoding is taking place?

**Comment by bago** [comment]
Try to change the DOCTYPE of the master template.
In XHTML the `&` "HAVE TO" be encoded to `&amp;` when written in an element attribute, so the BROWSER does this when you ask it to put that address in that DOM element (that's why you can't find it in the code).

**Comment by MichaelJPDX** [comment]
I was afraid that's where the problem might lie, but I'm not able to find a doctype or other combination that keeps it from converting the & in URLs. I'll just have to have a post process to edit the URLs, since getting the flaky third-party to fix their code is not an option.

On a related note, I have an element that <i>is</i> properly encoded in the template - `&#9658;`. It's not edited or otherwise touched by any input, but when I download the built message it's unencoded. Any idea why that is happening? It looks like it was a bug that was supposedly fixed.

**Comment by bago** [comment]
I'm not sure I understand the "related note". Please open another issue if you think there is a bug. Please test it on multiple browsers and on mosaico.io, too, before reporting, so we know if this is browser related and deployment-related.
