### ISSUE TITLE
Mosaico backend in JAVA any examples samples ? 

### ISSUE THREAD

**Issue by mkucaj1986** [voidlabs/mosaico#204]
Mosaico backend in JAVA any examples samples ?

**Comment by bago** [comment]
There are no existing backends in java.
It should be simple,if you are a java developer.

Start from here:
https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico
https://github.com/voidlabs/mosaico/blob/master/backend/README.txt
https://github.com/blueimp/jQuery-File-Upload/wiki
