### ISSUE TITLE
how to use background image in email template

### ISSUE THREAD

**Issue by harshwardhanbsc** [voidlabs/mosaico#205]
How to use a background image into the email template. what property we need to use

**Comment by bago** [comment]
Never tried, but maybe something like this:
```html
<td background="http://mosaico.io/srv/f-default/img?method=placeholder&amp;params=258%2C150" style="-ko-attr-background: @image.src; background-image: url(http://mosaico.io/srv/f-default/img?method=placeholder&amp;params=258%2C150); -ko-background-image: url(@[image.src]);">
```

**Comment by snowcoda** [comment]
This article is also a good source (although about 2 years old). There are also links to further reading at the bottom of the article which will help highlight any potential email client issues you may encounter:

**Litmus: Understanding Background Images in Email**
https://litmus.com/community/learning/25-understanding-background-images-in-email
