### ISSUE TITLE
Hi Cannot find the dist folder?

### ISSUE THREAD

**Issue by jacobtisson** [voidlabs/mosaico#206]
i downloaded the full package but iam unable to find dist folder specified for a number of js. should i procure them my own or is something wrong with the download?

**Comment by Hiswe** [comment]
I think you forget to build the project

https://github.com/voidlabs/mosaico#buildrun--

**Comment by jacobtisson** [comment]
Hi i am using a windows system and i am doing this in Visual studio 2010. when i run pm>npm install
it gives error. i am new in git hub can you please tell me how to properly build this app in VS? Thanks.

**Comment by bago** [comment]
The build is not made for VS. So, simply follow the Readme and build it the way the project tell you to do it. Once you know how it is built, if you are smart with VS then you will make the necessary changes so to use whatever build/IDE you want.
