### ISSUE TITLE
HTML templates created by us have image that I want to load automatically

### ISSUE THREAD

**Issue by harshwardhanbsc** [voidlabs/mosaico#211]
Hi Team,

My custom HTML template have some images that are replace by placeholder when I make blocks using your template language.

Is there is any way so that I can load default images inside my templates blocks instead of loading just placeholders.

http://prntscr.com/ckl2r3 ( template image loading placeholder)

http://prntscr.com/ckl34x ( template image with default images)

**Comment by bago** [comment]
Try with

```html
<img src="path" data-ko-placeholder-src="placeholderpath" data-ko-editable="image.src" />
```

Let me know if this really works and if this your expected behaviour.

**Comment by bago** [comment]
10 days no answers :-( closing.

**Comment by sibbu2005** [comment]
Not working for me . I am using version 0.16.0 of editor
