### ISSUE TITLE
Mosaico and AWS S3 Bucket

### ISSUE THREAD

**Issue by NkDimi** [voidlabs/mosaico#214]
I am using Mosaico and everything is working nice. 

Now I would like to use `CodeDeploy` from AWS to deploy changes in Mosaico without downtime. I would like to replace the `uploads` folder to be on `AWS S3 Bucket` and not on local. 

I will appreciate any advice.

**Comment by bago** [comment]
Sorry, I never used S3 buckets. 
Here is a doc about what mosaico expects from a backend:
https://github.com/voidlabs/mosaico/tree/master/backend

**Comment by Hiswe** [comment]
For NodeJS you should [aws-sdk](https://www.npmjs.com/package/aws-sdk)

With this you can upload and stream back images.
During streaming, you can resize images with GraphicMagic

**Comment by NkDimi** [comment]
We decide to use` s3cmd` with synchronization and run it with `crontab` job. This is cheaper then to use aws-sdk. Thank you for help.

**Comment by ravir636** [comment]
please help, how did u write code to upload files on aws or where...

**Comment by NkDimi** [comment]
@ravir636 I can not remember all steps but this i find on my git in main.js I add or change this line i can not remember
`var config = require('../server-config.js');`

Then there I create connection 

`// Put here your email sending configurations!
module.exports = {
        emailTransport: {
                 host: 'email-smtp.eu-west-1.amazonaws.com',
                 port: 25,
                   auth: { user: 'user1', pass: 'password' }
        },
	emailOptions: {
                from: 'email', // sender address
                 bcc: 'email',
        }
};`

**Comment by ravir636** [comment]
If any conceret implementation you can provide so it would be really helpful for me ..anyway thanks for answer.
