### ISSUE TITLE
How to enable Preheader ?

### ISSUE THREAD

**Issue by kattapug** [voidlabs/mosaico#215]
Hi, Must say this editor is just awesome. 

On the demo version, there is an option to enable Preheader. See below, on my version, the highlighted section is not available.

![d d preheader](https://cloud.githubusercontent.com/assets/3859047/19016089/b9256552-8808-11e6-95ba-b480d1cb3731.JPG)
 
How do I enable it?

Thanks

**Comment by bago** [comment]
Are you testing the same template? (versafix-1)?
Are you sure you are doing the same things locally and on mosaico.io?
Did you change anything in your local code after cloning the project?

**Comment by kattapug** [comment]
I am sorry I could not reply earlier, my developer has been off for the week. So I have not been able to reply.  He is back on Monday so I will be able to have and reply by Wednesday the latest. Please can you reopen this for my. Thanks

**Comment by kattapug** [comment]
Hi please close this has been fixed. Thanks for keeping this open.
