### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by michaelkesnerj** [voidlabs/mosaico#216]
Our server engineer has tried to install numerous times with issues. Please find logs attached. 

[mosaico.txt](https://github.com/voidlabs/mosaico/files/509846/mosaico.txt)
[npm debug file.txt](https://github.com/voidlabs/mosaico/files/509847/npm.debug.file.txt)

**Comment by bago** [comment]
I don't know what's wrong and what kind of environment you're trying to build, but this doesn't seem to be mosaico specific. You server is not able to create files, create threads, clone github repositories and other basic stuff.
