### ISSUE TITLE
installed Mosaico but can't get images to work

### ISSUE THREAD

**Issue by SewHappy58** [voidlabs/mosaico#217]
![screen shot 2016-10-06 at 2 38 49 pm](https://cloud.githubusercontent.com/assets/7072324/19167839/0637bcfa-8bd3-11e6-8dab-b7aa762aac1a.png)

I can't seem to get the images to work.  What am I doing wrong?
http://phpstack-26911-58106-157312.cloudwaysapps.com/editor.html

**Comment by HCSTT** [comment]
hello SewHappy58, I would like to know is you are able to share information regarding mosaico installation process, I would like to install it on a web server. 

Thank you in advance

**Comment by SewHappy58** [comment]
Hello, what information did you need?  I have it installed but the images aren't working.  I used GIT to install.

**Comment by HCSTT** [comment]
thank you for your faster answer, to be honest I need all the necessary information I know about hosting, web site etc but I don’t understand how mosaico work, I mean to install it, I was thinking just to upload to a web server to make it work, apparently is no simple like that.

**Comment by SewHappy58** [comment]
your right.  It's not simple.  I used GIT to install.  But I had to make sure that nodeJS was installed on my server or could be used.  I had to go to the hosting company for that.  The other part is ImageMajick.  I had to make sure that was installed.  Once you import the files, you need to SSH into your server and follow the instructions to set it up.

**Comment by HCSTT** [comment]
I was searching online a tutorial to follow instruction, can’t find anything to make understand better the procedure. did you find any documentation ?

**Comment by SewHappy58** [comment]
Nope.  I went through my hosting company for help.

**Comment by HCSTT** [comment]
I will ask if hostgator can help me to install it, its very good tool to save time and create responsive emails.

**Comment by bago** [comment]
In order to build mosaico you have to know how to install software on your server (e.g: I can't explain how to install ImageMagick) and you have to be familiar with Node.js builds. 

You opened this issue without complying with the rules written in the main Readme that explain what you have to write in a issue, I'm closing this down.
