### ISSUE TITLE
How to get only HTML code of a template in editor.html?

### ISSUE THREAD

**Issue by vinay-vik** [voidlabs/mosaico#220]
I am using mosaico in Django framework. I want to save the HTML code of the template in another table along with the other basic information about the template. Can you help me on how to get the HTML code of the template in editor.html
Thanks

**Comment by Hiswe** [comment]
There is a   viewModel.exportHTML method on the viewModel in [src/js/viewmodel.js](https://github.com/voidlabs/mosaico/blob/master/src/js/viewmodel.js)

So you can add a plugin to gather all informations you want and make an ajax post. 

Or you can surcharge the save button action

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins
