### ISSUE TITLE
How to Install-Need Proper installation instruction for backend php 

### ISSUE THREAD

**Issue by md-haroon** [voidlabs/mosaico#221]
Hey @bago  i cnt get any installation instruction for your  mosaico backend php., can you please give step by step instruction for working with php

**Comment by bago** [comment]
Here is the third party project "php backend": https://github.com/ainterpreting/mosaico-php-backend
Mosaico is a javascript library, we don't provide "installation instructions" for backends.

**Comment by md-haroon** [comment]
ho sorry @bago can you help me how to run mosaico **without nodejs environment**

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico
https://github.com/voidlabs/mosaico/blob/master/README.md
https://mosaico.io/commercial/
