### ISSUE TITLE
Expand tool menu?

### ISSUE THREAD

**Issue by TheNeusser** [voidlabs/mosaico#224]
Hi,

thanks for the great email editor. It's a very nice tool and easy to use.
I've read a lot issues, but I don't found any helpfully entry for me.

I would like to expand the tool menu and also add a new "selection page".
For example add the menu "Test":
![image](https://cloud.githubusercontent.com/assets/23077698/19761427/33270284-9c36-11e6-8a79-9faa3ace9dc2.png)

How is the best and easiest way to add this to the tool menu?

Thanks for your help.

Cheers,
TheNeusser

**Comment by bago** [comment]
The "toolbox" is defined here:
https://github.com/voidlabs/mosaico/blob/master/src/tmpl/toolbox.tmpl.html

The width of the toolbox is defined via CSS (less).

**Comment by TheNeusser** [comment]
Hi,

I got it. Thanks.
