### ISSUE TITLE
jshint:all fail

### ISSUE THREAD

**Issue by loiclavoie** [voidlabs/mosaico#229]
During the installation process, I get this error:

`Warning: Task "jshint:all" failed. Use --force to continue.

Since I'm not a front-end developer, I don't really know what jshint is nor where to start to debug it.
Any hint?

**Comment by bago** [comment]
not happening here..  and can't find many context informations in the bug report in order to do some investigations.

**Comment by loiclavoie** [comment]
It's still happening on my side, but like I said, I have very little knowledge of that kind of front-end development (I'm currently learning it as I play with it). 

What info would help your investigation?

**Comment by bago** [comment]
jshint is a linter: it checks code formatting and raise errors/warning if it finds code with wrong "code style".
Did you change anything in the sources? What version did you download? What is your environment?
Provide full output of your grunt command.

**Comment by loiclavoie** [comment]
I'm still investigating the problem right now. I'll close the task for now and reopen it when I have more information. (I have multiple problem with the interface, like the download button missing and all).
