### ISSUE TITLE
Output HTML contains unexpected data- attributes or replaced attributes (was: "data-" still in html after export)

### ISSUE THREAD

**Issue by foyarash** [voidlabs/mosaico#230]
Hi,

I currently have an issue with the html export.

I have this error in my console: Output HTML contains unexpected data- attributes or replaced attributes

It seems its because i still have data- attributes which were not removed by the exportHtml() function. 

How the error happens: i create a template with just a text block, then center the content with the tinymce toolbar, then export the html, and I get the error while exporting the html.

So I tried on mosaico.io, but it seems that the bug cannot be reproduced.
What would be the cause of that?

**Comment by bago** [comment]
I can't find a bug in your template if you only "talk about it" ;-)

**Comment by bago** [comment]
Last question: apart the console log, do you have issues with the output html? What kind of data- attribute is left in the code? is it a data-ko- attribute or something else? does it break things?

**Comment by foyarash** [comment]
So I actually did a fork of the versafix-1 template to create my own template. The only thing which differs is a modified css, also with some blocks removed like the preheader block. I'm not touching the blocks templates contained in the mosaico.min.js at all (e.g : i apply css with my css files, but i'm not modifying the block itself).

Now i add just a simple text block on my edit area, and i center it's content. Then i call the viewModel.htmlExport() from my script, and i get the console log.

To answer your second question, yes it break things for style. For example with my centered block, i get something like this: 

`<p data-mce-style="text-align: center;" style="Margin: 1em 0px; Margin-bottom: 0px;">Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>`

So the text is not centered as i want because there is still the data-mce-style.

Hope this will help a bit, don't hesitate for more details

**Comment by bago** [comment]
data-mce-style... so it is tinymce related.. the issue must be the tinymce upgrade (mosaico.io still runs an older tinymce).

You can try altering this code removing the 'raw' parameters:
https://github.com/voidlabs/mosaico/blob/master/src/js/bindings/wysiwygs.js#L232
```javascript
value(editor.getContent());
```

**Comment by foyarash** [comment]
Thanks for your answer 👍

**Comment by bago** [comment]
I don't think the code above is the solution.. it seems it may be a bug with the "clientside inliner".. I still have to investigate.

**Comment by bago** [comment]
As I wrote in #231 it turned out that the "data-" console output is nothing "bad" and is not the cause of the missing style in the download. It is just a coincidence... so the "garbage" data-mce-style attribute could be cleaned (I will add some code to clean it up) but the real issue is another and unrelated and is about what happens with the new clientside inliner.

Thank you for spotting the issue.
