### ISSUE TITLE
Include my own placeholders

### ISSUE THREAD

**Issue by TheNeusser** [voidlabs/mosaico#233]
Hi,

I would like to add my own "placeholder" (e.g. a placeholder for Surname, Firstname, ....).
I've added my own tool tab to the editor. 
![image](https://cloud.githubusercontent.com/assets/23077698/20208800/c1e29b12-a7f0-11e6-9de0-6bd250f4397b.png)

Now I would like to "drag and drop" one of the placeholder to any text in one of the template blocks. I would like to insert only the text (e. g. ##FirstName##) to the text part of a block.
![image](https://cloud.githubusercontent.com/assets/23077698/20208910/68fbb19a-a7f1-11e6-9ea8-e0b26ae83840.png)

My problem is, that I couldn't "drop" the text to the blocks.
I don't have any clue, how I can insert the text.

I'm very thankful for any tip.

Cheers

**Comment by bago** [comment]
I don't have suggestions. IMHO drag&drop is not a good UI/UX for the placeholders.

We did a similar customization by creating a Tinymce plugin to insert placeholders and altering the tinymce configuration started by mosaico so to include that toolbar plugin. See Tinymce website on how to create plugins.
