### ISSUE TITLE
Style vs Content tab (bgcolor)

### ISSUE THREAD

**Issue by Smus** [voidlabs/mosaico#235]
Hi

I have made a template with 10 modules, all have a outer and inner background color, that I want to be able to change in the Style tab and not in Content.

![image](https://cloud.githubusercontent.com/assets/4640401/20433598/a4de9d4a-ada4-11e6-8681-bf234b56437d.png)

All modules have the color as a variable:
`style="background-color:#ffffff;-ko-background-color: @backgroundColorOuter; -ko-attr-bgcolor: @backgroundColorOuter"`

So the question is, how can I "link" them together for all modules, and change all at the same time?

**Comment by bago** [comment]
by default properties ending with  theme, style, color, radius will dedault to the Style tab. You can add a "category: style" to your property definition or change the name to backgroundOuterColor and it will be moved to the style tab.

**Comment by bago** [comment]
When you move them to "style" they will start being "linked" because properties using the same name in the saame "theme section" will share the same property value unless you flag the top-right check to customize the single blog.

**Comment by Smus** [comment]
Ahh okay, that fixed the issue.. I didnt know about the names "theme, style, color, radius". Thanks!
