### ISSUE TITLE
Making "thumbnails"/"block thumbnails"

### ISSUE THREAD

**Issue by Smus** [voidlabs/mosaico#236]
I cant make the small thumbnails for my moduls, with i run the 
`grunt makeThumbs:main:toptoy`

```
Creating thumbnail ./templates/toptoy/template-toptoy.html
_full
clipRect 0 0 680 4572
finished 0 true
exiting
null
```

It only creates the "_full" image for the overview.. im sure its very little that im missing.
Do you have to do something special for it to make the thumbnails?

**Comment by bago** [comment]
Do you have a data-ko-container attribute in a container block?
Do you have "data-ko-block" attributes for each of you blocks?

**Comment by Smus** [comment]
Ahh I forgot the data-ko-container="main".. now it works.. thanks!
