### ISSUE TITLE
Darg and Drop image behavior from gallery

### ISSUE THREAD

**Issue by LucDebono** [voidlabs/mosaico#237]
After installing version 0.15, the behavior obtained locally when dragging and dropping images from the Gallery to a block is different from the one offered by Mosaico online.
Locally, when grabbing an image from the Gallery, it appears full size, making it difficult to properly drop in a block.
However, online, Mosaico seems to be displaying a thumbnail version of the image.
Appreciate if you can point me to the problem.

**Comment by bago** [comment]
Cannot reproduce this: I don't see differences between a local "head" run and the mosaico.io version wrt gallery drag&drop management.

Maybe you did something wrong with the filesystem folders? Delete your "uploads" folder and upload new images from the mosaico interface...

**Comment by LucDebono** [comment]
Hi Bago,

Sorry if the information provided was not sufficient.
I am providing 2 screen shots illustrating the same action, with the same image, comparing behavior of Mosaico.io with local implementation. As you will see, locally, I do not get the "thumbnail image" when dragging from the gallery, which is an issue when using large image as I am not able to drop them properly in the image container.
Is there a specific property that needs to be enabled to obtain this behavior?

![same image with mosaico online](https://cloud.githubusercontent.com/assets/23562095/20456313/8968d91a-ae42-11e6-8c59-89cc1e0afd4d.png)
![same image with local implementation](https://cloud.githubusercontent.com/assets/23562095/20456316/8dcad3c8-ae42-11e6-8d3c-f2e64b54cd68.png)

**Comment by bago** [comment]
Well, that screenshot is not for a basic checkout of mosaico from github and a run via "grunt": if you implemented your own backend then you probably did something wrong with the "thumbnailing" part of the upload or the gallery browsing.

**Comment by LucDebono** [comment]
Thank you Bago,

Let me validate with my developer if he can pinpoint the problem.

**Comment by LucDebono** [comment]
Can you please take a look at these 2 screen shots. It seems the CSS property driving the Thumbnail display during the Drag and Drop are not the same between the Mosaico version available online and the Mosaico package.
Thanks for your help.

![mosaico online](https://cloud.githubusercontent.com/assets/23562095/20526340/a384ad8c-b091-11e6-94c3-331f92059cd4.png)

![mosaico package](https://cloud.githubusercontent.com/assets/23562095/20526347/a8261ec0-b091-11e6-9107-7264d24a15af.png)

**Comment by bago** [comment]
As I wrote you before I just tried downloading the latest mosaico, running "grunt" , uploading an image and dragging and it is show as a thumbnail...  if you look at your "src" you see it points to a "thumbnail" url.. so maybe you have something wrong in the thumbnail generation... did you change anything in the code?

**Comment by bago** [comment]
No answers to questions...
