### ISSUE TITLE
colorpicker: change default theme colors

### ISSUE THREAD

**Issue by Smus** [voidlabs/mosaico#238]
Is it possible to change the default colors for the color picker?

![image](https://cloud.githubusercontent.com/assets/4640401/20520313/999d7bf4-b0a6-11e6-9c3a-e9a43f778929.png)

**Comment by Smus** [comment]
Nevermind, found them in evol.colorpicker.js :)

**Comment by Smus** [comment]
hmm or maybe not :-( That wasnt the correct place

**Comment by bago** [comment]
mosaico currently depends on evol colorpicker 3.2.1 and "embeds" evol 3.2.1 in the "compiled" output.
evol colorpicker 3.2.1 doesn't support overriding the palette via configuration.

Newer colorpicker (https://github.com/evoluteur/colorpicker/blob/master/js/evol-colorpicker.js#L211) added support for "customTheme" option, but I didn't have time to check if the newer colorpicker is compatible with mosaico.

**Comment by pbatroff** [comment]
Hmm, is this solved? I need to do exactly this - add a custom palette with company colors. And can't really figure out if this is supposed to be a solution, or just stating it doesn't work.

**Comment by francescbassas** [comment]
+1 to this enhancement. Can it be reopened?

**Comment by IProSoft** [comment]
@bago could You share more specific example, where and how include plugin ?

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins
