### ISSUE TITLE
Spellchecking

### ISSUE THREAD

**Issue by huelsemann** [voidlabs/mosaico#239]
I would like to enable browser-based spell checking when editing text content. I have noticed that the spellcheck attribute is set to false and that - once I set it to true manually - spell checking will work. 

Would it be possible to enable this for all text blocks by default and if yes, what needs to be changed?

![spellcheck](https://cloud.githubusercontent.com/assets/15138785/20601404/c2bbd3b0-b258-11e6-8634-94ae7859cb57.png)

Thanks in advance!

**Comment by bago** [comment]
I think this depends on tinymce initialization options... try creating a plugin and passing it to the mosaico startup options:

```javascript
var plugin = function(vm) {
  ko.bindingHandlers.wysiwyg.fullOptions['browser_spellcheck'] = true;
}
```

https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins

Please report back if it works.

**Comment by bago** [comment]
Any news? Did it work? How?

**Comment by huelsemann** [comment]
Sorry for the late response but I was on holiday and my colleagues didn't find the time to look into this.

Unfortunately it does not work with the plugin - however, it does make a difference as the spellcheck attribute is gone completely when the plugin is defined:

With plugin:
![image](https://cloud.githubusercontent.com/assets/15138785/21305739/a40e361e-c5cd-11e6-821f-cb391220372c.png)

Without plugin:
![image](https://cloud.githubusercontent.com/assets/15138785/21305760/bb8963b8-c5cd-11e6-96df-7b43a646a9b1.png)

I also tried setting this in wyswig.js as described in #247 with the same effect (spellcheck attribute is gone).

If you have any further ideas please let me know. 

Thank you!

**Comment by bago** [comment]
I guess this is a tinymce issue more than a mosaico issue: if you find a way to make tinymce 4 in "inline mode" to support spellchecking then I can help porting that method to mosaico.

**Comment by huelsemann** [comment]
I finally managed to get the spellcheck working. The trick was to set this in in the standardOptions in wysiwygs.js instead of the fullOptions, which did not work.

So, in order to enable browser spellchecking, either use a plugin like this (using standardOptions instead of fullOptions in your suggestion):

var plugin = function(vm) {
  ko.bindingHandlers.wysiwyg.standardOptions['browser_spellcheck'] = true;
}

or - similar to #27# - change line 171 in wysiwygs.js from
  standardOptions: {},
to
  standardOptions: { browser_spellcheck : "true" },
