### ISSUE TITLE
Templating - Is it possible to move template folder in a Mosaico Way

### ISSUE THREAD

**Issue by perlpty** [voidlabs/mosaico#241]
Hi, I would like to know if it is possible to move the template folder in a mosaico fashion.
My mosaico installation is protected with HTTP Basic Auth by using Apache.
However,  template images must be available to the public when sending emails.

I did solved this problem, by 1) moving the template folder outsite the protected directory, 2) Adding a .htaccess rule to mosaico folder to redirect template requests to outside mosaico folder and 3) Re-writing template image src with the backend.

The above scenario works, but Im looking for a simpler way to achieve that goal.  I mean, probably my solution is overkill for this goal.  I guess that there might be **a simple Mosaico config to specify the template folder location**, but I couldn't find it.

Any help is appreciated!

**Comment by bago** [comment]
you can move the template wherever you want. When you "initialize" mosaico you can pass "full path" to the templates.. they can even be on a different domain.

**Comment by perlpty** [comment]
I tried to do relative url path like this:  `template: '../../' ` and then absolute path like this
template: 'http://MYDOMAIN.COM/templates'   without success.

Some background:  Mosaico is installed 2 folder levels below the domain path, like: `www.mydomain.com/myprotectedfolder/mosaico` and the templates are located 1 level below the domain path like this:  `www.mydomain.com/templates`  

I tried to alter editor.html code like this:
```
	var ok = Mosaico.init({
		    imgProcessorBackend: 'img',
		    emailProcessorBackend: 'dl/',
		    titleToken: "MOSAICO Responsive Email Designer",
		    fileuploadConfig: {
		      url: 'upload/',
			      // messages??
		    },
		    strings: json,
                    //template: '../../'
		    template: 'http://mydomain.com/templates'

	});
```


The only reference to this issue was #171 , but I couldnt find the right keyword.  I may not be "template" but "template-path" or something else.  Or maybe I am not understanding the big picture.

**Comment by bago** [comment]
template should be a full template path to the html.

If you use the "demo index"  to create edits in the localstorage then you should work in viewModel.newEdit to alter the template path.

**Comment by perlpty** [comment]
Thanks a lot!   viewModel.newEdit  it is!!!  Now working pretty nice...

**Comment by bago** [comment]
for anyone else jumping here: index.html is just a demo file that is used to show how mosaico can be run using localstorage... it is not intended to be part of the mosaico library itself, that is only a "javascript+css" file.
