### ISSUE TITLE
knockout-jqueryui 2.2.3 not fully compatible with Jquery UI 1.12

### ISSUE THREAD

**Issue by Hiswe** [voidlabs/mosaico#242]
jquery-ui 1.12 introduce a [new API for buttons](http://api.jqueryui.com/button/) and knockout-jqueryui is still based on the old one.

An easy fix is to downgrade jquery-ui to 1.11 for now…

**Comment by bago** [comment]
Can you describe the issue you see?
I'm using jquery-ui 1.12 and my buttons seems to work fine...

**Comment by Hiswe** [comment]
@bago I have made an answer here https://github.com/gvas/knockout-jqueryui/issues/61#issuecomment-263911011

It's more a graphical issue, due to options changing.
