### ISSUE TITLE
integrated with an existant CMS

### ISSUE THREAD

**Issue by domenico81** [voidlabs/mosaico#243]
Hi
I'd like to know if your project can be integrated with an existant CMS. In this moment we use TinyMCE to create and edit our newsletter. So, is it possibile to save the HTML, created by your component, in a database? Is it possibile to import HTML inside your component, to allow users to edit their newsletter?
Best Regards

**Comment by bago** [comment]
Yes this is possible: like Tinymce, mosaico doesn't do this for you.. you have to do the load and store stuff.

In mosaico the "work object" is not the HTML output, but a couple of JSON objects. You will have to salve/load them and save the "html export" separately.
https://github.com/voidlabs/mosaico/wiki/Replacing-TinyMCE-or-CKEditor-with-Mosaico
