### ISSUE TITLE
big vs smaller toolbar.  Is it possible to force which one to use?

### ISSUE THREAD

**Issue by perlpty** [voidlabs/mosaico#244]
Hi.  I was wondering how can I force which toolbar to use: big or small.
I did read:   [Template language](https://github.com/voidlabs/mosaico/wiki/Template-language)
and it specifies:

> for inline elements, or for div: mosaico automatically use the multiline editing (and the big toolbar) when you use data-ko-editable on TD or DIV tags while it uses the single line editing (and the smaller toolbar) when you use it on other tags.

However, I 'd like force sometimes the one I wish use and not use the automatic feature. I couldn't find the option to do that.  For instance, How could use the SMALL toolbar within a TD element?

Why do I ask this? Because when using the Big Toolbar TinyMCE automatically asign the Paragraph Style but sometimes what I need is the DIV Style.

So, 2 options would be possible to this issue:
1) Force toolbar option with some template Keyword
2) A workaround Making TinyMCE to default to DIV Style instead of Paragraph style.

Thanks in advance.

**Comment by bago** [comment]
I think the <p> behaviour is not related to the toolbar you use: tinymce adapt the <p> behaviour to the tag it is used. This makes sense in HTML.

If you want the small toolbar create a spam element and make it "editable": if you don't want this element in the output then you can add a data-ko-wrap="false" to the same element.

**Comment by perlpty** [comment]
Ok... I  will try that.  My current template is like this:
`<TD style="some styles"  data-ko-editable="titleText" >My content</TD>`

2 Questions:
**1) You suggest I should do this:**
`<TD style="some styles"><span data-ko-editable="titleText" data-ko-wrap="false">My content</span></TD>`

 Is that correct?

2) I have not use  `data-ko-wrap="false"` yet, so I cannot say.  But what I expect by using "data-ko-wrap"  is that **styles applied to SPAN element be copied to TD tag because SPAN element would disappear.**  Is that thought correct?

**Comment by bago** [comment]
`data-ko-wrap="false"` means that tag will only be used during editing and will be removed in the final output. No style is copied around. Tinymce is used to edit content, not to style the "editable" tag..

**Comment by perlpty** [comment]
Ok. I did test. The result is that the element disappear and styles are applied as inline html not css, that I thought before.

SMALL toolbar only has 2 styles: Bold and Italic and they are applied as this:
BOLD = <strong>bold text</strong>
ITALIC = <em>italic text</em>

OK.  **It solves the 1st issue about using Small Tool Bar.** perfectly!!!!

But still I would like to explore the 2nd option ( Making TinyMCE to default to DIV Style instead of Paragraph style. )  because sometimes that you also have links and other stuff, but don’t want TinyMCE add some P tags around them because of the space added when editing .  If I change to 
`Formats > Blocks > Div` using the Big toolbar, the P tag is substituted by a DIV tag, which does not create the extra Space in that editable area.

So, I would be a matter of:
A) Telling Tiny MCE to default block styles to DIV instead of paragraph 

B) or Telling TinyMCE to not print any tag after editing.  Im not sure if that option (B) is possible.

C) or using / adding inline (SPAN tags) for format styles.

I tried reading some [TinyMCE docs](http://archive.tinymce.com/wiki.php/Configuration3x:formats)  but it needs to be TinyMCE available to configure inside mosaico.

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/issues/178#issuecomment-233759016

**Comment by perlpty** [comment]
Exactly, I just found that link.  Ok, I will try to see how can I use that information.

**Comment by perlpty** [comment]
Just to add:  Everything worked perfect with that plug-in solution.

**Comment by bago** [comment]
Thank you for the update/feedback!
