### ISSUE TITLE
templating - grunt makeThumbs:main:yourtemplatename -  not working as expected

### ISSUE THREAD

**Issue by perlpty** [voidlabs/mosaico#246]
Hi.  I have been doing my own template, and it works very good.  However last time I tried to make the template thumbs, they were not as expected.

WHY?
I define a property named "contentshow" like this:
`contentshow {label: Show Content; widget:select; options: all=Show All|reverse=Reverse Order|left=Only Left Content|right=Only Right Content; }`

In template HTML I use the property like this (here I show summarized concept for better undertanding):
```

<div data-ko-display="contentshow eq 'all'" data-ko-wrap="false">
	LEFT HTML CONTENT
	SPACE HTML CONTENT
	RIGHT HTML CONTENT
</div>

```
```
<div data-ko-display="contentshow eq 'reverse'" data-ko-wrap="false">
	RIGHT HTML CONTENT
	SPACE HTML CONTENT
	LEFT HTML CONTENT
</div>
```

```
<div data-ko-display="contentshow eq 'left'" data-ko-wrap="false">
	LEFT HTML CONTENT
</div>
```
```
<div data-ko-display="contentshow eq 'right'" data-ko-wrap="false">
	RIGHT HTML CONTENT
</div>
```
I must say that Mosaico logic is working as expected, no problem with that.  Mi issue is only with thumbnail generation.

Here is the **expected result**, taken from a previews template building stage:

![bigintroblock](https://cloud.githubusercontent.com/assets/23323762/21022879/32279966-bd4c-11e6-8cc5-7a8d6059e526.png)

But **after using the above property**, the thumbnail is like that:

![bigintroblock](https://cloud.githubusercontent.com/assets/23323762/21022908/5280e9b0-bd4c-11e6-9e36-a8e4a86070f6.png)

This situation is probably happening because "makeThumbs" does not know anything about the logic Mosaico is using to render this property.  

So **here are the Questions**:  
1) Is it possible to instruct "makeThumbs"  to only show a preview of the FIRST repeated content?
2) Is there any TAG that I can use in the template in order to avoid thumbnail generation for a particular section?

**Some possible workarounds** for this issue come to my mind:
1) Modify the template by removing the unwanted section and after that re-assemble the template.  However, it is hard to do that since I have defined several blocks like that.

2) Make extra blocks for each sub-section.  But, again, since I have many blocks like this It would be a big increment to the current block amount. For instance, now I have 12 blocks.  And 3 of them have 3 extra section (reverse,left,right) + 1 normal section ("ALL").  Then, for 3 blocks with 3 extra section it would be 9 additional blocks ( 3 blocks x 3 extra section = 9 ).  So, the template would have 21 (12+9) blocks instead of 12.   So, it is not very practical.

So, I think the best option would be to limit/control  "makeThumbs" somehow, as described in the Question section.

I have read everywhere and I could not find how to control "makeThumbs".

Thanks in advance.

**Comment by perlpty** [comment]
Ok.  I found the solution. 
Just applied a simple inline CSS  to the extra sections:
`style="display:none;"`

**Comment by bago** [comment]
Yeah! data-ko-display will remove any "display: none" style from the element it is applied to (I just added a sentence here: https://github.com/voidlabs/mosaico/wiki/Template-language#data-ko-attributes) . This is meant to solve this very specific issue.. so your "html" can be opened in a browser and show you a correct version of your template (of course only one of your variations, but at least a correct one).

The "thumbnailer" task also add a "preview" class to the body of your template before previewing... this means that you can even add custom css styles that will only be applied during the preview, e.g:
```html
<style type="text/css" data-ko-remove>
    .preview .block { border: 3px solid red; }
</style>
```

This style will be removed by mosaico, but will be used by the thumbnailer.
