### ISSUE TITLE
Font size in WYSIWYG

### ISSUE THREAD

**Issue by Smus** [voidlabs/mosaico#247]
Hi, is there anyway to get the font-size picker in the wysiwyg editor, like you can with color, bgcolor e.g,.. the issue is that its not always all the text that need to change size, just a few words.

Maybe under FORMAT, where you have the h1,h2,h3,h4,h5.. 

![image](https://cloud.githubusercontent.com/assets/4640401/21052074/786cdf76-be23-11e6-99c8-312cd89cc3cd.png)

**Comment by bago** [comment]
Have a look at these issues:
https://github.com/voidlabs/mosaico/issues/239
https://github.com/voidlabs/mosaico/issues/194
https://github.com/voidlabs/mosaico/issues/178

**Comment by Smus** [comment]
Found what I needed in wysiwyg.js

```
fullOptions: {
    toolbar1: 'bold italic forecolor backcolor hr styleselect removeformat | link unlink | pastetext code',
    toolbar2: "styleselect formatselect fontselect fontsizeselect", 
    plugins: ["link hr paste lists textcolor code"],
    // valid_elements: 'strong/b,em/i,*[*]',
    // extended_valid_elements: 'strong/b,em/i,*[*]',
    // Removed: image fullscreen contextmenu
    // download custom:
    // jquery version con legacyoutput, anchor, code, importcss, link, paste, textcolor, hr, lists
  },
```

Just needed to add toolbar2
