### ISSUE TITLE
Templating - Block fixed

### ISSUE THREAD

**Issue by perlpty** [voidlabs/mosaico#248]
Hi.
I would like to know how do "footerBlock"  get fixed at the bottom of the "versafix-1" template, and it is not possible to add another or remove it.  It is a great feature because Unsubscribe links should always be there.

This feature might be related to "themes" but I don’t full undertand them yet.
In   "versafix-1" template, footerBlock & preheaderBlock  have theme = "frameTheme" while others have theme = "contentTheme"

my current relevant CSS code is like this:
```
<----Content Definitions Above---->

contentTheme { label: Main Style; }
frameTheme { label: Frame Style; }
template { label: Page; theme: frameTheme;  properties: blockBgColor; }
COL3COPYRIGHTBlock { label: Unsubs Block - 2 Cols; theme: frameTheme; }	

<----Other Block Definitions Below---->
```
For reference, "tedc15" only 1 have theme:
`bodyTheme { label: Body; }`

and does not expose the Fixed Block Feature.

I think that I might be missing something else, but I dont get it yet.  Any help is appreciated.

Thanks.

**Comment by bago** [comment]
if you declare da data-ko-block inside a data-ko-container then you have a draggable block and a "container" where to drag blocks.
If you declare data-ko-block outside a container then you have a "fixed block".

Theming has nothing to do with this: theming deals with "default values" for the block. You may notice that by default when you change a color you change the color of all the blocks that belongs to the same "theme"..

**Comment by perlpty** [comment]
Thanks you very much!  The solution works perfectly and it was Exactly what I was looking for.
Since there is only 1  `data-ko-container="main"` all fixed blocks could be only at the very top or at the very bottom of the template.  At least  until there is a way to use more than 1  `data-ko-container` in any template.

**Comment by bago** [comment]
Right. We designed the language so to support multiple "containers" but the code at this moment does support only one container and it has to be named "main".
