### ISSUE TITLE
How to detect if block content modified

### ISSUE THREAD

**Issue by fiend-etalonsoft** [voidlabs/mosaico#25]
Hello guys.
I'd like to detect somehow that user dropped a block and changed its content to prevent using of newsletter with default block content.
Is it possible to detect somehow what block content changed (or not changed) ?
thank you in advance.

**Comment by bago** [comment]
Mosaico doesn't keep in the "content model" the "changed status".

Sometimes the default text is OK to be used (e.g: for the Unsubscribe link or other smaller texts around the template).

What you can probably do is to look for some content, like "Far far away, behind the word mountains" in the generated email and alert the user in this case.

**Comment by fiend-etalonsoft** [comment]
Thanks for quick reply.
I need it just to display warning message to end user. For example mailchimp does the same.
Ok, I will try to implement it with some custom plugin for tinymce.

thanks again for amazing editor

**Comment by bago** [comment]
I'm closing this because I don't think such a feature could be part of the "client-side" library: if you have suggestions about how it could work on the client side and be implemented as a new feature  in mosaico please reopen/comment.
