### ISSUE TITLE
Add class name (not replace it)

### ISSUE THREAD

**Issue by dmaus** [voidlabs/mosaico#250]
I want to add a class name to a div like this:
`<div class="class1 class2" style="-ko-attr-class: @prop  ">`

...with a select widget:
`prop{ label: ClassName; widget: select; options: class3|class4; }`

But it replaces the class name instead of adding it. 
`<div class="class3"> `

instead of:
`<div class="class1 class2 class3"> `

Any chance to make this work? Thx

**Comment by bago** [comment]
This should work and give class3 default value to prop:
```html
<div class="class1 class2 class3" style="-ko-attr-class: class1 class2 @prop">
```

if that doesn't work try with this:
```html
<div class="class1 class2 class3" style="-ko-attr-class: class1 class2 @[prop]">
```

please report back.

**Comment by dmaus** [comment]
I tried that, but i get the following error:

![screen shot 2016-12-13 at 18 17 40](https://cloud.githubusercontent.com/assets/2518368/21150772/7973d3e4-c160-11e6-8ec4-de0c59ff7efb.png)

**Comment by bago** [comment]
You did not write what I wrote.

**Comment by dmaus** [comment]
Yeah sorry. You where right. Works! Thx
