### ISSUE TITLE
What are minimum Browser requirements?

### ISSUE THREAD

**Issue by perlpty** [voidlabs/mosaico#251]
Hi.  **What are minimum Browser requirements?** or **are there any OS or Graphic Card minimum requirements?**

I have installed Mosaico 0.15 and I use it in my desktop computer without any issues.
Desktop is: Ubuntu 12.04LTS 64-bit. I don't usually update the system software.  It is somehow old.
In this computer's browsers Mosaico is seen without any issues.  Here are some screenshots of the Mosaico menu.

![u12](https://cloud.githubusercontent.com/assets/23323762/21266782/9094fa32-c375-11e6-8c6b-3712cf79d408.jpg)

However, I tried today to see it on the laptop  today.  Laptop is: Ubuntu 14.04 LTS 64-bit.  The laptop is newer than Desktop, I have updated System software a little more often than Desktop, but browsers are not updated that frequently. Here are some screenshot of the Mosaico Menu in this Laptop.

![u14](https://cloud.githubusercontent.com/assets/23323762/21266882/f6b7a53a-c375-11e6-9303-a8142429a209.jpg)

As you can see, Laptop is newer with browsers just a little older than desktop counterparts but Mosaico Menus does not render properly. Except for Chromium, all browsers in Laptop are older than Desktop's ones.

BTW, **There are no error on [network] console.**  The console results are the same as Desktop.

Just in case and because of this situation, **I'm also wondering if the Menus I see in my Desktop are the one I should expect?**

In a previews Mosaico release (v0.15 but older commit, just before the knockout version upgrade) The menu icons displayed the word "PREVIEW" for the Preview screen instead of just an icon.  

Don't get me wrong, An icon is good.  I have no regrets of that, I'm just wondering if Mosaico is rendering properly in my Desktop PC since Laptop rendering is not equal as Desktop rendering.

Thanks.

**Comment by bago** [comment]
Everything is working as expected: laptop has less space so we do some "reponsiveness".

Browser support is set here: https://github.com/voidlabs/mosaico/wiki#browser-support

The git version after 0.15 but before the latest fix had an incompatibility issue between libraries that made it show labels instead of icons.. but 0.15 and current head should be consistent.

**Comment by perlpty** [comment]
Yes, It is... Indeed, Laptop is 1366 x 768 px and Desktop is 1600 x 900px... Sorry I didn’t realize that could be the reason.  Thank very much for the answer.

Ok, now a few  questions:

1) In a future, do you think **it's worth considering to render full Mosaico in medium screen like: 1366 wide?**??  It is just a question not a suggestion... 
I know they are always building  screens with more pixels as time passes, however, there are still a lot of PCs with 1366px as w-resolution.  1024px is gone for good. 1280px maybe is not worth either,  _but 1366 is well alive_.  I ask this because sometimes the only thing you have is a laptop with a medium screen like this one and you need to make a Responsive email in a hurry.

2) So, 1366 is too small to display Full Mosaico, and 1600 is OK. What about 1440 x 900 (WXGA+) or 1400x1050 (SXGA+) ?? Is this OK or too small?  **Is there any minimum screen width requirement?** Maybe it could also be a good idea to publish this screen requirement along side browser specs.
I dont have 1440 nor 1400 screen but I change resolution on my desktop and PREVIEW icon disappears, so **I guess the minimum screen width should be 1600 for a Full Mosaico. Is that true?**

3) There is a lot of free space to in the toolbar to display the Gallery text, so **why just displaying the gallery icon and not its text too?**

Thanks.

**Comment by bago** [comment]
IMHO the "preview" needs space... so you can't have it where this is no such space.
THe "editing area" may be needed larger than you see: this depends on the template you load.

You can easily change this on your own... there are some simple rules in the less files... just look for @media declarations...
