### ISSUE TITLE
upload files in different folder based on localstorage variable

### ISSUE THREAD

**Issue by parthacal** [voidlabs/mosaico#260]
Need to upload files based on variable set in localstorage.
e.g. uploads/123/(filename)
uploads/124/(filename)

I have localstorage already set which will have values like 123 or 124...

I couldnot find a way to do that. Can anyone help me on this?

Thanks
Partha

**Comment by bago** [comment]
Just change the Mosaico.init parameters ( https://github.com/voidlabs/mosaico/blob/master/editor.html#L45 ) and start Mosaico.init after you read your custom parameter from the localstorage.
