### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by claudiorouge** [voidlabs/mosaico#262]
Hi all.
I have a problem: when i launch the "grunt" command i have this:

Running "postcss:dist" (postcss) task
Warning: Promise is not defined Use --force to continue.
Aborted due to warnings.

anyone can help me?
thank you

**Comment by Hiswe** [comment]
@claudiorouge I think you use an old version of NodeJS which doesn't support Promise.
Try with the 6.

**Comment by claudiorouge** [comment]
@Hiswe Thank you.
i have solved the problem with uninstall nodejs and install following this guide:
https://nodejs.org/en/download/package-manager/

Thank you very much!

**Comment by Hiswe** [comment]
@claudiorouge You're welcome. 

You should checkout [nvm](https://github.com/creationix/nvm). That's a very handy package to manage different node versions on your computer.

**Comment by bago** [comment]
Yes, we recently moved to node >= 6 as requirement for the build because some of our dependencies need that. It is already specificed in package.json and in the readme, so I close this as I can't see anything more we can do to prevent this issue.
