### ISSUE TITLE
Add plaintext editor

### ISSUE THREAD

**Issue by darkblinded** [voidlabs/mosaico#263]
I found that mails created with Mosaico have formatting problems in the plaintext part. For example linebreaks in text blocks are ignored in the plaintext part of the email. 

To solve this one could add a section in the editor to view and edit the plaintext part.

What do you think?

**Comment by bago** [comment]
Mosaico library is about creating html: it is not an "email" creator, but only a creator for the "html of your email" (the template).

For the same reason mosaico doesn't give you tool to choose the Sender name or the Subject, nor let you add attachments then I don't see reasons why it should let you specify a "text-plain" version of the email.

If anyone wants to extend the mosaico library so to add full "email" creation (subject, sender, recipients, cc/ccn, attachments, plain text and anything else) then it could "make sense" but I don't see "plaintext editor" an option for mosaico.

**Comment by darkblinded** [comment]
Okay, I understand. I had a wrong idead and was refering to the already existing test-send feature.

**Comment by bago** [comment]
Ideas are always welcome! This doesn't fit the current library, but this may push someone else creating something bigger *using* (around) mosaico.

Thank you!.
