### ISSUE TITLE
Mosaico with php application

### ISSUE THREAD

**Issue by wishwa** [voidlabs/mosaico#265]
hi,

We are planning to integrate mosaico editor with Angular, PHP application. I'm new to mosaico. Could you please assist me to where to start. If you guys have any documentation related to this could you please share it with me.

Thanks
Wishwa

**Comment by Hiswe** [comment]
Hi,

I think you could start with the [build process](https://github.com/voidlabs/mosaico#buildrun--) and check how it was [integrated with php here](https://github.com/ainterpreting/mosaico-php-backend)

There is also many closed tickets about mosaico integration that can answer your questions.

**Comment by bago** [comment]
Also read
https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md
https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico
https://github.com/voidlabs/mosaico/wiki
