### ISSUE TITLE
Problem when saving image

### ISSUE THREAD

**Issue by duda-spsouza** [voidlabs/mosaico#266]
The mosaic has a possibility to save chosen image of the computer but in my application works differently within the application there is a gallery of images that has a point of choice any image and thus changing the "SRC" of the source image and to a destination But I'm having a problem that I can not save the "SRC" destination always after saving structure shows the "SRC" source.

I know there is this semantics to search for images locally <img data-ko-editable = "leftImage.src">

Is there any solution to this problem "data-ko-editable = 'leftImage.src'" to solve my problem?

**Comment by bago** [comment]
I'm sorry I don't think I understand the issue from your description.

If you don't use ```data-ko-editable="leftImage.src"``` but instead use ```src="defaultSrc.png" style="-ko-attr-src: leftImage.src"``` then your src will be edited in the "Content" tab and you can add the "browsing" there. So.. you simply "drop" mosaico image editability management and switch to a simple "editable property", the same you do with "HREF"s.

**Comment by bago** [comment]
no feedback
