### ISSUE TITLE
Custom font to template

### ISSUE THREAD

**Issue by Kajakaran** [voidlabs/mosaico#267]
Hi,

Please anyone knows how to install custom fonts and to make available in the template style font options drop down?

Thanks
Kajan

**Comment by bago** [comment]
In the header of the template:
```
<!--[if !mso]><!-- -->
<link href="https://fonts.googleapis.com/css?family=Your+Web+Font" rel="stylesheet" type="text/css" />
<!--<![endif]-->
```
In the @supports -ko-blockdefs section of your template:
```
      face { label: Font; widget: select; options: Your Web Font, Fallback, serif=Your Web Font|Arial, Helvetica, sans-serif=Arial|Arial Black, Arial Black, Gadget, sans-serif=Arial Black|Comic Sans MS, Comic Sans MS5, cursive=Comic Sans|Courier New, Courier New, monospace=Courier|Georgia, serif=Georgia|Impact, sans-serif=Impact|Lucida Console, Monaco, monospace=Lucida Console|Lucida Sans Unicode, Lucida Grande, sans-serif=Lucida Sans Unicode|Times New Roman, Times, serif=Times New Roman|Verdana, Geneva, sans-serif=Verdana}
```

This will probably work, but the link will be present in the output email even if the user doesn't use this font at all.

Webfonts have too poor supports by email clients (in europe less than 25% opens happens on webfonts enabled email clients), right now, so we didn't plan supporting that use case in any special way.

**Comment by Kajakaran** [comment]
@bago 
Thank you for for that. I will try this.

**Comment by bago** [comment]
Did it work?

**Comment by Kajakaran** [comment]
Yes It worked
Thanks @bago

**Comment by mkrishtopa** [comment]
Thanks @bago !
