### ISSUE TITLE
mosaico not working in local environment

### ISSUE THREAD

**Issue by marcomas** [voidlabs/mosaico#27]
Hello guys,

I can not run an application locally, I downloaded the source code, but it fails, I miss JS libraries:

/dist/mosaico-material.min.css?v=0.10
/dist/notoregular/stylesheet.css
/dist/mosaico.min.js?v=0.11

The error returned was "Mosaic is not defined"
where can I download the libraries that are missing?

thank you in advance.

**Comment by bago** [comment]
Did you read the build instructions in the README? You need node.js and grunt to build it. What you download are sources that must be "compiled".

**Comment by marcomas** [comment]
Thanks for quick reply.

ok, it will mean that I read the documentation
thanks again

**Comment by marcomas** [comment]
Hi bago,

I managed to run the application, but now I have another problem, when I load a picture, not really charge, I must set some configuration parameter?

I'm sorry for my bad English

thanks again

**Comment by bago** [comment]
Are you running "grunt" in the background? Do you have any error on the grunt console?
Are you opening mosaico in http://127.0.0.1:9000 ? if you open it with a "file://" url then it won't work because of browser security settings.

If you did all of this, open your javascript console and tell me what do you see in console.

**Comment by marcomas** [comment]
you are running "grunt," I'm opening mosaic http://127.0.0.1:9000, the JavaScript console is empty, in the console "grunt" you see some mistakes, following the content of the console:

>> Local Npm module "grunt-parallel" not found. Is it installed?
Loading "phantom-thumbnailer-editor.js" tasks...ERROR
>> Error: Cannot find module 'webpage'

Running "bowercopy:libs" (bowercopy) task
bower_components\knockout\dist\knockout.js -> dist\vendor\knockout.js
bower_components\jquery\dist\jquery.min.js -> dist\vendor\jquery.min.js
bower_components\jquery\dist\jquery.min.map -> dist\vendor\jquery.min.map
bower_components\jquery-ui\jquery-ui.min.js -> dist\vendor\jquery-ui.min.js
bower_components\jquery-ui\themes\smoothness\jquery-ui.min.css -> dist\vendor\jq
uery-ui.min.css
bower_components\jqueryui-touch-punch\jquery.ui.touch-punch.min.js -> dist\vendo
r\jquery.ui.touch-punch.min.js
bower_components\knockout-jqueryui\dist\knockout-jqueryui.min.js -> dist\vendor\
knockout-jqueryui.min.js
bower_components\blueimp-canvas-to-blob\js\canvas-to-blob.min.js -> dist\vendor\
canvas-to-blob.min.js
bower_components\blueimp-load-image\js\load-image.all.min.js -> dist\vendor\load
-image.all.min.js
bower_components\jquery-file-upload\js\jquery.iframe-transport.js -> dist\vendor
\jquery.iframe-transport.js
bower_components\jquery-file-upload\js\jquery.fileupload.js -> dist\vendor\jquer
y.fileupload.js
bower_components\jquery-file-upload\js\jquery.fileupload-process.js -> dist\vend
or\jquery.fileupload-process.js
bower_components\jquery-file-upload\js\jquery.fileupload-image.js -> dist\vendor
\jquery.fileupload-image.js
bower_components\jquery-file-upload\js\jquery.fileupload-validate.js -> dist\ven
dor\jquery.fileupload-validate.js
bower_components\evol-colorpicker\css\evol.colorpicker.min.css -> dist\vendor\ev
ol.colorpicker.min.css
bower_components\evol-colorpicker\js\evol.colorpicker.min.js -> dist\vendor\evol
.colorpicker.min.js
bower_components\tinymce\tinymce.min.js -> dist\vendor\tinymce.min.js
bower_components\tinymce\themes -> dist\vendor\themes
bower_components\tinymce\skins -> dist\vendor\skins
bower_components\tinymce\plugins -> dist\vendor\plugins
bower_components\webfont-notosans\regular -> dist\vendor\notoregular

Running "bowercopy:fontawesome" (bowercopy) task
bower_components\font-awesome\fonts\fontawesome-webfont.woff2 -> dist\fa\fonts\f
ontawesome-webfont.woff2
bower_components\font-awesome\fonts\fontawesome-webfont.woff -> dist\fa\fonts\fo
ntawesome-webfont.woff
bower_components\font-awesome\fonts\fontawesome-webfont.ttf -> dist\fa\fonts\fon
tawesome-webfont.ttf
bower_components\font-awesome\fonts\fontawesome-webfont.svg -> dist\fa\fonts\fon
tawesome-webfont.svg
bower_components\font-awesome\fonts\fontawesome-webfont.eot -> dist\fa\fonts\fon
tawesome-webfont.eot
Some bower components are not configured:  [ 'knockout-sortable',
  'knockoutjs-reactor',
  'mensch',
  'toastr',
  'knockout-undomanager',
  'knockout.wrap',
  'jquery.iframe-transport',
  'console-browserify',
  'blueimp-file-upload',
  'jsep',
  'tinycolor' ]

Running "copy:res" (copy) task
Created 7 directories, copied 29 files

Running "jshint:all" (jshint) task

√ No problems


Running "combineKOTemplates:main" (combineKOTemplates) task

Running "browserify:debug" (browserify) task
>> Bundle build/mosaico.js created.

Running "browserify:main" (browserify) task
>> Bundle build/mosaico.debug.js created.

Running "exorcise:main" (exorcise) task
Exorcising source map from build/mosaico.debug.js

Running "less:css" (less) task
File build/mosaico.css created
File build/mosaico-material.css created

Running "postcss:dist" (postcss) task
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#style() is deprecated. Use Node#raw()
Container#remove is deprecated. Use Container#removeChild
Node#before is deprecated. Use Node#raws.before
Node#_value was deprecated. Use Node#raws.value
Node#semicolon is deprecated. Use Node#raws.semicolon
Node#after is deprecated. Use Node#raws.after
Container#eachComment is deprecated. Use Container#walkComments instead.
Node#removeSelf is deprecated. Use Node#remove.
Node#between is deprecated. Use Node#raws.between
Node#_important was deprecated. Use Node#raws.important
AtRule#afterName was deprecated. Use AtRule#raws.afterName
>> 1 processed stylesheet created.
>> 1 sourcemap created.

Running "postcss:material" (postcss) task
>> 1 processed stylesheet created.
>> 1 sourcemap created.

Running "express:dev" (express) task

Running "express-server:dev" (express-server) task
Web server started on port:9000, no hostname specified [pid: 4160]

Running "watch" task
Waiting...
express deprecated res.json(status, obj): Use res.status(status).json(obj) inste
ad node_modules\jquery-file-upload-middleware\lib\filehandler.js:19:21
error: Property mso-table-rspace: 0pt at C:\Users\MarcoM\Desktop\MOSAICO\mosaico
-0.11\backend\-html-#undefined is invalid: Unknown property 'mso-table-rspace'.
error: Property mso-table-lspace: 0pt at C:\Users\MarcoM\Desktop\MOSAICO\mosaico
-0.11\backend\-html-#undefined is invalid: Unknown property 'mso-table-lspace'.
>> File "dist\vendor\mosaico-material.min.css" added.
>> File "dist\vendor\mosaico.min.css" added.
>> File "dist\vendor\mosaico.min.js" added.
Completed in 0.002s at Sun Nov 01 2015 09:58:43 GMT-0430 (Hora estándar de Venez
uela) - Waiting...
error: Property mso-table-rspace: 0pt at C:\Users\MarcoM\Desktop\MOSAICO\mosaico
-0.11\backend\-html-#undefined is invalid: Unknown property 'mso-table-rspace'.
error: Property mso-table-lspace: 0pt at C:\Users\MarcoM\Desktop\MOSAICO\mosaico
-0.11\backend\-html-#undefined is invalid: Unknown property 'mso-table-lspace'.
>> File "dist\vendor\mosaico-material.min.css" deleted.
>> File "dist\vendor\mosaico.min.css" deleted.
>> File "dist\vendor\mosaico.min.js" deleted.
Completed in 0.001s at Sun Nov 01 2015 10:00:24 GMT-0430 (Hora estándar de Venez
uela) - Waiting...


thanks again

**Comment by marcomas** [comment]
I installed the module "grunt-parallel", but continue to leave the error

Loading "phantom-thumbnailer-editor.js" tasks ... ERROR
Error: Can not find module 'webpage'

**Comment by bago** [comment]
1) grunt-parallel is not needed on my setup: which versions of node.js and npm do you have?
2) You can ignore the "Can not find module 'webpage'".

About your images upload issue, did you install imagemagik? Do "convert" on command line output imagemagik help?

**Comment by bago** [comment]
Closing this because of no feedback on the last question. Please reopen if you still have issues.

**Comment by tiagobernardes** [comment]
i have this issue too.

Loading "phantom-thumbnailer-editor.js" tasks...ERROR

and next url not show anything
http://localhost:9000/img/?method=placeholder&params=166%2C130

**Comment by bago** [comment]
Ignore the thumbnailer error.
Did you read the readme about imagemagick and the convert command?

Do you see console messages in the running grunt when that url is called?

**Comment by marcomas** [comment]
Hi Bago, 

I was able to run the project.
sorry if I have not written more, and that I was busy on another project

Thanks again

**Comment by tiagobernardes** [comment]
Hi Bago,

installed imagemagick in my environment (win7 64) but  the images are still not being presented. (see the attached image)

I have no errors in the console.


![mosaico](https://cloud.githubusercontent.com/assets/15774469/11168844/8252e534-8b99-11e5-8d6a-7c2d61ac324c.png)

**Comment by bago** [comment]
Open a command prompt and write "convert" .. it should result in the imagemacick command help. If this does not happen then you didn't install imagemagick correctly or it is not in your path.

**Comment by tiagobernardes** [comment]
Oh yes now !!
It is already working with images! :D
thank you

**Comment by janietom2** [comment]
Images path does not work with Apache/PHP

Using:
OS X El Capitan 10.11.2
MAMP

However it is fully working using grunt

**Comment by srinathMayee** [comment]
i have this issue:

Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'load-grunt-tasks'
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.

**Comment by bago** [comment]
@srinathMayee this is NOT the same issue. So, don't pollute unrelated issues. Please read the readme to understand how to open issues. I don't reply to issues that don't include the required informations: https://github.com/voidlabs/mosaico/blob/master/README.md

**Comment by MaheshSundaramurthy** [comment]
![image](https://cloud.githubusercontent.com/assets/20756874/17277744/a4533116-5718-11e6-82f1-9ad148770dc3.png)

Image upload is not working. Kindly help. No errors seen in console and image magick is installed.
Running "Magick Convert" in command line shows magick help. Still image not working.

Any assistance in bringing up my environment will be of great help

In the browser, failed to load URL is seen for the image.
![screen1](https://cloud.githubusercontent.com/assets/20756874/17277766/4e0c0cbe-5719-11e6-8807-a12e7301785a.png)

Thanks
Mahesh

**Comment by bago** [comment]
I wrote "convert" not "magick convert".
Are you sure that the command console output is the "latest" (after you saw the error on the image upload)?
Can you check the "Network" tab of your browser to see what kind of response you get on the image resource call when you upload? Also, check the "Javascript console" to see if you get logs during the image upload/download.

**Comment by MaheshSundaramurthy** [comment]
Hi Bago,
Thanks for the reply. Please find the requested information. Kindly help
The Console output is latest and does not show any error. Image Attached.
In Network tab, we are noticing 3 GET Requests.  Images Attached

FAILS - http://127.0.0.1:9006/img/?method=placeholder&params=258%2C150
SUCCESS - http://127.0.0.1:9006/uploads/Chrysanthemum.jpg
FAILS-  http://127.0.0.1:9006/img/?src=http%3A%2F%2F127.0.0.1%3A9006%2Fuploads%2FChrysanthemum.jpg&method=resize&params=258%2Cnull

![console](https://cloud.githubusercontent.com/assets/20756874/17348561/f2248ec6-58e4-11e6-9e93-4f44a7a6e841.png)
![network1](https://cloud.githubusercontent.com/assets/20756874/17348568/fd9f0844-58e4-11e6-9ccf-d9d8125f1906.png)
![network2](https://cloud.githubusercontent.com/assets/20756874/17348570/001d02c4-58e5-11e6-83a4-f366efac3391.png)
![network3](https://cloud.githubusercontent.com/assets/20756874/17348572/01eedae6-58e5-11e6-833a-d0fa099639e4.png)

**Comment by bago** [comment]
I wrote "convert" not "magick convert".

**Comment by MaheshSundaramurthy** [comment]
![convert](https://cloud.githubusercontent.com/assets/20756874/17388290/47b53f68-59c9-11e6-8f14-c288414d02a3.png)
Hi Please find the snapshot with "convert" in command line. Please advise

**Comment by bago** [comment]
I can't help with this. "convert" is a dependency.. check with Image Magick help/site/forums to solve your issue with it. Once it works, then you will be able to use mosaico locally.

**Comment by MaheshSundaramurthy** [comment]
Ok. Let me check. Could you please share a snapshot how how the 'convert' work in command line. This way I would know what to expect while testing.

**Comment by bago** [comment]
The convert output is the same you got on "Magick convert". You probably just have to change PATH so to have image magic path before the Windows filesystem convert utility.

**Comment by MaheshSundaramurthy** [comment]
It worked. Nothing wrong with the install or configuration. Looks like from Image Magick 7 convert.exe is changed to magick.exe. Uninstalled and installed Image Magick 6. Image upload works now. 

Let me work on this more and next step is email. Let's see how it goes. Thanks again for all the help

**Comment by bago** [comment]
Thank you for reporting. I updated the Readme according to aheckmann/gm#559
