### ISSUE TITLE
Is there anyway to support "foreach" for element property?

### ISSUE THREAD

**Issue by jujusharp** [voidlabs/mosaico#270]
I need to dynamic create sub items in a container, and the count of the items can be customized with property. for example.
I have a <ul> containner, and all sub items are same styles with li. I can set the count of "li", and the <li> elements can be rendered with the COUNT I've set.

I noticed that knockout can support with `data-bind="foreach: myproperty"`, so can mosaico support this?

**Comment by bago** [comment]
Can you give me your use case? Is it a menu? Is there a "maximum" number of items that makes sense?

**Comment by jujusharp** [comment]
I has a block `<ul>` with `<li>some content</li>` items, and I want to make specific list items, then the items can be rendered with the specific item count.
for example. if I set the count of items to 4, then it can with code like:

    <ul>
       <li>put your content here</li>
       <li>put your content here</li>
       <li>put your content here</li>
         <li>put your content here</li>
    <ul>

if I set the count to 6, it can be with:

    <ul>
       <li>put your content here</li>
       <li>put your content here</li>
       <li>put your content here</li>
       <li>put your content here</li>
       <li>put your content here</li>
       <li>put your content here</li>
    <ul>

I looked the example templates in source code, it can only with defined content, and display with `data-ko-display="titleVisible"`, but it can't satisfied my requirement.

Thanks for your reply!

**Comment by bago** [comment]
I'm sorry you can't do that with our current template language.

But you can do ```<ul data-editable="listText"><li>sample content</li></ul>```: the user will be able to add new items using the enter key.

The use case doesn't seem so useful to me so I won't add it to the ideas/feature suggestions list: if your real use case is not a list of LI elements with editable contents inside each one then your answer is not an use case. If instead you only wrote an example then you didn't answer my "use-case" question. 

You also didn't answer to my questions about the maximum number of elements.

**Comment by jujusharp** [comment]
Sorry if my reply not direct make the issue clear. 
1. My user case is: I wanna to create some formatted sub items in a container for the template, for example, a list of images or double articles, all items in it have a fixed html structure. 
2. yes, this is a maximum number of elements.

and more, I can use UL for this user case, but if I use UL, I must valid all html content in the UL is within the fixed format after user edit it.

**Comment by bago** [comment]
I don't understand the "must valid all html content" thing: even if you create multiple editable placeholders you have to do the same input validation... 

Your options are

```
<ul>
<li data-ko-editable="firstText" data-ko-if="textsNumber gte 1">put your content here</li>
<li data-ko-editable="secondText" data-ko-if="textsNumber gte 2">put your content here</li>
<li data-ko-editable="thirdText" data-ko-if="textsNumber gte 3">put your content here</li>
<li data-ko-editable="fourthText" data-ko-if="textsNumber gte 4">put your content here</li>
<li data-ko-editable="fifthText" data-ko-if="textsNumber gte 5">put your content here</li>
</ul>
```

or
```<ul data-editable="listText"><li>sample content</li></ul>```

**Comment by jujusharp** [comment]
valid the contents means I need the li content with same dom structure. e.g

<ul data-editable="listText">
<li><img must hear><span>span must here</span><div>or some other dom must be here</div></li>
</ul>

And thanks for your reply, I think "gt or gte" is the solution in this scenario!

**Comment by bago** [comment]
I close this as won't fix as I think the existing "data-ko-if" solution is a good workaround for most use cases and we don't have strong/frequent use case requiring foreach handling, yet.

**Comment by ineffyble** [comment]
One use case that's come up for me is dynamically/automatically generating an index/table of contents, based around the blocks in use.
