### ISSUE TITLE
Getting html information

### ISSUE THREAD

**Issue by asbag** [voidlabs/mosaico#271]
Hi,

I'm trying to get some clue about how are "Saved Contents" stored. I found out that uploaded images are stored physically in "uploads" folder, metadata content can be get from localStorage, but I cannot see any other information about further content like dragged "blocks" and so on of each saved content session. How can you get html saved contents? Is this information stored physically somewhere? As far as I could discovered with localStorage you can get metadata information but is there any way of getting html content?

Hope you can understand my doubt.

Thank you so much for your help.

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/wiki/Saving-and-Loading
https://github.com/voidlabs/mosaico/issues/264
https://github.com/voidlabs/mosaico/issues/73

Content JSON: https://github.com/voidlabs/mosaico/blob/master/src/js/ext/localstorage.js#L40
Output HTML: https://github.com/voidlabs/mosaico/blob/master/src/js/ext/localstorage.js#L85
Plugins: https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins

**Comment by asbag** [comment]
Thank you!!,

Regards,
David
