### ISSUE TITLE
Image upload issue

### ISSUE THREAD

**Issue by manuvel** [voidlabs/mosaico#272]
Can anyone help to fix this issue?
404 Not Found		53ms	jquery.min.js (line 4)
"NetworkError: 404 Not Found - http://192.168.1.116/mosaico-master/upload/"

Response:-

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /mosaico-master/upload/ was not found on this server.</p>
</body></html>

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/blob/master/README.md
https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md
