### ISSUE TITLE
Question about variables inside the template file

### ISSUE THREAD

**Issue by Frolipon** [voidlabs/mosaico#273]
Hello

This is not really an issue, but more a need to know if something is possible.

First of all, thanks for opensourcing your tool, it's really great :-)!

I woul like to know if it is possible to define variables usable in the HTML inside the HTML file that is meant to be the template.

More precisely:
For a template given, I created a dropdown allowing me to select "Brand 1", "Brand 2", "Brand 3" like this:
```
myBrand {
        label: Brand Selection;
        widget: select;
        options: brand1=Brand 1|brand2=Brand 2|brand3=Brand 3;
}
```

This means I can personalise the header/footer with 
```
<div data-ko-display="myBrand eq 'brand1'" data-ko-wrap="false">
        code for header Brand1
</div>

<div data-ko-display="myBrand eq 'brand2'" data-ko-wrap="false">
        code for header Brand2
</div>

<div data-ko-display="myBrand eq 'brand3'" data-ko-wrap="false">
        code for header Brand3
</div>
```

But I would like to define somewhere in the template a variable with a color code for example, so that I can use it inside the blocks. I know I can do it for each individual block, but I want to use only one general dropdown defining the graphic guidelines, to have something like this:

```
brandColor {
    if myBrand eq "brand1" [myColor=#110000]
    if myBrand eq "brand2" [myColor=#001100]
    if myBrand eq "brand3" [myColor=#000011]
}


<div data-ko-block="coverImageBlock">
    <p style="color: @myColor;">
        My copy inside a block
    </p>
</div>
```

The main idea is that by selecting only one item, I can update colors, font-family, … everywhere at once in the template.
This is particularly useful for a company that shoot a newsletter on several brand with the same structure, but whith different looks.

Kind Regards,

**Comment by bago** [comment]
I'm sorry this is something not implemented in mosaico.

I think this would be better mapped as "template themes" so that you define multiple themes and you can switch to a predefined theme instead of customizing it. We don't have this feature in roadmap right now.

You can use ternary in order to compress the use of a given 
```color: @[myBrand eq "brand1" ? _root_.brand1Color : myBrand eq "brand2" ? _root_.brand2Color : _root_.brand3Color]```

in your template you will also need:
```template { label: Page; properties: brand1Color=#110000 brand2Color=#001100 brand3Color=#000011 myBrand=brand1; }```

This way you can choose the brand and you can even alter the default color for each brand.

Otherwise


```color: @[myBrand eq "brand1" ? '#110000': myBrand eq "brand2" ? '#001100' : '#000011']```
and in the template
```template { label: Page; properties: myBrand=brand1; }```
if you want the 3 colors to be hardcoded.

**Comment by Frolipon** [comment]
Thanks for the answer.

I tried the fix with the hardcoding solution, but it doesn't seems to work.
when I use the the code for the color, the system doesn't seem to recognise a variable.

If I have:
```
myBrand {label: Brand Color; widget: select; options: brand1=Brand1|brand2=Brand2|brand3=Brand3;}

template { label: Page; theme: frameTheme ;properties:  myBrand=brand1; }
```
and in the HTML:
```
<div style="font-family: arial, helvetica, sans-serif;font-size: 20px; color: @[myBrand eq "brand1" ? '#110000': myBrand eq "brand2" ? '#001100' : '#000011'] ;text-align: center;font-weight: bold;line-height:normal;" data-ko-editable="titleText">
   My Title
</div>
```

But the builder does not seems to find the myBrand variable. I don't have the dropdown in the content panel.

If I add a
```
<div data-ko-display="myBrand eq "brand1" data-ko-wrap="false">
</div>
```
somewhere in the template, then the dropdown in the content panel appears, but with no results for the colors.

This lead me to think that this instruction:
` color: @[myBrand eq "brand1" ? '#110000': myBrand eq "brand2" ? '#001100' : '#000011'] `
is not recognised by the builder.
If I check the HTML after downloading it, the code for the builder is still there.

I tried with simple quotes instead of double quotes, but the result is the same.

I tried also with:
```
<div style="font-family: arial, helvetica, sans-serif;font-size: 20px;color: #ffffff; -ko-color: @[myBrand eq "brand1" ? '#110000': myBrand eq "brand2" ? '#001100' : '#000011'] ;text-align: center;font-weight: bold;line-height:normal;" data-ko-editable="titleText">
   My Title
</div>
```
But then I have a crash.

I also tried the solution where the color is defined in the
`template { label: Page; properties: brand1Color=#110000 brand2Color=#001100 brand3Color=#000011 myBrand=brand1; }`, which wood be a great solution, but it doesn't work either.

Do you have any idea why I can't make the
` color: @[myBrand eq "brand1" ? '#110000': myBrand eq "brand2" ? '#001100' : '#000011'] `
work? Did I miss something?

**Comment by bago** [comment]
Please note that you can't put doublequotes in values for html attributes that you are enclosing in double quotes. So use different quotes or encode them.

> But then I have a crash.

Define "crash". If the editor doesn't start or break then have a look at the browser Javascript console output.

**Comment by Frolipon** [comment]
No, I didn't used double quotes in the values. I just tried 
`color: @[myBrand eq 'brand1' ? '#110000': myBrand eq 'brand2' ? '#001100' : '#000011']`
instead of.
color: @[myBrand eq "brand1" ? '#110000': myBrand eq "brand2" ? '#001100' : '#000011']
About the crash, here is the log error:

![image](https://cloud.githubusercontent.com/assets/14838636/22212923/b51eb402-e192-11e6-8fe1-db915b480b40.png)

**Comment by bago** [comment]
The error doesn't seem to be generated by that code. The first javascript exception is really telling you that your html value contains double quotes.... you just have to read the html after the error to see how mosaico is readying your code.

**Comment by Hiswe** [comment]
Following @bago suggestion I've successfully came up with a solution (in the zip).

[sub-themes.zip](https://github.com/voidlabs/mosaico/files/754356/sub-themes.zip)

For the error, it was the double quotes in the ternary that breaks.

This doesn't work:

```
color: @[myBrand eq "brand1" ? _root_.brand1Color : myBrand eq "brand2" ? _root_.brand2Color : _root_.brand3Color]
```

This does:

```
color: @[myBrand eq 'brand1' ? _root_.brand1Color : myBrand eq 'brand2' ? _root_.brand2Color : _root_.brand3Color]
```

---

@bago I've tried also to implement in mosaico parser something that can handle code like this :

```
@` overrideColor ? overrideColor : _root_[ _root_.myBrand ] .coloraccentVar `;
```

Back-tick are used to have an easy regexp in `utils.js` but it breaks with an "Unexpected computed member expression"… no times to really dig-in more. 
If you have some ideas of how it can be implemented, I will be glad to know :)

**Comment by bago** [comment]
Well, you're digging deep in stuff I don't have fresh memory for. I thought the expression language as something flexible but not to this extent. 

Maybe this kind of "logic" belongs to the editor UI itself and not to the template author. What I say is that "multibrand handling" is not something that I see "template related" but something that could be applied to any template as long as the editor let you do this (like a "multi-theme" or theme switcher). Unfortunately this may be even more complex (deeper in the internal structures) than altering the expression language.

**Comment by Hiswe** [comment]
@bago Thank for your answer :) I will look deeper in the expression language if I have time.
