### ISSUE TITLE
Run mosaico in https

### ISSUE THREAD

**Issue by asbag** [voidlabs/mosaico#274]
Hi,

I'm trying to run mosaico in https mode. Is it possible???

Thank you in advance.

Regards,
David

**Comment by bago** [comment]
Sure, you can see https://mosaico.io demo .. it is running in https.

**Comment by asbag** [comment]
Sorry, I saw that it's possible, but unfortunately I was not able to do it, I'm not very goot at node.js programming.

I clone git source,, create a  self-signed Certificate and  changed Gruntfile.js like this: 
....
    express: {
      dev: {
        options: {
          /*
          showStack: true,
          hostname: '127.0.0.1',
          open: true,
          bases: ['.'],
          */
          key: grunt.file.read('livereload.key').toString(),
          cert: grunt.file.read('livereload.crt').toString(),          
          protocol: 'https',
          hostname: 'clientes.gms.es',
          script: 'backend/main.js',
          background: true,
          port: 9006,
        }
      }
    },
....

but nothing happens if I enter  https://localhost:9006 url, only if I enter http://localhost:9006 seems to work.
Is there anything else I am missing?

Best Regards,
David

**Comment by asbag** [comment]
Sorry, clientes.gms.es links to 127.0.0.1, so it's the same as localhost.

**Comment by bago** [comment]
Please note that the bundled backed and node server is just an example that should not be used in production, so I don't see why you would run it in https.

That said, you can write your own Node backend and run it in https... 
Haacking backend/server.js would require something like:

```javascript
var https = require('https');
var options = {
    ca: [fs.readFileSync(PATH_TO_BUNDLE_CERT_1), fs.readFileSync(PATH_TO_BUNDLE_CERT_2)],
    cert: fs.readFileSync(PATH_TO_CERT),
    key: fs.readFileSync(PATH_TO_KEY)
 };
https.createServer(options, app).listen(8443);
```
