### ISSUE TITLE
versafix-1 template issue with longTextStyle.linksColor

### ISSUE THREAD

**Issue by markalston** [voidlabs/mosaico#275]
Having a problem with the versafix-1 template using apache.  It works fine running via grunt.  I am not using the php-backend. The tedc15 template works fine.

The issue is with the
```
 -ko-color: @longTextStyle.linksColor;
```
lines in template-versafix-1.html.

The browser just show a red screen. The console errors are:
```
TODO error!!! Trying to set a new default value for bodyTheme longTextStyle.linksColor while it already exists (current: #3f3f3f, new: #ccc)  mosaico.min.js:1443:10105

Model ensure path failed undefined name -ko-color value @longTextStyle.linksColor default #ccc element undefined  mosaico.min.js:1428:2257

Exception while parsing the template Exception parsing expression @longTextStyle.linksColor TypeError: t[u].defaultValues is undefined <replacedhtml xmlns="http://www.w3.org/1999/xhtml">  mosaico.min.js:1447:8868

uncaught exception: Exception parsing expression @longTextStyle.linksColor TypeError: t[u].defaultValues is undefined
```
If I remove all the lines referencing @longTextStyle.linksColor it works fine.

Server version: Apache/2.4.18 (Ubuntu)
Server built:   2016-07-14T12:32:26

Tested using Firefox 50.1 and Chrome 55.0

**Comment by bago** [comment]
1) You are using apache and NOT using php: what is your backend?
2) Mosaico is a clientside library: if it works with grunt but not via apache this simply means that the versafix-1 template is broken when served to mosaico library. If mosaico receives the same code then it runs in the same way.. You can even try downloading the template via "apache" and compare the downloaded template to the one you have in the mosaico download so you see if your backend (apache or anything else) is doing something weird.

**Comment by markalston** [comment]
My apologies.  You are absolutely correct that it was a backend issue.  I thought I was working in a clean mosaico install and without the backend participating.  That obviously isn't possible as I have learned from fixing the php-backend problems.  My issue was caused by the bad editor.html that the php-backend uses.

As you obviously know, the php backend is completely borked and has had no updates in over a year.  I have reworked it and now have a working fork at https://github.com/markalston/mosaico-php-backend.  

I am not a php programmer and hope that someone else will take over this backend at some point but at least for now it works properly with image uploading and resizing, and downloading and testing the template.

If you want to change your links to my fork (or at least change the README.md to say that the Access Interpreting one is badly broken) that would help future mosaico users greatly.

**Comment by Rar9** [comment]
I´m getting the same versafix gray issue with mosico 2.12 for drupal 7 php 7.4

model.js:504 TODO error!!! Trying to set a new default value for bodyTheme longTextStyle.linksColor while it already exists (current: #3f3f3f, new: #ccc)
modelEnsurePathAndGetBindValue @ model.js:504
declarations.js:130 Model ensure path failed undefined name -ko-color value @longTextStyle.linksColor default #ccc element undefined
elaborateDeclarations @ declarations.js:130
parser.js:403 Exception while parsing the template Exception parsing expression @longTextStyle.linksColor TypeError: Cannot read properties of undefined (reading 'longTextStyle.linksColor') <replacedhtml xmlns=​"http:​/​/​www.w3.org/​1999/​xhtml">​…​</replacedhtml>​
processBlock @ parser.js:403

**Comment by bago** [comment]
Mosaico 2.12 doesn't exists.

The latest release for mosaico is 0.18.9:
https://github.com/voidlabs/mosaico/releases

**Comment by Rar9** [comment]
its Civicrm Mosaico 2.12 https://civicrm.org/extensions/email-template-builder

**Comment by Rar9** [comment]
I tried on civicrm chat , its an old issue that jsut doesnt get resolved

**Comment by bago** [comment]
I'm sorry but I can't fix issues that are not reported against a mosaico release from this project.

If you can reproduce the bug with the latest mosaico release then open a specific issues with details about how to reproduce it.
