### ISSUE TITLE
Problem building

### ISSUE THREAD

**Issue by ManuelEsp** [voidlabs/mosaico#276]
Hello. I'm trying to build mosaico and when I run "npm install" I keep getting this error.

![image](https://cloud.githubusercontent.com/assets/24298023/22440981/4826358c-e714-11e6-9f67-c0350aa69cdf.png)

It says: "." is not recognized as an internal or external command

When I run grunt it keeps waiting forever.
I already read the readme and coldn't find the solution.

I'm using: 
-Windows 7
-npm v3.10.10
-node v7.3.0

Thanks!

**Comment by bago** [comment]
"grunt" is expected to wait forever in the "watch" task.. what do you see if you open a browser to 127.0.0.1(oryournodeIP):9006 ?
