### ISSUE TITLE
Personalization/ place holder tags in editor 

### ISSUE THREAD

**Issue by pkasar** [voidlabs/mosaico#278]
Do you support the tags in editor which can be replaced in the backend?
For example, our users should be able to select [FirstName], etc in editor inside text area?
If you dont support that, what is the best way for us to develop a plugin and contribute to the code?
similar question to links, social icons as well

tyvm
kasar

**Comment by bago** [comment]
You can create a tinymce plugin and configure it via "mosaico viewModel plugin" (https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins)

Have a look at those issues:
https://github.com/voidlabs/mosaico/issues/233
https://github.com/voidlabs/mosaico/issues/194
https://github.com/voidlabs/mosaico/issues/239
https://github.com/voidlabs/mosaico/issues/247
https://github.com/voidlabs/mosaico/issues/178
