### ISSUE TITLE
Can not install...

### ISSUE THREAD

**Issue by mherbold** [voidlabs/mosaico#28]
The entire install process works fine except for npm install for node-byline which returns:

[root@liquidweb3 /home/usked/subdomains/alpha/public/mosaico]# npm install
npm WARN package.json mosaico@0.11.0 No repository field.
npm ERR! git clone git://github.com/SevInf/node-byline.git Initialized empty Git repository in /root/.npm/_git-remotes/git-github-com-SevInf-node-byline-git-d6518a15/
npm ERR! git clone git://github.com/SevInf/node-byline.git
npm ERR! git clone git://github.com/SevInf/node-byline.git github.com[0: 192.30.252.130]: errno=Connection timed out
npm ERR! git clone git://github.com/SevInf/node-byline.git fatal: unable to connect a socket (Connection timed out)
npm ERR! Error: Command failed: github.com[0: 192.30.252.130]: errno=Connection timed out
npm ERR! fatal: unable to connect a socket (Connection timed out)
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Socket.<anonymous> (child_process.js:979:11)
npm ERR!     at Socket.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:466:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/usked/subdomains/alpha/public/mosaico
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0

**Comment by bago** [comment]
"npm ERR! git clone git://github.com/SevInf/node-byline.git github.com[0: 192.30.252.130]: errno=Connection timed out"

Connection timed out to Github? Maybe you're having network issues.
Please run npm install multiple timesuntil it works.
If multiple executions stops on the same error then report the error (npm is not so reliable).

**Comment by mherbold** [comment]
NPM worked on all of the other packages.  It is failing only on this one for some reason.  I can ping 192.30.252.130 just fine.  It stops on the same error every time.  I will go ahead and report the error.

 

-          Marvin Herbold

**Comment by bago** [comment]
I don't know what's going on.. You may try this: https://github.com/npm/npm/issues/5257#issuecomment-60441477

Let me know!

**Comment by mherbold** [comment]
It was my firewall - it was blocking outbound connections to the GIT port.  I have fixed it and this issue is resolved!
