### ISSUE TITLE
-ko-attr-#attrname# bug

### ISSUE THREAD

**Issue by dmaus** [voidlabs/mosaico#280]
I want to insert a data attribut like: 
`<div data-something="foo">` 
with -ko-properties as CSS styles like:
`-ko-attr-data-something-new: "foo"`
but it deletes the minus-hyphen and only inserts: 
`<div datasomething="foo">`

**Comment by bago** [comment]
What's the use case? (I don't know email clients where you use data-* attributes).

Do you have a git fork with the template you are creating?

**Comment by dmaus** [comment]
I need it to catch some variables with javaScript in the Browser. 
Is it somehow possible or do i have to change the source code to make this work?
Sorry, i dont have a git fork...

**Comment by bago** [comment]
Maybe it is a bug. I don't know if/when this will be fixed as the use case is almost unique and you're not working in the open.
