### ISSUE TITLE
Does Mosaico support "save as " template? 

### ISSUE THREAD

**Issue by mricha06** [voidlabs/mosaico#282]
We have integrated mosaico in our product and would like to offer a "save as" kind of functionality for our users. For example, they should be able to save a master template, with the links for facebook, linkedin etc added. Whenever they want to create a mailer, they should be able to "save as" this template, and add more stuff relevant to that particular template. How can this be done ?

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/wiki/Saving-and-Loading
