### ISSUE TITLE
Problem making image source editable

### ISSUE THREAD

**Issue by ManuelEsp** [voidlabs/mosaico#285]
As the title says, I'm having troubles making the image src editable. Here's the code for the block

```
<table data-ko-block="hero" bgcolor="#ffffff" width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse; width: 100%; table-layout: fixed; margin: 0 auto;"> 
  <tr>
    <td height="10"></td>
  </tr>
  <tr>
    <td align="center"><a href="#"><img data-ko-editable="image.src" src="http://portlike.s3.amazonaws.com/img/PCB%20Templates/hero-banner.png" width="95%" height="100%" alt="Hero" title="Hero" align="center"/></a></td>
  </tr>
  <tr>
    <td height="10"></td>
  </tr>
</table> 
```

And this is what I put in the style tag:

`image { label: Image; properties: src url alt }`

After doing this, I get the following js errors:

![image](https://cloud.githubusercontent.com/assets/24298023/23082349/c2eafc54-f537-11e6-9887-3ed662691970.png)

I've successfully made the text parts of my template editable but I was not able to do the same with the image src. Is there something I'm missing?
Thanks!

**Comment by bago** [comment]
The snippet sounds correct. I can't reproduce the issue without the full template html .

**Comment by ManuelEsp** [comment]
I already solved it, thanks! I just had to define the "src".
