### ISSUE TITLE
How to add bullet or numbered list inside a block

### ISSUE THREAD

**Issue by ManuelEsp** [voidlabs/mosaico#286]
Hello. I noticed that in the versafluid template on the website you can add bullet lists as a text format, but I couldn't find that example in the versafix template. Anyone knows how can I add that option to my templates? 
Thank you in advance.

**Comment by bago** [comment]
Have a look at those issues:
#233
#194
#239
#247
#178

You can configure tinymce toolbar via "mosaico viewModel plugin" (https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins)
