### ISSUE TITLE
Blocks move when I try to edit them

### ISSUE THREAD

**Issue by ManuelEsp** [voidlabs/mosaico#288]
I'm having this issue right now. This is how the block looks when I place it in my template and when I download it afterwards:

![image](https://cloud.githubusercontent.com/assets/24298023/23275398/212af2c2-f9e5-11e6-843a-d4a471f66ee0.png)

But when I click on it to edit its content, it moves down a little and the edition tools appear:

![image](https://cloud.githubusercontent.com/assets/24298023/23275423/3ffff6c0-f9e5-11e6-89f8-9ad73d37629d.png)

You can see it's not aligned with the other parts of the block like in the first picture.
Anyone knows why could this be happening?
Thanks in advance!

**Comment by bago** [comment]
Depends on HTML, TAGS, nestability, Tinymce.
If you don't share your template it is hard to guess.

**Comment by bago** [comment]
Not enough informations. Closing this.
