### ISSUE TITLE
CSS/Style disapear after sending mosaico's template to mail

### ISSUE THREAD

**Issue by kjedrol** [voidlabs/mosaico#289]
Hello,

I want to ask You for help.
When i try to send template, builded from 1 block prepared by me to my e-mail, everything works fine, until i check message. 

In Mosaico everything looks good[Bottom picture], but when i send it to my mail[Top picture], everything looks like it is without css.
Why does it happen?
Thanks in advance.

![issue](https://cloud.githubusercontent.com/assets/26062939/23397328/539c5992-fd98-11e6-97c7-3ca3962bd4a5.png)

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>

    <style type="text/css">
        @supports
            -ko-blockdefs {

            text {
                widget: text
            }

            listsize {
                widget: select;
                options: 1 | 2 | 3;
            }

            color {
                widget: color;
            }
        }
        
        .kut{
        	width: 1432px;
        	height: 10000px;
        }
        
        .tekst_temat{
        	
        	margin-top: -180px;
        	margin-bottom: 0px;
        	font-size: 72px;
        }
       
        .tekst_depart{
        	margin-top: 0px;
        	font-size: 48px;
        	background-color: rgba(37,59,73,0.8);
        }
        
        #zdj_baner{
        	
        }
        
        .ojciec{
        	display: flex;
        }

        .ojciec2{
        	display: flex;
        }
       
        .tekst_pl{
        	width: 716px;
        	background: lightblue;
        }
       
        .tekst_eng{
        	flex: 1;
        	background: lightgreen;
        }
       
        .more_info_pl{
        	width: 716px;
        	background: red;
        }
       
        .more_info_eng{
        	flex: 1;
        	background: yellow;
        }
     
    </style>
</head>

<body >
<div class"kut" data-ko-container="main" data-ko-wrap="false">

    <div data-ko-block="HeaderAndText">
        <h1 class="tekst_temat" data-ko-editable="headerText">Temat</h1>

        <h2 class="tekst_depart" data-ko-editable="bodyText">
            Department
        </h2>
        <div class="ojciec">
<div class="tekst_pl" data-ko-editable="abodyText">
	test pl
</div>
<div class="tekst_eng" data-ko-editable="bbodyText">
	test eng
</div>
		</div>
       <div class="ojciec">
<div class="more_info_pl" >
	test pl
</div>
<div class="more_info_eng">
	Wi
</div>
		</div>
	</div>

	</div>

</body>
</html>
`

**Comment by bago** [comment]
I'm sorry I'm not a precog and I can't see what you don't write. If you need help please READ first:
https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md#rendering-issues-with-templates-generated-by-mosaico

**Comment by kjedrol** [comment]
Help please

**Comment by bago** [comment]
You dind't read CONTRIBUTING because you still didn't answer all of the points required for rendering issues.
Now I think I can guess the answer, but the next time I'll close issues opened without complete required informations: help here is not granted.

If you want mosaico to do CSS inlining you have to use:
```html
<style type="text/css" data-inline="true">
```

If you want to create a template from scratch you have to understand what CSS inlining is, and why SOME email clients do not support styles not inlined. If you expect a generic html to be shown "as is" on every email client then you are wrong. 

Mosaico sends what your template declare.

**Comment by kjedrol** [comment]
I apoligise.
I wrote it very quickly, because i need to have it asap.
Next time I will respect every rule, and Mosaico's developer.

Thanks so much!
