### ISSUE TITLE
Uploads not working

### ISSUE THREAD

**Issue by mherbold** [voidlabs/mosaico#29]
OK Now that I have my Mosaico installed, I am testing it out and my image uploads are not working.  I checked the developer tab in Chrome and it is whining about /uploads not existing at the root website address.  I have Mosaico installed at https://somedomain.com/mosaico and the uploads folder is at https://somedomain.com/mosaico/uploads.  But it is currently looking for uploads at https://somedomain.com/uploads instead.  Is there a way to fix this (some config file somewhere?)

**Comment by bago** [comment]
Yes, look at editor.html the Mosaico.init() methods takes backend urls as configuration.

**Comment by mherbold** [comment]
OK - getting closer.

My placeholder images are not showing up (broken images) - it is looking for them at the root /img instead of /mosaico/img.

Also - when I try to upload an image, it fails with a 404 not found on /mosaico/upload.  Any clues?

**Comment by mherbold** [comment]
Shoot accidentally clicked on close and comment instead of just comment...

**Comment by mherbold** [comment]
I should probably mention when I run grunt makeThumbs I get an error message at the top, but at the bottom it says completed with no errors.  The error message at the top is 

Loading "phantom-thumbnailer-editor.js" tasks...ERROR
>> Error: Cannot find module 'webpage'

Then it goes through a bunch of clipRect and finished lines and then ends with "Done, without errors."  Not sure if this is something to be concerned about.

**Comment by mherbold** [comment]
I updated editor.html and added /mosaico to the imgProcessorBackend and emailProcessorBackend lines.  Those error messages are gone now.  I still cannot upload images - the 404 error on /mosaico/upload is still there.  Hmm.

**Comment by mherbold** [comment]
Actually I just double checked - there's still a 404 error on /mosaico/img - so I guess that means the browser is not able to connect to the back end for some reason?

**Comment by mherbold** [comment]
Ahh reading up I missed the 2nd part of your last comment regarding changing the server side so that it listens to a different URL.  Sorry to waste your time - I will look into that now.

**Comment by bago** [comment]
You can ignore the "Error: Cannot find module 'webpage'".

You need makeThumbs only if you create new master templates or change a master template, so for basic integration you won't need it at all (and anyway I have that error too, but it works).

About moving the backed to different paths, you'll find your way: please note that the bundled backend is only for reference/demo/development and not ready for production use: you'll need authentication/user management based on your environment.

**Comment by mherbold** [comment]
I already have authentication in my environment so we're good to go on that point.

I just updated main.js by adding /mosaico to the app.get, app.use, and app.post function call parameters.  For example app.get('/mosaico/img', function(req, res)...

Then I killed the grunt process and restarted it.

My browser (Chrome) still gets a 404 error when trying /mosaico/img - I am not sure how this is supposed to be working anyway as http/https requests are going to Apache on my server and I am not certain how it is supposed to end up getting to the node.js back end.  Is there something that I am missing in this picture?

Perhaps it's due to my site being on HTTPS instead of HTTP?  I'm just guessing.

**Comment by bago** [comment]
If you want to use Apache you will have to write your own backend using your language of choice INSIDE apache.

The opensource distribution you download contains the client library and a development BACKEND written in JS and running in NODE, by default using port 9000.

Either you use nodejs+grunt(that will start a node.js webserver) or you write your own backend: mosaico backend example is not made to work in apache.

**Comment by mherbold** [comment]
OK - I think I got it.  So basically I use your Node back end as reference and make my own back end using, say, PHP.  I'll give that a shot.  Thanks for the clarification.

**Comment by bago** [comment]
Yeah! You may contribute to the project a PHP backend example when you're done ;-)
Of you can gen in touch with Mosaico team and get commercial help from them.

**Comment by tiagobernardes** [comment]
I have same issue...
in the demo, the following url works:
http://mosaico.io/srv/f-bnxv2jr/img?method=placeholder&params=166%2C130

in my case, this url is not work
http://localhost:9000/img?method=placeholder&params=166%2C130

It should be easy! :)
help please

**Comment by bago** [comment]
This does not seem the same issue.
Do download/test work in your setup? Do image upload works?
If only the image resize/placeholder doesn't work then you are missing imagemagick and the convert command line utils: there is a note about this in the main readme.

**Comment by kbalajijan1** [comment]
Hi,

Getting the following error when tried to upload an image.

"Errore inaspettato durante il caricamento(SyntaxError: Unexpected token <)"

Attached is the log of event handler of upload. Could you help me on this.

![upload_event](https://cloud.githubusercontent.com/assets/8971969/11169759/99136990-8be6-11e5-9030-bff7a4d29f71.png)

FYI: I am using Access Interpreting sample PHP backend.

Thanks.

**Comment by mistaguy** [comment]
Go the same issue today.  this issue is not related to mosaico but rather mosaico-php. Please check your config.php and make sure the uploads directory exists or change it

**Comment by kbalajijan1** [comment]
Hi,

I have given 777 permission to uploads directory. Now I am not getting ```fileuploadfail``` message but still image is not getting uploaded. 

Following else if condition is not satisfied. Any idea?

```else if ( !empty( $_FILES ) ) {
//image upload codes
}``` 

Also, may I know what has been used to upload the images without form submit(page load). 

Thanks

**Comment by bago** [comment]
Please report issues against the PHP backend if you use the PHP backend: we are not the mantainers of that backend and I don't know that code.
https://github.com/ainterpreting/mosaico-php-backend

**Comment by kbalajijan1** [comment]
Hi,

Thank you. I got clarified from PHP backend after raising a ticket in the above mentioned link.

Now I can able to upload the images and I can see the uploaded images in the ```uploads``` directory

But the issue is, After uploading I can still see the placeholder image(534x200) instead of the uploaded image in the block.

In http://mosaico.io/ it's working fine. I can see the img src method has been changed from placceholder to resize one and src query string has been added.

In my case I can still see the img src as ```img/?method=placeholder&params=534%2C200```.

Is this releated to front-end or back-end. Could you explain how the image get rendered after uploading?

Thanks

**Comment by mherbold** [comment]
I bet the back end is crashing trying to create the thumbnails.  Immediately after moving the uploaded file (the move_uploaded_file PHP call) it uses ImageMagick to resize the image into a thumbnail and puts it in the $thumbnails_dir.  I would check 2 things: Check the $thumbnails_dir in config.php to make sure it is correct, and check the actual thumbnails directory on the server to make sure PHP can write to it.  Both $thumbnails_dir and $static_dir needs to be writeable by PHP.

**Comment by kbalajijan1** [comment]
Hi 

I have created $thumbnails_dir and $static_dir and given write permission. Now I can see image files in the thumbnails_dir but images became fully black. Unable to see the actual image. What mistake I did?

Thanks.
