### ISSUE TITLE
Add extra buttons in toolbar

### ISSUE THREAD

**Issue by asbag** [voidlabs/mosaico#291]
Hi,

I initialize mosaico with "start" method instead of "init" method. However I was wondering if it's possible to insert or integrate an extra button in the toolbar close to "save" button to interact with external parts of website. Is it possible at this moment or does it need extra development?.

Thank you very much!!

**Comment by witzig** [comment]
https://gist.github.com/witzig/e22b65ff047b573e7d612ab0a9ca41c8

**Comment by asbag** [comment]
It works perfectly!!! Thank you so much.
