### ISSUE TITLE
images with no height

### ISSUE THREAD

**Issue by Snowalker** [voidlabs/mosaico#295]
Hi guys, I need to create blocks where the editable images will have various heights so I wanted to create blocks with only width on the images, no height, something like this:
`<img  data-ko-editable="image.src" src="imagepath" style="display:block; -ko-attr-alt: @image.alt;" border="0" alt="" width="500"/>`

However, the script breaks with errors like:
**IMG data-ko-editable MUST declare width and height attributes, or their placeholder counterparts data-ko-placeholder-width/data-ko-placeholder-height**

The emails are heavy on graphics and I don't want to end up creating a new block every time the new images have different width or height. 

Is it possible to import images with variable width and height to a block?

**Comment by bago** [comment]
Just follow what the error says and add a data-ko-placeholder-width/height for the default size you want the placeholder to be when you drop it in the template. Height will then adapt depending on the image being uploaded.

**Comment by Snowalker** [comment]
I added -ko-attr-height: @imageHeight and now I can add images with different height as long as the width is the same. However, now where the placeholder image is supposed to be, it shows up as a missing image. I can still click and upload but I want it to be able to see the placeholder. How can I do that?

**Comment by bago** [comment]
15 days, no updates. Closing.
