### ISSUE TITLE
Can I execute external javascript?

### ISSUE THREAD

**Issue by lixed17** [voidlabs/mosaico#297]
hi,i wonder how can i run javascript in templates.i found that mosaico has replace html/head/body tags during parsing progress.And i tried do the same thing on script tag,but it dosen't work. only the script tag cannot be replaced back successful.
`replace(/(<\/?)replaced(html|head|body|script)([^>]*>)`.
when I running on the server,the html file shows
`<replacedscript type="text/javascript">... </replacedscript>`
How can I convert `<replacedscript>` into `<script>`?
And I know I can't use javascript in email, I'm using it in another situation.
Thank you so much

**Comment by Hiswe** [comment]
I think that you should read this issue:

https://github.com/voidlabs/mosaico/issues/287

As far as I know, mosaico is focused on producing html for emails, so no JS

And if you are handling this html serverside, you could do any post-operations there.

**Comment by bago** [comment]
> How can I convert <replacedscript> into <script>?

If you want to replace it when exporting then patch viewModel.exportHTML method.
If you want to replace it before editing happens then you have to work in processBlock inside converter/parser.js
