### ISSUE TITLE
Releasing or sharing of customised mosaico code under GPL terms

### ISSUE THREAD

**Issue by ajaygirijr** [voidlabs/mosaico#298]
Hi,

First of all I would like to thank you for creating such a wonderful email editor tool and make it open source with lots of useful features.

I am supposed to integrate this email editor tool in one of my client's project. For some client specific requirements I have made some customizations to some of the core library files of mosaico. Now in order to satisfy sharing of these customized changes as per your defined GPL terms what I am supposed to do?

How can I share my updated or customized mosaico implementation with Mosaico team to fulfill your GPL terms requirement? Please guide.

**Comment by bago** [comment]
Hi, a good way to share sources is to make your own fork here on github!

**Comment by ajaygirijr** [comment]
Hi,

Thanks for you quick response.

For implementing my customization I have made some minor changes directly in couple of javascript files inside the '/dist/' folder. Also I have added couple of new JS files and folders directly into the '/dist/' folder required for my new functionality. I think this is not the correct way to do customization. Please comment.

Also please guide on how to share my code now considering the above case.

**Comment by bago** [comment]
Patching "dist" is not the best way to do that, but if you worked there, then you can simply release that.

Put your changes in the open in a github repository: if I will find some time I'll tell you if you had a better way to do that customization.

**Comment by ajaygirijr** [comment]
Hi,

My mosaico customizations were based on Mosaico version 0.15.0.  I have created new mosaico branch at 'https://github.com/ajaygirijr/mosaico/tree/mosaico_v_0_15'. Here I have committed all my customization along with the "/dist/" folder containing only the changed set of files and new folders. 

Have also submitted a pull request for the same i.e https://github.com/voidlabs/mosaico/pull/299
