### ISSUE TITLE
Send test by email

### ISSUE THREAD

**Issue by blsn** [voidlabs/mosaico#300]
I installed Mosaico on vagrant virtual machine, and it seems to work okay (http://192.168.10.10:9006).
When I try to perform the email 'TEST', I receive 'Stopping Express server' notification with the following error message:

![nodemailer](https://cloud.githubusercontent.com/assets/2880423/24329569/0b736568-1213-11e7-90cf-93e31de3a72c.jpg)

How to configure SMTP options in Mosaico so I can send the test to an email?

**Comment by Hiswe** [comment]
All params of the dev server are here:

https://github.com/voidlabs/mosaico/blob/master/server-config.js

Anyway, I think this backend is really designed to be a development server so default are for development SMPT server like [mailcatcher](https://github.com/sj26/mailcatcher)
