### ISSUE TITLE
How to delete or remove gallery images permanently?

### ISSUE THREAD

**Issue by ajaygirijr** [voidlabs/mosaico#301]
1. Is there any way I can trigger the removal of gallery images? The  images are stored at backend server.
2. Does Moxiemanager provides the ability to delete or remove the gallery images? If yes, what is the exact steps to do that as I was  not able to find?

**Comment by bago** [comment]
There is no option to delete images in Mosaico.
Moxiemanager is a commercial product and is not part of mosaico: you can refer to their website if you have questions about it.
AFAIK moxiemanager license is not GPL compatible, so you probably can't integrate Mosaico GPL version with Moxiemanager.
