### ISSUE TITLE
External background for social block

### ISSUE THREAD

**Issue by foyarash** [voidlabs/mosaico#302]
Hi,

So I wanted to add an external background to my social block. I've done it this way:

<img width="1248" alt="screenshot 2017-03-30 02 03 07" src="https://cloud.githubusercontent.com/assets/11079152/24503275/acc0181c-1551-11e7-8e74-c874ee2cd427.png">

The problem is that, when I want to change the external background for all blocks, the external background for the social block seems to be independant. 

For example suppose I have 3 blocks: 2 text blocks and 1 social block. If I change the external background of all blocks from one text block, it will change the external background of my 2 text blocks, but not my social block.

Same, if I change the external background from my social block, only the external background of my social block will change.

Is there something bad that I am doing?

Please tell me if you need more explanations.

Thanks by advance

**Comment by bago** [comment]
See the "theme:" declaration in the "@supports -ko-blockdefs {" section.
Each block declares which theme it belongs to.

Some versafix block is declared to be in the "Frame" theme (theme: frameTheme), most blocks are declared to be in the "Content" theme (theme: contentTheme).

When you use a style that stylename is created in that "theme".

So all of your "externalBackground" defined in "contentTheme" blocks will be the same color and will switch together. All of your "externalBackground" defined in "frameTheme" blocks will be the same color and will switch together.

Of course for a specific block the user can use the "customize this block only" tool and change only that block and not the whole "theme" the block belongs to.

**Comment by foyarash** [comment]
Thanks for this complete and clear answer, that's all I needed :)

I just now have the popup telling me that the template version is obsolete, but I'll find a way to deal with it.

Thanks again :)

**Comment by foyarash** [comment]
Ok I actually need help on this x)

So I have this warning : `WARN Property  theme.frameTheme!R.externalBackgroundColor found in model is not defined by template: removing it`

I changed what you told me: the socialBlock in the -ko-blockdefs has now theme: contentTheme

Any idea of what could be wrong? HTML code of my social block didn't change

**Comment by foyarash** [comment]
Ok this was a problem from me, i was refreshing the same template without saving it, which caused this problem

Closing the issue
