### ISSUE TITLE
Docker build exception 

### ISSUE THREAD

**Issue by vladox** [voidlabs/mosaico#304]
Hi 
When building the docker image I get the following error:

```Shell 
Step 7/12 : RUN cd /tmp && npm install
 ---> Running in 8f49536006a6  
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.  
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead  
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue  
npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130  
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm  
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue  
/bin/sh: line 1:     5 Killed                  npm install   
```

it there fix for this?
TIA
Vlad

**Comment by bago** [comment]
Formatting is not good, so I don't see the error.. I only find "WARN" and warns are not blocking.

**Comment by vladox** [comment]
Hi Bago  
Thanks for your answer!
You are right but the after the last line, when executing "docker build -t mosaico/mosaico .":  
`/bin/sh: line 1:     5 Killed                  npm install`  
the docker script doesn't seem to continue, stays stalled for ever.  
What can be the reason? Is the docker install still working?  
The docker version we are using is: Docker version 17.03.0-ce, build 60ccb22  
Thanks for any hint.  
Best regards  
Vlad

**Comment by vladox** [comment]
Hi Bago
OK I think I found the problem, npm was running out of resources in the server.
Thanks for having a look anyway!
Regards
Vlad
