### ISSUE TITLE
Mosaico adding the following code: ''br data-mce-bogus="1"

### ISSUE THREAD

**Issue by LucDebono** [voidlabs/mosaico#307]
Mosaico is adding the following code: ''br data-mce-bogus="1"
Such results in the addition of undesired breaks in the template. 
Is there a method to avoid such addition of code ?

Thanks in advance.

**Comment by bago** [comment]
Missing full informations about how to reproduce the issue, which version, how to run, which browser, what steps to do to see the problematic content.
https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md

**Comment by bago** [comment]
no update from the reporter.
