### ISSUE TITLE
'Try Mosaico' demo at mosaico.io gives incorrect browser version warning

### ISSUE THREAD

**Issue by mlncn** [voidlabs/mosaico#312]
Apologies if this isn't the best place to report this.

A popup lists minimum browser versions, including that i would need "Firefix >= 20"

It then blocked going to the demo.

Granted, i'm using Firefox, not Firefix, but i'm hoping version 54 of Firefox will work.  It would be better give a warning but let it try.

These are the two tests of the editor which wouldn't work.

https://mosaico.io/editor.html?0.15#templates/versafix-1/template-versafix-1.html
https://mosaico.io/editor.html?0.15#templates/versafluid/template-versafluid.html

Thanks!

**Comment by bago** [comment]
Your browser is failing compatibility tests. My Firefox works fine and thousands of users are using mosaico.io using firefox, so it must be something in your browser.

Please go here and report back the content of the text area:
http://mosaico.io/controlloalterazioni.html

**Comment by mlncn** [comment]
That's a relief!  Ah, here's the content of the text area:

```
PROBLEMA

---------------------
<!DOCTYPE html>
<html><head><title>A</title>
<script type="text/javascript" id="RTCEarlyScript"> window.oldSetTimeout=window.setTimeout;window.setTimeout=function(func,delay){return window.oldSetTimeout(function(){try{if(!document.documentElement.getAttribute('stopTimers')){if(typeof func=='string') {var nfunc = new Function(func); nfunc();} else func();}}catch(ex){}},delay);};  window.oldSetInterval=window.setInterval;window.setInterval=function(func,delay){return window.oldSetInterval(function(){try{if(!document.documentElement.getAttribute('stopTimers')){if(typeof func=='string') {var nfunc = new Function(func); nfunc();} else func();}}catch(ex){}},delay);}; </script></head>
<body><p style="color: red;" data-bind="style: { color: 'red' }" align="right">B</p><div data-bind="text: content">dummy content</div>

</body></html>
```

**Comment by bago** [comment]
You have the RightToClick extension installed and this extension manipulates HTML content. Doing so it would break the email template generation. That's why we give that alert.

Any extension that alters html for every iframe in the page is an incompatible extension: AFAIK apart RTC extension, the only other extensions doing that are spam stuff.
