### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by gordon-matt** [voidlabs/mosaico#313]
This is my first time working with Mosaico and I need to integrate it into a project, but I cannot seem to even get the demo working. I downloaded the latest release (0.16) and opened **index.html** in **FireFox**. Everything seems okay until clicking on a template, then I just get a red background with nothing else. The first template I attempted was the tutorial, which gave the following error message:

`XML Parsing Error: mismatched tag. Expected: </meta>.
Location: .../templates/tutorial/template-tutorial.html
Line Number 26, Column 3:`

I closed the tag and tried again, but then I got a new error:

`TypeError: a.match is not a function`

So I decided to leave that and try another template, namely **versafix-1** and of course that failed as well. The error message was as follows:

`XML Parsing Error: duplicate attribute
Location: .../templates/versafix-1/template-versafix-1.html
Line Number 419, Column 91:`

As the message says, there's a duplicate attribute. I removed one of them and tried again... one more error:

`XML Parsing Error: duplicate attribute
Location: .../templates/versafix-1/template-versafix-1.html
Line Number 589, Column 113`

I removed that duplicate as well and then guess what?    :-D

I get this one again:

`TypeError: a.match is not a function`

Any chance I could get some help with this?

**Comment by Hiswe** [comment]
Have you read the build instructions and launch the demo server?

**Comment by gordon-matt** [comment]
@Hiswe , perhaps I've overlooked a couple of things. Yes, I did build it with grunt, as instructed, but I didn't notice the instructions about a demo server until now. I will look into it further, thanks.

**Comment by gordon-matt** [comment]
OK I am still having issues, but not related to this. I see what you mean about a server and I decided to go with making my own backend for .Net Core, which is what I will be needing it for anyway. I will open a new issue for the problem I am having now.
