### ISSUE TITLE
I have install node and npm but still is not working on iis server 

### ISSUE THREAD

**Issue by vesnaveen** [voidlabs/mosaico#314]
I have installed node v6.10.2 version and npm with 4.5.0 version. and i also deployed application on my local server but when i am in editor.html page. its giving me error:
"NetworkError: 404 Not Found - http://localhost:90/dist/mosaico-material.min.css?v=0.10"
mosaico...?v=0.10
"NetworkError: 404 Not Found - http://localhost:90/dist/mosaico.min.js?v=0.16"
mosaico...?v=0.16
"NetworkError: 404 Not Found - http://localhost:90/dist/mosaico-material.min.css?v=0.10"
mosaico...?v=0.10
ReferenceError: Mosaico is not defined

Please suggest me what is the solution.

**Comment by Hiswe** [comment]
Have you build mosaico?

**Comment by bago** [comment]
Solutions:
https://github.com/voidlabs/mosaico/blob/master/README.md
https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico

If they don't work, then, before opening an issue:
https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md

**Comment by vesnaveen** [comment]
Hi Bago.
I build it and its running but still test and download link is not working. 
I am using iis server with **port :90** 
I am getting error ("NetworkError: 404 Not Found - http://localhost:90/dl/")

![untitled](https://cloud.githubusercontent.com/assets/12605452/25226277/0c41ae68-25e2-11e7-8059-e970f1ec4fad.png)

This is image of node command 
Sorry for opening again

**Comment by bago** [comment]
This is not about mosaico. You don't have privileges to bind port 90, maybe you are not root and you can't bind ports under 1024. There's a reason we use an higher port. If you want to change things you are free to do that , but these are not mosaico issues.

**Comment by bago** [comment]
Either you use the sample backend (started by "grunt" and using node.js express server) or you develop your own backend. Not both. One of them. You need a working backend in order to use mosaico in a browser.
https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico

**Comment by vesnaveen** [comment]
Its working now with change port.
Thanks a lot :)

**Comment by ATabish90** [comment]
Hi vesnaveen,

Extremly sorry for writing here. I know its a closed issue but I don't have the other way to ask this. Can you please let me know how did you manage the back-end IIS server with mosaico. Mine is an ASP.NET application in which I am trying to integrate this editor. 
I'll be grateful if you help me out on this. 

Thank,

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico
https://github.com/gordon-matt/Mosaico.NetCore

**Comment by bago** [comment]
.NET backend is not part of this project, so if you have issues with that library go there.
Writing a new backend is not an hard task, so you can write it like you write any other application you host in IIS: mosaico itself does not run in the backend but in the browser and does not care about the technology you have on the backend, as long as you provide its backend services.

**Comment by ATabish90** [comment]
Hi bago,

Thanks for the prompt response. Yes, I do know that mosaico is independent of the back-end technology. I was actually not aware of that Mosaico.NetCore project that we have shared. The thing is, I really liked the editor and want to integrate it with my application by any means.

Thanks for sharing the .netcore project. Will try to integrate using that.
