### ISSUE TITLE
Which HTML standard to use?

### ISSUE THREAD

**Issue by blsn** [voidlabs/mosaico#315]
Under Mosaico template's folder there are two different HTML standards:

template-tedc15.html
```
<!doctype html>
<html>
<head>
  <style type="text/css">

```
template-versafix-1.html
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="initial-scale=1.0" />
  <meta name="format-detection" content="telephone=no" />
  <title style="-ko-bind-text: @titleText">TITLE</title>
  <style type="text/css">

```
Which HTML standard to apply in my templates for better responsive emails?

**Comment by bago** [comment]
I'm sorry this is OffTopic.

You can use the doctype you prefer. If you want a good responsive template, use versafix-1 as-is.
The Doctype is not so important wrt responsiveness: it does matter if you want to use video in email (for some platform). It also make differences in some renderings, but not responsivity.
