### ISSUE TITLE
workaround imagemagic

### ISSUE THREAD

**Issue by DirkVR** [voidlabs/mosaico#316]
My webhostprovider doesn't allow installing imagemagic due to security issue.
Is the a way to work around this?
Can this extension work without imagemagic installed on server?

**Comment by bago** [comment]
Mosaico is a javascript library running in the browser.
It also requires some minor backend services and you can develop them with the technology you want (eg: using PHP and libgd):
https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico
