### ISSUE TITLE
.NET Core backend errors

### ISSUE THREAD

**Issue by gordon-matt** [voidlabs/mosaico#317]
I am making my own backend for Mosaico in .NET Core. Ultimately I need it for integration into a CRM system I am building for a customer of mine, but I decided to create an open source backend demo here on GitHub for others as well:
[Mosaico.NetCore](https://github.com/gordon-matt/Mosaico.NetCore)

I am having an issue when dragging and dropping a "block" onto the main content area. The error is a 404 for "**/localhost:25583/mosaico/img/**". It appears that something is going wrong when it tries to get the image location from the block.

I am using release 0.16 without any modifications. All I have done is placed the content from index.html and editor.html into .cshtml files and serving them that way... and made a couple of necessary path changes in those, since I have placed all the assets in **~/mosaico/**

Any help would be much appreciated.

**Comment by bago** [comment]
It seems an issue with the backend. editor.html tell mosaico where to find the img backend, by default:
```
  var ok = Mosaico.init({
    imgProcessorBackend: basePath+'/img/',
```

So either you make your backend to answer to that /img/ path, or you change the imgProcessorBackend to match your backend img processor url.

**Comment by gordon-matt** [comment]
@bago, Thanks for the response, but I already did change the **basePath** to `/mosaico`. The full script from my **Editor.cshtml** is as follows:

```
$(function () {
            if (!Mosaico.isCompatible()) {
                alert('Update your browser!');
                return;
            }
            // var basePath = window.location.href.substr(0, window.location.href.lastIndexOf('/')).substr(window.location.href.indexOf('/','https://'.length));
            //var basePath = window.location.href;
            //if (basePath.lastIndexOf('#') > 0) basePath = basePath.substr(0, basePath.lastIndexOf('#'));
            //if (basePath.lastIndexOf('?') > 0) basePath = basePath.substr(0, basePath.lastIndexOf('?'));
            //if (basePath.lastIndexOf('/') > 0) basePath = basePath.substr(0, basePath.lastIndexOf('/'));
            var basePath = '/mosaico';
            var plugins;
            // A basic plugin that expose the "viewModel" object as a global variable.
            // plugins = [function(vm) {window.viewModel = vm;}];
            var ok = Mosaico.init({
                imgProcessorBackend: basePath + '/img/',
                emailProcessorBackend: basePath + '/dl/',
                titleToken: "MOSAICO Responsive Email Designer",
                fileuploadConfig: {
                    url: basePath + '/upload/',
                    // messages??
                }
            }, plugins);
            if (!ok) {
                console.log("Missing initialization hash, redirecting to main entrypoint");
                document.location = ".";
            }
        });
```

**Comment by bago** [comment]
Try opening your backend img url with your browser, bypassing mosaico... if your backend is written correctly then you have to see the response json. If you get a 404 then your backend is not responding to the path you told to mosaico.

**Comment by gordon-matt** [comment]
There's no problem with my path. If I browse directly to a file in that location, then I get the image in the browser. For example, I just tried this:  localhost:25583/mosaico/img/byvoxmail.png  and there was no problem. It seems to me the problem has something to do with mosaico unable to get the url of the image from the block, because the text shows up fine, but the image does not display. Also, I have just noticed the complete url for the 404 is as follows:  localhost:25583/mosaico/img/?method=placeholder&params=534,200. I think from this I can see I probably need to implement some action method for accepting those parameters and returning an image based on them. So 2 things come to mind now:

1. Where can I find a list of methods I need to implement on the backend?

2. Shouldn't that URL also include the location of the image it wants to be resized (assuming those parameters are for resizing the image) ?

**Comment by bago** [comment]
The "img" backend service is an image manipulation service:
https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico
https://github.com/voidlabs/mosaico/tree/master/backend
https://github.com/voidlabs/mosaico/blob/master/backend/README.txt
https://github.com/tubaman/mosaico-server-tests

**Comment by gordon-matt** [comment]
@bago, thanks for the info; it was very helpful. I am in the middle of creating the backend services at the moment, but there's still an issue here in that the **src** parameter is not being sent. As per my url in my previous comment, you can see mosaico is sending the **method** and **params** query values, but not the **src**. Any idea why that may be happening?

**Comment by bago** [comment]
"placeholder method" doesn't need a source: mosaico just want a "fake/placeholder" image of a given size: you can create that image as you like. You can even change mosaico so tu use placehold.it instead of your server to get a placeholder image.

in a viewModel plugin just write:

```
var plugin = function(vm) {
 ko.bindingHandlers.wysiwygSrc.placeholderUrl = function(width, height, text) {
   return "'http://placehold.it/"+width+"x"+height+".png/cccccc/333333&text="+text;
 };
}
```

**Comment by gordon-matt** [comment]
@bago, Sorry for the late response... I have been busy with another project. Anyway, I'm not sure if we are on the same page here..

I am trying to implement the backend services: **/dl**, **/upload** and **/img**, as per your link, [https://github.com/voidlabs/mosaico/tree/master/backend](https://github.com/voidlabs/mosaico/tree/master/backend)

The problem I mentioned is with regards to the **/img** service.. I implemented my code as follows for now:

```
[Route("mosaico/img")]
public IActionResult Image(string src, string method, string @params)
{
    throw new NotImplementedException();
}
```

I can clearly see **method** and **params** coming through fine.. but **src** is null. My question is why is Mosaico trying to use this service but send null for **src**?

**Comment by bago** [comment]
I already answered you in the above comment.  When "method" is "placeholder" then it is up to the backend to decide what kind of image send as placeholder. Mosaico just tell you the size of the placeholder.

**Comment by gordon-matt** [comment]
OK, I see. That makes sense, thanks. I haven't had time to continue working on this yet, but anyway I will close this issue, as I think it's solved now.

**Comment by gordon-matt** [comment]
FYI to anyone else interested in a .NET Core backend.. I finally got around to looking at this again a couple of days ago and implemented it here: [Mosaico.NetCore](https://github.com/gordon-matt/Mosaico.NetCore)

**Comment by bago** [comment]
@gordon-matt I didn't test it but skimming through the code it seems something more than a "basic backend" (it seems it also uses DB for authentication and other stuff).
Can you add some documentation (a README) to the project, so that I can add it to Mosaico docs to help .NET people that want to use mosaico?

**Comment by gordon-matt** [comment]
@bago, You can ignore the stuff about DB authentication, etc which you saw.. Basically, I created a new project in Visual Studio which includes all of that stuff by default and then added Mosaico and modified a few of the default things (like Layout and Index pages, etc). Just look at the **HomeController** if you want to see the backend I've written. You can ignore most of the other files.

It still needs a bit of refining though and also I plan to implement some "save to database" functionality.
