### ISSUE TITLE
MJML support

### ISSUE THREAD

**Issue by HLFH** [voidlabs/mosaico#318]
Hi,

Can you support MJML?
https://github.com/mjmlio/mjml

I would love th be able to use it with Mosaico.

Thanks,

**Comment by bago** [comment]
Mosaico take an "HTML master template" and gives you an UI to create a send-ready "HTML template".
MJML take an "MJML document" and transpile it to a send-ready "HTML template".

How do you think MJML could be supported by Mosaico? What do you expect to do with MJML? and what do you expect mosaico to do with it?

**Comment by bago** [comment]
No answers to my questions.

**Comment by HLFH** [comment]
This issue is best fitted for [GrapesJS](https://github.com/artf/grapesjs-preset-newsletter/issues/3).

**Comment by witzig** [comment]
Shameless plug: https://github.com/witzig/mjml-mosaico

@bago, we already talked about this per email. Feedback welcome.

Thanks.
