### ISSUE TITLE
Changes in JS files not reflecting

### ISSUE THREAD

**Issue by taxima** [voidlabs/mosaico#32]
Hi,

I am new to node.js and knockout.js. I tried to add some code in viewmodel.js but the changes are not    
reflecting in my localhost.

I restarted my server but no luck. what should I do get JS changes.

Thanks.

**Comment by bago** [comment]
The main library is built from sources when you run "grunt" (src/js files are bundled in dist/*js files).

WHen you run grunt by default it build the library and start the backend server on port :9000.
It also starts a "watch" process to see changes in sources and rebuild the app automatically and this will automatically reload your browser when you make changes (depending on your computer/disk speed it may be 5-30 seconds after your change).

What do you mean with "restarted my server" ? (stopped grunt and started it again?).

Please provide output: grunt should log it detected your file changed and will start building the library.

**Comment by taxima** [comment]
Thank you. I failed to run grunt by default. Now it's working.
