### ISSUE TITLE
Can Img method run without grunt  and and node

### ISSUE THREAD

**Issue by vesnaveen** [voidlabs/mosaico#322]
Hello 
 I am migrating template functionality in asp.net website . I want to use imgProcessorBackend for load and display images . Right now there is no working with node.js and run grunt in my application. so i want to just know is it possible to access **img**  and **upload** url without run grunt and node ,If yes then where is the source of it or Can i make custom functionality for this

Please suggest me.
Thanks

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico
