### ISSUE TITLE
image upload not working

### ISSUE THREAD

**Issue by rohan5894** [voidlabs/mosaico#324]
i Have install your app in my server, I am getting issue in  image upload,its   not working can you please help me to resolve this issue . 

Please let me know  what i am doing wrong 
Please check site 
Site Url :http://itams.com:9006/

**Comment by Hiswe** [comment]
You should look if you have graphicmagic installed on your server.

And also check the logs of the development server application.

**Comment by rohan5894** [comment]
I am not getting any error in terminal 
I have installed imagemagick currently i need to install graphicmagic installed in my server ???

**Comment by bago** [comment]
"I have installed imagemagick currently"

currently => restart grunt 

check that "convert" command on the command line is found in the path and gives you the imagemagick help.

**Comment by rohan5894** [comment]
I have installed both the imagik and graphicmagic can you list out commands how to check if 
both are installed properly or not .

**Comment by rohan5894** [comment]
HI @bago  ,
I have checked the identify command also, imagik is installed .
The issue i am getting is when I am creating template and uploading 
image , the image gets uploaded on server and is present on uploads folder
.The image get disappears  from the template . can you look in to this issue 
http://itams.com:9006/

**Comment by Hiswe** [comment]
@rohan5894 I think you should test the dev backoffice on a local machine and put some [logs in it](https://github.com/voidlabs/mosaico/blob/master/backend/main.js)

I had no problems using it before and it's impossible to help you on your server like this.

**Comment by sascha-fath** [comment]
Same here. Trying manual install of depedencies.
Trying Grunt
Trying Docker (Supposedly out of the box)
Trying node.js backend.
Trying PhP backend
Trying Django backend.
Nothing work!

**Comment by karuppiah7890** [comment]
It's an issue with ImageMagick from what I tried recently. In your server, type this :

```
identify --version | grep Delegates
```

And see the delegates available. I had issues when none were available, and that happened when I installed from source or sometimes even when I used package manager (in centos). But it all worked fine when I installed with RPMs.

**Comment by bago** [comment]
@karuppiah7890  I think your issue may be unrelated to the @sascha-fath  issue given @sascha-fath  tried all of the backends. Given @sascha-fath tried all backends and "from his words" got the same result, and considering that all of the image manipulation IS in the backend, then I must assume this issue is invalid (@sascha-fath did some error reporting, or didn't really test correctly any of the backends). I also don't know what is the difference between "Grunt" and "node.js" backends. @sascha-fath failed to provide detailed logs for the default "grunt" solution explained by README, so I close this as invalid.

**Comment by karuppiah7890** [comment]
@bago Yes, he did try different back ends, and got same result, so it means, problem is probably in the ImageMagick. He could have used the same ImageMagick software for all, that's why I think it might be the issue.

**Comment by bago** [comment]
maybe.. too few inputs to say. maybe his host have other issues... like some special selinux policy or who know what else. There is no single information but "centos7x64" and I succesfully run the demo in my centos7x64 box, so it is clearly not enough.
