### ISSUE TITLE
Flickering in Firefox

### ISSUE THREAD

**Issue by DanSnelson** [voidlabs/mosaico#325]
I have fully implemented Mosaico into our system.

I have recently found an issue in firefox where certain elements flicker when selected. If you are to select a block you have placed in the template and then select a text element, the elements flicker when the surrounding box is fading in and out.

This also occurs on the demo version of mosaic on your site.

I think this potentially could be performance based depending on how fast your computer is running as i do find it happens when my computer is particularly slow.

I was just wondering whether you were aware of this and whether you'd implemented any fixes. 

It's not a big issue just thought it would be worth letting you guys know that it occurs even on the mosaico.io site.

**Comment by bago** [comment]
I just tested mosaico with Firefox and I can't see any flickering.

What version of mosaico and what OS and hardware are you on?

Can you record a video? 

@others: anyone else reproducing the flickering described by @DanSnelson? How explicit is the flickering? Do you reproduce it with just a couple of blocks or do you need a special configuration of blocks to see the flickering?

**Comment by DanSnelson** [comment]
Hi, I am using windows 7 running, intel i5 3.20 GHz processer, 8Gb RAM.

I am seeing this issue on the versoin of mosaico on the website

I attach a video of the flcikering occuring. Apologies for the quality of the video, i don't have any great video capturing software.
[mosaico-video.zip](https://github.com/voidlabs/mosaico/files/1044923/mosaico-video.zip)

I suspect it is just a performance based issue but thought it'd be good to bring up.

**Comment by bago** [comment]
I tested on a small atom with 4GB ram and much less capabilities than your setup and I can't see flickering.

I guess this is something bad with your display drivers: try updating your graphic drivers.

**Comment by bago** [comment]
I tentatively close this as I had no updates and no one else confirmed. Please reopen if anyone see this and have more details to share.
