### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Darkool** [voidlabs/mosaico#327]
Hi everyone, Im new using grunt and Im really confusing how it works, I even tried reading articles about it, I hope you can solve my questions:

I installed npm on my debian server with 
`apt-get install npm`

then I downloaded your mosaico's folder from github and I uploaded it to my server on my /home folder

after this I did cd /home and perform: 
  `npm install -g grunt-cli`

then I tried to go to my host:9006 and nothing happens

My question is how can I  build it? In case of use PHP backend I should move mosaico's folder to my website folder? /var/www/html/

thanks in advance.

**Comment by bago** [comment]
Just read again the instruction. You missed at least the "grunt" command, and maybe also something else... just make sure to read all of the README and also read CONTRIBUTING if you open more issues or want to add more informations to this issue.
