### ISSUE TITLE
Alter component size

### ISSUE THREAD

**Issue by balacodeboard** [voidlabs/mosaico#328]
Hi,
We are using Mosaico for creating the email template.  Is Mosaico support to edit component size?
I know it is supporting to alter image size in some of the blocks but not for all the blocks.  It is also useful of the text space as well.

**Comment by bago** [comment]
Yes it is supported. Just have a look at the versafix-1 template and how it declares things to make them resizable and replicate it.

Also have a look at this:
https://github.com/voidlabs/mosaico/wiki/Template-language
And at the tutorial template.
