### ISSUE TITLE
Better spport for an overall template

### ISSUE THREAD

**Issue by bwl21** [voidlabs/mosaico#33]
As far as I understand <div data-ko-container="main"> has a double role:
1. it defines the droppable blocks
2. it defines the dropzone

But if I want to make a Template with a given main structure, I need several drop zones.

Would it be possible to have one container which defines the blocks and another placeholder for dropzones.

Then I could have a template like this:

      <div data-ko-blockdefinitions="main"> </div>

      <div data-ko-container="main">
        <h1> Week 1 </h1>
        <div kdata-ko-dropzone></div>
        <h1> Week 2 </h1>
        <div kdata-ko-dropzone></div>
        <h1> Week 2 </h1>
        <div kdata-ko-dropzone></div>
        <h1> Week 3 </h1>
        <div kdata-ko-dropzone></div>
      </div>

Which would give me the overall structure of the letter with slots to drop in blocks.

The dropzones might be serialized, such that moving up and down would move blocks even between dropzones.

**Comment by bago** [comment]
This doesn't sound like a very common use case... What if an user only wants to put 3 weeks instead of 4?

IMHO you should simply have to promote your "<h1>Week #</h1>" to the status of "block", so that the user will also insert/move them between the others blocks in that container.

I think mosaico will eventually support multiple containers, but I found most modern, responsive templates to use a "single column" layout and I alwats kept this feature as a low priority one: also more questions are related to "multi-dropzones": are blocks tied to their dropzones or any block can be dropped to any dropzone? At this time I didn't collect yet enough use-cases for this requirement to think more about it.

**Comment by bwl21** [comment]
In our use case it is always 4 :-). This is in fact the issue, that,  when creating a new newsletter, I have to click insert the Week headers manually and update all titles again. The content of a Week could be composed by multiple draggable blocks. In other words, I have a fixed structure of headers and flexible content.

As of now, I have a fixed header, a dropzone and a fixed footer. Many newsletters have always the same structure of headlines with a variation of blocks in between.

I agree that there might be other priorities. I also agree that one could think further of letting the dropzones know the suitable blockdefinitions. This ticket was also the attempt to be a bit more flexible without the need to go to nestable blocks.

**Comment by bwl21** [comment]
I thought again about this, and would solve it differently:

In fact i see three levels:

* M2: the NewsletterClass. This is what we currently call "Template". It controls the newsletter creation process. In other words, Newsletters are instances of the NewsletterClass".
* M1: NewsletterSample. The user can compose a Sample newsletter by adding all the Blocks. This sample can be used as a kind of "Template" which acts as a starting point for a particular campaign.
* M1: Newsletter. This is what the author produces based on the NewsletterClass. But repeating campaigns might have always similar structure. So instead of creating a Newsletter from scratch he could start with the NewsletterSample.

**Comment by bago** [comment]
I close this one as it would probably be better solved by a "saved example contents" (to be used as starting content) and not with very specific language features.

**Comment by bwl21** [comment]
Exactly. I think the same which is the reason why I long for backwards compatibility. I se you allready settled the crossreference.
