### ISSUE TITLE
Integrate behind Login System

### ISSUE THREAD

**Issue by ar27111994** [voidlabs/mosaico#330]
Hi im running mosaico on my php web app with the help of php backend. Now I want to integrate the web app's built in login system with mosaico. A solution in my mind is to integrate login by placing an index.php in the mosaico's root with which no body could enter mosaico without permission but that would still be vulnerable because if someone enters mosaico after logging in and then logouts in another tab, then they wil stilll be able to perform all the operations of mosaico without logging in again. How can I overcome this loophole. Is there a js function in mosaico that fires on every event/action so that I can put an ajax call to check permissions in that function? Please help. Thanks.

**Comment by bago** [comment]
Mosaico is just a javascript library.

You can (well, you are supposed to) put index.html content and editor.html content inside a PHP file using authentication. Also, your backend implementation should implement this authentication for image browsing and upload.
