### ISSUE TITLE
Android Outlook app image issue

### ISSUE THREAD

**Issue by DanSnelson** [voidlabs/mosaico#332]
Hi guys,

I've been doing some testing in outlook mobile android app and noticed that in the versafix template, the triple and double article blocks look very wide and thin?

i've attached a screenshot so you can see what I mean.
![screenshot_2017-06-13-12-09-05](https://user-images.githubusercontent.com/18598022/27089811-64a77d76-5053-11e7-919e-7d086975f993.png)

I was just wondering whether you'd come across this before and if you have any ideas hwo to fix it.

It's to do with the height being restricted so the user can adjust the height of the image instead of it automatically resizing proportinally to the width of the email. In the screenshot it shows the image as full width but the height doesn't adjust.

any ideas?

**Comment by DanSnelson** [comment]
I can confirm this is the case. I linked a gmail account to the outlook app and it rendered fine. The only reason i bring this up is because it squashes the images when their height is defined instead of "data-ko-placeholder-height" so for two & three column layouts you cannot have the controlled height so that they all stay in line if that makes sense? I guess its just another one of those annoying things you have to deal with. (not nearly as annoying at the 1px line in outlook 2016!).

**Comment by bago** [comment]
There are plenty of bugs from the thousands (millions?) different email reading environments you may find. So we assign a priority based on penetration of that reading environment: we decided to ignore this one. If Microsoft cares about rendering they can easily update the "breaking proxy". 

And about the 1px issue, they recently upgraded the Outlook 2016 version, and now we see much more 1px lines appearing even in templates where the lines were not appearning before ;-)

**Comment by bago** [comment]
@DanSnelson Can you please update the outlook app from the android playstore and check the email rendering?

**Comment by bago** [comment]
No answers, let's tentatively close this. Open a new issue if the new outlook app is still affected.
