### ISSUE TITLE
A few issues with images?

### ISSUE THREAD

**Issue by Freelensia** [voidlabs/mosaico#333]
Hi,

Please bare with me as I am a beginner in coding and have no knowledge of node.js. I use Windows 10. I have successfully installed run the off-line version of the Mosaico yesterday (node.js, grunt, imagemagik, git are all properly installed as per the instructions). I can add images to the e-mail template and they display OK in the interface.

Issue 1: I cannot edit the images like I do on the web version. There is no icon appearing that takes me to that menu. Is it an issue with Imagemagik? I have installed legacy files as instructed.

Issue 2: In the HTML code, the image URLs are stored locally on my computer, like this:
`http://127.0.0.1:9006/img/?src=http%3A%2F%2F127.0.0.1%3A9006%2Fuploads%2FCerberus%2520Cover%2520Photo%2520white%2520words%2520(4).jpg&method=resize&params=534%2Cnull`

This will not work when we launch the e-mail live. So what is the correct way to treat images? Do I have to host the images myself then manually edit the code to put in the right URLs?

Issue 3: The in-built social icons cannot be saved.
http://127.0.0.1:9006/templates/versafix-1/img/social_def/facebook_bw_ok.png
Returns a non-sensible image.
Could you tell me where they are located on the C drive?

Thanks!

**Comment by bago** [comment]
This is the intended behaviour. "Grunt" is just a development/demo backend. If you publish it to a "public host" then the references will work.

Resized images are not stored on "C drive": the DEMO backend creates them on the fly.

**Comment by bago** [comment]
Issue 1 is because image editing is provided by "Moxiemanager": an external third party library that is deployed on the demo mosaico.io BUT is not available on the GPL library.
