### ISSUE TITLE
Replace TinyMCE by CKEditor wysiwyg.

### ISSUE THREAD

**Issue by MXStayeR** [voidlabs/mosaico#336]
Hello!
Thank you for the great opportunity to create templates using mosaico, it's realy awesome!
I noticed that TinyMCE wysiwyg has some problems such as empty space at bottom of window with right scroll appending after some wysiwyg activity. Also I can't find any decision of wrapping long words to a new line (as {word-wrap:break-word;} at CSS).
I found that CKEditor wysiwyg don't have such problems.
Do you have any experience to replace TinyMCE by CKEditor at /src/js/bindings/wysiwygs.js?
Thank you once more!

Best regards, Kir Chernenko.

**Comment by bago** [comment]
In my experience tinymce was better at dealing with browser issues so I never tried integrating ckeditor in mosaico.

BTW to use something else you just need to overwrite ko.bindingHandlers.wysiwyg (you can probably do that in a viewModel plugin so to be able to inject at the right time).

It should be an almost standard knockoutjs plugin for "inline editing": maybe you can find something already available on the web.

**Comment by MXStayeR** [comment]
Here is the plugin I wrote to replace TinyMCE by CKEditor. It's far from perfect, but it works ))) It solves problems with scroll and empty space at bottom of window, excludes non-hiding wysiwyg toolbars and allows to manage a huge number of wysiwyg options.  I hope it will help somebody. I have to notice that I use full version of CKEditor and I have to disable some of it's toolbar buttons. 

`var textEditorPlugin = {

    widget: function($, ko, kojqui) {

        // Remove scrollfix for standart TinyMCE
        ko.bindingHandlers.wysiwygScrollfix = {};

        // Rewrite WYSIWYG
        ko.bindingHandlers.wysiwyg = {

            currentIndex: 0,
            init: function(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {

                ko.bindingHandlers.focusable.init(element);

                var value = valueAccessor();
                var noLinkElement = false;
                var tagName = $(element).prop("tagName").toLowerCase();
                if(tagName === 'a' || tagName === 'span') {
                    noLinkElement = true;
                }

                if (!ko.isObservable(value)) throw "Wysiwyg binding called with non observable";
                if (element.nodeType === 8) throw "Wysiwyg binding called on virtual node, ignoring...." + element.innerHTML;

                var selectorId = element.getAttribute('id');
                if (!selectorId) {
                    selectorId = 'wysiwyg_' + (++ko.bindingHandlers['wysiwyg'].currentIndex);
                    element.setAttribute('id', selectorId);
                }

                // Allow CKEditor to edit inside buttons and titles
                CKEDITOR.dtd.$editable['a'] = true;
                CKEDITOR.dtd.$editable['span'] = true;

                // Remove some buttons from toolbar
                CKEDITOR.config.removeButtons = 'Image,SelectAll,Format,Font,FontSize,RemoveFormat';

                // Help CKEditor to enable toolbar buttons
                if(!$(element).attr("contentEditable")) {
                    $(element).attr("contentEditable", true);
                }

                $(element).on('click', function(){
                    // Create instance of CKEditor
                    var editor = CKEDITOR.instances[selectorId];
                    if (!editor) {
                        CKEDITOR.inline(selectorId);
                        editor = CKEDITOR.instances[selectorId];
                    }

                    // Disable Link and Unlink buttons for tags <a>, <span> because
                    // all links for blocks wih this tags are driven by Mosaico tools
                    if(noLinkElement) {
                        editor.config.removeButtons = 'Image,SelectAll,Link,Unlink,Format,Font,FontSize,RemoveFormat';
                    }

                    // Change item value with changes at CKEditor instance
                    editor.on('blur', function() {
                        value(editor.getData());
                    });
                });

                ko.computed(function() {
                    var content = ko.utils.unwrapObservable(valueAccessor());
                    try {
                        // we failed setting contents in other ways...
                        // $(element).html(content);
                        ko.utils.setHtml(element, content);
                    } catch (e) {
                        console.log("TODO exception setting content to editable element", e);
                    }
                }, null, {
                    disposeWhenNodeIsRemoved: element
                });

                // do not parse html content for KO bindings!!
                return {
                    controlsDescendantBindings: true
                };
            },
        };



        return {
            widget: 'text',
            parameters: { param: true },
            html: function(propAccessor, onfocusbinding, parameters) {
                return '<div>' +
                            '<input size="7" type="text" data-bind="value: ' + propAccessor + ', ' + onfocusbinding + '" />'+
                        '</div>';

            }
        };
    },
    viewModel: function(vm) {
        // of course you can also define helper functions in the viewModel (you can access them in the widget code as $root.function()
    }
};`

**Comment by bago** [comment]
This way you are "abusing" the widget plugin for "text" types. There's no need to do that.

Given ko is "global" it should work as a simple viewModel plugin, like:

```javascript
var textEditorPlugin = function(vm) {
    ko.bindingHandlers.wysiwyg = { ... };
}
```

Did you try this?

**Comment by bago** [comment]
No answers, so no need to keep this open.
