### ISSUE TITLE
Unable to download html

### ISSUE THREAD

**Issue by taxima** [voidlabs/mosaico#34]
Hi, Clicking on Download button leads to page not found and says "localhost/dl" not found on the server. I don't see /dl folder in github. How it works? Could you help me on this. 

Also you said you have done inline styling in php(backend) in your site but in github you have used Styliner. Is  Styliner itself is enough or I have to work something in backend for inline styling.

Thanks.

**Comment by bago** [comment]
DL is not a folder but a path configured in the backend service.

Are you running mosaico default node.js backend?
Styliner is the inliner and dows inlining in the node.js backend (ran through grunt)

**Comment by taxima** [comment]
I am sorry, I am unable to understand "configured in the backend service". Could you tell me whether Download will work if I use mosaico's github code only at my localhost or I have do any backend code at my end or I missed out any thing to do.  

Other features are working fine except this Download.

Thanks.

**Comment by bago** [comment]
read the main Readme and the wiki: https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico

Download, Test and Image upload/resize are the only features that need a backend: everything else works on the client side.

DO test and image upload work fine in your environment? If so, please check javascript console and your server logs to see if you have errors logged.
If they don't work then you are not running the backend part of Mosaico: either start "grunt" (with no parameters) to keep the local server running at port 9000 or write your own backend (or use the php backend linked in the previous links)

**Comment by taxima** [comment]
Thank you very much. Your comments helped much. 

One last question, Could you tell me about how the unique hash key(editor.html**#uv40uba**) gets generated.

Thanks.

**Comment by bago** [comment]
It is just a random thing for the demo:
https://github.com/voidlabs/mosaico/blob/master/index.html#L83

If you want to integrate it into your environment you'll probably use a completely different way to save/load templates: that hashkey  is only used in the demo code to use the "localstorage" plugin (to save in the browser).
