### ISSUE TITLE
Support for Field Tokens

### ISSUE THREAD

**Issue by gordon-matt** [voidlabs/mosaico#342]
It would be fantastic if there was some support for some "field tokens". I'm not sure if that's the best word to use, but what I mean is that usually when creating email templates, you want some fields that you can find and replace when sending batch emails. For example:

`Dear {FirstName} {LastName},`

Obviously the backend needs to find and replace these.. What I am asking for is the possibility to provide Mosaico with an array for these field tokens and then have a list of drag-and-drop fields for the user.. For example:

```
Mosaico.start({
	fieldTokens: ['FirstName', 'LastName', 'Title'],  // <-- something like this
	imgProcessorBackend: basePath + '/img/',
	emailProcessorBackend: basePath + '/dl/',
	titleToken: "MOSAICO Responsive Email Designer",
	//etc
```
At the moment, a user needs to:

1) Know all the different fields that are available

2) Manually type them and probably make a mistake sometimes.

So if you could support field tokens, to let users drag and drop them like the blocks, that would be awesome.

**Comment by Hiswe** [comment]
@gordon-matt In my opinion this should be a tinymce plugin, as it affects mainly text-blocks.

you can pass options to tinymce in the init function:

```js
Mosaico.init({
  tinymce: {
    // your options
  },
}, plugins);
```
In my opinion, it shouldn't be hard to write :)

**Comment by gordon-matt** [comment]
I've just come back to this issue now and I'm considering adding a new menu item at the top, next to the Save button - like "Tokens" or something.. which will open a modal dialog where a user can select a token from a list and that will get inserted to whatever text is currently selected. Only I have 2 questions about this:

1. How do I add a new menu item? I can see how to add new plugins, here:
https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins

However, it doesn't explain how the add a new menu item to call the plugin. So far I have only successfully used the plugins argument to replace the existing "Save" method with my own.. which is fine because an icon already exists on the menu for that.

2. Is there some way to get the current element/text that the user is editing, so that I can insert the token?

Maybe my idea is not going to work, I'm not sure yet. Any help / feedback would be most welcome.

@Hiswe, thanks for your suggestion as well, but I'm not really sure how I would go about doing that. Would you please elaborate? If it's not too much to ask, perhaps someone could put together some "skeleton code" where I can plug in the implementation.

**Comment by gordon-matt** [comment]
OK, I have my own solution working at the moment, which was to do the following:

After `Mosaico.start`, add this:

```
setTimeout(function () {
    var tokensButtonHtml = '<a title="Show Field Tokens" href="javascript:void(0)" onclick="showTokens();" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary" role="button"><span class="ui-button-icon-primary ui-icon fa fa-fw fa-i-cursor"></span><span class="ui-button-text">Tokens</span></a>';
    $(".rightButtons").append(tokensButtonHtml);
}, 3000);
```

That will add a new button to the menu bar. Also add these 2 functions:

```
function showTokens() {
    $("#tokens-modal").modal('show');
};

function insertToken(token) {
    $("#tokens-modal").modal('hide');
    tinymce.activeEditor.execCommand('mceInsertContent', false, '[[' + token + ']]');
};

```

And finally, have a bootstrap modal on the page as follows:

```
<div class="modal fade" id="tokens-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Field Tokens</h4>
            </div>
            <div class="modal-body">
                <ul class="list-group">
                    @foreach (var keyValue in fieldTokens)
                    {
                        <li class="list-group-item">
                            <a href="javascript:void(0);" onclick="insertToken('@keyValue.Key');">@keyValue.Value</a>
                        </li>
                    }
                </ul>
            </div>
            <div class="modal-footer">
                <div class="pull-right">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</div>
```

NOTE: I am using .NET, so the `<ul>` is being populated with a `foreach` loop that iterates over a collection I pass in from the `ViewBag`, but which could be on the model instead if you wish. If working in another language, you will of course have to replace that section with your own.

Also, don't forget to add bootstrap CSS and JS to the page.

My .NET Core backend with the above solution can be found here:
[Mosaico.NetCore](https://github.com/gordon-matt/Mosaico.NetCore)

Final note: this works, but is a bit of an ugly hack. It would be great if there was some proper way to do this, as requested in the original post. For this reason, please leave the issue open unless you decide not to support this.

**Comment by MrCsabaToth** [comment]
@Hiswe I tried different ways but it doesn't work. I'm using `Mosaico.start()` but I guess that should work just as `Mosaico.init()`. It looks like that I need to fiddle in the source code because the toolbars are hard coded: https://github.com/voidlabs/mosaico/blob/master/src/js/bindings/wysiwygs.js#L173
Is there a better way?

**Comment by Hiswe** [comment]
@MrCsabaToth for the TinyMCE I could only give you what I've done so far:

https://github.com/goodenough/mosaico-backend/blob/master/src/js/ext/custom-text-editor.js

As for the rest, Mosaico is really plugable. You should be able to write custom backbones templates and include them in the existing app. And of course extending the viewModel if needed :)

**Comment by MrCsabaToth** [comment]
@Hiswe Makes sense, you you declare `tinymceConfigFull`!

**Comment by bago** [comment]
IMO the tokens have a meaning only in the tinymce context, so I can't see why we would need an UI *outside* from the tinymce toolbar.

There are a lot of tinymce plugins and it is easy to create one and configure mosaico to use that tinymce configuration.

e.g: first from a very fast google search https://github.com/fisa/TinyMCE-Placeholder
