### ISSUE TITLE
Can't create new wysiwyg plugin

### ISSUE THREAD

**Issue by MXStayeR** [voidlabs/mosaico#351]
Hello again! And thanks for great job with mosaico!
I try to create a plugin, that will realize custom widget to edit content inside template blocks, but i am confused at start of work. What my hydrated code looks like:

`
// At template 
custom: {label: Custom; widget: custom;}

< div data-ko-editable="custom" > Content < /div >

// At plugin
var customWidgetPlugin = {
    widget: function($, ko, kojqui) {

        ko.bindingHandlers.wysiwygCustom = {
             init: function(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
                ko.bindingHandlers.focusable.init(element);
                console.log("Init Custom Widget");               
            }
        };
        ko.virtualElements.allowedBindings['wysiwygCustom'] = true;

        return {
            widget: 'custom',
            parameters: { param: true },
            html: function(propAccessor, onfocusbinding, parameters) {
                 var vidgetHtml = '';
                return vidgetHtml;
            }
        };
    },
    viewModel: function(vm) {}        
    
};
`
Widget is initialized with other working plugins. I thought, I will see log string at console, when block will be initialised or clicked, but my widget don't work - TinyMCE works. Can you help me to know where is my bad? Thanks a lot!

**Comment by bago** [comment]
data-ko-editable will always invoke the ko.bindingHandlers.wysiwyg binding. You wysiwygCustom binding will be ignored.

widgets are there for "properties" that are not used in "data-ko-editable" but are used in "-ko-" styles.
