### ISSUE TITLE
Errors from ImageMagick aren't logged and makes debugging the issue tough

### ISSUE THREAD

**Issue by karuppiah7890** [voidlabs/mosaico#352]
Recently I had an issue in image uploading and found that the express server is silently ignoring ImageMagick related errors without spitting them out

**Comment by karuppiah7890** [comment]
I am talking about this line https://github.com/voidlabs/mosaico/blob/master/backend/main.js#L100 and this line : https://github.com/voidlabs/mosaico/blob/master/backend/main.js#L108

**Comment by bago** [comment]
Thank you! We already have upstream improvements about this.. I'm just checking if they can be ported as-is and if they fix this issue.

**Comment by karuppiah7890** [comment]
Oh, okay :)
