### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by teerapongj** [voidlabs/mosaico#356]
Hi, I can't seem to get the images displayed properly. I can upload.

I use EC2 CentOS 6.9 NodeJS backend and ImageMagick version below.

node -v
v8.4.0
npm -v
5.3.0
ImageMagick-6.7.2

running "convert" and "identify" it work.

Please help suggest how to fix it.
Thanks.

Here's the screenshot.
![mosaico_image](https://user-images.githubusercontent.com/31066871/29515744-ce753cfa-8697-11e7-840d-2c01f205a427.jpg)

**Comment by bago** [comment]
Output for the "grunt" console?
Output from the browser debug window? (console / network tab)

**Comment by teerapongj** [comment]
Thank bago,

Here's the screenshot.

grunt
![mosaico1](https://user-images.githubusercontent.com/31066871/29553347-003230c4-8745-11e7-9449-a223665f5e7d.jpg)

console
![mosaico2](https://user-images.githubusercontent.com/31066871/29553359-0e1b77d6-8745-11e7-8a11-e35ea4847a87.jpg)

network
![mosaico3](https://user-images.githubusercontent.com/31066871/29553390-32f16dae-8745-11e7-9f0d-73c85fe04887.jpg)

**Comment by karuppiah7890** [comment]
@teerapongj @bago I think the bug exists in the ImageMagick processing

**Comment by karuppiah7890** [comment]
@teerapongj @bago I think the bug exists in the ImageMagick processing

**Comment by karuppiah7890** [comment]
#352 is the reason why nothing is logged

**Comment by teerapongj** [comment]
Thank karuppiah7890,

I got this error when upload image.
![mosaico5](https://user-images.githubusercontent.com/31066871/29557522-925c6d58-8753-11e7-91c7-0b8368554eaf.jpg)

**Comment by bago** [comment]
This may be related to a non standard imagemagick securitypolicy:
https://www.imagemagick.org/script/security-policy.php

The "demo backend" is really basic and doesn't aim to provide broad compatibility as it is just a demo. It uses "absolute url" for referencing images so imagemagick have to download resources via http and this may be limited by the security-policy of imagemagick.

**Comment by bago** [comment]
I did some change to the demo backend so to avoid using URL for image src and instead find the local path for them so that imagemagick doesn't have to retrieve the image via HTTP and maybe that specific security policy would not trigger (but I didn't see your security policy, so I'm just guessing).
