### ISSUE TITLE
Build/Run - Error running npm install

### ISSUE THREAD

**Issue by tiagobernardes** [voidlabs/mosaico#36]
Hello guys,

I have a problem with the installation.

You are running the following command: npm install

the following error appears:

C:\Temp\mosaico-master>npm install
npm WARN install Couldn't install optional dependency: Unsupported

 mosaico@0.11.0 postinstall C:\Temp\mosaico-master
 bower-npm-install --non-interactive

(node) util.error is deprecated. Use console.error instead.
Error: Cannot find module 'bower/node_modules/bower-logger'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Temp\mosaico-master\node_modules\bower-npm-install \lib\install.js:9:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

someone give me a help? thank you

**Comment by bago** [comment]
1) repeating the same npm install multiple times after the error gives you the same error or goes further on?
2) node version, npm version, os version?

**Comment by tiagobernardes** [comment]
Node - 5.0.0
Npm - 3.3.12
Os - win7 64

**Comment by bago** [comment]
I'll try updating my local install (I stull use node 0.12 and npm 2.7.4). But please confirm me that you already tried running "npm install" multiple times and eveytime you get the same issue.

**Comment by tiagobernardes** [comment]
yes, perform several times and already had other problems, but I was solving.
Now, I run the process from the beginning and always have only this error.

**Comment by bago** [comment]
Cannot updated node right now, but usually the "cannot find module" issues are node install issues. Sometimes reinstalling node, running "npm cache clean" and manually removing the node_modules folder fix the issue.

If you run some of this tests let me know, otherwise I'll try with node 5 in the next days.

**Comment by tiagobernardes** [comment]
Instead of 'npm install' did 'npm update'.
Did not seem to be errors. I think it is resolved.
Thank you

**Comment by tiagobernardes** [comment]
Instead of 'npm install' did 'npm update'.
Did not seem to be errors. I think it is resolved.
Thank you
