### ISSUE TITLE
Copy image address not work

### ISSUE THREAD

**Issue by teerapongj** [voidlabs/mosaico#360]
Hi,

When i download email.html file and put it to browser.
![mosaico1](https://user-images.githubusercontent.com/31066871/29707367-3b5395a0-89af-11e7-958d-32a36c8fe51b.jpg)

Then copy image address to new tab, it does not show image as picture below.
![mosaico2](https://user-images.githubusercontent.com/31066871/29707374-407110b2-89af-11e7-8a68-47934d7ff84c.jpg)

Please help suggest how to fix it.

Thanks.

**Comment by bago** [comment]
Cannot reproduce here, sorry. Not enough reported info to be able to give suggestions. https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md
