### ISSUE TITLE
Copy image address not work

### ISSUE THREAD

**Issue by teerapongj** [voidlabs/mosaico#361]
Hi,
I use EC2 CentOS 6.9 NodeJS backend and ImageMagick version below.

node -v
v8.4.0
npm -v
5.3.0
ImageMagick-7.0.6-9

upload image and display work normally.

But when i download email.html file and put it to browser new tab.
![mosaico1](https://user-images.githubusercontent.com/31066871/29811399-85332fca-8ccd-11e7-9b05-3daf95f53d8e.jpg)

Then copy image address and past to new tab address bar, it does not show image as picture below.
![mosaico2](https://user-images.githubusercontent.com/31066871/29811916-3a924b84-8ccf-11e7-93f2-bd21177febb4.jpg)

Please help suggest how to fix it.

Thanks.

**Comment by bago** [comment]
What version of mosaico? Can you update to the LAST one?

The url in the downloaded email SHOULD be the same that mosaico uses during the editing: so if you see the image while you edit the email then you should also be able to see the same url outside from the editor (it is the same url). You can even inspect the url of the "working" image inside the editor and compare it with the url in your downloaded email, they should match.

Check your browser network console to see if the url is the same and make sure you're using the latest master code as I committed changes to node backend.

**Comment by santiph** [comment]
This doesn't work on Gmail. I have latest Mosaico version and I'm testing in local.
Is this a known issue?

**Comment by bago** [comment]
@santiph you are offtopic.. this issue is not about Gmail but mosaico and copy-url.

**Comment by teerapongj** [comment]
Thank Bago,
After update to last version of mosaico, it work.
