### ISSUE TITLE
Create a block for write HTML code directly

### ISSUE THREAD

**Issue by theVannu** [voidlabs/mosaico#363]
Dear all,
we are trying Mosaico editor and we are able to configure a PHP backend, all run good and there aren't bug for now.
We have two questions:

- Is it possible to create a new drag&drop Block (maybe called "HTML Code) for coding the template using HTML code (like a WYSIWYG editor).

- Is it possible to see the HTML code of a dragged block directly into Mosaico and edit its HTML

someone have experience of this?

Thank you

**Comment by bago** [comment]
I don't understand... when you add the "text block" you have a block whose content is completely edited via TinyMCE (a WYSIWYG editor) and you also have an "edit sources" button.

**Comment by theVannu** [comment]
Sorry, my mistake! I have found the edit sources button into text block! Thank you for reply @bago
