### ISSUE TITLE
Task makeThumbs not found

### ISSUE THREAD

**Issue by jorenvh** [voidlabs/mosaico#365]
When I run grunt makeThumbs I get the following response

```
Warning: Task "makeThumbs" not found. Use --force to continue.

Aborted due to warnings.
```

Same goes for running the tutorial thumbs etc..

When checking the grunt file there is no reference to it, when adding it manually from previous versions it still doesn't work.

Some guidens would be great

KR
Joren

**Comment by bago** [comment]
makeThumbs required phantomjs in the build and this made the build a lot bigger and slower. We had complaint about this, so we decided to remove makeThumbs. You can create the thumbnail image manually.

We plan to publish another repository with the "tooling" we use to create the versafix-1 template and this will reinclude the makeThumbs utility. I'm sorry we have no ETA. 

If you need the makeThumbs now just checkout an older release.

**Comment by Edo78** [comment]
Can you update the templates/tutorial/mosaico-tutorial.md ?
It's pretty bothering when the tutorial tell you to do something that you can't do.

**Comment by bago** [comment]
sure, thank you for pointing this out!

**Comment by dejan9393** [comment]
There are still references to makeThumbs in the main readme.md file

**Comment by MarioClot** [comment]
I'm interested in makeThumbs utility too, hope you let us know when it's updated

**Comment by bago** [comment]
I don't have an ETA for this.

BTW here you can find the old scripts:
https://github.com/voidlabs/mosaico/tree/a907fd859862da24bac1d84acb54beb6a021ab75/tasks

**Comment by denics** [comment]
if you want to use the old makeThumbs you should also modify your Gruntfile.js and add

```
...

  grunt.initConfig({

makeThumbs: {
      main: {
        templates: './templates/*/*.html',
        template: './templates/%/*.html',
        outputFolder: 'edres',
        renderWidth: 680,
        outputWidth: 340
      }
},

... 
```

and install phantomjs locally:

```
npm install phantomjs
```

**Comment by bago** [comment]
An update on this:

The [versafix-template](https://github.com/voidlabs/versafix-template) project now includes also the code to generate the thumbnails.

https://github.com/voidlabs/versafix-template/blob/master/src/makeThumbs.js
https://github.com/voidlabs/versafix-template/blob/master/src/phantom-thumbnailer-editor.js

The code has not been extrated to its own library (unlike we did for HTMML), yet, but it should be easy to use it or adapt the versafix-template project to work on your own template (if you don't need the HTMML translation you can comment it out in the index.js).

So, I close this one as I consider thumbnail creation out of scope for the mosaico library (you can even create them by hand, mosaico doesn't care how they are generated).

**Comment by MarioClot** [comment]
It works like a charm, thank you
