### ISSUE TITLE
Facing issues uploading images from Xampp(Apache)

### ISSUE THREAD

**Issue by vencoder** [voidlabs/mosaico#366]
Greetings,

Here is what I have done so far - 
I used npm to install Mosaico on Windows 7. It went smoothly after installing ImageMagic. I can upload images, export templates as HTML too. So far so good. 

Next step was to use the PHP Backend. I am using https://github.com/markalston/mosaico-php-backend which has been recommended in the Mosaico project page. Here is where the trouble starts. 
The page says - 
> First, install and set up Mosaico.  **Done**
Next - 
> Then install these files on **top** of the Mosaico installation. 

Now, the mosaico installation exists under C:\Users\Admin\AppData\Roaming\npm\Mosaico. 
I cd into the directory, type **grunt** at the command line and I can access http://127.0.0.1:9006 and edit the default template that ships with Mosaico. 
What I probably haven't understood is, where should I copy the contents of backend-php? 
I am sorry I haven't completely understood this part > **Then install these files on top of the Mosaico installation.** 
Should I copy C:\Users\Admin\AppData\Roaming\npm\Mosaico to Xampp\htdocs first. Then copy backend-php under it or? 
I have copied the necessary DLL's for imagick too. 

Let me list out what I attempted with the php-backend: - 
1. Copy C:\Users\Admin\AppData\Roaming\npm\Mosaico to Xampp\htdocs.
2. Copy backend-php under xampp\htdocs\mosaico
3. I can access the template builder but I cannot upload the images.
4. The necessary folders were copied with the .htaccess file that shipped with the php-backend archive.
5. What should I do with the following - 
       * Url for image serving in final download */
      //SERVE_URL => "https://YOUR_EMAIL_IMAGE_SERVER_URL/",
Should this point to http://127.0.0.1:9006/upload or http://localhost/mosaico/upload? 
Any files that require editing ? 
Any/all help would be greatly appreciated. 

Firefox console is displaying this error message when I click on "Show Image Gallery" link - 

"<br />
<b>Notice</b>:  Use of undefined constant SERVE_URL - assumed 'SERVE_URL' in <b>D:\xampp\htdocs\mosaico\backend-php\config.php</b> on line <b>9</b><br />"

Kind regards and thanks in advance.

**Comment by theVannu** [comment]
Hello, have you configured the properties of Mosaico into the editor.html file?
https://github.com/voidlabs/mosaico/blob/4411651102e5476539fc407053bc364302f247ef/editor.html#L40

As you can see there are 3 parameters to configure with the same URL that you set on your php backend.

I also suggest you to read this .md file https://github.com/voidlabs/mosaico/blob/master/backend/README.txt it help me a lot!

**Comment by vencoder** [comment]
Hi theVannu,

Thanks for the quick reply. 

When I click on Gallery, I see a GET request for http://localhost/moss/upload/ which gives a  "The requested URL was not found on this server".

I am relatively new to this and Javascript has never been my strength. 

Question - Should I hardcode the URL into editor.html like this 
var ok = Mosaico.init({
    imgProcessorBackend: 'http://localhost/moss/img/',
    emailProcessorBackend: 'http://localhost/moss/dl/',
    titleToken: "MOSAICO Responsive Email Designer",
    fileuploadConfig: {
      url: 'http://localhost/moss/upload/',
      // messages??
    }
  }, plugins);
or leave it the way it has shipped? 

I seriously think I am messing up config.php
//SERVE_URL => "https://YOUR_EMAIL_IMAGE_SERVER_URL/",
	SERVE_URL => "http://localhost/",
Which folder should it point to within the webapp? 
Thanks a ton.

**Comment by vencoder** [comment]
Hi theVannu,

Can you share a sample config.php?

**Comment by theVannu** [comment]
@vencoder  exactly! you have to hardcode the URL into editor.html.
You have to configure the config.php too with the correct URLs but I don't use this PHP-backend so I am not able to share a config.php file. (My mosaico project is integrated into a Laravel project so I use a Model-View-Controller approach with my own backend totally different from the PHP-backend provide with Mosaico)

**Comment by vencoder** [comment]
@theVannu, awesome.
Well, appears there is no easy way out of this. 
When I click on the gallery tab, I can see Referer - editor.html making a request - GET http://localhost/moss/upload/
The response however not very encouraging -  The requested URL was not found on this server.
A folder exists by the name /upload under moss. I deleted .htaccess and got rid of the Object not found error but am faced with a new one. 
![2](https://user-images.githubusercontent.com/24566642/30286204-687a5e3c-973e-11e7-9c07-fb55efb8924f.jpg)

I am relatively new to PHP. Is there a plugin that helps integrate Mosaico with Laravel?

**Comment by bago** [comment]
From the CONTRIBUTING file:
https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md#issues-runningediting

> if you are having issues running with Apache then specify you installed the php backend from access interpreting and WHY you think you are having problem with mosaico.js and not with that specific backend (did you try with bundled node.js backend?)

I think this belongs to the php backend github project unless you identify an issue in the javascript library itself.

Here you find our docs about serving mosaico:
https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico

And here are the backend services to be implemented by a backend if you want to write your own with laravel:
https://github.com/voidlabs/mosaico/blob/master/backend/README.txt

**Comment by vencoder** [comment]
Apologies for raising an unrelated issue. 
I will raise it under markalston/mosaico-php-backend.
