### ISSUE TITLE
Regular TinyMCE editor textarea (not floating)

### ISSUE THREAD

**Issue by dennisnovac** [voidlabs/mosaico#368]
Is there any way (without re-writing half of the source code) to have a full omnipresent TinyMCE editor, instead of floating panels with only a few options when selecting a chunk text?

Thanks.

**Comment by bago** [comment]
Never thought at it.
Have a look at https://www.tinymce.com/docs/configure/editor-appearance/#fixed_toolbar_container

Let us know.
