### ISSUE TITLE
Request for simple HelloWorld-example

### ISSUE THREAD

**Issue by modist** [voidlabs/mosaico#37]
Hi,

Currently trying to create a template - but having issues getting the template to work.

Would it be possible to have a - really simple - example - demonstrating the basic features - such as
- removing content (on/off)
- editing textblock
- editing image

the template should only contain the necessary markup - stripped for all CSSunrelated to Mosaico.

Does this make sense ?

Kind regards

**Comment by bago** [comment]
HI modlist, have a  look to #38  https://github.com/voidlabs/mosaico/pull/38
Bernhard is working on something you may find useful!
