### ISSUE TITLE
Add setting to load mosaico in which container you would

### ISSUE THREAD

**Issue by kevle88e** [voidlabs/mosaico#370]
[appendTo.txt](https://github.com/voidlabs/mosaico/files/1323982/appendTo.txt)
Hi,

I've just added an option to mosaico to allow you to append mosaico in the html element you would : 

`  var at = options.appendTo ? options.appendTo : global.document.body;
  
  $("").appendTo(at); `

when using init or start method it allow you to specify option "appendTo"

**Comment by bago** [comment]
Can you explain why you need this option? Are you running mosaico inside an element that is not "full window"? Doesn't this break mosaico media queries and other mosaico positioning code?

**Comment by bago** [comment]
No answers, closing it.
