### ISSUE TITLE
Need help regarding some questions

### ISSUE THREAD

**Issue by vencoder** [voidlabs/mosaico#371]
Hi,

This is not really an issue w.r.t Mosaico but I couldn't find a forum for Mosaico where I could post questions regarding its usage.

I managed to build Mosaico & run it with Node after installing all its related dependencies. Everything worked as expected. Could save templates, upload images, do practically everything that the Mosaico demo does. 

My question is - Does Mosaico require Node.js to work even with PHP? 

I stopped Node.js server, copied the entire build files to a public folder under htdocs in Xampp on Windows. 

Next, I followed the steps as listed in mosaico-php-backend but failed to get images working with it. I have taken care of the dependencies like ImageMagick.

I have read the "Serving Mosaico" section and re-read the part that says - "Mosaico is a frontend/javascript application". This probably means my backend needs troubleshooting.

I hope I am right in diagnosing the problem because I don't know if Mosaico should be running separately with Node.js or it can function independently under a PHP or Java web container without Node. 

Another question, will images used in the email template be served by Node.js or my PHP backend, ie, /uploads folder which should reside in my PHP webapp? 

Added later - I am using https://github.com/markalston/mosaico-php-backend for my PHP backend. I copy/pasted the entire contents of the archive to my htdocs/mosaico folder and made the necessary edits. 

Best Regards!

**Comment by Hiswe** [comment]
You're right for everything:

- Mosaico is a frontend lib so NodeJS is only required for the build step.
- After building, the frontend lib is really nothing more than a JS file that you have to drop on any webpage like you would do with ol'jQuery
- The Node demo server is, well, a demo server written in NodeJS. So if you have another backend running on another language you won't need NodeJS anymore.
- The server is handling anything relative to :
  - the images (uploading & serving)
  - sending mails

So it's seems to me that's more an issue with the backend.   
If you have trouble with images, you should check the response's content, and the log of your server.
And if you need more help you should write an issue on the backend's github :)

I hope it helps ^^

**Comment by vencoder** [comment]
Hello Hiswe,

First things first, a big thank you for the reply.

I reckon the issue is with the backend. Let me fix it and revert.

Thank you once again and yes, it certainly helped because when I saw the source of the HTML email file served by Node, I could see that the images were being served by node and the url was src="http://localhost:9006/img/?src=http%3A%2F%2Flocalhost%3A9006%2Fuploads%2abc.jpg which had me thinking on a different tangent altogether.

**Comment by Hiswe** [comment]
you're welcome :)
