### ISSUE TITLE
Ability to toggle display of a tag, keeping its content (data-ko-wrap?)

### ISSUE THREAD

**Issue by JKingsnorth** [voidlabs/mosaico#377]
According to the documentation (https://github.com/voidlabs/mosaico/wiki/Template-language) there is an attribute: data-ko-wrap

"data-ko-wrap="condition" => if condition is false this element is removed (but the content is kept)"

So can we use this to achieve something like being able to toggle whether an image has a link:

```
<a data-ko-wrap="imagelinkVisible" href="imagelinkLink">
  <img src="img.jpg">
</a>
```

I haven't been able to get this working. When we try this the boolean widget we set up for 'imagelinkVisible' never appears, and the <a> tag always appears.

If we change this simply to data-ko-wrap="false" then the <a> tag still always appears.

**Comment by bago** [comment]
Hi, there is a "shortcut" for this and it is the "data-ko-link" attribute:

`<a href="" data-ko-link="image.url"><img src="img.jpg"></a>`

THis is equivalent to:

`<a href="" data-ko-wrap="image.url" style="-ko-attr-href: @image.url;"><img src="img.jpg"></a>`

And empty url will work as "no url" and "no wrapper needed".

You imagelinkVisible solution should work too.. need source code to check why it does not work, or have a look at javascript console for interesting mosaico logs.

**Comment by JKingsnorth** [comment]
@bago thanks, I'll check out the shortcut you mentioned, that would be great.

Here's the full template code I'm using (against the master version of mosacio). If you load this up you can see that the 'toggle' doesn't appear. But if you change it from data-ko-wrap to data-ko-display it works fine.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>

    <style type="text/css">
        @supports
            -ko-blockdefs {

            visible {
                label: Visible;
                widget: boolean;
            }
            
            testVisible {
                label: Include link?;
                extend: visible;
            }

            text {
                widget: text
            }
            
        }
    </style>
</head>

<body >
<div id="preface">
    <h1>This is the Mosaico Tutorial</h1>
</div>

<div data-ko-container="main" data-ko-wrap="false">

    <div data-ko-block="HeaderAndText">
        <h1 data-ko-editable="headerText">this is header</h1>

        <a data-ko-wrap="testVisible" href="#" style="background: red">
            This should/not link.
        </a>
      
    </div>

</div>

<div id="trailer">
    <h1>This is the end of Mosaico Tutorial</h1>
</div>

</body>
</html>
```

**Comment by bago** [comment]
I tested the template and this is working "as expected".

In the "editor" you will keep seeing the link, but in the preview and the generated html the link won't be there anymore.

data-ko-wrap only applies to final preview/output and not to the editing. I guess this could be better documented, but this behaviour is needed for the editing and data-ko-wrap is mainly used for tags that are needed in the editing area but not wanted in the final output.

**Comment by JKingsnorth** [comment]
I've edited the wiki to reflect this (https://github.com/voidlabs/mosaico/wiki/Template-language), thanks for the help.
