### ISSUE TITLE
Mosaico won't work in Firefox Quantum

### ISSUE THREAD

**Issue by SimonIMG** [voidlabs/mosaico#383]
Just tried launching a fresh, local install (NPM, Grunt) of Mosaico in Firefox Quantum 57.0 (64-bit).

I go to http://127.0.0.1:9006 and I get the welcome screen. I select a master template and I'm taken to a blank, crimson screen and I get an alert box "Update your browser!".

The console has no errors; it's blank.

Also tried private browser window.

**Comment by bago** [comment]
Well, we currently have hundreds of users using Mosaico with Firefox Quantum, so it must be something specific to your setup.

Please open this page with your browser and paste here the text you see in the text area:
http://mosaico.io/controlloalterazioni.html

**Comment by bago** [comment]
No answers, waste of time.

**Comment by casso** [comment]
i have the same problem in firefox quantum 61.0
demo shows this error:
`<p>Your browser is not supported.</p>
    <p>Please open this page with a modern browser or update your browser.</p>
    <p>Supported browsers: </p><ul>
      <li>Internet Explorer &gt;= 10</li>
      <li>Google Chrome &gt;= 30</li>
      <li>Apple Safari &gt;= 5</li>
      <li>Mozilla Firefix &gt;= 20</li>
    </ul><p></p>`

**Comment by bago** [comment]
Come on, did you read my previous answer?? If so, answer to the questions.

**Comment by elboletaire** [comment]
Waste of time? Maybe what's a waste of time is answering you, but hey, I'm not like you:

- Yes, it happens with the demo at mosaico.io
- No, only happens with firefox afaik
- I'm on Ubuntu Linux
- Well, the demo page doesn't work. I guess it's the latest version?

And always shows this message

![imatge](https://user-images.githubusercontent.com/153305/46798812-4ea1b400-cd53-11e8-980c-b86f83da7b9f.png)

Despite I'm using Firefox 62.0 x64:

![imatge](https://user-images.githubusercontent.com/153305/46798838-5e20fd00-cd53-11e8-9934-6b726164c408.png)

**Comment by elboletaire** [comment]
Ok, found it out. Any of you have the metamask plugin enabled @casso @SimonIMG ???

Disable it and mosaico starts working.

**Comment by bago** [comment]
The alternation control page clearly shows that you have a plugin (Metamask) that is manipulating any page you load, and it would break Mosaico behaviour, so we declare your browser incompatible.
