### ISSUE TITLE
How To Center Button

### ISSUE THREAD

**Issue by Bad959FL** [voidlabs/mosaico#386]
I'm using the mosaico newsletter software and I'm trying to center the buttons which are currently aligned left. Attached is a screenshot. Thanks!

![how-center-button](https://user-images.githubusercontent.com/34247252/33566908-7a5c6fd0-d8ef-11e7-8339-cbd05d7d69f1.jpg)

**Comment by bago** [comment]
The master template "versafix-1" does not let you center that button, so you can't unless you change the master template: you need html knowledge to alter the master template.

A future release of versafix-1 will support an alignment option for the block.

**Comment by bago** [comment]
versafix 1.1.16 supports this. It is included since 0.17.0 release
