### ISSUE TITLE
How can I use html2canvas in my mosaico project?

### ISSUE THREAD

**Issue by sibbu2005** [voidlabs/mosaico#388]
Hi all,
Thanks for this nice tool,
I using this in my project , but I am not an expert in knockout.js. i was using canvas2html to campture the screen-shot of exported HTML content.
I have no Idea how to do this. Kindly suggest. What I did?

1. I  cloned this https://github.com/niklasvh/html2canvas to bower_components .
2. Created a **canvas2html.js**
`"use strict";

var ko = require("knockout");
var $ = require("jquery");
var hc = require("html2canvas");
var console = require("console");

var extendValueAccessor = function(valueAccessor, obj) {
  return function() {
    ko.utils.extend(obj, valueAccessor());
    return obj;
  };
};

var options = {
  show: {
    delay: 500
  },
  track: true,
  items: '[title][title!=""][title!=" "]'
};
//html2canvas
ko.bindingHandlers.html2canvas = {
  init: function(element, valueAccessor, allBindingsAccessor, data, context) {
    if (typeof $.fn.html2canvas !== 'undefined' && typeof ko.bindingHandlers.html2canvas !== 'undefined') {
      // position: { my: "left+15 top+15", at: "center+30 center+30" }
      // NOTE title with "" and " " is needed to avoid default html2canvass in native file upload controls
      return ko.bindingHandlers.html2canvas.init(element, extendValueAccessor(valueAccessor, options), allBindingsAccessor, data, context);
    }
  },
  update: function(element, valueAccessor, allBindingsAccessor, data, context) {
    if (typeof $.fn.html2canvas !== 'undefined' && typeof ko.bindingHandlers.html2canvas !== 'undefined') {
      return ko.bindingHandlers.html2canvas.update(element, extendValueAccessor(valueAccessor, options), allBindingsAccessor, data, context);
    }
  },
};`

3- and in bindings...
`require("./bindings/html2canvas.js");`

I dont know how to use.
I just follow the way as some jquery UI are added.

@bago

**Comment by bago** [comment]
I'm sorry i don't know html2canvas. I don't think you need something special for mosaico, but I can't help with this and I don't think html2canvas is good enough to really create worthful screenshot. You need a server side phantomjs (or similar) if you want to create screenshots.

**Comment by sibbu2005** [comment]
thanks @bago
