### ISSUE TITLE
imagemagick failed to run

### ISSUE THREAD

**Issue by hatchwald** [voidlabs/mosaico#389]
![image](https://user-images.githubusercontent.com/32924664/33824768-090451b0-de92-11e7-8470-900cf70dbdc7.png)
at install grunt , at this moment I am waiting for long time , but this installation still not done .
I am sorry for my bad english

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/blob/master/README.md
https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md
