### ISSUE TITLE
Add tracker prarams to all URL

### ISSUE THREAD

**Issue by yrancillac** [voidlabs/mosaico#39]
Hi,
Is it possible to add tracker params to all href by the content tab ?
I tried to concat 2 varibles into -ko-attr-href but I got errors...

Thx

**Comment by bago** [comment]
What are you trying to accomplish?

And how did you do "concatenation"?
What "errors" did you get?

**Comment by yrancillac** [comment]
My goal is to construct an URL like : http://url?traking=param
I was trying to do something like that : -ko-attr-href: @buttonLink.url @tracking

And the error is : 
``` 
Model ensure path failed undefined name -ko-attr-href value @buttonLink.url @tracking default  element <a replacedstyle="text-decoration: none; color: #3f3f3f; font-weight: normal;
                                  -ko-color: @buttonStyle.color; -ko-attr-href: @buttonLink.url @tracking" href="" data-ko-editable="buttonLink.text"> mosaico.min.js:1262:2398

Exception while parsing the template Cannot find default value for @buttonLink.url @tracking in  <table width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#bfbfbf" class="vb-outer" data-bind="virtualAttrStyle: 'background-color: '+(externalBackgroundColor._defaultComputed())+';'+'', virtualAttr: { bgcolor: externalBackgroundColor._defaultComputed() }, attr: { id: id }, uniqueId: $data" style="background-color: #bfbfbf; ; ">
```

**Comment by bago** [comment]
Mosaico tried to parse your "href" attribute in order to put default values in your 2 variables.
You href does not include the "space" that you have between your variables, so it won't work.

try with "@[buttonLink.url]@[tracking]", but you will have to define the default values for these variables in the "@support -ko-blockdefs" declaration.

I still don't get why you need that. You user is allowed to put any url in the url field and you will simply append to his urls your own parameters? How can you do tracking if you can't control the host?

I'm willing to enhance mosaico to support an use case, but I have to understand the use case, first.

**Comment by rimkat** [comment]
Hi, 

Please help me :( 

I am in the same case, I would like to add several tracker params to all href in a template.
When trying the proposed method I have this error
`parser.js:3 TODO ERROR Property lookup exception Found an unexpected path termination url for model HeaderAndText for titleLink.url HeaderAndText titleLink.url HeaderAndText titleLink.url 
Model ensure path failed undefined name -ko-attr-href value @[titleLink.url]@[trackingOrigin] default https://www.google.com/ element 
Exception while parsing the template Exception parsing expression @[titleLink.url]@[trackingOrigin] Found an unexpected path termination url for model HeaderAndText for titleLink.url 
stylesheet.js:2 Uncaught Exception parsing expression @[titleLink.url]@[trackingOrigin] Found an unexpected path termination url for model HeaderAndText for titleLink.url`

My goal is to build a link like
https://url/#{(trackingOrigin)}|trackingSource&g.lu=
I try to concatenate by doing `"-ko-attr-href:@[titleLink.url]@[_root_.trackingOrigin]@[_root_.trackingSource]"` 
I have defined the elements in "@support -ko-blockdefs" like that :
`template { label: Template; properties: trackingOrigin=XXXXXX trackingSource=000000; }
titleLink {label: Title link;extend: link;}
trackingOrigin {label: Tracking Origin; extend:text;}
trackingSource {label: Tracking Source; extend:text;}` 

Can you tell me if the method is good or not?

Thx
