### ISSUE TITLE
Preheader strings in template are not available to translation

### ISSUE THREAD

**Issue by Vgratioulet** [voidlabs/mosaico#391]
Hello,
I translated the versafix theme using the solution you provided in https://github.com/voidlabs/mosaico/issues/308 but I can't reach
'Page', 'Show Preheader' and the preheader help string

is there a way to do that, other than modify the template ?

I'm also looking into translating the content of the spans :  'Unsubscribe', 'Button', 'Title', Sample text...
if you can point me in the right direction

if it can be of any help to someone, here is my plugin :
```
    templateLanguagePlugin = function(viewModel) {
      $.get('templates/lang/template-fr.json', function(tstrings) {
        viewModel.tstrings = tstrings;
        viewModel.ut = function(category, key) {
            var res = viewModel.tstrings[key];
            if (typeof res == 'undefined') {
              console.warn("Missing translation string for",key,": in template, using default string");
              res = key;
            }
            return viewModel.tt(res);
          };
      });
    }
```
and my translation file (for French)
[template-fr.json.txt](https://github.com/voidlabs/mosaico/files/1574619/template-fr.json.txt)

**Comment by bago** [comment]
Your best option is translating the master template. So you can translate whatever you want.

Try using "viewModel.t" instead of "viewModel.tt".. it will help translating strings from the "@supports -ko-blockdefs" section, but it won't translate span/div contents as they are not labels, but contents.

The only way you have to customize contents is to alter the master template.

**Comment by Vgratioulet** [comment]
Thanks for your reply,
I think I don't understand the advice. If I replace viewModel.tt by viewModel.t in my plugin, it tries to translate the template translated strings with the main translation file. And it doesn't reach 'Page', 'Show Preheader' nor the preheader help string

**Comment by Vgratioulet** [comment]
I tried translating `Show Preheader` in the template : 
- `Afficher l'entête` breaks the template, 
- `Afficher l\'entête` displays the backslash,
- `"Afficher l'entête"` displays the double quotes 

could you tell me how I should write it ?

**Comment by Vgratioulet** [comment]
Thanks, it works fine with the spelling : "Afficher l'entête"
