### ISSUE TITLE
Unable to view image editing option

### ISSUE THREAD

**Issue by ATabish90** [voidlabs/mosaico#393]
Hi,

I have downloaded and configured mosaico without any issue. All the features are working fine. There is only one option missing in my downloaded project and that is an image editing option. Please find the screen shots below

Visible on website demo

![image](https://user-images.githubusercontent.com/33214884/34381481-b5f60708-eb2e-11e7-8bc4-4635dbd42dda.png)

Not visible on downloaded project.

![image](https://user-images.githubusercontent.com/33214884/34381509-eab34e74-eb2e-11e7-87f1-2a64818ab66c.png)

Is this feature not yet released for the developers ?

**Comment by bago** [comment]
That's moxiemanager, it cannot be integrated in the GPL open source version because of licensing issues:
https://github.com/voidlabs/mosaico#live-demo
