### ISSUE TITLE
how to configure mosaico in ssl server.

### ISSUE THREAD

**Issue by keertha** [voidlabs/mosaico#395]
http://cake.xxxxx.fr:9006/  - loading

https://cake.xxxx.fr:9006/ - Not loading

**Comment by bago** [comment]
Mosaico demo backend is HTTP. You can't access HTTP backend using HTTPS protocol. 
If you need HTTPS either use a webserver supporting it or put an HTTPS reverse proxy in front of it (hitch/pound).

Please note that the demo backend is not suitable for production. It is a development backend (https://github.com/voidlabs/mosaico/blob/master/backend/README.txt) , so there's no point in supporting HTTPS.
