### ISSUE TITLE
Image rendering in Apache

### ISSUE THREAD

**Issue by njolin** [voidlabs/mosaico#4]
Images render with broken placeholders in editor.  Verified that imagemagik is installed and configured properly, but am unable to upload any images in the editor.

When trying to upload an image, I get:
error inaspettato durante il caricamento (not found)

Also, image placeholders show as broken links as well.  

Any other pre-requisites needed or scripts added?

Thanks much for your help and this awesome editor.  Very well done!

**Comment by njolin** [comment]
Sorry, just found the backend folder now.  Will check that out.  Do you have any examples on the img and upload scripts?
Thanks!

**Comment by bago** [comment]
The backed/main.js is a working example of a minimal backend.
The readme.txt describes the expected endpoints (configured in options to Mosaico js initialization in editor.html)

If you run mosaico via grunt it will automatically start a node-express web server with the minimal working backend.

**Comment by njolin** [comment]
Got it,  Thanks!
