### ISSUE TITLE
Import External HTML.

### ISSUE THREAD

**Issue by sibbu2005** [voidlabs/mosaico#403]
I would like to import external HTML page and want to edit it using Mosaico editor.I will use this in my project , there is a requirement that user will upload HTML and edit it using the editor. Is there any way that I can parse my HTML page and convert it to JSON and then import it.
@bago 

Regards
Dhananjay

**Comment by sibbu2005** [comment]
@bago How I will convert an HTML into a compatible JSON. I have an HTML that I exported From Mosaico  Editor. Now I want to parse that HTML elements and want do a reverse engineering for creating a compatible JSON.

**Comment by sibbu2005** [comment]
@bago  does your paid version has this facility that we can import HTML. All mail editors have this facility that user can upload HTML and can edit source code.

**Comment by bago** [comment]
NO. Mosaico cannot and will never be able to import html code: it is simply not how mosaico works.

https://github.com/voidlabs/mosaico/wiki/Replacing-TinyMCE-or-CKEditor-with-Mosaico
https://github.com/voidlabs/mosaico/wiki
