### ISSUE TITLE
Mosaico Outlook 2013 Corrupt HTML Format

### ISSUE THREAD

**Issue by talhakoc** [voidlabs/mosaico#404]
Hi,

I'm using Outlook 2013 and noticed that somehow when I send any e-mail using Mosaico/Versafix template, 3 colums are not show in the same line as in the following screenshot. 

<img width="790" alt="temp" src="https://user-images.githubusercontent.com/6253345/35260365-2ec30fa8-001c-11e8-93bc-cf25f8482fb7.PNG">

Any idea about how to resolve this?

PS: Sorry if this is not the right place to ask.

Regards,
Talha

**Comment by bago** [comment]
I'm sorry this is a bug of outlook trying to deal with html. It is out of the scope of Mosaico to support similar scenario: we care the email are *viewable* by Outloook (and this is already a pain), we don't care at all that they are editable by outlook (whatever you let outlook do, will break things, anyway).
