### ISSUE TITLE
Problem with adding attachments

### ISSUE THREAD

**Issue by FrankieCollen** [voidlabs/mosaico#405]
Hello, I've had a fantastic experience with Mosaico and created a lovely email template. I'm having a problem though when I add other attachments to the email I want to send the formatting goes all out of place. I can guess its to do with adding something while it currently has a code etc. I was just wondering how to fix it? 
![screen shot 2018-01-26 at 15 16 06](https://user-images.githubusercontent.com/35843330/35446417-8e576bde-02ac-11e8-885d-283410074000.png)
![screen shot 2018-01-26 at 15 16 22](https://user-images.githubusercontent.com/35843330/35446421-9117571c-02ac-11e8-9db5-ca344309ddc4.png)

**Comment by bago** [comment]
Use a different way to send your email. Mosaico simply creates an HTML. Adding attachments is not related at all with the email html, so it much be your buggy client.

**Comment by FrankieCollen** [comment]
I don’t understand what you mean by different way to send your email?

Kind Regards,

Francesca Collen


On 30 Jan 2018, at 09:59, Bago <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #405<https://github.com/voidlabs/mosaico/issues/405>.

**Comment by bago** [comment]
Mosaico simply gives you html.

If the tool you use to add attachment breaks this html, then change this tool. Mosaico doesn't care at all about attachments. They are in parallel world. THere is nothing mosaico can do to fix the issue of your tool.

**Comment by FrankieCollen** [comment]
Thankyou for clearing that up.

Kind Regards,

Francesca Collen


On 30 Jan 2018, at 10:08, Bago <notifications@github.com<mailto:notifications@github.com>> wrote:


Mosaico simply gives you html.

If the tool you use to add attachment breaks this html, then change this tool. Mosaico doesn't care at all about attachments. They are in parallel world. THere is nothing mosaico can do to fix the issue of your tool.
