### ISSUE TITLE
Add translations as a configuration option! (was: Rename toolbar)

### ISSUE THREAD

**Issue by tiagobernardes** [voidlabs/mosaico#41]
I need to translate toolbar.
How do I do?

**Comment by bago** [comment]
Do you need multilanguage or just a single language that is not english?

The good news is that the code already takes into consideration the ability to translate the interface.

The bad news are 2:
1) that the library does not expose a configuration option to define the translations
2) some strings are in the library, some strings are in the template definitions.

So, at this time you have to follow this:
1) Start at https://github.com/voidlabs/mosaico/blob/master/src/js/viewmodel.js#L26 and https://github.com/voidlabs/mosaico/blob/master/src/js/viewmodel.js#L153 . Every translatable string goes through this .t() function. So you can change the hardcoded map and build your library.
2) In the template, e.g: https://github.com/voidlabs/mosaico/blob/master/templates/versafix-1/template-versafix-1.html#L11 you can see a @supports -ko-blockdefs section with a lot of stuff: label, help and options properties define text that will be visible to the editor "user".

**Comment by tiagobernardes** [comment]
is only set to a single language.

**Comment by bago** [comment]
I keep this open as a "feature request" so that we expose a configuration option to pass translations to the library (it should be easy).

**Comment by tiagobernardes** [comment]
I'd like to help but do not know how .
I saw that the function "t"  returning the key ( in English ) and not the value (in Italian) of the array strings.
It will be possible with a multidimensional array?

**Comment by bago** [comment]
If you want to change the language strings without altering mosaico code you can do that injecting a "mosaico plugin":

```
Mosaico.init(optionsObject, [function(vm) {

var strings = {
 ... translations as you see in viewModel.js
};

vm.function(key, paramObj) {

    var res = strings[key];
    if (typeof res == 'undefined') res = '##' + key + '##';
    if (typeof paramObj !== 'undefined')
      for (var prop in paramObj)
        if (paramObj.hasOwnProperty(prop)) {
          res = res.replace(new RegExp('__' + prop + '__', 'g'), paramObj[prop]);
        }
    return res;
});
}]);
```

This way you replace the t() function with your own (using your strings).

Of course I would better add a simple configuration for this, but in the mean time you can do that this way. Let me know if this works.

**Comment by bwl21** [comment]
If there is a framework to contribute tranlations, I volunteer to provide German strings.

**Comment by bago** [comment]
Suggestions are welcome, in the mean time you can have a look at the italian translation array in viewModel.js and make a similar array for germam and paste it here.

Maybe we should simply make CODE_LN.json files with { english: translated, english2:translated2 } strings . Then we will define later how to load them.

**Comment by bwl21** [comment]
actually there are two options:

CODE_LN.json 

or a json with all languages: This is, what we use in another project

```json
{
  "- Adauga categorie noua": {
    "de": "- Kategorie anlegen",
    "en": "- add new category ",
    "usage": "awm_admin"
  },
  "- Editare categorie": {
    "de": "- Kategorie bearbeiten",
    "en": "- Ediit Category",
    "usage": "awm_admin"
  },
  "1. Ihre Angaben": {
    "de": "1. Ihre Angabe",
    "en": "1. Your entries",
    "usage": "form"
  }
}
```

the "usage" key is used to prioritize the translation

**Comment by bago** [comment]
I thought the "single file" would increase the size of the library where
most users won't need multilanguage.
Let's say we support 100 languages, you have a lot of wasted resources...

Not sure what other libraries do (tinymce bundle english and get other
languages dynamically from separate language files)

Stefano

**Comment by bwl21** [comment]
Single File is easier to maintain, but in this case, I propose to use one file per language. I am not aware if there is a "standard" for this issue.

**Comment by bago** [comment]
I tried to use a string format compatible with http://i18next.com/

i18next has functions to automatically detect the language, to automatically load the language file from the backend, to edit the translations and see what need to be completed...

So maybe the best option is:
1) use i18next format, then have a configuration option to pass this "object" to the Mosaico.init (so we can have simple translations without i18next
2),then write a mosaico plugin to support i18next

Maybe some grunt task can be added to provide the translation interface (never did that).

**Comment by bwl21** [comment]
Sounds reasonable. I was not aware of this specification, but it looks good.

**Comment by bago** [comment]
I'm currently refactoring the code to allow for translations to be passed from the outside without altering the main mosaico code.

In the mean time I set up a Transifex project so anyone can easily provide strings for his own mother language! https://www.transifex.com/void-labs/mosaico/

If anyone wants to collaborate to contribute a translation please write me at info on the mosaico.io domain, writing me your email, your name and the language/languages you want to contribute to.

**Comment by bago** [comment]
Now you can provide a "strings" object to Mosaico.init options.
The object is a simple key/value pair and you can see the translation object for italian in https://github.com/voidlabs/mosaico/blob/master/src/lang/mosaico-it.json

**Comment by bwl21** [comment]
I propose to handle loading of the file etc. in mosaico, such that it is simple to configure the editor

```
Mosaico.init{Mosaico.init({ lang: 'en'})}
```

**Comment by bago** [comment]
i18next does all of this, but I don't want to add i18next dependency for people that simply needs one language. And people using a single language will prefer to bundle the language instead of slowing down the editor to let it download the language file.

**Comment by bwl21** [comment]
I did a brute force hack:

```javascript
  var strings = $.ajax('src/lang/mosaico-de.json', {type: "GET", async: false}).responseText;
  strings = $.parseJSON(strings);

  var ok = Mosaico.init({
      strings: strings,
      imgProcessorBackend: basePath+'/img/',
      emailProcessorBackend: basePath+'/dl/',
      titleToken: "MOSAICO Responsive Email Designer",

      fileuploadConfig: {
         url: basePath+'/upload/'
      // messages??
    }
  }, plugins);

```
I would appreciate if the language files were at least compiled to `dist` folder, even if integrator is on his own to utilize them.

I also see the issue that the template cannot yet be made multilingual (even if seems not that easy).

**Comment by bwl21** [comment]
@bago could you please comment the request to put the language files in the "dist" folder. Also please comment what you think about my approach of loading the language file. Based on this approach it would even be possible to implement a language switch without downloading *all* langugage files.

**Comment by bago** [comment]
I'll move translations to the "res" folder: the "res" folder is already copied to the dist folder when building.
