### ISSUE TITLE
Feature request: send emails via Mailgun with inline attachments

### ISSUE THREAD

**Issue by tleyden** [voidlabs/mosaico#411]
Thanks for Mosaico!  Awesome work .. it was just what I was looking for.

I have a feature request with regards to sending mails via the Mailgun API, and I'm willing to contribute some code as well if possible.

I'd rather not have to keep a Mosaico server running publicly, I just want to run it locally in order to build the emails, and then I want to send them via the Mailgun API.  However, there is one tricky part with the images, since the image URL's embedded in the email HTML point back to the Mosaico server by default.  Instead of that, I'm looking for a way for the HTML to contain img references like:

```
<img src="cid:my_image.jpg">
```

and then when I sent the email via Mailgun, I could just do:

```
cat my_mosaico_designed_email.html | curl https://api.mailgun.net/v3/messages -F inline=@path/to/my_image.jpg -F html="<-"
```

which would inline the image attachment, so that the HTML email would be fully self-contained and not require any external hosting.

Is this something the plugin framework could do?  Or would Mosaico need to be reworked in order to support this kind of pluggable behavior?  

Also, a few problems that I can see with this approach:

1.  Mosaico seems to do the resizing of the images when serving the img url, but with inline attachments they'd need to be resized before they are attached.  
1. There are "placeholder" images that would need to be generated and attached inline

Any hints on how to implement this, and whether a PR would be considered, would be very helpful.

**Comment by bago** [comment]
I'll do this on the backend... have a loot a the "test" feature (calls the /dl backend with an option to specify the destination email).

On the backend I would look for "img[src]" attributes and replace them with identifier, and then http request the url that you just replaced and save it in a temporary location so to be able to send it to mailgun.

You probably could do this on the client side too but I don't think it worth it.. you have to do much more work and you would have to ask for mailgun auth and store it in the client....
