### ISSUE TITLE
Pass dynamic values to custom TinyMCE toolbar button

### ISSUE THREAD

**Issue by CSMarco** [voidlabs/mosaico#414]
Hello,
we are trying to add a custom button to the TinyMCE toolbar which includes a custom submenu for all available value placeholders which are going to be parsed when an e-mail is sent out. We managed to add such button with static values in the wysiwygs.js file directly in TinyMCE's options, but didn't manage to pass a list of available variables from our database to TinyMCE and the submenu of this button.
What would you suggest for passing dynamic values to a TinyMCE button?
We also tried writing a custom TinyMCE plugin which didn't work out as we wanted.

**Comment by bago** [comment]
Have a look at this issues and related issues: https://github.com/voidlabs/mosaico/issues/310

**Comment by CSMarco** [comment]
@bago Thank you! Doing it like described in the issue worked
