### ISSUE TITLE
Buttons won't work properly on iphone

### ISSUE THREAD

**Issue by lintay** [voidlabs/mosaico#419]
Hi the buttons works fine on a desktop browser, but they will only work on my iphone when I push and hold it down for a second or two...

**Comment by bago** [comment]
Which template? Which version of mosaico? Does it happen on mosaico.io?
Make sure you read https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md#rendering-issues-with-templates-generated-by-mosaico
and then add a comment here.

**Comment by bago** [comment]
no anwers, closing.
