### ISSUE TITLE
Cannot add any image either inside a template block or the gallery

### ISSUE THREAD

**Issue by frufin** [voidlabs/mosaico#421]
I had no problem installing and running mosaico locally on my Mac OSX 10.11.3.
The application is served on 127.0.0.1:9006, i can edit anything from templates, but when i try to add any image, i get the following error 

On Chrome 64 -> `jQuery.Deferred exception: Cannot read property 'parseMetaData' of undefined TypeError: Cannot read property 'parseMetaData' of undefined
    at N.(anonymous function).(anonymous function).loadImageMetaData (http://127.0.0.1:9006/rs/mosaico-libs.min.js?v=0.17.0:12:421228)
    at N.(anonymous function).(anonymous function).n (http://127.0.0.1:9006/rs/mosaico-libs.min.js?v=0.17.0:12:416823)
    at e (http://127.0.0.1:9006/rs/mosaico-libs.min.js?v=0.17.0:12:29181)
    at t (http://127.0.0.1:9006/rs/mosaico-libs.min.js?v=0.17.0:12:29483)`

On Firefox 60 -> `jQuery.Deferred exception: l is undefined loadImageMetaData@http://127.0.0.1:9006/rs/mosaico-libs.min.js?v=0.17.0:12:421226
n@http://127.0.0.1:9006/rs/mosaico-libs.min.js?v=0.17.0:12:416796
e@http://127.0.0.1:9006/rs/mosaico-libs.min.js?v=0.17.0:12:29179
c/</t<@http://127.0.0.1:9006/rs/mosaico-libs.min.js?v=0.17.0:12:29483
 undefined`

Then i started successfully a backend server on port 3000 ("node main.js" from /backend), as i supposed it was the missing part, but got same results....

Thanks for help !

**Comment by bago** [comment]
The backend is automatically started on port 9006 when you run "grunt" or "grunt server". "node main.js" is not something needed or expected.

Please try the last prerelease 0.17.0. Current head include work in progress code and may have issues.

**Comment by bago** [comment]
I just fixed the issue, you can also download again the latest head.

**Comment by frufin** [comment]
Thanks !!
