### ISSUE TITLE
How to upgrade Mosaico with latest changes to existing code

### ISSUE THREAD

**Issue by sumitsijaria** [voidlabs/mosaico#422]
Can you please let me know how I can upgrade latest code to existing customized app. 

I would like to add feature for image editing etc.

**Comment by sumitsijaria** [comment]
@bago

**Comment by bago** [comment]
image editing is not something part of mosaico:
https://github.com/voidlabs/mosaico/blob/master/README.md#live-demo

I can't tell/guide you on how to upgrade a customized version of mosaico: I'd say "look at the diff"!

BTW, where is your customized version repository? What improvements did you apply? Maybe something can be merged back so you don't need a fork.

**Comment by sumitsijaria** [comment]
I want to use latest verafix and fluid templates in my project. 

What are all dependencies for updated version of verafix template I need to import apart from verafix template folder

**Comment by bago** [comment]
I know people using latest versafix with mosaico 0.14, maybe also 0.13. I don't this there is any special requirement about that version of mosaico.

versafluid is not a free/opensource template.

If you want more help, share your fork.
