### ISSUE TITLE
Paragraph text is huge

### ISSUE THREAD

**Issue by CaptainHypertext** [voidlabs/mosaico#424]
![email template issue](https://user-images.githubusercontent.com/15058607/37408637-e127d160-2772-11e8-8a76-b4466486ae55.png)

I had this start happening to a user.  The paragraph text is huge and it also happens for newly created blocks.  Newly created emails don't have this problem, just this particular one.  This screenshot is in the Mosaico editor.  Is this something you've seen before and maybe know what's causing it?

Any help is appreciated.

**Comment by bago** [comment]
Well, it seems you simply changed the default font size for paragraphs in the Style tab.

**Comment by CaptainHypertext** [comment]
🤦‍♂️ ... you da man.  That did it.
