### ISSUE TITLE
In Title and Button, content is not editable when defaut content is removed

### ISSUE THREAD

**Issue by Vgratioulet** [voidlabs/mosaico#426]
In Firefox 52/Debian and Firefox 59/Ubuntu, on every button and title when I remove the default content then click outside the field, I can't focus on it again to write the new content.
it doesn't happen on text paragraph, the field is still focusable with a black border when I mouseover it. And when I click in the rectangle I have a orange limit at the beginning and the end.
 
If I click in 'Content' in the button link to write an url (in the left side of the screen), the button text field (in the right side) becomes focusable again with the orange limits.
There is no editable property for the title to help make the title text field focusable again.
I reproduced it on https://mosaico.io/editor-0.17.4.html

**Comment by bago** [comment]
OK. Are you able to focus it again if you focus the previous or next editable text and use TAB or CTRL+TAB to move the focus to the "missing" editable? If yes, then it is still editable, but being empty you are not able anymore to select it via mouse. In this case it should be easier to fix. Otherwise I need more infos.. please let me know.

**Comment by Vgratioulet** [comment]
yes, with TAB and CTRL+TAB I can reach those fields, good work-around, thanks

**Comment by bago** [comment]
OK, I can reproduce it. Title and buttons are no more focusable if they are emptied. This is somehow template-related but maybe we need a fix (either in the template or in the editor) so that even empty inline  editable elements can be focused.

**Comment by bago** [comment]
I added some defaull style to make sure inline editable are inline-block, have a minimum width and are never empty.

**Comment by Vgratioulet** [comment]
Works perfectly, thanks
