### ISSUE TITLE
After clicking ADD button, random hash value is gone from URL

### ISSUE THREAD

**Issue by kbalajijan1** [voidlabs/mosaico#43]
Hi,

Try below the scenario

1. Click versafix-1 from http://mosaico.io/ 
2. Click ADD button instead of clicking on block image

The random hash value in the URL is gone. Even though I can able to save the template, unable to reload.

I think ```viewModel.addBlock()``` function should have ```event.preventDefault()```.

Thanks,

**Comment by bago** [comment]
What is the issue with that hash disappearing?

**Comment by kbalajijan1** [comment]
Nothing. If I reload the page without hash, it leads to the homepage where as if hash is there I can still stand in the editor.html page after reloading that's it. If this is an expected behavior please close the issue.

Thanks

**Comment by bago** [comment]
OK, got it! I will have a look.
