### ISSUE TITLE
How to integrate Mosaico with textarea like Tinymce

### ISSUE THREAD

**Issue by Sandeepges** [voidlabs/mosaico#445]
I want to replace tinymce with mosaico .Is it possible to do so.If so Please provide with appropriate
steps to integrate it

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/wiki/Replacing-TinyMCE-or-CKEditor-with-Mosaico

**Comment by Sandeepges** [comment]
Hi @bago ,I'm unable to understnad the content in the link provided by You.
is there any code snippet ton insert mosaico into textarea element like tinymce,pleae do provide sample snippet

**Comment by Hiswe** [comment]
@Sandeepges in short Mosaico Editor isn't a text editor working inside a textarea: It's a more complex  solution that produce HTML suitable for mailing. 
That's what the wiki's trying to explain in detail, and maybe your looking at the wrong solution for your problem.
