### ISSUE TITLE
Uncaught ReferenceError: tinymce is not defined

### ISSUE THREAD

**Issue by anasvn** [voidlabs/mosaico#447]
I'm getting an error after landing the page

`tinymce.min.js:9 Uncaught ReferenceError: tinymce is not defined
    at Object.create (tinymce.min.js:9)
    at init (tinymce.min.js:9)
    at i.init (tinymce.min.js:8)
    at new i (tinymce.min.js:8)
    at Function.l [as extend] (tinymce.min.js:8)
    at tinymce.min.js:9
    at tinymce.min.js:2
    at tinymce.min.js:2
    at e (tinymce.min.js:2)
    at tinymce.min.js:9`
I could not edit the text contents also.

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md#are-you-having-issues-with-mosaico
https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md#issues-runningediting

**Comment by anasvn** [comment]
@bago  I have solved this issue by upgrading _tinymce_ to the latest version.
