### ISSUE TITLE
Text not editable in local environment

### ISSUE THREAD

**Issue by elcaptain** [voidlabs/mosaico#448]
Hello,
I am running mosaico on my local machine. I didn't hat any problems installing or compiling.
My problem is that there is no field to edit any text of the blocks in the preinstalled templates (Chrome and Firefox on MacOS).
![screen shot 2018-05-16 at 17 04 31](https://user-images.githubusercontent.com/15268562/40125452-457dba0a-592b-11e8-8105-3b37af78e23f.png)

There is an error about tinymce in the console:

Uncaught ReferenceError: tinymce is not defined
    at Object.create (tinymce.js:29185)
    at o.init (tinymce.js:29712)
    at o.init (tinymce.js:25720)
    at new o (tinymce.js:25691)
    at Function.l [as extend] (tinymce.js:25732)
    at tinymce.js:30462
    at tinymce.js:44
    at tinymce.js:27
    at e (tinymce.js:43)
    at tinymce.js:30456

Tinymce should be installed in the "npm install" process or do i have to do that manually?

Thanks for your time.

**Comment by bago** [comment]
npm version?
mosaico version?

**Comment by elcaptain** [comment]
Oh, sorry if didn't mention that.
npm 3.10.10
mosaico 0.17.3
node 6.11.4

**Comment by bago** [comment]
I just tested with 

npm 3.10.10
mosaico 0.17.3
node 6.11.4

and it worked fine.

- Are you sure you did a clean install?
- How did you download mosaico 0.17.3?
- npm install and grunt logs?
- size of the generated dist/rs/mosaico-libs.min.js

**Comment by elcaptain** [comment]
- I just installed to a new directory
- I downloaded the master.zip from github
- npm output:
npm WARN deprecated formidable@1.0.17: Old versions of Formidable are not compatible with the current Node.js; Upgrade to 1.2.0 or later
npm WARN prefer global coffeescript@1.10.0 should be installed with -g
npm WARN prefer global nave@0.5.3 should be installed with -g
npm WARN prefer global jshint@2.9.5 should be installed with -g
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> fsevents@1.2.4 install /Users/jonas/Documents/mosaico/node_modules/fsevents
> node install

[fsevents] Success: "/Users/jonas/Documents/mosaico/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> iltorb@1.3.10 install /Users/jonas/Documents/mosaico/node_modules/iltorb
> detect-libc prebuild-install || node-gyp rebuild


- grunt output: 
Running "googlefonts:noto" (googlefonts) task
>> 1 font downloaded.

Running "copy:res" (copy) task
Created 6 directories, copied 40 files

Running "copy:root" (copy) task
Copied 1 file

Running "copy:htmls" (copy) task
Copied 2 files

Running "copy:fontawesome" (copy) task
Copied 5 files

Running "uglify:deps" (uglify) task
>> 1 sourcemap created.
>> 1 file created 2.42 MB → 923.19 kB

Running "cssmin:deps" (cssmin) task
>> 1 file created. 358 B → 322 B

Running "jshint:all" (jshint) task

✔ No problems


Running "combineKOTemplates:main" (combineKOTemplates) task

Running "browserify:main" (browserify) task
>> 1038689 bytes written (8.87 seconds)
>> Bundle build/mosaico.js created.

Running "exorcise:main" (exorcise) task
Exorcising source map from build/mosaico.js

Running "less:css" (less) task
>> 2 stylesheets created.

Running "postcss:dist" (postcss) task
>> 1 processed stylesheet created.
>> 1 sourcemap created.

Running "postcss:material" (postcss) task
>> 1 processed stylesheet created.
>> 1 sourcemap created.

Running "express:dev" (express) task
Starting background Express server
Express server listening on port 9006

Running "watch" task
Waiting...
- dist/rs/mosaico-libs.min.js is 924kb

**Comment by bago** [comment]
Can you send me the "dist/rs/mosaico-libs.min.js is 924kb" not working? The size is ok, so tinymce should be there... maybe it have been added in the wrong order.. I have to see the result to analyze it as it worked fine in my npm3 deploy.

**Comment by elcaptain** [comment]
Hi bago, sorry for the delay.
After downgrading to npm@3.10.10 and node@6.11.4 and a new compile it is working now. Since the bug is not reproducible by me anymore I'll close this ticket. Sorry for bothering.
