### ISSUE TITLE
Pagination For Blocks

### ISSUE THREAD

**Issue by sibbu2005** [voidlabs/mosaico#449]
Hi , I have added 70-80 Blocks in my mosaico template. Now I wants to implement pagination , so that I can show 10 Blocks at a time. I found pagination is working on  Gallery, and I redined the blockDefs as 
`blockDefs:ko.observableArray([]).extend({
      paging: 10
    }),`
Can we do this?
And how will display Pagination?
but I am not sure Where I will put the HTML for pagination navigation .
https://github.com/voidlabs/mosaico/blob/master/src/tmpl/block-show.tmpl.html
https://github.com/voidlabs/mosaico/blob/master/src/tmpl/blocks-show.tmpl.html

@bago

**Comment by bago** [comment]
I can't see your fork code... I give higher priorities to people asking for support and sharing their code. Share your blocks, and I'll be happier to give back my support ;-)

If you are a commercial license user then please ask this question to the support email.

**Comment by sibbu2005** [comment]
thanks for your reply 
Here is my fork, I want to paginate , when Number of blocks exceeds 10.
https://github.com/sibbu2005/mosaico

https://github.com/sibbu2005/mosaico/blob/master/src/js/viewmodel.js
https://github.com/sibbu2005/mosaico/blob/master/src/js/template-loader.js
https://github.com/sibbu2005/mosaico/blob/master/src/tmpl/toolbox.tmpl.html

**Comment by sibbu2005** [comment]
did it 
working now.
Steps:
1- define an array with pagination control.
2- assign the values of blockDefs to this array
3- Create a new tmpl file for blocks to load
4- and implement it as gallery pagination working.

Now its working, I have created over 100 blocks and now I can paginate .
![blockpager](https://user-images.githubusercontent.com/4980123/40573116-a7bb40b0-60d9-11e8-8337-c3b7ffa84a9e.png)
