### ISSUE TITLE
mosaico should be more robust upon server errors

### ISSUE THREAD

**Issue by bwl21** [voidlabs/mosaico#45]
If anything goes wrong at the server side, there is no feedback to the user. mosaico silently does not work.

For example, if upload of an image fails, and the server does not respond with a valid JSON, one needs to open the console  ...

I don't know if we have a specified error response from the server such that mosaico can detect error conditions. But if the reponse is not a valid JSON, mosaico could report the response in an alert.

**Comment by bago** [comment]
It should already show upload errors using the tooltip library: mosaico expects the backend to provide "jquery file upload" errors.

well, maybe I missed to provide translations for them and you get italian errors, too..

**Comment by bwl21** [comment]
I saw some italian messages, but while trying https://github.com/ainterpreting/mosaico-php-backend I had the problem that image upload silently failed. The reason was that ImageMagick was not on the server. So upload worked fine but subsequent processing had a problem. And this can always happen (e.g. if quota is exceeded). 

In other projects, I always use the same ajax - response:

```json
{
"code": 0, 
 "message": "this is the message for the user",
 "payload": {
              "files":  [{}]}
             }
}

```
for sake of backwards compatibility I propose to leave out the level "payload":

```json
{
"code": 0, 
 "message": "this is the message for the user",
 "files":  [{}]
}

```

**Comment by bago** [comment]
Mosaico deals with remote error messages:
https://github.com/voidlabs/mosaico/blob/master/src/js/bindings/fileupload.js#L228
https://github.com/voidlabs/mosaico/blob/master/src/js/bindings/fileupload.js#L228

Mosaico uses jqueryfileupload for file uploading, so it expect the backend to reply with jqfu style errors:
https://github.com/blueimp/jQuery-File-Upload/blob/master/server/php/UploadHandler.php

We use mosaico.js in our application and I'm sure errors are displayed, so maybe this has something to do with translations or with server resulting in unexpected erros. Also, I'm not sure the bundled node.js backend returns the errors the frontend expect (the node.js backend is a one-night hack made so to have a "self-contained" build/run environment for developers).

So, the "expected" behaviour is the backend to return jquery-file-upload-php errors, the frontend to show localized errors. If anything does not comply with this, we have a bug.

**Comment by bwl21** [comment]
In our case, the upload worked well. There was a problem with the processing of the upload. How should this be reported by the backend? Should'nt we distinguish between technical errors (protocol errors, upload errors) and semantical errors?

I vote for a general error reporting approach here. This should apply for other operations as well, e.g. 

Nevertheless mosaico should somehow be robust against server malfunction. At least it should report if the response is no valid JSON string.

**Comment by bago** [comment]
What did the server reply in that case? So I can emulate and deal with that response.

**Comment by bwl21** [comment]
The response is HTML as created by PHP in case of an error.


![screenshot_390](https://cloud.githubusercontent.com/assets/2022976/11363601/1da62bc4-929b-11e5-91c1-a1a88e79acf5.jpg)

**Comment by bago** [comment]
What HTTP status code and status text? "500 Server Error"?

**Comment by bwl21** [comment]
I reproduced the issue by turning off image magick on my server:

status code: 200 Ok

Response: 
```html
<br />
<b>Fatal error</b>:  Class 'Imagick' not found in <b>/home/www/mosaico/upload/index.php</b> on line <b>44</b><br />
````

Browser log:

![screenshot_394](https://cloud.githubusercontent.com/assets/2022976/11382614/37ea6f6e-9303-11e5-808d-4d8e61f06b45.jpg)

**Comment by bago** [comment]
The php backend should not return "200" for a "Fatal error".

BTW I tried it here and I see an 'Unexpected upload error' in the toastr. Don't you see it?

Maybe you're seeing an italian version of that message, but you have to see the message...

**Comment by bwl21** [comment]
No, I do not see this message. I still have turned of "imagemagick" on http://weichel21.de/mosaico

I am using chrome

**Comment by bago** [comment]
![test-mosaico-error](https://cloud.githubusercontent.com/assets/173498/11383187/d7280a66-9306-11e5-9d69-79d8824421e2.png)

**Comment by bago** [comment]
I already fixed the italian string by changing it to english (I will push tomorrow).

I don't know why you don't see that toastr... how do you upload?

**Comment by bwl21** [comment]
very strange, I did not see this message. 
But I was trying to upload an image directly to the gallery (with file selection dialog or by dragging the file), I don't get this message.

When I push the upload button on a placeholder and use the file selection dialog of the operating system, then I do get this message. But when I drag a file to the placeholder, the message does not show up.

**Comment by bago** [comment]
good catch!

**Comment by bwl21** [comment]
I now turned on ImageMagick again ... so the test cases no longer work at weichel21.de

**Comment by bago** [comment]
With the latest version you should get errors also in the gallery pane and see them in english.
Please close this or tell me if there are other backend errors that should be handled differently.

**Comment by bwl21** [comment]
I merged your master branch in to my tutorials branch and tried again. 

* drag file to galery
* upload to galery via system file selector
* drag file to block
* upload file to block via system file selector

In each of these cases i got

![screenshot_395](https://cloud.githubusercontent.com/assets/2022976/11396920/8b246cb2-9375-11e5-90ef-3f8cf448ba93.jpg)

This is an exceptional situation in which you might alert the raw response. But maybe the message comes from another layer in which you do not have access to the raw response.

So I close this. Thanks a lot.
