### ISSUE TITLE
OWA - Versafix social icons not aligned

### ISSUE THREAD

**Issue by CaptainHypertext** [voidlabs/mosaico#450]
In Outlook Web, I'm seeing this with the versafix template:
![mosaico bug](https://user-images.githubusercontent.com/15058607/40242015-7029ceaa-5a8a-11e8-8eeb-a132422a23f4.PNG)

Particularly the social icons are stacked up vertically instead of horizontally.  This is how the same email looks in Gmail:
![mosaico social gmail](https://user-images.githubusercontent.com/15058607/40242092-a6f4334e-5a8a-11e8-8203-3cc18798d0fa.PNG)

However, if I test these blocks with the demo site, it looks fine.  This issue is consistent on my end, and I've tried a few different emails from my system.  I even made sure to use the latest original versafix from github to ensure I hadn't messed anything up, and no dice.  If I inspect the images in OWA and remove the `display: block` style, they line up properly.

Any thoughts on why this could be happening?

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md#rendering-issues-with-templates-generated-by-mosaico

Which version of mosaico are you using?
What backend are you using?

**Comment by CaptainHypertext** [comment]
Sorry, I'm no longer working on the project that uses Mosaico.  You may close this if you think it's isolated.
