### ISSUE TITLE
Can it integrated with angular 5 application

### ISSUE THREAD

**Issue by kumar88kanishk** [voidlabs/mosaico#453]
I have an angular 5 application which i am building and this module is very impressive, great job done!! you guys!! But sadly i dont find any documentation to integrate with angular 5. Please peddle me towards the solution!!!

**Comment by senyaak** [comment]
As I know - you should implement it by yourself. 
The main problem is the build - this library do not work well with webpack. Im also trying to do the same now, only for angularjs. So if I succees - I will link here my fork. But this is a big if :D

**Comment by bago** [comment]
Use an iframe and load mosaico in the iframe.
Please consider Mosaico a "Single Page Application", you don't probably want to consider it a "component" as it requires a full page and it is a feature that is used for minutes, not for seconds... so simply load it in its won page or in a fullsize frame....
