### ISSUE TITLE
how we can upload, uploaded images to aws s3 bucket

### ISSUE THREAD

**Issue by ravir636** [voidlabs/mosaico#456]
i am trying to read images from uploaded json but get the Uncaugth error: error fs.readFileSync is not a funtion. i put this code inside  localstorage.js file 

var fs = require('fs');
var imagepath='C://Users/Administrator/Pictures/Screenshots/12353.png';
		
var base64str = base64_encode(imagepath);
	function base64_encode(file1) {
    var bitmap = fs.readFileSync(file1);
    return new Buffer(bitmap).toString('base64');
}

appreciate any help..

**Comment by Hiswe** [comment]
I think you have mixed server side code with client side.
The `localstorage.js` is a client file and so can't access your file system. 

If you try to read files from S3/filesystem this should be handled by your server. 
You should also provide a route to mosaico for accessing those images.

**Comment by ravir636** [comment]
from font side, can we access file system.....?b/c i want to save only template uploaded images whichever is uploaded from blocks (dynamic time)

**Comment by Hiswe** [comment]
There is an [official SDK for Amazon services](https://www.npmjs.com/package/aws-sdk) available in NPM.
The documentation is quite good so maybe you should give it a try :)

**Comment by ravir636** [comment]
I mean how or what code we have to change on main.js file ,..

**Comment by Hiswe** [comment]
in the front-end you should configure 2 things

```
{
  imgProcessorBackend: `url for resize`,
  fileuploadConfig: { /* configuration for upload */  } 
}
```
you can see that in [this fork](https://github.com/goodenough/mosaico-backend/blob/master/server/views/mailing-edit.pug#L43-L56)

in the backend you should handle those entry-points to use the S3

**Comment by ravir636** [comment]
@Hiswe  there is no server folder in my mosaico.. can you please tell how we can congifure in main.js file of backend

**Comment by Hiswe** [comment]
You will need to provide your own server logic. The server's file provided
is only meant for a demo purpose.

So either you modify the existing file, or you come up with your own server
(the server folder in the fork)

**Comment by ravir636** [comment]
can you provide simple solution so that we can modified existing files to storage in s3.

**Comment by Hiswe** [comment]
Nope

**Comment by ravir636** [comment]
@Hiswe  as you said change in existing so how we can.. if anything you can provide related to this its really great help for me.

**Comment by Hiswe** [comment]
https://github.com/goodenough/mosaico-backend

Also you should close this issue because it isn't related to Mosaico. 
The editor is a just front-end library which can be plugged to any server that have the right routes

**Comment by ravir636** [comment]
@Hiswe its related to mosaico, when we are uploading file on blocks its automatically comes in /upload folder. so now i want to do same image store in s3 buckets. thats my point and help that i need.

**Comment by ravir636** [comment]
@Hiswe  can you please help out with these issue ..its really great help for me..

**Comment by Hiswe** [comment]
@ravir636 I've already helped you as much as I can:

– I provided you  an implementation of the AWS on a server
