### ISSUE TITLE
TinyMCE tools not appearing in Internet Explorer

### ISSUE THREAD

**Issue by shawnboy777** [voidlabs/mosaico#459]
I apologize if this issue has been addressed, but I did not find a similar one in the Issues.  I'm using version 0.17.3 of Mosaico and when I load my editor in Internet Explorer 11, the TinyMCE toolbars do not activate. I can edit the text inside the blocks, but there are no tools visible.

I went to mosaico.io and tested it there, and the tools appear in IE when I click a text element.  So, what could be the problem with my installation?

Thanks for your help!

**Comment by bago** [comment]
Do you see errors in the IE11 javascript console?

With "0.17.3" do you mean the release package or the current master?

What if you download https://github.com/voidlabs/mosaico/releases/download/v0.17.3/mosaico-0.17.3-dist.zip from there and run "npm install" + "grunt server" ?

**Comment by shawnboy777** [comment]
Thank you for your reply.  I do not see any "errors" in the console, other than a message that states, "The model being loaded has been created with a different editor version 0.17.1 runtime: 0.17.3"

I built my system from the current master, but I will try the release package next.  I should also note that I am using a php backend (would that make a difference?).

**Comment by bago** [comment]
Did you change the editor.html in order to use your own php backend? Make sure your editor.html includes the resources the same way the editor.html found in the dist folder for current mosaico do.

**Comment by shawnboy777** [comment]
I have heavily modified my editor file to work with my php backend (it is renamed editor.php) but it does contain all of the resources that were in the original file.  The TinyMCE works perfectly in firefox, chrome, and safari, just not IE.

**Comment by bago** [comment]
Please try running grunt with the embedded node.js backend and the bundled editor.html and let me know if it works.

Also try both the current master or the one I documented previously:
---
What if you download https://github.com/voidlabs/mosaico/releases/download/v0.17.3/mosaico-0.17.3-dist.zip from there and run "npm install" + "grunt server" ?
---

If that works, then you have to have a deeper look at your changes.

**Comment by shawnboy777** [comment]
Pardon my ignorance, but how do I run the npm install using the dist.zip?

**Comment by shawnboy777** [comment]
Nevermind my last comment (I figured it out).  I have the server built and running using the dist.zip, running on port 9006, and still getting the same result.

**Comment by shawnboy777** [comment]
If you would like to see what is happening, go to http://153.42.16.249:9006

**Comment by shawnboy777** [comment]
Good morning.  I was just wondering if you had found anything on why this is happening. I don't keep my nodejs running continually, so if you need to see anything on my service that will help to figure out the problem, let me know and I will start it up for you.  Thanks!

**Comment by bago** [comment]
I've been able to reproduce it and added the "bug" label, so you can stop your node. Thank you.

**Comment by shawnboy777** [comment]
Great, thank you.
