### ISSUE TITLE
template backend function

### ISSUE THREAD

**Issue by tiagobernardes** [voidlabs/mosaico#46]
I intend to put functionality in a block for data to backend?
would then be a button on the module, pass a parameter and make a call to the server. receive an image URL and description to fill the block.
if possible, what is the best way to do this?

**Comment by bago** [comment]
this is an unsupported scenario and you will need to put A LOT your hands in the code.

The easier way I can see is:
- add a new "widget" type named "contentfetch" (or something similar)
- implement its code in https://github.com/voidlabs/mosaico/blob/master/src/js/converter/editor.js#L57
- you will have to write a "text field" for your "parameter" and a button implementing your remote fetch logic.
- in the callback you will need to access sibling content properties and you can do this using "$parent" special variable provided by knockout.

**Comment by tiagobernardes** [comment]
A plugin would be great!

the experiences I made, following the process that transmitiste me, did the
following:
- I created a widget
- Modified the convert -> editor, adding a text box and a button
- With jquery, I created a function to fetch data to my backend.
- Finally was replacing the values in the template builder.

Everything was going well, the values have changed in HTML and visually
were as expected.
When a download or sending e-mail in html was submitted as before it was
obtained data.

What could this be?

Best Regards
TB



On 23 November 2015 at 12:05, Bago <notifications@github.com> wrote:

> this is an unsupported scenario and you will need to put A LOT your hands
> in the code.
>
> The easier way I can see is:
>
>    - add a new "widget" type named "contentfetch" (or something similar)
>    - implement its code in
>    https://github.com/voidlabs/mosaico/blob/master/src/js/converter/editor.js#L57
>    - you will have to write a "text field" for your "parameter" and a
>    button implementing your remote fetch logic.
>    - in the callback you will need to access sibling content properties
>    and you can do this using "$parent" special variable provided by knockout.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voidlabs/mosaico/issues/46#issuecomment-158915753>.
>



-- 
Tiago Bernardes
