### ISSUE TITLE
Gallery Live Search and use images, without upload

### ISSUE THREAD

**Issue by sibbu2005** [voidlabs/mosaico#460]
How can we Integrate a third party web service that we can use free images directly from web search?
Like pixabay service.

**Comment by bago** [comment]
Mosaico works with local images because it needs a backend to resize/crop images to its needs. Either you make a way to download the remote image when you select it, so to have a local reference, or you improve the backend so to support resizing/cropping remote images.

**Comment by sibbu2005** [comment]
thanku
