### ISSUE TITLE
Social Icon link text box should be hide when icon is not visible

### ISSUE THREAD

**Issue by sibbu2005** [voidlabs/mosaico#464]
What I missed, It is not working for me.
[[https://gist.github.com/sibbu2005/6691b8a28f73ade75676de7413639cdc](https://gist.github.com/sibbu2005/6691b8a28f73ade75676de7413639cdc)]
![mosaico-social-issue](https://user-images.githubusercontent.com/4980123/42202228-42004098-7eb8-11e8-8794-7e409ae891a5.png)

is there any doc on custom controls.

**Comment by bago** [comment]
Does it happen on mosaico.io using versafix?

Widget visibility is "smart": if the editor thinks the property is currently used by the template then it shows the editor, if it is not used (mainly because the html using it is not currently displayed) then it doesn't show it.

**Comment by sibbu2005** [comment]
Yes , I have added some blocks after copying versafix . I unable to detect where I am making mistakes.

**Comment by bago** [comment]
Q: Does it happen on mosaico.io using versafix?
A: Yes , I have added some blocks after copying versafix .

So.,. does it happen on mosaico.io? 
- If yes, which browser/os versions are you on? do you see javascript console errors?
- If no: make sure the template show the issue on last downloadable release of mosaico and share the template with the issue.

**Comment by sibbu2005** [comment]
using : Chromium

**ERROR: found unexpected -ko- attribute in compiled template , you probably mispelled it**

[-ko-color", "data-ko-block", "data-ko-block", "data-ko-block", "data-ko-block", "-ko-color", "-ko-width", "-ko-border-left-color", "-ko-border-left-style", "-ko-border-left-width", "-ko-border-right-color", "-ko-border-right-style", "-ko-border-right-width", "-ko-width", "-ko-border-left-color", "-ko-border-left-style", "-ko-border-left-width", "-ko-border-right-color", "-ko-border-right-style", "-ko-border-right-width", "-ko-border-top-color", "-ko-border-top-style", "-ko-border-top-width", "-ko-width", "-ko-border-left-color"]

But these properties are working.

**Comment by bago** [comment]
You probably made some syntax error while creating your template (the property won't work if they are logged that way.. you probably didn't check the right properties).

So if you need help:
1) enable debug logging in javascript console dev tools
2) check your code
3) share your "broken" template and open a new issue asking for help.

Otherwise if you can't share, buy a commercial license (including support).
