### ISSUE TITLE
Disable Edition! Is there a flag in which i can set a readonly mode? 

### ISSUE THREAD

**Issue by jgroac** [voidlabs/mosaico#465]
Hi!
I wonder if is there a way to disable the edition on mosaico, something like a readonly mode! 
I've been searching on the docs and i couldn't found a way to do that. 

I would appreciate your help.

Cheers

**Comment by bago** [comment]
I don't understand: what do you mean by "disable the edition" ?
The output is a simple html.. so you can simply show that html if you want a "readonly" version of the email.
