### ISSUE TITLE
Running it on Apache

### ISSUE THREAD

**Issue by AnibalDuarte** [voidlabs/mosaico#471]
Hello everyone, and thanks for spending you time making this amazing tool.

I want to use Mosaico to generate my customer's e-mail templates, then I've installed it and successfully runned it on localhost:9006 with the PHP backend. I've created and saved some e-mail templates like expected without major problems.

But now I need to install and run it on my customer's server, over an subdomain, without needing to run over grunt and run it on port 80.

The question is: how can I do that?

**Comment by bago** [comment]
You talk about "php backend" but if you "runned it on localhost:9006" and without apache you have not used the php backend at all.. you used the bundled "node.js dev backend".

Go to the php backend project and follow their instructions.
