### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Gorgona9** [voidlabs/mosaico#478]
Hello dear developers.
I have a question about mosaico language. How is it possible to use a dynamic variable instead of a label?? 
For example: 
image { label: Image; properties: src url alt }
I want to have a dynamic label instead of a static string "Image". Does your language apply this opportunity?
p.s. Thank you for an awesome tool.

**Comment by bago** [comment]
I'd say the answer is no, but I really don't get your question.. what's a dynamic label? How would it be dynamic?

**Comment by Gorgona9** [comment]
Actually I need to change the text according to the main language. That's why I would like to insert a variable instead of a static text in the place of label.

**Comment by bago** [comment]
Read this:
https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins#viewmodel-plugins

Otherwise simply use multiple master-templates and load the "already localized" master template (I use this way, but I also saw people using the translation plugin hack)
