### ISSUE TITLE
copy/paste and conserve hyperlinks

### ISSUE THREAD

**Issue by angeline2321** [voidlabs/mosaico#479]
![image](https://user-images.githubusercontent.com/44001100/46685289-1ec3a680-cbc3-11e8-91d1-5c9986f56e66.png)
I am using mosaico through PowerBase and have had the same challenge in Google Chrome Version 69.0.3497.100 (Official Build) (64-bit) as well as Microsoft Edge 42.17134.1.0. I am attempting to paste text that already includes hyperlinks into mosaico and would like to conserve the links as opposed to having to insert them all over again. I have attempted to copy and paste from a Word document as well as from other sections of mosaico template emails and have not been successful with either process. The template I'm using is labeled My Design versafix-1.

**Comment by bago** [comment]
Just clic on the second-last button of the toolbar so that "formatted paste" is enabled, and then paste again.
