### ISSUE TITLE
Cannot upload pictures on WAMP

### ISSUE THREAD

**Issue by parismav87** [voidlabs/mosaico#48]
Hello, and congratulations on your great project!
I have a problem: 
I have transferred all the necessary files (with the apache backend sample) to my wamp/www folder, and when i enter localhost:9000 I can see the template selector screen. I can also create a template, block by block, but when trying to upload images, it fails. I can't see the image in the "recents" tab, although a copy of the image is created in "uploads" folder in the file system. 
Grunt is running with no errors. 
Any help would be appreciated

**Comment by bago** [comment]
Please open this issue against the php backend project. Make sure you followed their instructions correctly.

**Comment by parismav87** [comment]
Done! Thanks!

**Comment by bago** [comment]
If you confirm this is a problem with the backend please close this issue, otherwise add context so we can deal with this.

**Comment by bago** [comment]
I tentatively close this one. Please reopen if you still think it is a problem on the client library.
