### ISSUE TITLE
How to intercept changes inside a plugin

### ISSUE THREAD

**Issue by francescogabbrielli** [voidlabs/mosaico#483]
These are 2 questions really.

I have modified the save button in the bar so that it saves to backend. I want to intercept changes so that the user is prompted if he wants the changes to be sent to the backend or not.

I achieved this by subscribing to the `name` property of the `undo...`  is there a cleaner way to do it?
```javascript
function getIoPlugin(config) {
	
	return function (viewModel) {
		
		var saveCmd = {
			name: 'Save', // l10n happens in the template
			enabled: ko.observable(false),
			saved: null,
		};

		// listen for changes
		viewModel.undo.name.subscribe(function(value) {
			var diff = !_.isEqual(saveCmd.saved, viewModel.exportJSON());//lodash
			if (!saveCmd.enabled()) {
				if (!saveCmd.saved)
					saveCmd.saved=viewModel.exportJSON();
			} else if (diff)
				viewModel.metadata.changed = Date.now();
			saveCmd.enabled(diff);
		});

		// save data
		saveCmd.execute = function () {
			
			if (!saveCmd.enabled())
				return;
			
			saveCmd.enabled(false);
			
			if (typeof viewModel.metadata.key === 'undefined') {
				viewModel.metadata.key = 'generate your unique key here';
			}

			var postData = {
				metadata: viewModel.exportMetadata(),
				content: viewModel.exportJSON(),
				html: viewModel.exportHTML()
				//js: viewModel.exportJS()
			};

			$.post(config.saveProcessorBackend, postData)
					.done(function (result) {
						viewModel.notifier.success(viewModel.t('Successfully saved.'));
						viewModel.metadata.saved = Date.now();
						saveCmd.saved = postData.content;
					})
					.fail(function (jqXHR, textStatus, error) {
						viewModel.notifier.error(viewModel.t('Saving failed. Please try again in a few moment or contact us.'));
						saveCmd.enabled = true;
					})
					.always(function () {
					});
		};
		viewModel.save = saveCmd;
		
	};
		
}
```

Second question (probably already made somewhere else): how to add a different button that is not a 'save', 'test' or 'download', that are hardcoded in the source `main.tmpl.html` ?

**Comment by bago** [comment]
2 options:
1) Dump the "exported JSON" at start and compare it when the user leave the page: if they are different you can prompt.
2) If you are altering the source code you can do this:
```
var undoserializer = require("js/undomanager/undoserializer.js");
undoserializer.setListener(listenFuncContentUndoManager);
```
The undomanager exposes a "setListener" and can invoke your method for each model change. I plan to make this event "public" sooner or later, but I have to first identify the best way do to that and I need use cases. 

For your use case the #1 sounds a better and easier solution.

**Comment by francescogabbrielli** [comment]
Thanks for your answer your answer is exhaustive and really explanatory. For the menu, I was adding the butttons with jQuery, but it's true... I can just edit the HTML.
