### ISSUE TITLE
<p data-ko-editable="text"></p> insert/edit link

### ISSUE THREAD

**Issue by ivinkaf** [voidlabs/mosaico#489]
Hi,

if I apply data-ko-editable="text" in p tag - I get editor with two options (bold and italic), is there a way how to add third options: insert/edit link? (I don't want to use data-ko-editable in td or div tag)

thanks

I.

**Comment by bago** [comment]
have a look at #473

You have ko.bindingHandlers.wysiwyg.fullOptions and ko.bindingHandlers.wysiwyg.standardOptions variables that you can override with your preferred tinymce options/toolbar.

```
var customFontsPlugin = function(vm) {
ko.bindingHandlers.wysiwyg.standardOptions.toolbar = whatyouwant;
};
```

See tinymce documentation in order to understand how to configure your tinymce.
