### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by sanjaymv** [voidlabs/mosaico#49]
Installation failed giving this errors
$ npm install
npm WARN install Couldn't install optional dependency: Unsupported

> mosaico@0.11.0 postinstall C:\wamp\www\newsletter
> bower-npm-install --non-interactive

(node) util.error is deprecated. Use console.error instead.
Error: Cannot find module 'bower/node_modules/bower-logger'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\wamp\www\newsletter\node_modules\bower-npm-install\lib\install.js:9:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)

------------
For grunt below error
![screenshot_2](https://cloud.githubusercontent.com/assets/2740161/11366776/897998fc-92c0-11e5-948a-8566a5282298.png)

Node Version : 5.1.0
npm Version : 3.3.12

**Comment by tiagobernardes** [comment]
remove 'bower-logger' folder, run command 'npm install bower-logger' and try again

**Comment by sanjaymv** [comment]
Hi Tiago 
Thanks for support. I just try that for npm it is getting same error and for grunt am getting this error again . Not installing now too
![screenshot_3](https://cloud.githubusercontent.com/assets/2740161/11367238/6697697e-92c3-11e5-8cce-1e1f7b2500c9.png)

**Comment by tiagobernardes** [comment]
try to run command 'npm install webpage' and  'npm install grunt-parallel'

**Comment by sanjaymv** [comment]
Hi

Webpage module is not there i think, it get error. grunt-parallel i already try and it installed fine without issues.
![screenshot_1](https://cloud.githubusercontent.com/assets/2740161/11374549/a1bcfb94-92e7-11e5-94c9-03ed76f12bf9.png)

**Comment by bago** [comment]
npm cache clean
npm install (multiple times if you get differnt errors, stop if same error)
npm update (multiple times if you get differnt errors, stop if same error)

if "npm update" still keeps throwing the same error paste it. Otherwise if it works, start grunt and paste its error.

Repeat this whole process twice to confirm you stuck in the same "place" both times.

**Comment by sanjaymv** [comment]
Hi 
Done, npm update doesn't throw any errors it runs fine. But the grunt still throwing same error.
![screenshot_2](https://cloud.githubusercontent.com/assets/2740161/11397603/cef35e4c-938b-11e5-811e-bfccfb6d0f5b.png)

**Comment by bago** [comment]
remove the project.
download it again.
do "npm cache clean"
then "npm install" and "npm update" in a loop until both of them returns no error.
once all of this work, run "grunt".

Unfortunately npm is not very solid and whenever a download breaks it doesn't recognize this and leave "garbage" around, breaking everthing in the most weird ways.

**Comment by sanjaymv** [comment]
Hi

Yes i did , like that last days am doing it many times , npm update doesn't have any issues so far. But is really sad i can't see the script working n my local machine :(

**Comment by bago** [comment]
You can try unistalling node.js and reinstalling and look in your home directory to remove npm npm-cache folders (%user%/AppData/roaming/npm*).

**Comment by bago** [comment]
I just set up Travis to build mosaico on different node.js versions:
https://travis-ci.org/voidlabs/mosaico

Travis doesn't provide Node 5.1, but until 4.1 it is able to build and test Mosaico correctly.

I also did some fixes to the build so Travis was happy to build it.

Please try again from scatch and if it doesn't work, downgrade node to one of the versions that travis shows in green (0.11 <= node version <= 4.1)

**Comment by bago** [comment]
No updates since my last suggestions, I'm closing this. Please reopen if you run the other tests (full cleanup or full cleanup + node downgrade)
