### ISSUE TITLE
Cannot drag and drop images after html download.

### ISSUE THREAD

**Issue by ramachandranvenkat** [voidlabs/mosaico#490]
I create template with some blocks and images.
once i download to html again i try to do drag and drop of images (insert/update).
I do get error in the browser console as

Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
I think it's because of jquery, is there any way to fix this issue?

**Comment by bago** [comment]
I don't understand the issue. Are you working on mosaico.io on your locally deployed mosaico with unchanged sources or what else?

What browser/OS are you on? Does it happen on mosaico.io? Does it happen with a different browser?

**Comment by ramachandranvenkat** [comment]
yes, i am working with mosaico,
I drag and drop some images to template and save it. 
the next time if want to do drag image over the block i do get error and image get moved to corner of the gallery. 

![image](https://user-images.githubusercontent.com/16936469/49513085-db7d6f80-f8b5-11e8-89ca-a20ed1911b1a.png)

see the purple colored box image, 
i am trying to drop it, but its sits on the top left side of the gallery and i get error as below. 

![image](https://user-images.githubusercontent.com/16936469/49513200-3747f880-f8b6-11e8-98a5-3d016e235d98.png)

**Comment by ramachandranvenkat** [comment]
yes, it's because of our custom code.. 
it's working fine in mosaico. 
I am trying to implement text block similar to uploaded image block, when i drag and drop text block it's should replace the existing block's text. 
can you guide me  how and where should i alter the code? 
or is there any plugins available? 

Thanks.

**Comment by ramachandranvenkat** [comment]
@bago do you have any thoughts regarding custom text blocks?

**Comment by bago** [comment]
I can't help with custom code: where's your repository? 

"The binding 'extdroppable' cannot be used with virtual elements" is clear: you can't use the extdroppable binding on a virtual element but only with real elements. I guess you used it in some element that is translated to virtual in the code. If you are on data-editable you can have a look at the code handing elements with that attributes.

**Comment by ramachandranvenkat** [comment]
thanks
