### ISSUE TITLE
Gallery File Manager

### ISSUE THREAD

**Issue by barryflam** [voidlabs/mosaico#492]
Hi, your online demo has a file manager pop up when you click the gallery icon on an image.

This functionality doesn't appear to be on the version I downloaded from github. Am I missing something?

Thanks

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico#live-demo
It's provided by MoxieManager, a commercial software that can be integrated only with the commercial version of Mosaico because of licensing issues.

**Comment by barryflam** [comment]
Thanks :)
