### ISSUE TITLE
Retina Images

### ISSUE THREAD

**Issue by barryflam** [voidlabs/mosaico#494]

**Comment by barryflam** [comment]
I'm using img.src to load in an image. The dimensions are 215x143 but I want to pull in an img of size 480x319 so they look better when they go responsive.

The placeholder img is generated from the width and height. But I would like it to display the actual img dminesions.

Is this possible? Thanks

**Comment by bago** [comment]
one option could be to alter your backend so to ignore the requested sizes and provide bigger images.
