### ISSUE TITLE
Change color of outline when dragging block

### ISSUE THREAD

**Issue by barryflam** [voidlabs/mosaico#495]
Could you tell me where I can update the color of the red outline when you drag a block.

**Comment by bago** [comment]
Look for the .isdragging class and the makeDroppable mixin: the 2px dashed outline uses the @mosaico-selection-color variable.

**Comment by barryflam** [comment]
I'm looking for the red outline from the below screenshot.
![red-outline](https://user-images.githubusercontent.com/38406748/50685369-d45e9400-1010-11e9-88b4-5593028cc2c0.png)

**Comment by bago** [comment]
Have a look at the sortable-placeholder class (just add the sortable-placeholder  to an "editable block" div and you'll be able to see it and debug with your inspector.

**Comment by barryflam** [comment]
Perfect thanks that worked!
