### ISSUE TITLE
image upload error

### ISSUE THREAD

**Issue by Stozen-spb** [voidlabs/mosaico#496]
Hello. I'm trying to install mosaico to ubuntu. And when I start to upload image I get this error:

`Running "watch" task
Waiting...
(node:7639) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
events.js:193
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '.tmp/upload_2942a0c59723d6c5f8c9fca408eab313'
Stopping Express server
`

**Comment by Stozen-spb** [comment]
![_004](https://user-images.githubusercontent.com/28354688/51121228-faaddc00-1827-11e9-9cbd-76e99e5ffc0f.png)

**Comment by Stozen-spb** [comment]
I just create tmp folder in mosaico root and all works.

**Comment by luxlux** [comment]
this have not worked for me.

Error was:

> TypeError: os.tmpDir is not a function
>     at new IncomingForm (/Users/lutz/mosaico-master/node_modules/formidable/lib/incoming_form.js:29:41)
>     at UploadHandler.post (/Users/lutz/mosaico-master/node_modules/jquery-file-upload-middleware/lib/uploadhandler.js:68:20)
>     at /Users/lutz/mosaico-master/node_modules/jquery-file-upload-middleware/lib/filehandler.js:48:25
>     at Layer.handle [as handle_request] (/Users/lutz/mosaico-master/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/Users/lutz/mosaico-master/node_modules/express/lib/router/index.js:317:13)
>     at /Users/lutz/mosaico-master/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/Users/lutz/mosaico-master/node_modules/express/lib/router/index.js:335:12)
>     at next (/Users/lutz/mosaico-master/node_modules/express/lib/router/index.js:275:10)
>     at urlencodedParser (/Users/lutz/mosaico-master/node_modules/body-parser/lib/types/urlencoded.js:100:7)
>     at Layer.handle [as handle_request] (/Users/lutz/mosaico-master/node_modules/express/lib/router/layer.js:95:5)


So the error is cased by a call of "os.tmpDir" which is deprecated in the node module "formidable". now "os.tmpdir" is correct.
A very old version of formidable was installed from the installer.

**My Solution was:**
In "package.json" of mosaico, i have added "formidable" in the newer Version 1.2.2 as direct dependency. 


```
 ....
  "dependencies": {
    **"formidable": "^1.2.2",**
    "blueimp-canvas-to-blob": "3.27.0",
....
```

then i started the install again with: 
`npm install`

now it works!
