### ISSUE TITLE
broken images node

### ISSUE THREAD

**Issue by milancxe** [voidlabs/mosaico#497]
Hello,
I have issue with images.
When I run mosaico in local, everyhing works fine (I use node backend with grunt on ubuntu and imagemagick v7)
When I run mosaico on server, I use the same settings. So with node and grunt. Imagemagick is installed v7. ( I checked versions of imagemagick with convert --version)
But on server I have some odd behavior.
Placeholders are broken, and images are not working correctly.

I have read documentation and issues that I found related to this problem, but I am not sure what went wrong...

Do you maybe have a hint for me why would I have this behaviour?

Thanks!

See image:
![broken placeholder](https://user-images.githubusercontent.com/5347328/51320524-6b3f3d80-1a60-11e9-926e-195134db1557.png)

**Comment by bago** [comment]
Javascript console? Browser "network tab" log? "grunt" console outputs?

**Comment by SoftwareAssassin2000** [comment]
I am having this same issue. I see that it's because the image URL is pointing to:
http://localhost/img/?method=placeholder&params=...

Instead of pointing to:
https://mosaico.io/srv/f-insbkau/img?method=placeholder&params=...

I'm using `template-versafix-1.html`. When I check the template file I see the URL correctly pointing to the Mosaico.io URL:

```html
<tr><td width="100%" valign="top" align="center" class="links-color"><!--[if (lte ie 8)]><div style="display: inline-block; width: 166px; -mru-width: 0px; -ko-width: @[imageWidth]px"><![endif]--><a href="" data-ko-link="image.url"><img alt="" border="0" hspace="0" align="center" vspace="0" style="vertical-align:top; height: auto; margin: 0 auto; color: #3f3f3f; font-size: 13px; font-family: Arial, Helvetica, sans-serif; -ko-font-size: @[longTextStyle.size]px; -ko-color: @longTextStyle.color; -ko-font-family: @longTextStyle.face; -ko-attr-alt: @[image.alt == '' ? null : image.alt]; width: 100%; max-width: 166px; -ko-attr-width: @[imageWidth]; -ko-max-width: @[imageWidth]px; height: auto" data-ko-editable="image.src" width="166" data-ko-placeholder-height="130" src="https://mosaico.io/srv/f-default/img?method=placeholder&params=166%2C130"></a><!--[if (lte ie 8)]></div><![endif]--></td></tr>
```

I noticed a method in `converter-spec.js` called `templateUrlConverter`. I thought it may be the culprit but it appears not to be tampering with the URL:

```js
var templateUrlConverter = function(url) {
  return url;
}
```

I will continue to post if I learn more. Any help would be appreciated.

**Comment by SoftwareAssassin2000** [comment]
Console shows the following when the page loads:

```txt
Refused to apply style from 'http://localhost/rs/mosaico-libs.min.css?v=0.17.4' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
jquery-migrate.min.js:33 JQMIGRATE: Migrate is installed, version 3.0.1
editor.html?0.17.4:1 Refused to apply style from 'http://localhost/rs/mosaico-libs.min.css?v=0.17.4' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

Networking tab shows in red the same file mentioned above in the console: `http://localhost/rs/mosaico-libs.min.cs`. All the other requests appear to be responding with 200 OKs. When I copy that URL to the browser it responds with "Cannot GET /rs/mosaico-libs.min.cs".

**Comment by bago** [comment]
Javascript console? **Browser "network tab" log? "grunt" console outputs?**

**Comment by SoftwareAssassin2000** [comment]
Browser console and network tab output shown above. I get this output from grunt console every time I start it - not sure if it's related:

```txt
ImageMagick failed to run self-check image format detection. Error: Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%m" "" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (D:\src\IW\system\web-portal\node_modules\gm\lib\command.js:232:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.cp.emit (D:\src\IW\system\web-portal\node_modules\gm\node_modules\cross-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
```

**Comment by milancxe** [comment]
On backend I had no issues, no error output. similar on frontend. 
I have resolved this issue with reinstalling Imagemagick... not sure what was the problem since convert command worked for me...
