### ISSUE TITLE
Issue while uploading images in my localhost

### ISSUE THREAD

**Issue by godara-ravi** [voidlabs/mosaico#499]
Hi there,

I am facing the issue while uploading an image in my localhost. Maybe i am not using exact path but i am not sure about it. In console i am getting the error while uploading an image like this: 

- http://localhost/contaqt2/dragDropEditor/default/upload/ 404 (Not Found)
- viewmodel.js:3 fileuploadfail T.Event {type: "fileuploadfail", timeStamp: 1548408888657, jQuery33103597507562201463: true, target: input.fileupload.nofile, isTrigger: 3, …} {disabled: false, create: null, dropZone: a.fn.init(1), replaceFileInput: false, singleFileUploads: true, …}
![upload_issue](https://user-images.githubusercontent.com/47026411/51738021-25afef80-20b4-11e9-8076-58cca7858cc1.PNG)

**Comment by bago** [comment]
Either you didn't deploy a backend at that URL or you didn't configure the backend url in the Mosaico initialization.

**Comment by godara-ravi** [comment]
I didn't start "grunt" but all are working fine, just image uploading not
working. So, should i need to run command "grunt" or without this it will
working fine?

*Regards,*
Ravi Kumar
Web Developer

**Comment by bago** [comment]
Well, uploading is something that needs a backend. 
If you don't use the development backend (that is started at the end of the "grunt" command) then I guess you're using your own backend. Either it is broken or it is misplaced/misconfigured.

https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico

**Comment by godara-ravi** [comment]
@bago yes, there was issue with backend configuration. I am using my own php backend.
Thanks for sorting this out!
