### ISSUE TITLE
Update created template

### ISSUE THREAD

**Issue by godara-ravi** [voidlabs/mosaico#501]
@bago i created a template using mosaico and saved into mysql database correctly. Now, i want to update that saved template which is stored in mysql. Is this possible or anywhere documented it is? If yes, please let me know. I really need to update my created templates.

Thanks!

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/wiki/Saving-and-Loading

**Comment by godara-ravi** [comment]
@bago yes. Thanks for updating this!
