### ISSUE TITLE
Question: images with rounded corners

### ISSUE THREAD

**Issue by wdecraene** [voidlabs/mosaico#504]
Is it possible (without patching) to extend processImg with a function to do some extra stuff with images during upload (eg. add rounded corners to images)? Just like processImg:resizeImage(), but then something like addRoundedCorners() ?

**Comment by bago** [comment]
Not without patching. Mosaico expect to work with a "simple" backend supporting simple crop/resize, so it doesn't give you a way to ask for something more complex than this (because people have their own backend and we don't want to put complex thing there).
