### ISSUE TITLE
Invalid email when I try to put more than 1 email address

### ISSUE THREAD

**Issue by Samuraty** [voidlabs/mosaico#506]
Hi, Is It possible to send the template to different users at the same time? 
Mosaico uses nodemailer : "to - Comma separated list or an array of recipients email addresses", but when I try to send it I can just put one email (if I write more I get an error). 

Many thanks.

**Comment by bago** [comment]
This is delegated to the backend. The development backend is just a development backend not meant to be used in production. The library itself doesn't have this limitation (as you can see on mosaico.io where the library is used against a production backend).

**Comment by Samuraty** [comment]
Thank you, I finally solved my problem :)
