### ISSUE TITLE
how to make local style as default instead of global styles.

### ISSUE THREAD

**Issue by ramachandranvenkat** [voidlabs/mosaico#507]
How / where can we alter the style display, 
I need local style should be default instead of global style. 

please let me know where to alter these functionality.

**Comment by bago** [comment]
IMHO it makes no sense in usability: if you start with "local" then the global won't work the way the user could expect (how could it work?)

That said, if you want to play, maybe you can have a look at model.js and replace the 2 "`customStyle=false`" with "`customStyle=true`". Never tested it, but sounds like the only place where we set a default. Let us know.

**Comment by ramachandranvenkat** [comment]
Thanks @bago it's works perfect.

**Comment by bago** [comment]
Let us know if you decide to keep it that way and if your users understand it or not. I decided not to make an option for the default because in our test the UX was not fine, but I'm interested in other experiences.
