### ISSUE TITLE
How to configure mosaico in angular 7 ?

### ISSUE THREAD

**Issue by NILJDV** [voidlabs/mosaico#509]
Can I configure mosaico in angular 7 ? I am trying to configure mosaico in angular 7 but unable to import it. type class issue.

**Comment by bago** [comment]
Mosaico is a fullpage app, just open it in its own window.  It's not meant to be integrated with other stuff in the page: maybe you can make it work this way, but you'll have to put your hands in the code and understand knockoutjs.
