### ISSUE TITLE
Embedded mosaico?

### ISSUE THREAD

**Issue by esteban-turnocheck** [voidlabs/mosaico#510]
Hi! Thanks for this great work! I've found it two days ago and totally loved it.
I have been digging and fiddling around into the source.
I've managed to serve the backend with my app (CodeIgniter/MySQL), but I can't find a way to achieve a visual integration into my app as I could do with, say, TinyMCE.
Is it that Mosaico only runs standalone? 
I'd like to acomplish something like 
![image](https://user-images.githubusercontent.com/22857390/54859103-1205bb80-4ce8-11e9-91bc-c1bf80fb748a.png)

Can it be done with mosaico? If not, any suggestions?
Thanks a lot!

**Comment by bago** [comment]
Mosaico is a full page application. Put it in a big enough iframe so it's like it is standalone.
