### ISSUE TITLE
Nested containers / blocks

### ISSUE THREAD

**Issue by bures** [voidlabs/mosaico#511]
I wanted to create a translation from MJML to Mosaico for the new Mailtrain (v2 beta), but now I hit the problem that I would need to create nested blocks.

Is there any option to have a block that defines a container inside (and in it other blocks)?

The use-case for this is a block that does two columns. Each column should be a container so that multiple blocks (each being image and text) could be dropped into it.

Thanks. T.

**Comment by bago** [comment]
Nested containers requires major changes to mosaico core, so unless you are ready to learn how mosaico internals works and work on it, the answer is that you currently can't do that and there are no plans to do that.

Please have a look at this repository for something related to Mosaico and MJML:
https://github.com/witzig/mjml-mosaico

PS: versafix-template (the master template bundled with mosaico) gives you much better email client compatibility/support than what MJML can do. Of course versafix doesn't have the flexibility of MJML. I don't see mosaico the best tool to "edit MJML": if you want a visual tool to edit MJML maybe GrapeJS by @artf is a better tool for the job ( https://github.com/artf/grapesjs-mjml )
