### ISSUE TITLE
can it be integrated with a VueJS app?

### ISSUE THREAD

**Issue by ashishkumar-ui** [voidlabs/mosaico#517]
I have a vue app which send the emails . I would like to use this for email editor part. is it feasible to do this?

**Comment by Hiswe** [comment]
@ashishkumar-ui Mosaico is a standalone web application made with Knockout. 
There is no reasons to integrate it inside a Vue app (no shared model, components, etc.)
Just serve it outside your Vue App.

You can find more information here (not same framework but same thing):

- #515 
- #509
