### ISSUE TITLE
Where are block IDs generated

### ISSUE THREAD

**Issue by louis71barker** [voidlabs/mosaico#521]
Hi, does anyone know which file is used to generate the block ids when a block is dragged in? im trying to pickypack this process with some custom guid for our editor and for the life of me i can not figure out where the IDs are generated when the block is dragged in? or any function that is called when a block is dragged in. Any help would be super appreciated

**Comment by bago** [comment]
This is the answer for 0.17.5 and previous releases (current head and future releases may change this).

You have to understand KnockoutJS first.

Block IDs are generated mainly by the "uniqueid" knockout binding: https://github.com/voidlabs/mosaico/blob/v0.17.5/src/js/bindings/virtuals.js#L7

The "uniqueid" binding is added by the parser while parsing the master template and generating block templates: https://github.com/voidlabs/mosaico/blob/v0.17.5/src/js/converter/parser.js#L35

Sometimes (when a bunch of blocks are inserted at bulk via custom methods or via undo/redo of bulk blocks operations, but they shouldn't happen in "normal" 0.17.x use cases) they are generated elsewhere:
https://github.com/voidlabs/mosaico/blob/v0.17.5/src/js/viewmodel.js#L166
https://github.com/voidlabs/mosaico/blob/v0.17.5/src/js/converter/wrapper.js#L274
