### ISSUE TITLE
Enhancement - Add Image Caption Field to Blocks Content

### ISSUE THREAD

**Issue by danfish** [voidlabs/mosaico#523]
Would be useful to have an image caption field in the content section of blocks with images.  Is there a work-around to adding a caption to an image?

Thanks for a great tool.

**Comment by bago** [comment]
Mosaico doesn't know anything about images, captions: this is a master template decision. versafix-1 master template (the master template we offer/bundle with mosaico) doesn't use/expose a caption, but another master template could provide that feature.

We don't plan to add image captions in that master template.
