### ISSUE TITLE
Overriding editor.js

### ISSUE THREAD

**Issue by digitaldots** [voidlabs/mosaico#526]
Hi,

Other than editing the editor.js code, is there a way to override the _propEditor variable?

In particular, I'd like to change the HTML outputted on lines 218 to 225 but would prefer not to change the source file.

I can amend widgets but this looks to be outside that?

Many Thanks,

S

**Comment by bago** [comment]
That's not a widget so you can't override it. THat 5 lines of code works in "coordination" with many other lines of code in other files. What are you trying to do? Why are you trying to change that?

Please show your use case and publish your fork: here I help other developers working in the "open".

**Comment by digitaldots** [comment]
Hi Bago,

Thanks for the quick response.

As before, I'm just looking at altering the front-end UI a little.

Yes, will publish my fork shortly.

S
