### ISSUE TITLE
Using Mosaico html on wordpress

### ISSUE THREAD

**Issue by trgolden3** [voidlabs/mosaico#528]
I am no programmer but am a happy user of Mosaico via Mailtrain.  It does a great job of formatting our newsletters and makes it attractive and easy.  I want to put the newsletters on our web site which is a Wordpress site.  I can use the html from Mosaico which works perfectly in a browser but when I try and use the same code in a Wordpress post it works...but it leaves sections of shaded grey interspersed throughout the content and makes things considerably less attractive. It looks like shading from html tables and I tried editing them a bit but with little success.  One solution would be to simply create two documents, one from Mosaico and the other using the same images and text in a new Wordpress post.  That solution is not that efficient and I wondered if anyone here might have some ideas about how to use the Mosaico files in a Wordpress post?  Thanks for any help!

Tom
<img width="1071" alt="Screen Shot 2019-06-30 at 8 49 59 PM" src="https://user-images.githubusercontent.com/52388538/60404624-b9607d00-9b78-11e9-96f9-efa15e9888a5.png">

**Comment by bago** [comment]
Mosaico output is **full page** HTML **optimized for email**. Wordpress doesn't accept HTML as is as post content, so you should ask this question is a wordpress forum, this is not something Mosaico can fix/workaround.

If you can, use an `iframe` tag, but I'm not a wordpress user, so I can't really help here.

**Comment by trgolden3** [comment]
Thanks for your response.
