### ISSUE TITLE
Saved Sessions Lost

### ISSUE THREAD

**Issue by itfcomp** [voidlabs/mosaico#530]
I have reinstalled Windows, and since then I seem to have lost my saved Mosaico sessions, and therefore my saved templates.

How do I get these back?  Is this related to a windows reinstall?

Thanks!

**Comment by bago** [comment]
If you're talking about mosaico.io DEMO, please note that's just a DEMO and what you do is stored in your browser. So if you change browser or reinstall the browser you loose your work.
