### ISSUE TITLE
Unnecessary font face declaration?

### ISSUE THREAD

**Issue by loker** [voidlabs/mosaico#532]
https://github.com/voidlabs/mosaico/blob/6225f4d1a2056fced024d185c493c9aafc18d589/templates/versafix-1/template-versafix-1.html#L606

Hi, I'm trying to create a new template and I'm using the versafix as a base/learning template. I noticed that some of the links of the images have font preferences even though they don't have any text content in the output. Maybe clearing these unused parts would be useful... Or am I missing something? :)

**Comment by bago** [comment]
1) This is not a mosaico issue but a versafix-1 master template issue
2) Yes, you're missing things: email clients are weird and declaring the right size in td with images is a good thing. We tested hundreds of email clients, don't ask me which one wanted that :-)
