### ISSUE TITLE
Runnig "watch" task

### ISSUE THREAD

**Issue by spyrek77** [voidlabs/mosaico#535]
![mosaico grund](https://user-images.githubusercontent.com/53329149/61929953-bc366e00-af7c-11e9-99de-32b53f0c2a23.jpg)

**Comment by dvlpr-shivendra** [comment]
It's not an issue. It's grunt watching any changes in the source. You can visit localhost on port 9006 on your machine and if you make any changes to the source code of mosaico grunt will update the output files.
