### ISSUE TITLE
how to add new block of 600*600 ?

### ISSUE THREAD

**Issue by huzaifa4725** [voidlabs/mosaico#536]
I am new user. I want to add new block into exisiting template .
I have added template-versafix.html. 
I copied the image block twice and changed width and height and image src but its not showing me new block with new image source.
Its showing me twice blocks with same thumbnail although second imageblock source is different
?
Have a look here http://prntscr.com/ol49jj

**Comment by bago** [comment]
1) Each block must have an unique name
2) The thumbnail shown on on the left is just an image you have to provide on your own or you can generate using some library (see https://github.com/voidlabs/versafix-template for this)
