### ISSUE TITLE
add dynamic input field

### ISSUE THREAD

**Issue by godara-ravi** [voidlabs/mosaico#538]
Hi @bago 

I want to add dynamic input fields in block. Could you please help me in this, how can i achieve it?

Thanks in advance!

**Comment by godara-ravi** [comment]
I already created a block with input field but i want create dynamic form which has input fields, checkbox, textarea and radio button etc. Please check this ASAP and let me know if it is possible. Thanks!
![form_block](https://user-images.githubusercontent.com/47026411/62352507-f0360400-b525-11e9-8c48-5d140d099e12.PNG)

**Comment by bago** [comment]
The current template language only let you have "sortable blocks". Inside a single block you can only deal with visibility flags (conditioned content), but you can't have elements to be added at user will.
