### ISSUE TITLE
Help: Saved templates disappeared

### ISSUE THREAD

**Issue by kianae** [voidlabs/mosaico#542]
Hello,

I have been reusing the same template I built out for the newsletter. Today the saved templates I had were gone. Are there updates that get made that would cause me to lose the templates? Can I upload one I'd downloaded before?

**Comment by bago** [comment]
What's your mosaico setup?

If you are talking about the DEMO on mosaico.io website, then it is just a DEMO and your templates are stored in your browser using a "localstorage" API. If you move to another browser or clean browser data you delete your saved data.

**Comment by bago** [comment]
No answers, closing.
