### ISSUE TITLE
Broken images in Mosaico

### ISSUE THREAD

**Issue by barbar72** [voidlabs/mosaico#546]
hello,

I'm french, so sorry for my poor langage :(

I have just installed mosaico 0.16 in my PC and when I drag and drop a picture to my mosaico's project, the picture display broken.

grunt console => no error
navigator (firefox) => no error (200)

ImageMagik is Ok (with legacy)

versions :
- node => 10.5.0
- grunt-cli v1.3.2
- grunt v1.0.4

![2019-10-18 12_39_18-Clipboard](https://user-images.githubusercontent.com/56722213/67088020-6a306d80-f1a4-11e9-90dd-acf6a9534f0e.jpg)
![2019-10-18 12_40_26-grunt](https://user-images.githubusercontent.com/56722213/67088063-86cca580-f1a4-11e9-925c-27c5d25ae90e.jpg)

![2019-10-18 12_41_44-D__temp](https://user-images.githubusercontent.com/56722213/67088143-ba0f3480-f1a4-11e9-8a1a-0ca532edc35a.jpg)

Is somebody can help me, please ?

**Comment by bago** [comment]
Why are you testing Mosaico 0.16 ?
Can you check 0.17.5 ? https://github.com/voidlabs/mosaico/releases/tag/v0.17.5

**Comment by barbar72** [comment]
I try to install 0.17.5
"npm init" to create the package.json
I don't know what information to do in, then I download a "package.json" at this place : https://github.com/voidlabs/mosaico/find/master
And take it for my mosaico project.

npm install
npm install -g grunt-cli
npm install grunt --save-dev

but when I do "grunt -v" here is the result :
> ...
Registering "tasks" tasks.
Tasks directory "tasks" not found.
...
Running "jshint:all" (jshint) task
Verifying property jshint.all exists in config...OK
Files: Gruntfile.js -> all
Options: force=false, reporter={}, reporterOutputRelative, sub, jshintrc, browserify
Gruntfile.js
  line 1   col 1   Use the function form of "use strict".
  line 2   col 12  'require' is not defined.
  line 5   col 3   'require' is not defined.
  line 30  col 19  'require' is not defined.
  line 60  col 11  'require' is not defined.
  line 63  col 11  'require' is not defined.
  line 4   col 1   'module' is not defined.
  ‼  7 warnings
Warning: Task "jshint:all" failed. Use --force to continue.
Aborted due to 
warnings.

**Comment by bago** [comment]
If you want to build, download the 0.17.5 source code from https://github.com/voidlabs/mosaico/archive/v0.17.5.zip . The package.json is there.

**Comment by barbar72** [comment]
YES.
thank you bago !
I installed with your link
- npm init
- npm install
- npm audit fix
- npm install -g grunt-cli
- npm install grunt --save-dev
- npm audit fix
