### ISSUE TITLE
package.json devDependencies are not use properly

### ISSUE THREAD

**Issue by benj0c** [voidlabs/mosaico#547]
First of all, we should clarify:
`dependencies` are required to run, `devDependencies` only to develop, e.g.: unit tests, CoffeeScript to JavaScript transpilation, minification, etc. `devDependencies` are also installed on `npm install` in a directory that contains package.json, unless you pass the --production flag.

If we agree on that, there is list of npm packages needs to be moved from `devDependencies` to `dependencies`:

- async
- body-parser
- connect-livereload
- express
- gm
- jquery-file-upload-middleware
- lodash
- nodemailer

**Comment by bago** [comment]
We consider the "backend" a "development backend" and not a part of the final product (a client side javascript library).

So, those libraries are needed only during development.

**Comment by bago** [comment]
In fact, if you download the "binary releases" you won't find the development backend nor the libraries you cited.
