### ISSUE TITLE
HOW TO CHANGE THE BLOCKS OF MOSAICO FOR NEW ONES?

### ISSUE THREAD

**Issue by pcajoao** [voidlabs/mosaico#549]
Im a new user. 
I notice that the blocks loaded in mosaico are simple .png files.
the replacement fo this .png for new ones solve my problem??

sorry for the poor language.

**Comment by bago** [comment]
Here is the project we use to create the versafix-1 template/block HTML definitions and also to create their PNG thumbnails:
https://github.com/voidlabs/versafix-template
