### ISSUE TITLE
mosaico posts invalid html to backend/dl

### ISSUE THREAD

**Issue by bwl21** [voidlabs/mosaico#55]
Playing with https://github.com/ainterpreting/mosaico-php-backend/issues/6 revealed that mosaico posts invalid html to the backend /dl. In line 3 the attribute http-equiv occurs twice which is not allowed in SGML/XML/HTML.

```html
action:download
filename:email.html
html:<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" http-equiv="Content-Type">
    <meta name="viewport" content="initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <title>TITLE</title>
...
```

**Comment by bago** [comment]
Which browser did you use? There are differences in the generated html depending on the browser (and sometimes on the template, too).

I had to add a workaround because sometimes the http-equiv was wiped by the browser, so maybe there are cases where it is now duplicated...

**Comment by bwl21** [comment]
I used chrome.

**Comment by bago** [comment]
OK, reproduced it: both the Styliner and our php proprietary inliner was not complaining and, instead, they was fixing it by removing one of the 2 attributes, silently.

**Comment by bago** [comment]
Fixed it! Thank you for reporting! :-)
Hope you can you the "new" inliner, now!

**Comment by bwl21** [comment]
I tried it but the problem is still there. I merged mosaico/master into my feature branch, did a grunt build and copied the result to my webserver. but I still get the same messages.
