### ISSUE TITLE
A video tutorial on how to set up mosaico

### ISSUE THREAD

**Issue by ShetDarshan** [voidlabs/mosaico#550]
A small video tutorial on how to set up the email template will be very helful .

**Comment by bago** [comment]
It's not clear if you are proposing a tutorial to use the editor, to create a master template, to run mosaico demo, to run a development environment, to integrate mosaico or what else.

BTW, we don't plan creating video tutorials (mosaico is targeted to developers and most developers looks for docs, not videos), but contributions are always welcome.
