### ISSUE TITLE
How to integrate Mossaico Email Builder with Angular 8 Project

### ISSUE THREAD

**Issue by preeti12** [voidlabs/mosaico#552]
Hi, 

I have to create Mosaico Email Template Builder project along with Angular 8 project for a requirement. 
Please let me know how to merge Mosaico Email builder project with Angular 8 Project.

Thank you.

**Comment by preeti12** [comment]
@bago pls assist

**Comment by bago** [comment]
Please make sure you search throught previous issues before you open new one, otherwise we'll close them with no answers.

https://github.com/voidlabs/mosaico/issues?utf8=%E2%9C%93&q=angular
