### ISSUE TITLE
Mosaico version update

### ISSUE THREAD

**Issue by preeti12** [voidlabs/mosaico#553]
Currently, email editor application is using Mosaico 0.16.  We have email templates designed/developed using using Mosaico version 0.16.
Now, We are planning to upgrade Mosaico Version to the latest one i.e. version 0.17.5.
Will this code upgrade affect earlier email templates developed using Mosaico 0.16.
Please assist
{
  "name": "mosaico",
  "version": "0.16.0",
  "description": "Free Email Template Editor",
  "main": "./src/js/app.js",
  "directories": {
    "test": "test"
  },

**Comment by preeti12** [comment]
@bago pls assist

**Comment by bago** [comment]
They should be compatible: if you see issues with upgrading then report them.
