### ISSUE TITLE
Conditional Blocks with Mosaico

### ISSUE THREAD

**Issue by preeti12** [voidlabs/mosaico#555]
Create email template with multiple blocks and the the display of those would be based on some parameter value.
if(condition == true){
"display textBlock"
}else if(condition2 == true){
"display imageBlock"
}else{
"Display textImageBlock"
}

**Comment by bago** [comment]
Look at versafix master template: 
`<div data-ko-display="preheaderVisible" data-ko-wrap="false">`
https://github.com/voidlabs/mosaico/wiki/Template-language#data-ko-attributes

PS: I'm not sure if this is the same of #556 or something different.
