### ISSUE TITLE
conditional mo-display-state property

### ISSUE THREAD

**Issue by preeti12** [voidlabs/mosaico#556]
How to manage "data-mo-display-state" property with some parameter
Steps: 
1. set value from mosaico content panel 
2. process values at parser.js 
3. conditionally display block

is that possible with Mosaico Builder?

**Comment by preeti12** [comment]
@bago pls assist

**Comment by bago** [comment]
I didn't understand your ticket.

There is a data-ko-display="condition" property that will hide or show an html content depending on the declared condition.
https://github.com/voidlabs/mosaico/wiki/Template-language#data-ko-attributes

PS: Please stop tagging me or anyone else you don't know in your issues (this won't raise the priority or visibility of your issues). If you need priority support we provide support as part of our commercial offer (https://mosaico.io/commercial/). Thank you!
