### ISSUE TITLE
Is Mosaico supported on IE11??

### ISSUE THREAD

**Issue by preeti12** [voidlabs/mosaico#557]
Created template using Mosaico.io on try session for french language using IE11.
French characters do not get displayed properly in preview/downloaded file. As it removes Meta charset tag when saved from IE browser.

When created and saved same template file using chrome it adds Meta charset tag and everything works fine. 
Please update if Mosaico supports IE11 or not? 
Please refer  @attached
![Chrome_screenshot](https://user-images.githubusercontent.com/1849921/71719943-efdbc500-2e45-11ea-9ef2-832d271880df.png)
![IE_error](https://user-images.githubusercontent.com/1849921/71719944-efdbc500-2e45-11ea-8026-37277e719acd.png)

 file.

**Comment by preeti12** [comment]
@bago @eric-void

**Comment by bago** [comment]
Thank you for reporting. We just reproduced the issue: sounds like IE11 strips the charset meta tag from the template.
