### ISSUE TITLE
Can't show context help tooltip

### ISSUE THREAD

**Issue by pshenichnikov** [voidlabs/mosaico#558]
Hi,
There is the context help tooltip on the demo mosaico site. But I don't have this tooltip in my mosaico installation. Please advise how to show this tooltip.
![Selection_073](https://user-images.githubusercontent.com/6286115/71770464-c30ad900-2f3d-11ea-99b3-16b8b69af83a.png)

thanks!

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico#live-demo

> On https://mosaico.io you can see a live demo of Mosaico: the live deploy has a custom backend (you don't see it) and some customization (custom Moxiemanager integration for image editing, customized onboarding slideshow, **contextual menu**, and some other small bits), but 95% of what you see is provided by this opensource library. You will also see a second working template there (versafluid) that is not part of the opensource distribution.
