### ISSUE TITLE
Having trouble with UTF-8 special characters

### ISSUE THREAD

**Issue by bwl21** [voidlabs/mosaico#56]
If the template or my email contains special characters such as öäü ® etc. the HTML string delivered to the backend has wrong encoding. This happens regardless if the template has the special characters or if the email author entered these.

It is hard for me to find out, where the issue comes from:

* mosaico doing the post without denoting that UTF-8 (see http://stackoverflow.com/questions/4902062/php-form-submit-utf8)
* mosaico-php-backend
* my server configuration

Wherever it is, If I observe the HTML in a php debugger (intelliJ Idea), the special characters are show as ` ��� `

I tried with mosaico.io, but there it works. 

Any hint is welcome.

**Comment by bago** [comment]
The form is here, if you want to try adding the accept-encoding attribute: src\tmpl\main.tmpl.html 
Another thing you can do is to use html entities in the template.

My users always create contents in UTF-8 and it works fine, but the encoded chars are not in the template, but in their content (but this is submitted all together by mosaico in the same post, so I guess it is something else)

If you want to deal with UTF-8 the backend must use the mb* string functions and not the usual string functions.

You can use the network tab in your Chrome to see if the content posted by mosaico.io has the same encoding of the content posted to your own website.

**Comment by bwl21** [comment]
I tried with html entities in the template, but got the same result. I want to work in UTF-8 at all.

In chrome network tab, the content posted by mosaico looks not very different than the one from  my own website:

my site: it says that the content cannot be decoded even if the request header looks the same.

![screenshot_402](https://cloud.githubusercontent.com/assets/2022976/11422839/8d01f994-943f-11e5-860a-74004a9aff9a.jpg)

mosaico.io: the content is visible

![screenshot_401](https://cloud.githubusercontent.com/assets/2022976/11422842/91fc16c8-943f-11e5-8834-8b4860c8fae8.jpg)

**Comment by bago** [comment]
Make sure you apache is configured to default to utf8 and you php is configured to use utf8.
As you saw, mosaico.js has no issues dealing with UTF8.

**Comment by bwl21** [comment]
Chrome says that it cannot decode the value of Html - Field in the request. This made me think, that the issue is not on the server side.

this is from my phpinfo. Could this be the problem?

	Local Value	Master Value
iconv.input_encoding	ISO-8859-1	ISO-8859-1
iconv.internal_encoding	ISO-8859-1	ISO-8859-1
iconv.output_encoding	ISO-8859-1	ISO-8859-1

**Comment by bwl21** [comment]
It appears to me that I need in editor.html:

```html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
```
or

```html
<meta charset="utf-8" />
```
more detailes in http://stackoverflow.com/questions/4696499/meta-charset-utf-8-vs-meta-http-equiv-content-type

as InlineStyle uses PHP DOMDocument, i will take the long version for now.

I propose to add this line in mosacio as well.

**Comment by bago** [comment]
So, if I understand it correctly, this is needed when the web server does not default to UTF-8 when publishing contents (As I don't see any change in Node.js and on my "default" Apache Httpd 2.4 deployment.

**Comment by bwl21** [comment]
This is how I understand it. I tested it on three different Apache Installations (one of it was a out of the box Bitname mamp stack). I could not even find out what the default setting was. One comment on stackoverflow said, that Apache configuration needs to be set to UTF-8 in order to make the <meta ... change work.

But all the three sytems the change fixed the problem of this issue.

Thanks for changing it in your distribution.
