### ISSUE TITLE
How to link to docs in Mosaico template mailing

### ISSUE THREAD

**Issue by Stani-icomia** [voidlabs/mosaico#560]
Hello, I recently started putting my newsletters on mosaico template and love the flexibility and the look of it. However, I can't work out how to link to word or pdf docs. for example i want the button to read Download Full Report and link it to a pdf/or word doc. how do i do that?

thanks,
Stani

**Comment by bago** [comment]
I don't understand the question. You have to upload your document to some place and use its URL.
