### ISSUE TITLE
src of image not getting saved in exportHTML function.

### ISSUE THREAD

**Issue by uplsaurabhA** [voidlabs/mosaico#562]
Hi, 
I am saving uploading images for template to s3, and trying to save resulting html to show later. 
I have achieved saving the image via srcSetter (in wysiwyg.js ;  element.setAttribute('src', src) in img.onload), so that it displays correctly (alongwith src of element). But when i am trying to download the template, the resulting image doesn't have any src (the alt text is coming up fine though). Can you help me by pointing where i might be going wrong?. Thanks.

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/issues?utf8=%E2%9C%93&q=is%3Aissue+s3

**Comment by uplsaurabhA** [comment]
Found duplicate similar issue  #514 . Thanks
