### ISSUE TITLE
How to update block preview icon/ image in Mosaico

### ISSUE THREAD

**Issue by preeti12** [voidlabs/mosaico#568]
Block images are under Templates> edre >  .png images for each block. 
Block images are not updated also , for some blocks there are no images.
How rebuild preview icon/ images for blocks?

**Comment by bago** [comment]
Those images are data/sources for mosaico library. You have to provide them as part of the master template data. So, if you alter the master template it's up to you to alter those images. Mosaico simply expect one image for each template block.

The versafix-1 master template https://github.com/voidlabs/versafix-template includes some builtin tools to generate its own block images.
