### ISSUE TITLE
How does mosaico compute the image urls

### ISSUE THREAD

**Issue by bwl21** [voidlabs/mosaico#57]
I still do not really get how it works with the images. Main issue is how
the POST to dl works.

I observe in mosaico.io:

``` html
<img border="0" hspace="0" vspace="0"
width="166" class="mobile-full" alt="" style="vertical-align: top; 
width:100%; height: auto; max-width: 166px;"
src="http://mosaico.io/srv/f-fsbfkap/img?src=http%3A%2F%2Fmosaico.io%2Ffiles%2Ffsbfkap%2Fscreenshot_401.jpg&amp;method=resize&amp;params=166%2Cnull">
```
But on my servers I get:

```html
<img border="0" hspace="0" vspace="0" width="166" class="mobile-full" alt="" 
style="vertical-align: top; width: 100%; height: auto; max-width:166px;"
src="uploads/screenshot_402.jpg?method=resize&amp;width=166">
```

Therefore mosaico-php-backend does not compute static images for the requested sizes.

**Comment by bwl21** [comment]
Answer by Stefano

src/js/app.js, look for the way
"ko.bindingHandlers.wysiwygSrc.convertedUrl" is defined.

If you see "?method" this means mosaico thinks the "uploaded images" are not on the same server of the "image resizer".

Maybe the "listFiles" returns relative urls or their absolute urls doesn't match the image processor url.

Stefano

**Comment by bago** [comment]
e.g: You could replace that method to use an https://cloudimage.io account that will give you resized/covered images (and download them from your original url) automatically.
So you don't have to care about make them static.

**Comment by bwl21** [comment]
Thanks for this hint. I am currently fixing mosaico-php-backend such that the genration of static images etc. works.
