### ISSUE TITLE
VueJS integration help (Unable to process binding)

### ISSUE THREAD

**Issue by rusicsemenov** [voidlabs/mosaico#571]
Hello, i try implemet mosaico in my project on VUEJS whithout index.html and have arror 
> Unable to process binding "template: function(){return 'main' }"
> Message: Cannot find template with ID main

If i try use only editor.html and init whith template oprions all work perfct

```
var ok = Mosaico.init(
                    {
                        template:
                            "templates/versafix-1/template-versafix-1.html",
                        imgProcessorBackend: basePath + "/img/",
                        emailProcessorBackend: basePath + "/dl/",
                        titleToken: "MOSAICO Responsive Email Designer",
                        fileuploadConfig: {
                            url: basePath + "/upload/"
                            // messages??
                        }
                    },
                    plugins
                );
```

But if i init Mosaico in project i recive error `Unable to process binding` maybe i need some structure for mosoico?  Maybe i can select target div for generate mosaico
![Screenshot_2](https://user-images.githubusercontent.com/20163858/77407400-21ba5300-6dc7-11ea-9907-34c0f5d6e458.png)

**Comment by bago** [comment]
Mosaico expect to work on its own full page. Run it in an frame if you are not ready to deeply understand and refactor mosaico sources.
