### ISSUE TITLE
Allow using/editing pre-header text without showing the pre-header block.

### ISSUE THREAD

**Issue by MikeyMJCO** [voidlabs/mosaico#582]
It would be good to show the pre-header text and control that without needing to show/use the pre-header block with the unsubscribe links etc.

**Comment by bago** [comment]
Mosaico doens't define anything in this regard. It's all about the template. Versafix-1 works that way, but it should pretty easy to create a different master template so to change the behaviour.

**Comment by MikeyMJCO** [comment]
So as far as I can tell Mosaico will only allow editing a block that is visible?

**Comment by bago** [comment]
Mosaico will only let you edit something that will have an impact on the output. Editing a block that is not there would not change the HTML. The preheader block is not there if you don't enable it.

**Comment by bago** [comment]
BTW if you put something like this in the main body, (so you move this out of preheaderBlock if you use versafix-template) then your preheaderText will be always present in the email and its editor will always be shown in the Content sidebar:
```
      <div style="display: none; font-size:1px; line-height: 1px; max-height:0px; max-width: 0px; opacity: 0; overflow: hidden; 
          -ko-bind-text: @preheaderText"></div>
```
