### ISSUE TITLE
' or &rsquo; in css style for translation

### ISSUE THREAD

**Issue by GuillaumeSorel** [voidlabs/mosaico#583]
Hi,
in French we use a lot of simple quotes between words and I haven't succeeded in showing them in the template

imageHeight { label: Taille de l&rsquo;image; extend: height; } 

![image](https://user-images.githubusercontent.com/49272839/85747647-c0788780-b707-11ea-8df4-0efd05e9836a.png)

Is this possible and how ?

best regards,
Guillaume

**Comment by bago** [comment]
Put everything in single or double quotes (double if you want to use single without escaping), so:
```
imageHeight { label: "Taille de l’image"; extend: height; }
```
or
```
imageHeight { label: 'Taille de l\'image'; extend: height; }
```

**Comment by GuillaumeSorel** [comment]
Thanks for your answer bago,
this is what I get in the browser when using

imageHeight { label: 'Taille de l\'image'; extend: height; }

![image](https://user-images.githubusercontent.com/49272839/85839298-092d5080-b79b-11ea-87c0-5d0d3c344207.png)
and when using

imageHeight { label: "Taille de l’image"; extend: height; }

![image](https://user-images.githubusercontent.com/49272839/85839579-632e1600-b79b-11ea-96e4-5e62e34c54a8.png)

Both options are actually not satisfying.

Any ideas?
best regards,
Guillaume

P.S: I opened an account on POeditor.com

**Comment by bago** [comment]
> Can you share your template and tell me which browser do you use, which version of mosaico, etc?

**Comment by GuillaumeSorel** [comment]
Here is the template
[template-versafix-1.html.zip](https://github.com/voidlabs/mosaico/files/4836797/template-versafix-1.html.zip)
I'm using Firefox 77.0.1 on Ubuntu Mate and Mosaico 2.3.1572289217 on CiviCRM 5.21.0 on DRUPAL 7.69

**Comment by bago** [comment]
Mosaico  2.3.1572289217 doesn't exists. Maybe you are reporting a CiviCRM bug. Please download mosaico and confirm that you see the bug with mosaico 0.17.5

**Comment by GuillaumeSorel** [comment]
ok I will get in touch with the developers of Mosaico/CiviCRM

**Comment by bago** [comment]
No news/updates, so I hope the issue was not in mosaico and I close this. Reopen if you decide to test latest mosaico released code and it is broken.
