### ISSUE TITLE
Integrating responsivefilemanager in mosaico

### ISSUE THREAD

**Issue by zuludevteam** [voidlabs/mosaico#587]
Hi, 

I gone through your demo and found that file manager was integrated using MoxieManager and due to licensing issues didn't have that feature for us.

So, here i planned to integrate the opensource filemanager https://www.responsivefilemanager.com/ in mosaico.

Can you please help me to integrate ?

**Comment by bago** [comment]
You have to create a viewModel plugin:
https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins#viewmodel-plugins

Then you can implement the methods:
```javascript
  vm.linkDialog = function() {
    var inputElement = this;
    var href = $(inputElement).val();
   // then your code to open your file manager and to make sure to set the "href" back with the selected option:
   //  $(inputElement).val(somethingfromyourfilemanager).change();
  };
```
You can do something similar for selecting images or editing images by implementing the

```javascript
  vm.editImage = function(src, done) {
    // here you can read the current image src with "src()" and then set the new image source with "src(newimagesource)".
  };
  vm.selectImage = function(src) {
    // here you can read the current image src with "src()" and then set the new image source with "src(newimagesource)".
  };
```
