### ISSUE TITLE
Image not editable when template is uploaded

### ISSUE THREAD

**Issue by lanredestiny** [voidlabs/mosaico#588]
I have tried all my best to make the email of a template editable by using the **data-ko-display=""** in <tr> and  **data-ko-editable=""** in the <img> tag. But whenever I use any of these editable tags, the template won't be visible. if I remove the display and editable tags the email template will be visible but image won't be edible. I have been on this for days now, please what am I not doing right. 

The file is attached below.
[versafix-2.zip](https://github.com/voidlabs/mosaico/files/4885551/versafix-2.zip)

**Comment by bago** [comment]
data-ko-display="condition" is use to hide or show an element depending on a condition.
data-ko-editable will do.

Please have a look at the tutorial template and look at your javascript console. Your template doesn't even have the "-ko-supports" object/variable declaration.

And read this, too:
https://github.com/voidlabs/mosaico/wiki/Template-language
