### ISSUE TITLE
Looking for reliable function calls that can call 'save' any time?

### ISSUE THREAD

**Issue by tjgragg** [voidlabs/mosaico#590]
Hello,
I'm using mosiaco within an iframe, wrapped in a form. I've made it so when I click the "Save" button, it posts a message to the parents, which then updates the form with both the html and the json metadata. 

I'm trying to see if there are any functions that get called reliable while modifying a template, so I can take out the manual process of clicking "save" to update the form.

Thanks!

**Comment by tjgragg** [comment]
I figured out how to do this when adding/moving/deleting/duplicating a block (within the viewModel object itself), but I'm still not sure how to do this when someone updates the contents of a block.

**Comment by bago** [comment]
Either you repeatedly run an exportHTML and compare it with the previous version and if you detect changes you call save, or you alter mosaico and attach some listener to undoserializer.setListener().
Unfortunately you can't currently get access to undoserializer from the outside of the default Mosaico build, so you'll have to alter mosaico sources at least to expose somehow the undoserializer.

The listener will be called for every action that involve the undomanager, so every change of the model. We have users that built a full record/replay system above this feature or a collaboration system to have multiple users work concurrently on the same template (even if this is not solid enough to deal with concurrency issues and breaks too easily, IMHO).
