### ISSUE TITLE
Image box use image_url

### ISSUE THREAD

**Issue by tjgragg** [voidlabs/mosaico#591]
So, instead of forcing people to upload images and use an image gallery, is it possible to have an image box use an imageUrl for its src? If not, this would be a very helpful feature.

**Comment by bago** [comment]
Mosaico have special management for images: you can see it automatically resize or crop them depending on the placeholder. You can't do that with remote images, so it requires images to be uploaded.

If you don't need mosaico to be able to deal with resizing then there's nothing preventing you from creating a master template that doesn't use the `data-ko-editable="image.src"` in images and instead use a `style="-ko-attr-src: image.src"` : this way Mosaico will only show you a text box and you will be able to insert an external url that will be used as the src for the image.
