### ISSUE TITLE
Use with Laravel

### ISSUE THREAD

**Issue by felloz** [voidlabs/mosaico#592]
Hello, do you have any documentation to use Mosaico to register the html into a database, thank you.

**Comment by bago** [comment]
Look at #73 to read suggestion on how to read/write the content. Keep in mind that HTML is not what you are working on, but an EXPORT. You can't load the HTML but you have to load the saved model (a json file) and then you can make changes and then save the changed model (and export an updated output HTML).

https://github.com/voidlabs/mosaico/wiki/Saving-and-Loading
https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico
