### ISSUE TITLE
Update tinymce to version 5.x

### ISSUE THREAD

**Issue by benj0c** [voidlabs/mosaico#593]
Hi to all,

The `package.json.NOTES` file says that tinymce lib is" locked "on version 4.5.8. However in version 5.x tinymce has introduced a new plugin for the emoticons I need. I tried to do an update to 5.1.4 and everything seems to be working properly. However, there is one bug, and that is when everything is deleted from the input (backspace) and the input is left blank, for some reason the `<span>` element is deleted and re-created, but from that moment that element no longer works properly.

Does anyone have a similar experience? Any advice or something?

**Comment by bago** [comment]
I tested a few versions of TinyMCE 5.x some weeks ago but it doesn't work well, yet. They still didn't fix the issues we reported since 4.6+. We guess they have no interest in fixing them. Last good version, in our opinion, is still 4.5.8.

**Comment by bago** [comment]
The issue you describe is one of the bugs we reported. Unfortunately we didn't find workarounds, so we can't update.

**Comment by benj0c** [comment]
We need new emoji plugin (from 5.x version). Do you have any idea how to make it works?

**Comment by bago** [comment]
this is a tinymce issue, I can't help as I don't know the differences in plugin format between tinymce 4.x and 5.x.
You can ask in their forum to understand how complex could be to backport the emoji plugin from 5.x to 4.x.
