### ISSUE TITLE
resizing images manually

### ISSUE THREAD

**Issue by NatFG** [voidlabs/mosaico#594]
I know that all images are being resized automatically, but is there or could there be an option to do it manually? Could I adjust it manually, making it bigger or smaller according to my needs?

**Comment by bago** [comment]
The size of the placeholder and its resizability depends on the master template.

Most blocks from versafix-1, our flagship master-template, have options to alter the width (usually small/medium/large) and the height is usually depending on the real image ration. When the height is forced, like in multiple column blocks, versafix-1 gives you an option to select the exact height or to remove the "forced height" and simply adapt it to the "image ratio".
