### ISSUE TITLE
Any way to import html from outer source and load it into mosaico editor.

### ISSUE THREAD

**Issue by nishantsharma054** [voidlabs/mosaico#599]
Hi, I was looking for a way to import an HTML into mosaico editor. I don't have the JSON and metadata for the template, just a plain simple html. Is it feasible? This is an urgent request by clients. If not feasible, is there any way this can be achieved?

**Comment by francescbassas** [comment]
In my experience, anything other than using the default versafix template requires development with a somewhat painful learning curve. You can find references to how the templates have to be [here](https://github.com/voidlabs/mosaico/wiki/Template-language) although my advice is that you start from the [versafix template](https://github.com/voidlabs/versafix-template) and [HTMML](https://github.com/voidlabs/htmml) language.

**Comment by bago** [comment]
No. Mosaico is not a general purpose HTML editor, but an email builder. It is "template based" but the template is not simple html.
https://github.com/voidlabs/mosaico/wiki/Replacing-TinyMCE-or-CKEditor-with-Mosaico
