### ISSUE TITLE
Make it easier to create simple editable templates

### ISSUE THREAD

**Issue by bago** [voidlabs/mosaico#6]
The current template language is very flexible but also complex: it supports complex scenarios, let you define you labels, what styles to make editable, alternatives, conditional blocks, expressions and automatic color manipulation.. this is much more than most users need and create a barrier for newbies.

Most people simply need to take their html template, define what are the draggable blocks and choose what images are editable and what texts/buttons should be changed by the user. Most time they don't need style customization or anything else, because they already hardcoded the right style in the template.

We should support a simpler language for simpler use cases!

**Comment by dabrowskid** [comment]
Is it possible to create nested blocks ? 
For example, blocks with two or three column layouts and than place inside text or images ?

**Comment by bago** [comment]
On 7 October 2015 at 11:23, dabrowskid <notifications@github.com> wrote:

> Is it possible to create nested blocks ?
> For example, blocks with two or three column layouts and than place inside
> text or images ?
>
No, this is not currently supported.
I'd like to support this scenario (editors like campaignmonitor and beefree
do this in a similar way to what I'd like) but this need major changes in
the editor code.
But don't expect it to be available soon, as it needs a lot of thinking
before we can start coding something.

For example: at this time the template defines everything. If we implement
a way to have "containers" that will accept basic content (button, image,
title, text, separator) then we have to understand if their html code is
"hardcoded" in the editor, or if this is something defined in the template
and in the latter case how this "declaration" happens.

BTW: this is a feature request deserving its own github issue.

**Comment by psyafter** [comment]
Let's create awesome Landing Pages editor :)
