### ISSUE TITLE
Changing Editor color and look

### ISSUE THREAD

**Issue by Thileepan** [voidlabs/mosaico#60]
First of all, I would say thanks to author for this project.

Where to change the editor toolbar default color? And in which folder the source code will be available for adding additional functionalities in toolbar?

Thanks in advance.

**Comment by bago** [comment]
https://github.com/voidlabs/mosaico/blob/master/src/css/app_standalone_material.less#L3

If you run it using "grunt" then you'll also get automatic "injection" of CSS changes (just save your file and wait few seconds and the webpage will show your changes on the fly without even reloading)
