### ISSUE TITLE
can't pull a request for fr.json

### ISSUE THREAD

**Issue by allinappli** [voidlabs/mosaico#601]
I get this error:

In editor.html:

    link http://mosaico.io

**Comment by bago** [comment]
I can't understand this report, sorry

**Comment by allinappli** [comment]
I wanted to [do a PR](https://github.com/voidlabs/mosaico/pull/600) for the fr.json file and encountered the mentioned error

**Comment by bago** [comment]
I don't understand how a PR can give an error like that.

BTW if you want to contribute language translations please read this:
https://github.com/voidlabs/mosaico/blob/master/res/lang/README.md
and join other french translators here:
https://poeditor.com/join/project/nsFNi6zyOm

**Comment by allinappli** [comment]
ok thanks. Still this was the error I got...
