### ISSUE TITLE
[help] I can't find source of some of the inline css such as max-width:605px and something called "replacedstyle" style in div.

### ISSUE THREAD

**Issue by nishantsharma054** [voidlabs/mosaico#603]
As per client's need I've been customising the templates. I want to increase the width from 600px to 780px. I've done find and replace on max-width: 600px to the updated config, but still when my template is rendered, I see some div with max-width :600px, and also there's something called "replacedstyle" in all the divs. How can I override the css that this "replacedstyle" has in it?

**Comment by bago** [comment]
you can ignore replacedstyles: they are internal stuff.
if you see a width then your "master template" is declaring that width.
Out default master template (versafix-1) doesn't have "max-width: 600px" so I don't know what you are talking about.
