### ISSUE TITLE
Somtimes the preview icon disappears in editor

### ISSUE THREAD

**Issue by bwl21** [voidlabs/mosaico#61]
Sometimes the tiny preview icon in the editor disappears. I could not find any systematic reason for it to appear/disappear.

**Comment by bago** [comment]
The icon should be visible when your window size is large enough to host the right panel.
It is hidden/shown via @media query.

So this is an expected behaviour. Please reopen with more details if I did not answered.

**Comment by bwl21** [comment]
Thanks.

**Comment by Vgratioulet** [comment]
To have the button and label shown event if the preview can't be fully seen, so the user knows he's missing something, 
and to have the preview button with the right buttons, 
I made it with the plugin : 
```
    toolbarPlugin = function(viewModel) {
        return {
            init: function(){
                $(".ui-button[for='showGallery'] > .ui-icon, .ui-button[for='previewFrameToggle'] > .ui-icon").each(function() {
                    this.style.marginRight = ".5em";
                });
                $(".ui-button[for='showGallery'] > .ui-button-text, .ui-button[for='previewFrameToggle'] > .ui-button-text").each(function() {
                    this.style.display = "inline-block";
                });
                $("label[for='previewFrameToggle']").prependTo("#toolbar .rightButtons").show();
            }
        };
    },
```
