### ISSUE TITLE
Public URL of raw HTML template

### ISSUE THREAD

**Issue by drzraf** [voidlabs/mosaico#611]
One missing feature would be the ability to obtain/copy a (public & random) URL storing/providing the template's (HTML) lives (and provide the raw HTML) (like GitHub raw diff URL).
Would be an alternative to the `dl` (download) URL trigger by a POST.
 
That would allow outsourcing online template composition  and still later retrieve resulting template (and would be **very** helpful)

**Comment by bago** [comment]
Mosaico is a javascript library, so this feature does not apply and I'm closing this as invalid.

The bundled backend is just a development backend, if you use mosaico you have to build your own backend and it should be trivial to have saved template being made available via public url.
