### ISSUE TITLE
templates are not saved

### ISSUE THREAD

**Issue by CFMazzarago** [voidlabs/mosaico#612]
Hi, I use Mosaic on my website with CiviCRM (5.41.2) and Drupal 9.2.6. When I create my template with Mosaic and click on the Save button, the popups that "confirm" the saving appear, but if I then exit the page and reopen the template, it is empty (no blocks of the ones I had added). How can I please? Thanks so much!

**Comment by bago** [comment]
Sounds like a CiviCRM issue.

**Comment by CFMazzarago** [comment]
> Sounds like a CiviCRM issue.

hello, what makes you think?

**Comment by CFMazzarago** [comment]
ok thanks
