### ISSUE TITLE
Sorry an error occurred and your information was not saved

### ISSUE THREAD

**Issue by jonty17** [voidlabs/mosaico#615]
Hi there
I'm getting the following error when I try and send a test email

`Sorry an error occurred and your information was not saved`

I'm also getting this error 

`Sorry an error occurred and your information was not saved`

I can't find anybody who has had similar errors and I am a bit stumped. Any hints tips or pointers would be extremely welcome!

Many thanks
Jon

**Comment by bago** [comment]
Read here and complete your report:
https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md
