### ISSUE TITLE
Outlook is not rendering button radius. 

### ISSUE THREAD

**Issue by yagna-it-solution** [voidlabs/mosaico#618]
When I apply button/hyperlink radius. It don't appear in outlook. Outlook show the button square. No rounded corner. How can I add condition?

**Comment by tbolon** [comment]
Outlook does not support rounded buttons.

**Comment by bago** [comment]
This is an outlook issue. A template could overcome this issue by using VML, but this solution have other issues so that's why versafix-template decided to not try to workaround that. BTW this is a template issue, not a mosaico issue.
