### ISSUE TITLE
CiviCRM CiviMail Recipient Drop Down Broken by Mosaico

### ISSUE THREAD

**Issue by 36m0nd** [voidlabs/mosaico#619]
Updating to Drupal CiviCRM 5.46.2, we are no longer able to select Recipients (Mailing List type Groups) through the drop down in the CiviMail interface as normal. Instead of bringing up Groups under subheadings "Include" and "Exclude" as normal, we have a spinning hamster wheel indefinitely (see attached image). Groups are otherwise functioning as normal in all parts of the database, including the "Test Group" functionality of CiviMail.

After testing, this feature starts working again only when we disable Mosaico. Re-enabling Mosaico re-introduces the issue.

We love using Mosaico as it makes it easy to put together HTML emails for non-technical team members but we will be stuck with basic HTML until this can be fixed...

We would be very grateful for any assistance!

<img width="667" alt="CiviCRM Mosaico Recipients Issue" src="https://user-images.githubusercontent.com/100602277/156015390-fed041a4-7b39-4d18-a3c8-1ebfd7a2d9e5.png">

**Comment by bago** [comment]
This sounds like a CiviCRM issue. You should open an issue there. We don't know how CiviCRM integrated Mosaico.
