### ISSUE TITLE
feature request: parsing multiple values with select property

### ISSUE THREAD

**Issue by InfGame** [voidlabs/mosaico#648]
I was trying to make a template with a Red, Green and Blue themed that had 3 different shades of each color.
I wanted to contol the Theme of the whole template with one property setting but could not find a way to parse all 3 hex values in 1 select property

I don't know if this feature already exists or not but it would be nice to be able to parse multiple values, be it strings, Integers, etc, with one property

**Comment by bago** [comment]
I'm not sure I understand your suggestion.

Can you both make an example of what the UI should look like and which template code you want to use?

**Comment by InfGame** [comment]
> I'm not sure I understand your suggestion.
> 
> Can you both make an example of what the UI should look like and which template code you want to use?

The UI would look the same tho In the code i would like to instance some kind of array where i can save multiple values.

Then when calling it you can pull one of these values out like on a normal Array

For example:

Instancing the property:

Color{
        label: Color;
        widget: select;
        options: ["#9e0529", "#720009","#f5e6e9"]=Red|["#38713f", "#0b4d1f", "#ebf1eb"]=Green|["#286f9c", "#104166", "#e9f0f5"]=Blue;
}

Calling the property:

<div style="background-color: #9e0529; -ko-background-color: @Color[0];"><div/>
