### ISSUE TITLE
Docker 

### ISSUE THREAD

**Issue by alfredo-ardito** [voidlabs/mosaico#673]
I followed the instructions to use docker
`docker build -t mosaico/mosaico`
and i'm getting these errors:

> ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/main: DNS lookup error
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: No such file or directory
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/community: DNS lookup error
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/community: No such file or directory

Am I missing something?

**Comment by bago** [comment]
"DNS lookup error" sounds like an issue in your environment. Your computer is not able to open that website. I just clicked on it and saw the content.

**Comment by alfredo-ardito** [comment]
I forgot to add the final error message:

`2 errors; 16 distinct packages available
The command '/bin/sh -c apk update' returned a non-zero code: 2
`

I can see the Index of /alpine/v3.16/main/ when I click on https://dl-cdn.alpinelinux.org/alpine/v3.16/main 
same thing for https://dl-cdn.alpinelinux.org/alpine/v3.16/community
How should I fix the issue in my environment?

**Comment by bago** [comment]
Sounds like a fault in your docker install. I can't really help much about proper docker install.

Here is the first result from the Google search I'd do:
https://stackoverflow.com/questions/66042756/apk-return-dns-lookup-error-on-docker-build
