### ISSUE TITLE
Placeholder generator

### ISSUE THREAD

**Issue by Ninos** [voidlabs/mosaico#682]
Currently the placeholder depends on an extra service (external image request to your site). Is it possible to move it to application, so no external requests are required?

**Comment by bago** [comment]
That's not totally true.

Mosaico library doesn't have any reference to external service: the library requires some backend services and you are supposed to implemnt thos services. This includes the placeholder generation.

The static version of version of versafix-template currently include references to external urls like https://mosaico.io/srv/f-default/* but they are not used at all when the template is loaded by the mosaico library. Those images could also be saved locally in the versafix-template folder or even removed at all. Mosaico library will ask the placeholders to the provided backend when you load it.

**Comment by Ninos** [comment]
Ah thx, as local fix I'll replace the link to custom static images 👍

**Comment by bago** [comment]
Anyway you shouldn't see them being requested *while* using mosaico. If you see the requests to mosaico.io and you're using the last mosaico version open a bug for that.
