### ISSUE TITLE
 [Feature] Fediverse social media buttons

### ISSUE THREAD

**Issue by dtw** [voidlabs/mosaico#699]
> When adding a Social Block to an email drafted with Mosaico, the choice of links is limited to the largest social media sites.
> 
> It would be incredibly useful (and fitting for a software used by many non-profits) to allow users to add other social media accounts, including those in the [Fediverse](https://en.wikipedia.org/wiki/Fediverse), like [Mastodon](https://joinmastodon.org/), [Pixelfed](https://pixelfed.org/), or [Peertube](https://joinpeertube.org/), as well.
> 
> One solution would be to replace the current Social Block picker with a custom number of free text fields and the chance to upload custom icons.
> 
> ![2022-12-20_09-34](https://user-images.githubusercontent.com/40486598/208621814-5aaf5085-d482-44ba-864c-e0c3469f0131.png)

Originally posted here: https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/issues/559

**Comment by bago** [comment]
This is a template choice, not an editor one. You can create your own master template including all of the social networks out there. Have a look at https://github.com/voidlabs/versafix-social-icons and https://github.com/voidlabs/versafix-template projects.

We have no plan adding every social out there to our flagship versafix template.
