### ISSUE TITLE
Support translatable labels/helps/blockDescriptions for template-defined UI

### ISSUE THREAD

**Issue by psyafter** [voidlabs/mosaico#70]
There is any way to use translations (like $root.t() or another) in template labels?
I want to use single template for different UI languages without maintain all same templates

I talk about template language:

      alt {
        label: $root.t('Alternative Text');
        widget: text;
        help: $root.t('Alternative Text Help');
      }

**Comment by bago** [comment]
There is no solution at this time (other than cloning the template for each language).

I need to think about this a little more: I never needed multiple language for Mosaico so I never invested many thoughts on this.

If we "rely" on editor translations then for every new template we would have to add new strings to the mosaico language file and its translations.. and this makes no sense.

We have 3 languages at this time:
1) editor UI language
2) "template defined" UI language
3) template content language

Of course 2 and 3 may have some "duplication" between templates, but given they are "template specific" it doesn't sound good to put translations in the "mosaico" editor UI translation files (1).

**Comment by psyafter** [comment]
It not must be part of editor UI translation file.
May be plugin...
For example I can pass in options property 'templateTranslations' array or json (key values).
Template viewmodel builder (this one that parse @supports -ko-blockdefs) can replace all tokens by values from templateTranslations.
So it stay only "extension" and mosaico framework take care to "translate" tokens before insert it into viewmodel.
It should not be observable but one time initialized

**Comment by bago** [comment]
This "templateTranslations" would be shared by all templates or one for each template?

**Comment by psyafter** [comment]
It would be shared be Mosaico for all tempaltes.
So I manage all translations for my types and supply it to editor when init.

I found where I can inject this code:
js\converter\stylesheet.js
if (decls[k].name == 'label') name = decls[k].value;

Here I can check supplied options and replace token (if exists).
One question - I can't find initial options that I supply to editor.
When me debugged code - I see that you not save supplied options.
Function "start" just do applyBindingOptions and then call templateLoader.load.

There is any global (for editor instance) var where I can copy translation array (in start/init function or even in plugin, but as I understand plugin run after template model is ready so it not right place..) and use it in _processStyleSheetRules_processBlockDef?

**Comment by psyafter** [comment]
I'm checked viewModel.exportJSON() string and it not contains 'labels' values for template model - so  I think you rely on real template model when restoring from storage.
If so then my way to implement it is right (saved templates always will use current token translation and will not save translated values).
I just need to know how to copy it to Mosaico instance witout using js global vars : )

By the way - the editor and infrastructure is fantastic :100: . I'll try adapt it to be landing pages builder

**Comment by bago** [comment]
At this time it will be easier for you if you try to "link" it to the mosaico-ui translations.

So in editor.html you should look for 
model._help
model._blockDescription
and
model._name (label)

At this time they are "wrote" as simple HTML while you will have to write valid Knockout code  for them.

e.g: you find something like this:
```
    title = model !== null && typeof model._help !== 'undefined' ? ' title="' + utils.addSlashes(model._help) + '"' : '';
```
and you add to this a 
```
' data-bind="attr: { title: $root.t(\''+utils.addSlashes(model._help)+'\') }"';
```
Or something similar...this way once "knockout" is "bound" the strings will update!
(this will make it easy to change the editor-UI+template-UI language, even "on the fly", but I have no time right now to explain how... next lesson ;-) )

**Comment by bago** [comment]
let me know if you "understand" Knockout data-binding or not: if you know it I can give you "faster" solutions ;-)

**Comment by psyafter** [comment]
I'm new in ko but already understand how it work :)
Changing UI of templates on the fly it nice, but too much (at now) :).
And ko create subscribers - so it extra memory for this idea.

Thanks, I understood what you suggest, but I'll manage translations out of editor code, so I think I'll add in editor ns new function for translating and var for copying array and then I'll call translating in _processStyleSheetRules_processBlockDef or _propEditor

You want me create pull request for it or it not something that you interesting and will not add to project?

**Comment by bago** [comment]
ko is good with "subscribers": if your methods doesn't use "observables" then it won't subscribe to anything. If the method access observable then you'll get a subscription. So, it will depend if viewModel.t will use an observable or not.

BTW: you could create a method similar to "t" that does the same thing (fallback to tt) so that at any time we can decide how to deal with that.

I don't like very much a solution where the "converter" use its own "conversion-time" translation that is different from the main editor-ui translation (most of editor-ui is in the converter itself, too).
For example, in my embed use case I set the language in a viewModel plugin and the viewModel plugin is invoked AFTER the template has been "converted".

So, the converter for a given template should produce the same output everytime (I thought we could even pre-compile templates in future if this become computationally intensive, but at this time it is less than 20% of startup and I decided to skip this).

That's why I would choose one of those 2 ways:
1) add a way so that a single template itself can declare multiple languages (e.g: via external language stylesheets)
2) use a viewModel/knockout method in the editor.

BTW, if you create something different open anyway a PR so I will be able to understand your solution and decide whether it can be merged or not.

**Comment by psyafter** [comment]
I does something fast and simple, because I want manage token on global level and not on template level.
By this way I manage all tokens for all templates in 1 single file. All templates using same tokens converter. So I shouldn't write labels and helps in every template but write tokens instead.

```javascript
var _translate = null;
var translate = function (token) {
	try {
		if (typeof (_translate) == 'function')
			return _translate(token);
	}
	catch (e) { }

	return token;
}
...
var init = function(options, customExtensions) {
        ...
        //cache translator function
	if (options && typeof (options.translate) == 'function')
		_translate = options.translate;
        ...
};

module.exports = {
  isCompatible: templateLoader.isCompatible,
  init: init,
  start: start,
  translate: translate
};


var _processStyleSheetRules_processBlockDef = function(blockDefsUpdater, rules) {
    ....
    if (decls[k].name == 'label') name = Mosaico.translate(decls[k].value);
    ....
}
```

**Comment by psyafter** [comment]
just added translation for options too (in my translation function):

			var ops = ['options_left', 'options_right'];
			$.each(ops, function (ix, el) { 
				if (typeof (trns[el]) != 'undefined' && res.indexOf(el) > -1)
					res = res.replace(new RegExp(el, 'g'), trns[el]);
			});

**Comment by bago** [comment]
If you do the change please ping back ith your diff/PR: I won't apply this one (I already wrote my motivations) bit this will help me identify the places where to do the changes (for the knockout based solution)

**Comment by psyafter** [comment]
No problem:)

I just shown my solution and as I understood it not a way you see solution so I not hope it will be merged.

Another "trouble" is that I work on final app.js and not on sources, so I can't commit it.
And I work in windows. There is no good tools (npm and other for complete setup of env) for windows that work without some magic, so I installed all from git on ubuntu and copied final src to my windows:)

I just need setup env on windows (just for your src) and attach other generated scripts to app, so I'll able work on separated files (not merged to 1 file) and then I can commit :)

ps: commits in single file I do directly in git on web)

**Comment by bago** [comment]
Hi, just send me the diff of your app.js .. I just need a reference, so don't waste time doing anything else :-)

About windows: please note I develop mosaico mainly on windows boxes (node works fine on windows too).

**Comment by psyafter** [comment]
Leave my code, it will not useful for you as it already contains another changes and using of my js library inside editor code :)
Btw - all needed changes of my solution for translating template types values are in prev comment. There are names of functions where I changed it, so it not too difficult to understand what I does.
But it very fast solution. 

I thing that can help me - callback that I can use in plugin so solution can be on plugin level only.
Plugin should support callback for this operations:
var _processStyleSheetRules_processBlockDef = function(blockDefsUpdater, rules) {
    ....
    if (decls[k].name == 'label') name = Mosaico.translate(decls[k].value);
    ....
}

-----------------

About my env: I'm not using node (never tried), I created backend on c# and adapted editor to work in asp.net webform :)
Setup of all needed src took me 3 hours (I have no experience with all tools like npm, grunt, less and what else :) So it wasn't simple task setup editor.
I just need to do it from src of editor only, not every other git projects, and link it to editor.html. Just because I won't all src of node_modules and bower_components. Ready to use files like in dist folder) are pretty enough for me. 
One question about windows - how you compile on windows from src to single js file and single css?

**Comment by bago** [comment]
On windows I do the same thing that I do on other platforms: install node, install grunt, run grunt. The grunt task, by default does all of the builds (in gruntfile you can see the single tasks for doing the js aggregation (browserify) and css aggregation (less+postcss).

About the callback I will think about it and if I can find a way to support both "your" solution and the "ko-binding" solution with a single callback style.

**Comment by bago** [comment]
I added a viewModel.ut() method and the editor now write knockout code to bind calls to that method (like we do in the rest of mosaico editor UI).
So, now you can simply write your own plugin to insert your string (just look at the simpleTranslationPlugin found in app.js) and you don't need to change mosaico core anymore.
