### ISSUE TITLE
Feature request: gif support

### ISSUE THREAD

**Issue by Almenon** [voidlabs/mosaico#700]
Great tool! One minor issue I had is that when I uploaded my gif to the versafluid template, it became a static image. It would be nice if it remained a gif for those animated ✨

**Comment by francescbassas** [comment]
Related issues:

https://github.com/Intervention/image/issues/176
https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/issues/285

**Comment by bago** [comment]
well, this is a "backend" issue. Mosaico simply ships a development backend that shouldn't be used in production, so we didn't care to support animated GIF. 

Of course it is possibile to develop a backend correctly resizing animated GIFs and this doesn't need changes to Mosaico itself: if your backend resizes animated GIFs correctly then mosaico will correctly use/show them!
