### ISSUE TITLE
idea: Manage end template in iframe

### ISSUE THREAD

**Issue by psyafter** [voidlabs/mosaico#74]
It can be nice if template will be managed in iframe and not in pseudo elements in same page.
By this way template css (and may be other resources such js that I want add to template) will not break editor area and logic

Does it possible?
Iframe live within same domain, so there is no restriction to access iframe, isn't?

**Comment by bago** [comment]
I evaluated the iframe and decided it was more problematic.

If you hack and find a working solution with an iframe we can of course talk about this, but in the mean time I don't change things that work fine.

I already parse/alter CSS so to limit their scope: your template CSS shouldn't be able to break the template: if you have one breaking then please send me the template so I can have a look.

The "mobile preview " happens in an iframe and I see there are many issues already implementing a simple preview: I don't even want to try to run tinymce or make the drag&drop work fine over an iframe.

**Comment by psyafter** [comment]
I think to use it for landing pages.
But I can't just load template with js and css files. It rely bootstrap and other js+css files.

What kind of problems were with iframe?
It possible to add additional js and css to iframe (ko with custom binders for linking data between main frame)
tinymce can be added (just in edit mode, not in final html) and will work like in main html
drag&drop over iframe - I found it possible and there is working example:
http://stackoverflow.com/questions/9724308/drag-and-drop-cross-frames-use-html5
http://www.useragentman.com/blog/2010/01/10/cross-browser-html5-drag-and-drop/ (search Drag and Drop Between Frames)
example: http://www.useragentman.com/tests/dragAndDrop/05b-crossFrameSetData/

**Comment by bago** [comment]
I had issues with tinymce and drag & drop: if you think you know how to overcome the issues, then please try!

My task was not to test evey possible implementation but find one that was working fine for my needs: the current solution was the easier and accomplish the job fine, so I'm not going to waste time with a new approach.

But, if you think you can do this and the results works better than the current one, then, why not!

**Comment by psyafter** [comment]
There are any commits with iframe implementation? 
I can try to fix issues with specific bugs, but I can't recreate editor with iframe, just because I not learned all code of editor and don't know where to start. it can took many weeks :)
But if you have src of your past tries with iframe, so I really can continue the code...

**Comment by bago** [comment]
It was 1 year ago, I guess there is no single line kept from that time... I was prototyping and found that the iframe (my first attemp) was a PITA so I moved to using an "in page" element.

BTW the mobile preview is in fact an iframe, so it shouldn't be hard if you want to try to make that "preview" a "wysiwyg editable area" and try to fix issues.


BTW the code that change the rendering behaviour from "show"(preview) to "wysiwyg" (editing) is
```
    <!-- ko withProperties: { templateMode: 'wysiwyg', templateModeFallback: 'show' } -->
       content
    <!-- /ko -->
```
You can see this in src/tmpl/main.tmpl.html

Instead the preview iframe is initialized partially in that main.tmpl.html and partly in the binding "src\js\bindings\bind-iframe.js "

Maybe you just have to add that ko comment to enable the wysiwyg templateMode somewhere in the bind-iframe.js where the html for mosaico is initialized... but I warn you that interaction between iframes is a PITA and it won't be about simple bug-fixing: you'll have to dig into jquery-draggable/droppable the knockout-sortable wrapper between the jquery and the knockout and much more.... 

But if you want to try you now have your pointers ;-)

**Comment by bago** [comment]
A fix: the template used by bindIframe is overwritten in src/js/template-loader.js:
```
ko.bindingHandlers.bindIframe.tpl = iframeTpl;
```
So if you want to give it a try your "withProperties" binding will have to be added somewhere in this template.

**Comment by psyafter** [comment]
thanks

**Comment by bago** [comment]
PS: don't think that I'm not able to do stackoverflow searches: If I dropped the iframe it was not before I did a lot of google searches ;-)

I have to say that when this I made this choice I still had IE8 as the minimum target platform and that with the months I ditched IE8/IE9 because of many other issues, so I don't know if limiting to IE10+ things could have been easier from the start (but I don't think so, as the preview iframe didn't work even in IE10 when I implemented it).

**Comment by psyafter** [comment]
as I understand you r used jquery drugndrop?
I found article that do it with clear html5 drugndrop support, may be it not too bad limit editor to valid html5 browsers with drug n drop support. I think IE10 support it, I'll try and let you know

**Comment by bago** [comment]
You're free to try your refactoring: it won't be so easy to replace the full drag&drop infrastructure. BTW if you want to attempt similar changes you will have to start digging in the code: you'll find your answers.
