### ISSUE TITLE
Built but missing 'dist' directory

### ISSUE THREAD

**Issue by sean-thorburn** [voidlabs/mosaico#79]
I have successfully built as demonstrated here:
https://travis-ci.org/voidlabs/mosaico/jobs/95390454

I am still missing the 'dist' directory though.
I have a 'bower_components' directory and a 'node_modules' directory.

What have I missed?
I plan to test this on IIS.

**Comment by bago** [comment]
grunt jasmine_node simply run the tests...
follow the main Readme if you want to build it (just run "grunt").
