### ISSUE TITLE
Paste HTML Code

### ISSUE THREAD

**Issue by Thileepan** [voidlabs/mosaico#81]
Is this possible to paste my own html code and see the preview in the editor? Along with drag and drop functionality, sometimes I may need to copy and paste the html code and see the html preview. I didn't expect drag and drop functionality when I copy and paste the html code.

Thanks
Thileepan

**Comment by bago** [comment]
Mosaico is a drag&drop editor, I don't see how it could be used as a "preview tool" for html.
