### ISSUE TITLE
Errors when building with grunt on ubuntu 

### ISSUE THREAD

**Issue by bradmac** [voidlabs/mosaico#82]
Just a heads up, this *did build* for a colleague on windows, but i ran into a long series of problems when building with a clean install of node using apt-get on ubuntu wily. Note that the recommended ppa is not currently available for wily, so i first used the default distro.

** So quite possibly not an issue with the mosaico script. **

...
Running "combineKOTemplates:main" (combineKOTemplates) task
Running "browserify:debug" (browserify) task
Warning: watch ENOSPC Use --force to continue.
Aborted due to warnings.

----

/mosaico$ grunt
Loading "phantom-thumbnailer-editor.js" tasks...ERROR
>> TypeError: undefined is not a function

---

And quite a few others.

**Comment by bago** [comment]
Please report your node version, npm version, and the output you get from "npm install"/"npm update" (if npm install fails then you can't run grunt..). I know people using ubuntu are building mosaico with no issues.

Travis Builds are on linux, too, you can see sample outputs for their builds here:
https://travis-ci.org/voidlabs/mosaico

**Comment by bradmac** [comment]
Unfortunately i've applied a whole series of hacks i found on stackoverflow of people having the same issues. So it would take a bit of work to undo them and get back to the original state.

I'll put more time into debugging and reporting the issue if we end up proceeding with it.

**Comment by bago** [comment]
If you have some detailed info (error condition, error thrown, hacks applied) we can add to the readme to warn ubuntu users write them here.

**Comment by bradmac** [comment]
This is one:
Fatal error: watch ENOSPC

Which was corrected by running this command:
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

More details here:
http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

But will take a bit of effort to reproduce other issues, which i cant do right now

**Comment by bago** [comment]
I wrote a reference to this issue in the main Readme. Anyone with the same issue please comment here with more details about how you fixed it.

**Comment by janietom2** [comment]
Same issue on Mac Os X (10.11.2)

**Comment by bago** [comment]
Does "same issue" means you saw "Fatal error: watch ENOSPC" ?
Please post FULL LOG, npm version, node version.

**Comment by janietom2** [comment]
Running "watch" task
Waiting...
Fatal error: spawn convert ENOENT

npm -> 3.3.12

node -> 5.2.0

Also the images are not exporting.

**Comment by BASTAWESY** [comment]
This issue was handled?
