### ISSUE TITLE
How to init with providing the email content?

### ISSUE THREAD

**Issue by bradmac** [voidlabs/mosaico#84]
We are looking at embedding mosaico into our application, which currently uses ckeditor and aceeditor. 

To this end I would like to modify the init code in editor.html to use content sourced externally. Eg:

````
var ok = Mosaico.init({
    imgProcessorBackend: basePath + '/img/',
    emailProcessorBackend: basePath + '/dl/',
    titleToken: "MOSAICO Responsive Email Designer",
    template : "templates/versafix-1/template-versafix-1.html",
    data : {
        content : "<div>My wonderful content</div>"
   },
    fileuploadConfig: {
        url: basePath + '/upload/',
        // messages??
    }
}, plugins);
````

There does appear to be a data property on the options object, which has a content property. But when i use the above i get a JSON parse error.

Can you suggest the correct way to initialise mosaico with a particular content to edit?

**Comment by bago** [comment]
"content" must be a javasciprt object, the same you get if you invoke the "viewModel.exportJSON()" method.

Look https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins for "The simplest plugin is the plugin that expose Mosaico viewModel to the window:" so you expose the viewModel and see how this object looks like.

Mosaico is not a general purpose editor, but a "template based, template customization"  editor. you can load only the data saved by mosaico itself and you can't edit "generic html".
