### ISSUE TITLE
Start the editor with several blocks inserted into it

### ISSUE THREAD

**Issue by Nick-Burdo** [voidlabs/mosaico#89]
Thank you for your wonderful work!
I need to start so that some blocks have been inserted into the editor. How can I do it?

**Comment by bago** [comment]
Add the "viewModel" export variable plugin:
Mosaico.init(options, [function(vm) {window.viewModel = vm;}]);

This way you have a global viewModel variable you can use.

Prepare your default content then run
viewModel.exportMetadata();
and
viewModel.exportJSON();

This will give you JSON for the metadata and the content-model for your current editing.

Next time you will start Mosaico this way:

Mosaico.init({  data: JSONENCODEDOBJECT}, plugins);

Where JSONENCODEDOBJECT is a JSON for "{ metadata: OBJECTYOUGOTFROMEXPORTMETADATA, content: OBJECTYOUGOTFROMEXPORTJSON }"
