### ISSUE TITLE
New Template not on all Computers visible

### ISSUE THREAD

**Issue by jb-alvarado** [voidlabs/mosaico#94]
Hello,
first: I have install mosaico on a network server and it runs truth apache mod_proxy.
Then I make a copy from the versafix-1 template, add it to the index.html and regenerate the thumbs. I can see this template now on my computer and work with it, but on all other computers this template is not visible. Only a empty square is on the frontage with the new name. But when I click on it, the page stays red.

And a site note:
When I send an email, or download the generate mail I get this message:

```error: Property mso-table-rspace: 0pt at /home/user/nodeapps/mosaico/backend/-html-#undefined is invalid: Unknown property 'mso-table-rspace'.
error: Property mso-table-lspace: 0pt at /home/user/nodeapps/mosaico/backend/-html-#undefined is invalid: Unknown property 'mso-table-lspace'.```

Platform is: 
ubuntu 14.04
Nodejs v4.2.6
npm 2.14.12

Regards!

Jonathan

**Comment by bago** [comment]
I'm sorry but I can't understand what you explain.

The errors you get about mso-table-rspace are not an issue, they are there always.
If something works on your computer but not on other computers then you have something in your setup, it is not something we can answer here without knowledge of your setup.

Start opening the javascript console and look if the browser is logging different stuff in your computers from the others.

**Comment by jb-alvarado** [comment]
Hello bago,
I try to explain it better:

I have install mosaico on a server, witch run in our network. And we have different clients in the network. 

I have also made a copy from the default templete, rename it and link it in the index.html. On my Computer (OSX) I can see the new template:
![mosaico](https://cloud.githubusercontent.com/assets/2212056/12638646/3bdbfc72-c59f-11e5-8234-2bf6d208188b.jpg)
It works in Firefox and in Safari. But when I open the page on a different computer or VM, the template is empty and the template site can not load. 

Console output is:
`Die Verbindung zu ws://mosaico.discovery.intern:35729/livereload wurde unterbrochen, während die Seite geladen wurde. livereload.js:191:18
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create`
It means something like: connection has cancel while site was loading.

The message I also get on my computer. I can disable livereload, then the message goes away, but the site still not load on other computers.

But now comes: when I open the site on a other computer and select the new template (the site is plank), and when I close the browser then and reopen them, the site is shown. Only when I refresh it goes away again.

Full console output on my computer: https://gist.github.com/jb-alvarado/26a0d5994be5d5b205e5

**Comment by bago** [comment]
Do other templates work fine? If yes, then there must be something in your template.. check that you changed the index.html correctly and check the differences in the template.

You send me the output on your computer, but if I understood you, your computer is the only one working fine, so why don't you send me the output of the computers that have issues?

**Comment by jb-alvarado** [comment]
I had done this to :):

Console from other computers:
`Die Verbindung zu ws://mosaico.discovery.intern:35729/livereload wurde unterbrochen, während die Seite geladen wurde. livereload.js:191:18 
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create`
It means something like: connection has cancel while site was loading

**Comment by bago** [comment]
Livereload is optional and isn't needed at all, so even if it fails to load everything should work anyway.

I don't get german, but I guess you have some firewall/proxy in your network that breaks the connections. 

Mosaico is really basic: an http page and some javascript.. if they can't be accessed via HTTP then it won't work.

**Comment by bago** [comment]
Look at the network tab in a browser that doesn't work and see what resources have issues being donloaded.

**Comment by jb-alvarado** [comment]
Oh... shame on me! You are right, we have a proxy... I don't now that this is because of this, but I rename the template from AD to something else, and now it works. It don't say way then it works on my computer, but now it works on all computer. This acronym AD makes always problems...

Sorry for bother you because of that!
