### ISSUE TITLE
Help with image Editor Plugin (Aviary Integration)

### ISSUE THREAD

**Issue by jrodri2001** [voidlabs/mosaico#95]
Hi, I'd like to add image editing functionality similar to the one in the demo, but not quite sure on how to accomplish that. The documentation implies this can be done, but it does not elaborate much on how exactly...

I'd like to use Aviary editor...

Thanks in advance.

**Comment by bago** [comment]
You can create a plugin and pass it to the mosaico initialization:

```javascript
var plugins = [];
plugins.push(function(viewModel) {
  viewModel.editImage = function(src) {
    var ondone = function(result) {
      src(result);
    };
    invoke_your_plugin(src(), ondone);
  }
});
Mosaico.init({ youroptions }, plugins);
```

So the plugin simply adds an "editImage" method to the mosaoco viewModel. Mosaico automatically add an img edit button to images and invoke that method when you click it.
The rest is in you hand: "src" is a function, you invoke it without parameters to know the current src (the one you want to edit) and the you invoke it with the new source to set the new path of the edited image.

I don't know aviary api, but it shouldn't be hard to invoke (you'll probably need a way to upload the altered image if the plugin you use doesn't already provide a way to do that).

**Comment by jrodri2001** [comment]
Thank you, That's exactly what I was looking for... I'll update later with my implementation in case other people is interested in doing the same...

**Comment by jrodri2001** [comment]
Hi, is there any way to have a reference to the actual image being edited, not just the src attr...?

**Comment by bago** [comment]
What do you mean? The "src" function gives you the unique reference to the uploaded image (before it is automatically resized by mosaico). There is no other reference to that image.

**Comment by jrodri2001** [comment]
I mean to get the actual img element, since the image doesn't have an ID
attribute to match it with jQuery.

**Comment by bago** [comment]
You can't. There is a layer over it and you can't work with the dom directly..

**Comment by jrodri2001** [comment]
well, that's going to be a problem, Aviary takes two arguments to lunch, the image url and either the img element or the img ID, is there any way to dynamically assign an ID to the img element?

**Comment by bago** [comment]
Are you sure aviary wants the image dom ID and instead it doesn't simply need an "identifier" that will pass you back when it saves ? In this case you'll have to generate random string identifiers and keep a maps of identifiers and their related "src" function so that when it calls "save" you'll have an identifier and you'll be able to retrieve the src function associated to that identifier.

Also, keep in mind the issue about images having to be in mosaico backend and not on aviary: if aviary gives you urls in their own domain then it won't work (you have to download them and upload them changed to mosaico.. and this will need some more coding in order to probably simulate a file-upload)

**Comment by jrodri2001** [comment]
According to their documentation, yes, needs to be the DOM element... https://developers.aviary.com/docs/web/setup-guide#constructor-config-image

Aviary exposes an onSave method which receives the new updated image on their servers, so I could update the image then in mosaico I guess... but not really sure on how without the reference to the actual image...

thanks for your help...

**Comment by bago** [comment]
Then try to create your own img element (document.createElement) assigning your own ID and applying a "display: none" and pass it to aviary.. then you can ignore what aviary does with that element as long as you invoke the "src" method you received in the editImage function.

**Comment by jrodri2001** [comment]
So, I ended up being able to plug in Aviary Editor, this is what I did:

in my html, created a hidden element for the image:
`<img id="aviary_img" src="" style="display: none"/>`

Added this function to define the Aviary Editor:
```javascript
var featherEditor = new Aviary.Feather({
    apiKey: 'YOUR_KEY_HERE',
    apiVersion: 3,
    theme: 'dark', // Check out our new 'light' and 'dark' themes!
    tools: 'all',

    onError: function(errorObj){
        console.log(errorObj);
    }

});
```

Then loaded the plugin as follows:

```javascript

        function uploadImage(url, src){
            $.post(BACK_END_IMG_URL, {
                url: url,
                dataType: 'json'
            }).done(function(data){
                var d = JSON.parse(data);
                src(d.files[0].url);
            });
        }

        plugins.push(function(viewModel) {
            viewModel.editImage = function(src, element, another) {

                var image_url = src();
                var temporary_img = $('#aviary_img');
                temporary_img.attr('src',src());

                featherEditor.updateConfig({
                    onSave: function(eID, newUrl){
                        //upload image to backend and update img source
                        img = uploadImage(newUrl, src);
                    }
                });

                featherEditor.launch({
                    image: 'aviary_img',
                    url: image_url 
                });


            }
        });
```

**Comment by NJseo** [comment]
jrodri2001, 

I'm trying to plugin the Avairy editor as well. but can't seem to get it to work. Your help would be appreciated.

 <script>
$(function() {
  if (!Mosaico.isCompatible()) {
    alert('Update your browser!');
    return;
  }
  // var basePath = window.location.href.substr(0, window.location.href.lastIndexOf('/')).substr(window.location.href.indexOf('/','https://'.length));
  var basePath = window.location.href.substr(0, window.location.href.lastIndexOf('/'));
  var plugins;
  // A basic plugin that expose the "viewModel" object as a global variable.
  // plugins = [function(vm) {window.viewModel = vm;}];
  
  var ok = Mosaico.init({
    imgProcessorBackend: basePath+'/php-backend/img/',
    emailProcessorBackend: basePath+'/dl/',
    titleToken: "MOSAICO Responsive Email Designer",
    fileuploadConfig: {
     url: basePath+'/php-backend/upload/',
      // messages??
	 // url: 'https://www.reviewlaunch.com/Uimg/1/',
	 
    }
  },  plugins);
  var featherEditor = new Aviary.Feather({
        apiKey: '1234567',
        onSave: function(imageID, newURL) {
            var img = document.getElementById(imageID);
            img.src = newURL;
        }
    });

    function launchEditor(id, src) {
        featherEditor.launch({
            image: id,
            url: src
        });
        return false;
    }
	function uploadImage(url, src){
            $.post(BACK_END_IMG_URL, {
                url: url,
                dataType: 'json'
            }).done(function(data){
                var d = JSON.parse(data);
                src(d.files[0].url);
            });
        }

        plugins.push(function(viewModel) {
            viewModel.editImage = function(src, element, another) {

                var image_url = src();
                var temporary_img = $('#aviary_img');
                temporary_img.attr('src',src());

                featherEditor.updateConfig({
                    onSave: function(eID, newUrl){
                        //upload image to backend and update img source
                        img = uploadImage(newUrl, src);
                    }
                });

                featherEditor.launch({
                    image: 'aviary_img',
                    url: image_url 
                });


            }
        });
  if (!ok) {
    console.log("Missing initialization hash, redirecting to main entrypoint");
    document.location = ".";
  } 
});

    </script>

**Comment by NJseo** [comment]
Yeah, seems as though I got some things working. Although still having troubles with saving the image.

**Comment by NJseo** [comment]
$(function() {
  if (!Mosaico.isCompatible()) {
    alert('Update your browser!');
    return;
  }
  // var basePath = window.location.href.substr(0, window.location.href.lastIndexOf('/')).substr(window.location.href.indexOf('/','https://'.length));
  var basePath = window.location.href.substr(0, window.location.href.lastIndexOf('/'));
  var plugins = [];
  plugins.push(function(viewModel) {
  viewModel.editImage = function(src) {
    var ondone = function(result) {
      src(result);
    };
    invoke_your_plugin(src(), ondone);
  }
})
  var featherEditor = new Aviary.Feather({
    apiKey: '**********************************',
    apiVersion: 3,
    theme: 'light', // Check out our new 'light' and 'dark' themes!
    tools: 'all',

    onError: function(errorObj){
        console.log(errorObj);
    }

});
  // A basic plugin that expose the "viewModel" object as a global variable.
  //plugins = [function(vm) {window.viewModel = vm;}];
        function uploadImage(url, src){
            $.post(BACK_END_IMG_URL, {
                url: url,
                dataType: 'json'
            }).done(function(data){
                var d = JSON.parse(data);
                src(d.files[0].url);
            });
        }

        plugins.push(function(viewModel) {
            viewModel.editImage = function(src, element, another) {

                var image_url = src();
                var temporary_img = $('#aviary_img');
                temporary_img.attr('src',src());

                featherEditor.updateConfig({
                    onSave: function(eID, newUrl){
                        //upload image to backend and update img source
                        img = uploadImage(newUrl, src);
                    }
                });

                featherEditor.launch({
                    image: 'aviary_img',
                    url: image_url 
                });


            }
        });
  
  var ok = Mosaico.init({
    imgProcessorBackend: basePath+'/php-backend/img/',
    emailProcessorBackend: basePath+'/dl/',
    titleToken: "MOSAICO Responsive Email Designer",
    fileuploadConfig: {
     url: basePath+'/php-backend/upload/',
      // messages??
	 // url: 'https://www.reviewlaunch.com/Uimg/1/',
	 
    }
  }, plugins);

  if (!ok) {
    console.log("Missing initialization hash, redirecting to main entrypoint");
    document.location = ".";
  } 
});

**Comment by NJseo** [comment]
could be: BACK_END_IMG_URL is not defined

**Comment by jrodri2001** [comment]
The image upload needs the backend functionality set up, so in my example I use this:
```
function uploadImage(url, src){
            $.post('http://localhost/templates/editor/upload/url', {
                url: url,
                dataType: 'json'
            }).done(function(data){
                var d = JSON.parse(data);
                src(d.files[0].url);
            });
        }
```

you can refer to the php backend project referenced in Mosaico documentation to set it up.

**Comment by NJseo** [comment]
Thanks jrodri2001. I ended up hiring out for the job. Its working pretty good now, except the email is useless until I can find a way to resize the images, put the newly saved images in the static folder, and then css-line the html. I been looking all around, got any suggestions?

**Comment by bago** [comment]
BTW, related to this task, I'm not sure Aviary "client" license is compatible with GPL license, so I don't know if legally (for the licensing/copyright law) this kind of integration is possible.
