### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by ktizoen** [voidlabs/mosaico#96]
Hi, I can't seem to get the images displayed properly. I can upload, view it in gallery but when I insert it in the templates placeholder, it became broken. Is there some settings I missed?
 THe image of the broken images

/img/?src=http%3A%2F%2Fsomedomain.com%3A9006%2Fuploads%2Faga_judah.jpg&method=cover&params=200%2C100

Here's the screenshot.

https://www.dropbox.com/s/orfjofobo3mhf2e/Screen%20Shot%202016-02-04%20at%2010.56.02%20AM.png?dl=0

**Comment by bago** [comment]
What backend are you using (node.js or php)?
Is "somedomain.com" the same domain where you're using mosaico?

Do you get errors in javascript console or in the server logs/console?

**Comment by ktizoen** [comment]
I'm running Mosaico on the same linux server(Ubuntu) at port somedomain.com:9006
Below are screenshots of the some errors.

![screen shot 2016-02-04 at 8 48 29 pm](https://cloud.githubusercontent.com/assets/17058606/12816753/c1f33ab4-cb80-11e5-91e9-3acf42ece624.png)
![screen shot 2016-02-04 at 8 44 38 pm](https://cloud.githubusercontent.com/assets/17058606/12816754/c5c225ce-cb80-11e5-843f-27a7cbe46b0d.png)

**Comment by bago** [comment]
Did you read mosaico Readme?
What does "convert" command on the command line of your linux return?

**Comment by ktizoen** [comment]
Yes, I have read the readme a few times. Imagemagick is installed.
Using node v5.5.0 (npm v3.3.12)

root@create:~# convert
Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP
Usage: convert.im6 [options ...] file [ [options ...] file ...] [options
...] file

Image Settings:

  -adjoin              join images into a single multi-image file

  -affine matrix       affine transform matrix

  -alpha option        activate, deactivate, reset, or set the alpha channel

  -antialias           remove pixel-aliasing..........

**Comment by bago** [comment]
Here is the code handling the server side resize: https://github.com/voidlabs/mosaico/blob/master/backend/main.js#L103

It's 3 lines of code... it should be pretty straight.
You may want to add some console.log in that "backend" code and restart the backend and then try to add more images to see what the backend logs.

Also: what does the browser says about that requests? Your "network" panel in the browser dev tools should tell you what kind of response the "img" call is returning (is it a 200? a 404? a 500? what content?)

**Comment by ktizoen** [comment]
There's no response on the 'network' panel.
I can see the images under the thumbnails and uploads folders.  The only message when I click on the "img" call is "This request has not preview available"
![screen-shot-2016-02-04-at-10 29 47-pm](https://cloud.githubusercontent.com/assets/17058606/12819902/8a21ec66-cb8f-11e5-8b18-a597d83373c4.png)

**Comment by bago** [comment]
The screenshot doesn't show the return code/response headers...

**Comment by ktizoen** [comment]
Right, it's 200

![screen shot 2016-02-04 at 10 46 05 pm](https://cloud.githubusercontent.com/assets/17058606/12820345/335fd788-cb91-11e5-952b-038be72be746.png)

**Comment by bago** [comment]
I just tested directly against your server and I tried uploading one image.
I don't know what's going on, but 

http://yoururl:9006/img/?src=http%3A%2F%2Fyoururl%3A9006%2Fuploads%2Fmosaico.io-full-resized.png&method=resize&params=258%2Cnull
doesn't work (0 bytes result)
If I pass it a relative url:
http://yoururl:9006/img/?src=uploads%2Fmosaico.io-full-resized.png&method=resize&params=258%2Cnull
It works (returns the resized image) but with a wrong content-length (so browsers will refuse to show it).

You may want to try an older node/npm/imagemagick.

**Comment by ktizoen** [comment]
Thanks for the tip, i'll try with an older version and revert back.

**Comment by bago** [comment]
Did this fixed by downgrading node? Or what else? Your solution may help others!

**Comment by ktizoen** [comment]
Tried a few configuration of the versions but still getting the same error. 
Latest using Centos 7.1 now.
node -v
v0.10.36
npm -v
1.3.6
nvm --version
0.13.1
Broken images in place of the placeholders.

**Comment by SewHappy58** [comment]
Did you get this fixed?

**Comment by ktizoen** [comment]
No, I'm not working on it anymore
