### ISSUE TITLE
Undo buttons not showing

### ISSUE THREAD

**Issue by jrodri2001** [voidlabs/mosaico#97]
Hi,

I am running into a problem and not sure how to solve it... I have initialized Mosaico from my database as follows:

```
var featherEditor = new Aviary.Feather({
    apiKey: 'MY_KEY',
    apiVersion: 3,
    theme: 'dark', // Check out our new 'light' and 'dark' themes!
    tools: 'all',

    onError: function(errorObj){
        console.log(errorObj);
    }

});

var ariadEditor = {
    getEditor: function (metadata, data, id, postUrl, imgPostUrl, images_path) {
        if (!Mosaico.isCompatible()) {
            alert('Update your browser!');
            return;
        }
        var template_metadata = metadata;
        var template_data = data;
        var template_id = id;
       window.location.href.lastIndexOf('/')).substr(window.location.href.indexOf('/','https://'.length));
        var basePath = window.location.href.substr(0, window.location.href.lastIndexOf('/'));
        var procesor_backend = basePath + '/dl';
        var plugins;
        var _postUrl = postUrl;
        var _imgPostUrl = imgPostUrl;
        // A basic plugin that expose the "viewModel" object as a global variable.

        plugins = [function (vm) {
            window.viewModel = vm;
            vm.logoPath = false;
            vm.enableUndo = true;
        }]

        plugins.push(function (mdkey, mdname, tid, viewModel) {
            
            var saveCmd = {
                name: 'Save', 
                enabled: ko.observable(true)
            };

            saveCmd.execute = function () {
                saveCmd.enabled(false);
                viewModel.metadata.changed = Date.now();
                if (typeof viewModel.metadata.key == 'undefined') {
                    console.warn("Unable to find ket in metadata object...", viewModel.metadata);
                    viewModel.metadata.key = mdkey;
                }

                var post = $.post(_postUrl, {
                    action: 'save',
                    id: tid,
                    metadata: viewModel.exportMetadata(),
                    source: viewModel.exportJSON(),
                    html: viewModel.exportHTML(),
                }, null, 'html');
                post.fail(function () {                    
                    viewModel.notifier.error(viewModel.t('Unexpected error talking to server: Save!'));
                });
                post.success(function () {                    
                    viewModel.notifier.success(viewModel.t("Template Saved..."));
                });
                post.always(function () {
                    saveCmd.enabled(true);
                });

                saveCmd.enabled(true);
            };
            
            var downloadCmd = {
                name: 'Download', 
                enabled: ko.observable(true)
            };
            
            downloadCmd.execute = function () {
                downloadCmd.enabled(false);
                viewModel.notifier.info(viewModel.t("Downloading..."));
                viewModel.exportHTMLtoTextarea('#downloadHtmlTextarea');
                var postUrl = procesor_backend ? procesor_backend : '/dl/';
                $('#downloadForm').attr("action", postUrl);
                $('#downloadForm').submit();
                downloadCmd.enabled(true);
            };

            viewModel.save = saveCmd;            
            viewModel.download = downloadCmd;
        }.bind(undefined, template_metadata.key, template_metadata.name, template_id));


        /**
         * Image Editor
         */
        plugins.push(function(viewModel) {
            viewModel.editImage = function(src, element, another) {
                var image_url = src();
                var temporary_img = $('#aviary_img');
                temporary_img.attr('src',src());

                featherEditor.updateConfig({
                    onSave: function(eID, newUrl){                        
                        var img = uploadImage(newUrl, src);                        
                    }
                });

                featherEditor.launch({
                    image: 'aviary_img',
                    url: image_url
                });


            }
        });

        var ok = Mosaico.init({
            imgProcessorBackend: images_path,
            emailProcessorBackend: procesor_backend,
            titleToken: "Lantern Responsive Email Designer",
            fileuploadConfig: {
                url: _imgPostUrl                
            },
            data: JSON.stringify({
                    metadata: template_metadata,
                    content: template_data
                })
        }, plugins);
        if (!ok) {
            console.log("Missing initialization hash, redirecting to main entrypoint");
            document.location = ".";
        }
    }

}

```

But the Undo Manager looks like it's not being load. When I run viewModel.undo.enabled() in console, I get false, Although, this option is enabled in the mosaico.js file by default... I haven't changed anything in mosaico's code nor the versafix default template... Any thoughts?

**Comment by bago** [comment]
Do you see any javascript console warn/error/log?
Can you simplify your code so to have a "minimal example" of the undo button disappearing?

PS I don't see the "uploadImage" function definitition. Did you solved your aviary integration issue? Can you update the issue? #95

**Comment by jrodri2001** [comment]
No, I don't see any javascript errors in console, just normal messages.
I tried disabling all the plugins and just loading the template, then only preview and gallery buttons are shown. Another thing I noticed is that when plugins are loaded, the Save buttons reads SALVA (italian I guess)

I did solved the Aviary plugin, will update the other ticket as soon as I can... Thanks for your help on that!

**Comment by bago** [comment]
Let's go a step back: just try to deploy mosaico AS IS without any change from your side and tell me if you see the undo button. If you see it, try to do the smaller change to editor.html so that your issue is visible and I can reproduce it.

**Comment by jrodri2001** [comment]
this is odd, I run mosaico locally loading the same data, and I can see the undo buttons just fine, but when I do the same on my integration (running Laravel website), then it doesn't show up... even with all the plugins disabled... is it possible that any other script loaded on my site might be interfering with mosaico? I don't see any error in the console though...

**Comment by bago** [comment]
Well, I don't know what you do via Laravel, so it's hard for me to guess...
Do the network tab say anything about problematic resources?
If you use laravel I guess you use apache: do you have anything that may alter the content?

Is your deploy public ? (maybe I can guess something if I see the page)

**Comment by jrodri2001** [comment]
Wow, I feel like an idiot at this point... ends up the whole problem was a missing jquery-ui library... but well, if it help others, when jquery-ui library it's not loaded then the toolbar won't render properly neither the bind style changes will work for the loaded template (such as changing font style), and without any warnings, errors or notices... :-)

Thanks for your help again...

**Comment by bago** [comment]
Well, maybe we should detect this and complain, at least in the javascript log.

**Comment by jrodri2001** [comment]
or maybe I should read the documentation more thoroughly... 

Although, now the buttons does show properly, but when I change the font style in the left side, it doesn't update the template, but it does update the preview panel... do you happen to know why that could happen?... is there something that I am missing on the template metadata or data source that prevents that binding to happen?

**Comment by NJseo** [comment]
jrodi2001, I was hoping your code was a solution to my probelm with Mosaico and Avairy. I copied it, but came back with code warning at just after template_id = id; Did you end up getting it to work, because now I have the entire page not displaying. Any help would be appreciated.

template_id = id;
        window.location.href.lastIndexOf('/')).substr(window.location.href.indexOf('/','https://'.length));
        var basePath = window.location.href.substr(0, window.location.href.lastIndexOf('/'));
        var procesor_backend = basePath + '/dl';
