### ISSUE TITLE
Store image names with the prefix random hash value

### ISSUE THREAD

**Issue by kbalajijan1** [voidlabs/mosaico#99]
Hi,

May I know which function triggers image uploading?

I have to save each session's image names with the prefix random hash value. For ex: images which are uploaded for the template with the hash value #3kbiety should be stored as "3kbiety_image_name". Is there any way to pass the hash value while uploading.

I use ainterpreting's PHP backend for image uploading but I would like to know whether I can pass the random hash value through the front end.

Thanks

**Comment by bago** [comment]
You can see that Mosaico.init takes the upload backend path as an argument.
You can change that path to accomodate the hash and then alter the backend logic to use that hash as a prefix or a folder or whatever you want.

**Comment by kbalajijan1** [comment]
You always think simple. It works good. Thank you.
